feast-dev/feast

- core/src/main/java/feast/core/validators/SpecValidator.java
- core/src/test/java/feast/core/validators/SpecValidatorTest.java
Add validation in feature spec registration to prevent users from registering feature that uses unsupported storage.
> Add more validation in feature spec registration

- Makefile
- pom.xml
Fix for #36.
ref: https://github.com/docker-library/openjdk/issues/247
> Add fix for tests failing in docker image

- rfcs/0001-python-sdk.md
Updating documents to cross-link #48
> Link Python SDK RFC to PR and Issue

- ingestion/pom.xml
> Update com.google.httpclient to be same as Beam's dependency

- core/pom.xml
> Fix jackson dependency issue

- testing/tf/cloud-build/cloud-build.tf
> Remove branch from cloud build trigger

- core/pom.xml
> upgrade jackson databind for security vulnerability

- cli/feast/cmd/get.go
- cli/feast/cmd/jobs.go
- cli/feast/pkg/printer/job.go
- cli/feast/pkg/printer/printer_test.go
- cli/feast/pkg/printer/specs.go
- cli/feast/pkg/util/utils.go
> Add get command

- core/pom.xml
> Embed ui build & packaging into core's build

- testing/tf/cloud-build/cloudbuild_master.yaml
> Build master

- core/pom.xml
> run yarn run build during generate-resource

- core/src/main/java/feast/core/model/JobInfo.java
> Increase the column size for storing raw import spec

- testing/tf/cloud-build/cloudbuild.yaml
> Disable test during docker image creation

- ingestion/src/test/java/feast/ingestion/ImportJobCSVTest.java
Currently, the build is broken. This fixes the unit tests.
> Fix unit tests

- cli/feast/cmd/jobs.go
> Add --name flag to submit job

- ingestion/src/main/java/feast/ingestion/transform/fn/LoggerDoFn.java
> Catch all kind of exception to avoid retrying

- serving/src/main/java/feast/serving/config/ServingApiConfiguration.java
`scheduledExecutorService` was a local variable which will be garbage collected after a while. This PR change `scheduledExecutorService` to be a field instead so that periodic feature spec reload will still be active.
Fix #188
> Fix periodic feature spec reload

- docs/install.md
1.12.7-gke.10 is not supported anymore.
> Update gke version

- core/pom.xml
- sdk/python/examples/quickstart/Quickstart.ipynb
https://nvd.nist.gov/vuln/detail/CVE-2019-12814
> Update jackson-databind version for security fix

- core/src/main/java/feast/core/dao/FeatureSetRepository.java
- core/src/main/java/feast/core/grpc/CoreServiceImpl.java
- core/src/main/java/feast/core/model/FeatureSet.java
- core/src/main/java/feast/core/model/Field.java
- core/src/main/java/feast/core/model/Source.java
- core/src/main/java/feast/core/service/SpecService.java
- core/src/test/java/feast/core/service/SpecServiceTest.java
- sdk/python/feast/client.py
- sdk/python/feast/feature_set.py
- sdk/python/feast/loaders/file.py
- sdk/python/setup.py
- sdk/python/tests/test_client.py
Fixes
* Fixes a problem where the `apply` feature set method would bump feature set versions if the order of features changed
* Fixed a null pointer exception during `apply` feature set method.
* Fix #346 
* Fix #344
Improvements
* Exceptions are now raised to end users in most cases for Python SDK
* Ordering of feature set results when reading them out through CLI
* Get feature set method now returns a more descriptive error
* Listing feature sets with the Python SDK now prints their names
> Bug Fixes: Python SDK and Feast Core

- README.md
README.md Link is broken. Should be `installing-feast.md`
> Fix installation link in README.md

- ingestion/src/main/java/feast/ingestion/ImportJob.java
- ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
- ingestion/src/main/java/feast/ingestion/transform/ValidateFeatureRows.java
- ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
- ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
- ingestion/src/main/java/feast/ingestion/transform/metrics/WriteDeadletterRowMetricsDoFn.java
- ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
- ingestion/src/main/java/feast/ingestion/utils/SpecUtil.java
- ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
- ingestion/src/main/java/feast/ingestion/values/FailedElement.java
- ingestion/src/main/java/feast/ingestion/values/FeatureSet.java
- ingestion/src/main/java/feast/store/serving/bigquery/GetTableDestination.java
- ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
- ingestion/src/test/java/feast/ingestion/ImportJobTest.java
- ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
- ingestion/src/test/java/feast/ingestion/util/StoreUtilTest.java
- ingestion/src/test/java/feast/test/TestUtil.java
Updated code to be compliant with new protos.
> Add integration with projects in ingestion

- sdk/python/cli.py
- sdk/python/feast/client.py
Added the following in accordance to CoreService.proto
```
feast projects create <name>
feast projects list
feast projects archive <name>
```
> Add project-related commands to CLI

- examples/basic/basic.ipynb
Updates the basic Feast example notebook to Feast 0.4 (currently based on 0.3)
Fixes #414
```release-note
None
```
> Update basic Feast example to Feast 0.4

- sdk/java/src/main/java/com/gojek/feast/RequestUtil.java
- sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
Fixes bug where not supplying versions while using the java sdk throws an error
Fixes #460 
```release-note
NONE
```
> Fix typo in split string length check

- protos/feast/core/CoreService.proto
Implementing batch feature validation as discussed in the RFC here: https://docs.google.com/document/d/1TPmd7r4mniL9Y-V_glZaWNo5LMXLshEAUpYsohojZ-8/edit?pli=1#heading=h.qy0z97i1uk9x
This PR only updates the proto file and not the generated code for discussion purposes.
> Update CoreService with GetFeatureStatistics method

- .prow/scripts/test-end-to-end-batch.sh
- sdk/python/feast/client.py
- tests/e2e/feature-validation.py
- tests/e2e/statistics/expected_output_basic_dataset.json
End to end tests that just test that you are able to retrieve singular instances of statistics over a dataset or single day. Will add more complex tests when I have solidified how aggregation will work.
```release-note
NONE
```
> Add basic end to end test for Validation statistics

- datatypes/java/pom.xml
- ingestion/pom.xml
- pom.xml
> Remove unused ingestion deps (#520)

- core/src/main/java/feast/core/service/AccessManagementService.java
> Remove transaction when listing projects (#522)

- ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
- ingestion/src/test/java/feast/ingestion/ImportJobTest.java
- ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
- serving/src/main/java/feast/serving/encoding/FeatureRowDecoder.java
- serving/src/main/java/feast/serving/service/RedisServingService.java
- serving/src/main/java/feast/serving/specs/CachedSpecService.java
- serving/src/main/java/feast/serving/util/Metrics.java
- serving/src/test/java/feast/serving/encoding/FeatureRowDecoderTest.java
> Encode feature row before storing in Redis (#530)

- core/pom.xml
- pom.xml
- serving/pom.xml
> Add log4j-web jar to core and serving. (#498)

- sdk/python/setup.py
> Relax fastavro version requirement in Feast (#500)

- CHANGELOG.md
- datatypes/java/README.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/requirements.yaml
- pom.xml
Updated changelog for release 0.4.7.
> Changelog for release 0.4.7

- serving/src/main/java/feast/serving/service/RedisServingService.java
- serving/src/test/java/feast/serving/service/RedisServingServiceTest.java
> Serving should not throw exception when key not found in Redis (#549)

- .github/workflows/lint.yaml
- Makefile
Related to https://github.com/gojek/feast/issues/556
- Adds a GitHub workflow that triggers linting of all PRs and pushes and pushes to `master`. 
- Adds dependency installation and go tests to Makefile
> Add GitHub Action for Linting

- CHANGELOG.md
Changelog update for release 0.4.7
Fixes #
```release-note
```
> Changelog v0.4.7

- .github/workflows/code_standards.yaml
- README.md
Just adds badges to the readme and renames `linting` to `code standards`
Fixes #563 
```release-note
NONe
```
> Add badges and rename linting to code standards

- .prow/config.yaml
- Removes tests that have already been migrated to GitHub Actions
- Disables long running tests (the are still available with the `/test [name]' command)
Fixes #580 
```release-note
NONE
```
> Disable or make tests available using manual triggers

- .github/workflows/code_standards.yaml
- .github/workflows/unit-tests.yml
Currently tests are only running when pushing to master or when submitting a PR to master. We also need tests to run when submitting a PR between branches.
```release-note
None
```
> Allow tests to run on non-master branches

- ingestion/src/main/java/feast/ingestion/ImportJob.java
- storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/write/BigQueryDeadletterSink.java
Changes the population job pipeline to use the deadletter API. Doesn't add option for deadletter type yet, will hold off on that until we implement a new deadletter sink.
> Change pipeline to use DeadletterSink API

- examples/basic/basic.ipynb
- infra/docker-compose/docker-compose.yml
1. Ensure that your code follows our [code conventions](https://github.com/gojek/feast/blob/master/docs/contributing.md#code-conventions) ✅ 
2. Run [unit tests](https://github.com/gojek/feast/blob/master/docs/contributing.md#running-unit-tests) and ensure that they are passing ✅ 
3. If your change introduces any API changes, make sure to update the [integration tests scripts](https://github.com/gojek/feast/tree/master/tests/e2e) ✅ 
4. Make sure documentation is updated for your PR! ✅ 
5. Make sure you have [signed the CLA](https://cla.developers.google.com/clas) ✅ 
This issue fixes the version of pandas library used inside the Jupyter notebook
Fixes #585  …
> Pin Jupyter Notebook version

- serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
- serving/src/main/java/feast/serving/service/HistoricalServingService.java
- serving/src/main/java/feast/serving/service/OnlineServingService.java
- serving/src/main/java/feast/serving/service/ServingService.java
- storage/api/src/main/java/feast/storage/api/retrieval/HistoricalRetriever.java
- storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retrieval/BigQueryHistoricalRetriever.java
Reopening this after rebasing on master.
Addresses most of @woop 's comments on PR #567
> Add better code docs to storage refactor

- Makefile
Backport the rest of the makefile changes, including linting, test commands for ci
> Backport makefile changes

- core/src/main/java/feast/core/model/Job.java
> Add index for join table for jobs-featuresets relation (#566)

- core/src/main/java/feast/core/config/FeastProperties.java
- core/src/main/java/feast/core/service/JobCoordinatorService.java
- core/src/main/resources/application.yml
- core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
- infra/scripts/test-end-to-end-batch.sh
- infra/scripts/test-end-to-end.sh
> Add pollingInterval config option (#565)

- sdk/python/feast/__init__.py
> Add __all__ exports to Python SDK (#587)

- core/src/main/java/feast/core/job/JobUpdateTask.java
- core/src/main/java/feast/core/job/Runner.java
- core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
- core/src/main/java/feast/core/model/Job.java
- core/src/test/java/feast/core/job/JobUpdateTaskTest.java
- core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
- core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
- core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
Backport #575 and #578
Fixes #
```release-note
```
> Fix runner to string inconsistency (#575)

- core/src/main/java/feast/core/service/SpecService.java
- core/src/test/java/feast/core/service/SpecServiceTest.java
> Create project if not exists on applyFeatureSet (#596)

- core/src/main/java/feast/core/model/Job.java
PR #566 mistakenly has the join columns swapped. This PR fixes it.
> Swap join columns

- OWNERS
Add khorshuheng to approvers list.
> Update approvers list

- .prow/config.yaml
- core/src/main/java/feast/core/model/Store.java
- infra/scripts/setup-redis-cluster.sh
- infra/scripts/test-end-to-end-redis-cluster.sh
- ingestion/pom.xml
- ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
- protos/feast/core/Store.proto
- serving/pom.xml
- serving/src/main/java/feast/serving/config/FeastProperties.java
- serving/src/main/java/feast/serving/config/ServingServiceConfig.java
- storage/connectors/pom.xml
- storage/connectors/rediscluster/pom.xml
- storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/retriever/FeatureRowDecoder.java
- storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/retriever/RedisClusterOnlineRetriever.java
- storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterCustomIO.java
- storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterFeatureSink.java
- storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterIngestionClient.java
- storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisIngestionClient.java
- storage/connectors/rediscluster/src/test/java/feast/storage/connectors/rediscluster/retriever/RedisClusterOnlineRetrieverTest.java
- storage/connectors/rediscluster/src/test/java/feast/storage/connectors/rediscluster/writer/RedisClusterFeatureSinkTest.java
This pull request adds REDIS_CLUSTER as a store. 
Fixes #478
> Add Support for Redis Cluster

- core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
Patch to fix bug introduced in #655 where for dataflow jobs jobs cannot be persisted in the db due to feature set column constraints.
> Fix DataflowJobManager to update existing job instance instead of creating new one

- docs/user-guide/feature-retrieval.md
Correcting a Typo in the documentation to have clearer understanding.
Fixes #
```release-note
NONE
```
> Typo Corrected

- sdk/python/feast/client.py
As described in the issue, it's problematic and doesn't serve any real purpose.
Fixes #598 
```release-note
Removes force_update from client.ingest()
```
> Remove force_update from python sdk ingest

- core/src/main/java/feast/core/model/Feature.java
- core/src/main/java/feast/core/model/FeatureSet.java
Feature set equality is missing check for labels. This PR adds it.
> Check for labels in FeatureSet equality

- docs/user-guide/data-ingestion.md
Fixes a minor typo in the documenation.
```release-note
NONE
```
> Fix typo in docs/user-guide/data-ingestion.md

- infra/scripts/test-end-to-end-batch-dataflow.sh
Ensures compute region tallies with kf-feast's.
```release-note
NONE
```
> Update to correct compute region

- docs/user-guide/feature-retrieval.md
This brings more clarity on, Point-in-time-correct Join and a typo correction.
> Clean up documentation

- CHANGELOG.md
- pom.xml
Releases Feast v0.5
Fixes #527
> Release Feast v0.5

- sdk/python/feast/cli.py
- sdk/python/feast/client.py
> Backport Python SDK bug fixes

- examples/basic/basic.ipynb
- examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
Updates the example notebooks to v0.5 Python SDK post PR #693 
- removes manual setting of projects (default to `default` project).
- update feature references in the format from `project/feature` to `feature`.
> Update Example Notebooks to Default Project and Update Feature Refrences

- core/pom.xml
- pom.xml
- serving/pom.xml
> Remove unused Hibernate dep from Serving

- sdk/go/client.go
- sdk/go/types.go
- sdk/java/src/main/java/com/gojek/feast/FeastClient.java
- sdk/java/src/main/java/com/gojek/feast/Row.java
- sdk/python/tests/test_feature.py
> Fix Go and Java SDK Regressions 

- sdk/python/feast/cli.py
> Fix feature_set_describe cli

- core/src/main/java/feast/core/grpc/CoreServiceImpl.java
- sdk/python/feast/client.py
- tests/e2e/basic-ingest-redis-serving.py
> Add support for version method in Feast SDK and Core

- core/src/main/java/feast/core/config/FeastProperties.java
- core/src/main/java/feast/core/config/JobConfig.java
- core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
- core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
- core/src/main/java/feast/core/job/direct/DirectRunnerConfig.java
- core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
- core/src/main/java/feast/core/job/option/RunnerConfig.java
- core/src/main/java/feast/core/util/TypeConversion.java
- core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
- core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
- core/src/test/java/feast/core/util/TypeConversionTest.java
- protos/feast/core/Runner.proto
> Refactor runner configuration, add labels to dataflow options (#718)

- core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
- core/src/main/java/feast/core/job/direct/DirectRunnerConfig.java
- core/src/main/java/feast/core/job/option/RunnerConfig.java
- core/src/test/java/feast/core/job/dataflow/DataflowRunnerConfigTest.java
- core/src/test/java/feast/core/job/direct/DirectRunnerConfigTest.java
> Fix pipeline options toArgs() returning empty list #765

- pom.xml
Add snapshot back to the pom revision again after 0.5.1 release.
Fixes #
```release-note
```
> Restore snapshot revision for branch v0.5

- .prow/config.yaml
- infra/scripts/test-end-to-end.sh
- tests/e2e/conftest.py
- tests/e2e/redis/basic-ingest-redis-serving.py
Enables end to end test with authentication. Related to #504 and PR #793
Fixes #
**Does this PR introduce a user-facing change?**:No
```release-note
NONE
```
> Test end to end with authentication.

- infra/charts/feast/README.md
- infra/charts/feast/README.md.gotmpl
Fix broken hyperlink to the required roles for the service account in Feast in Helm installation docs.
Fixes #802
No
> Update helm installation docs - Fix broken link

- .github/workflows/code_standards.yaml
- Makefile
- sdk/python/feast/cli.py
- sdk/python/feast/client.py
- sdk/python/feast/feature_set.py
- sdk/python/feast/field.py
- sdk/python/feast/grpc/auth.py
- sdk/python/feast/job.py
- sdk/python/feast/loaders/file.py
- sdk/python/feast/loaders/ingest.py
- sdk/python/feast/type_map.py
- sdk/python/feast/value_type.py
- sdk/python/feast/wait.py
- sdk/python/requirements-ci.txt
- sdk/python/tests/feast_serving_server.py
- sdk/python/tests/grpc/test_auth.py
- sdk/python/tests/test_client.py
- sdk/python/tests/test_config.py
- sdk/python/tests/test_feature_set.py
Supercedes #593.
Fixes #594 .
```release-note
NONE
```
> Enable Mypy static type checking

- examples/statistics/Historical Feature Statistics with Feast, TFDV and Facets.ipynb
- sdk/python/feast/client.py
Fixing the example to be consistent with how we retrieve features now (without project name)
> Remove project reference from feature set id in stats example notebook

- core/src/main/resources/db/migration/V2.2__Subscription_Migration.sql
To keep stores consistent (not only in proto) we migrate subscriptions explicitly
Fixes #
```release-note
```
> Ensure store subscriptions are migrated to allow exclusion schema

- core/src/main/resources/db/migration/V2.5__Fix_Subscription_MIgration.sql
- storage/connectors/bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoadsWithResult.java
- tests/e2e/redis/basic-ingest-redis-serving.py
1. Fix store.subscriptions migration SQL
2. Fix race condition in JobId generation (bq sink)
3. Fix e2e ingestion job api test
Fixes #
```release-note
```
> Sync v0.6 branch with master

- CHANGELOG.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/requirements.yaml
- pom.xml
Official release PR for Feast 0.6.0
> Release Feast 0.6.0

- core/pom.xml
- core/src/main/java/feast/core/service/AccessManagementService.java
- core/src/main/resources/db/migration/V2.6__Create_Project_If_Not_Exist.sql
- core/src/test/java/feast/core/grpc/CoreServiceAuthTest.java
- core/src/test/java/feast/core/service/AccessManagementServiceTest.java
Fixes most `feast.core` unit tests not running as described in issue  #882 
- Reverts JUnit 5 dependency in `core/pom.xml`
- Fix any broken unit tests. 
Fixes #882 
```release-note
NONE
```
> Fix unit tests not running in feast.core package.

- infra/scripts/setup-common-functions.sh
- infra/scripts/test-end-to-end-redis-cluster.sh
- infra/scripts/test-end-to-end.sh
- protos/feast/core/Store.proto
- storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
- storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
- storage/connectors/bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoadsWithResult.java
- storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
- storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
- storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
- storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisClusterFeatureSinkTest.java
- storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisFeatureSinkTest.java
1. Fix bq ingestion metric by adding timestamp to FeatureRowsBatch
2. Fix issue with JobIdPrefix generation 
3. Sampling bq `successful inserts` output
Fixes #
```release-note
```
> Backport of some hotfixes for 0.6.1

- CHANGELOG.md
- pom.xml
Preparation for release 0.6.1
Fixes #
```release-note
```
> 0.6.1 changelog

- pom.xml
> New Snapshot for 0.6 branch

- CHANGELOG.md
> Changelog for 0.6.1 

- docs/user-guide/feature-sets.md
Typo in documentation.
None
```release-note
NONE
```
> Typo in feature sets example.

- CHANGELOG.md
- datatypes/java/README.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/requirements.yaml
- pom.xml
Release v0.6.2 by:
- Updating `-SNAPSHOT` versions to non `-SNAPSHOT` versions
- Updating change log for v0.6.2.
Fixes #
```release-note
```
> Release v0.6.2

- datatypes/java/README.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/requirements.yaml
- pom.xml
Change Versions to v0.6.3-SNAPSHOT post release of v0.6.2
Fixes #
```release-note
```
> Change versions to 0.6.3-SNAPSHOT

- CHANGELOG.md
Add changelog for Release v0.6.2
Fixes #
```release-note
```
> Add Changelog for Release v0.6.2

- auth/src/main/java/feast/auth/config/SecurityConfig.java
- core/src/main/java/feast/core/config/CoreSecurityConfig.java
- datatypes/java/README.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/requirements.yaml
- pom.xml
- serving/src/main/java/feast/serving/config/ServingSecurityConfig.java
- serving/src/test/java/feast/serving/it/ServingServiceOauthAuthenticationIT.java
Release v0.6.2 with patch #927.
Fixes #
```release-note
```
> Release v0.6.2 with patch

- CHANGELOG.md
> Update v0.6.2 changelog with patch PR #927

- core/src/main/java/feast/core/service/StatsService.java
An extra line was not removed in #930 .
Fixes #
```release-note
N/A
```
> Remove extra line that duplicates statistics list

- Makefile
Fix python unit tests
Fixes #
```release-note
```
> Use setup.py develop instead of pip install -e

- .github/workflows/master_only.yml
Related to #972 . Fix was left out for master branch.
Fixes #
```release-note
NONE
```
> Fix rate-limiting issue on github actions for master branch

- .github/workflows/complete.yml
- .github/workflows/master_only.yml
Speeds up Github Actions docker builds by:
- Reverting misstep fix in #974 in  #972: Limiting `max_parallel` did not resolve the issue and slowed down builds.
- Enabling [Docker buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/) to speed up builds.
Fixes #
```release-note
```
> Speed up Github Actions Docker builds

- infra/scripts/test-end-to-end-batch-dataflow.sh
- sdk/python/requirements-ci.txt
> Add cryptography to python ci-requirements

- serving/src/test/java/feast/serving/it/BaseAuthIT.java
- serving/src/test/java/feast/serving/it/ServingServiceOauthAuthenticationIT.java
- serving/src/test/java/feast/serving/it/ServingServiceOauthAuthorizationIT.java
- serving/src/test/resources/docker-compose/core/application-it.yml
- serving/src/test/resources/docker-compose/docker-compose-it.yml
- serving/src/test/resources/docker-compose/job-controller/application-it.yml
`latest` tag is updated for each versioned tag, and in the latest version 0.7.0-rc.3, job-controller is separated from core, requiring it to be included in the test containers.
Fixes #
```release-note
NONE
```
> Add job-controller to test containers

- infra/charts/feast/templates/tests/test-feast-batch-serving.yaml
- infra/charts/feast/templates/tests/test-feast-online-serving.yaml
- sdk/python/feast/client.py
- sdk/python/tests/test_client.py
- tests/e2e/redis/basic-ingest-redis-serving.py
This PR removes functions from Python SDK which have been marked to be deprecated in future releases.
Fixes #
```release-note
Users should use get_historical_features instead of get_batch_features, and only pass in list of dictionaries for get_online_features instead of passing in proto EntityRow.
```
> Remove and update deprecation functions

- sdk/python/tests/dataframes.py
- sdk/python/tests/test_client.py
- tests/e2e/redis/all_types_parquet/all_types_parquet.yaml
- tests/e2e/redis/basic-ingest-redis-serving.py
- tests/load/ingest.py
Boolean lists are already supported when using python arrays. This PR update tests to reflect that.
Fixes #341 
```release-note
NONE
```
> Update tests with bool list

- CHANGELOG.md
- README.md
- datatypes/java/README.md
- docs/administration/audit-logging.md
- docs/contributing/development-guide.md
- docs/getting-started/deploying-feast/docker-compose.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jobcontroller/Chart.yaml
- infra/charts/feast/charts/feast-jobcontroller/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/requirements.lock
- infra/charts/feast/requirements.yaml
- pom.xml
New Release v0.7.0:
- Updates `CHANGELOG.md`  v0.7.0 changelog.
- Update versions in docs to point to v0.7.0.
- Bump versions on master to v0.8-SNAPSHOT.
Fixes #834 
```release-note
```
> Release v0.7.0 and Bump Versions

- .prow/config.yaml
- Makefile
This PR removes e2e batch tests from prow, and updates linting for e2e bq pytests.
Fixes #
```release-note
NONE
```
> Update prow config and makefile

- CHANGELOG.md
- datatypes/java/README.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jobcontroller/Chart.yaml
- infra/charts/feast/charts/feast-jobcontroller/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/requirements.lock
- infra/charts/feast/requirements.yaml
- pom.xml
> Bump version to 0.7.1 and add release notes to ChangeLog

- .github/workflows/master_only.yml
- datatypes/java/README.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jobcontroller/Chart.yaml
- infra/charts/feast/charts/feast-jobcontroller/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/requirements.lock
- infra/charts/feast/requirements.yaml
- infra/scripts/setup-common-functions.sh
- pom.xml
> Bump version to 0.7.2-SNAPSHOT

- sdk/python/feast/pyspark/abc.py
- sdk/python/feast/pyspark/launcher.py
- sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
- sdk/python/feast/pyspark/launchers/standalone/local.py
Launcher methods to accept JobParameters as object.
Fixes #
```release-note
```
> Refactor Spark Job launcher API

- infra/terraform/aws/helm.tf
- infra/terraform/aws/msk.tf
Add AWS managed kafka (MSK) cluster to the example terraform config.
Fixes #
```release-note
NONE
```
> add AWS managed kafka config to the example terraform

- sdk/python/feast/pyspark/launchers/aws/emr.py
- sdk/python/feast/pyspark/launchers/aws/emr_utils.py
Implement job cancellation for EMR
Fixes #
```release-note
NONE
```
> Implement EMR job cancelling

- infra/terraform/aws/helm.tf
Fixes #
```release-note
NONE
```
> Fix env var names for jupyter terraform config

- tests/e2e/conftest.py
- tests/e2e/requirements.txt
- tests/e2e/test_historical_features.py
- tests/e2e/test_online_features.py
This PR add end to end test for historical feature retrieval. The new test has been tested locally against a local spark cluster, but at the moment it will fail during the CI as the corresponding test infrastructure has not been set up yet.
Fixes #
```release-note
NONE
```
> Historical feature retrieval e2e test

- tests/e2e/test_historical_features.py
Unblock other PRs
Fixes #
```release-note
```
> Skip historical test until new e2e env is done

- examples/minimal/Feast 101.ipynb
- infra/charts/feast/charts/feast-jupyter/templates/deployment.yaml
- infra/docker-compose/docker-compose.dev.yml
A few tweaks/fixes to the notebook.
Fixes #
```release-note
NONE
```
> Make demo notebook work on AWS

- .github/workflows/release.yml
This PR adds a github workflow to build and push to Dockerhub for every new release.
Fixes #
```release-note
NONE
```
> Add gh workflow for dockerhub

- .prow/config.yaml
- infra/scripts/test-end-to-end-aws.sh
Adds a test job launcher for a remote e2e AWS test
Fixes #
```release-note
NONE
```
> Add end-to-end Prow Job launcher for AWS tests

- CHANGELOG.md
> Cherry-pick Changelog 0.7.1

- core/src/main/java/feast/core/config/WebSecurityConfig.java
- core/src/main/java/feast/core/controller/CoreServiceRestController.java
- core/src/test/java/feast/core/controller/CoreServiceRestIT.java
With new concepts introduced in light of 0.8 release, this PR exposes rest endpoint to retrieve entities and feature tables.
Endpoints added:
- `/v2/entities`
- `/v2/feature-tables`
Fixes #
```release-note
Users can now retrieve entities and feature tables via rest endpoints.
```
> Update rest endpoints

- infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
> fix jobservice helm chart

- sdk/python/feast/pyspark/launcher.py
Fixing job launcher for non-default project
Fixes #
```release-note
```
> Pass project from context to get entities

- .prow/config.yaml
Add region and change runner params.
Fixes #
```release-note
NONE
```
> Update prow trigger for AWS

- spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
- spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
> Deadletter path is being incorrectly joined

- sdk/python/setup.py
Removed unnecessary dependency that is causing a conflict in Feast CLI
```release-note
NONE
```
> Remove unnecessary Google Auth dependency

- datatypes/java/README.md
- docs/advanced/audit-logging.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jobservice/Chart.yaml
- infra/charts/feast/charts/feast-jobservice/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/charts/prometheus-statsd-exporter/README.md
- infra/charts/feast/requirements.lock
- infra/charts/feast/requirements.yaml
- pom.xml
- spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
> Bump version to 0.9.0-SNAPSHOT

- CHANGELOG.md
> Cherry-picking Changelog 0.8.1

- infra/terraform/aws/rds.tf
Upgrade RDS terraform module to include a fix for #1203 
Fixes # 1203
```release-note
NONE
```
> Bump terraform rds module version

- README.md
Fix for a link to Jupyter in Quickstart
Fixes #
```release-note
NONE
```
> Quickstart link fixed

- CHANGELOG.md
> Changelog 0.8.2

- .prow/config.yaml
Signed-off-by: Oleg Avdeev <oleg.v.avdeev@gmail.com>
Fixes #
```release-note
NONE
```
> add prow config for spark k8s operator integration testing

- infra/scripts/build-ingestion-py-dependencies.sh
> Add datadog(statsd) client to python package for IngestionJob

- .prow/config.yaml
- infra/scripts/azure-runner.sh
- infra/scripts/runner-helper.sh
- sdk/python/feast/contrib/validation/ge.py
- sdk/python/feast/pyspark/launcher.py
- sdk/python/feast/pyspark/launchers/k8s/k8s.py
- sdk/python/requirements-dev.txt
**What this PR does / why we need it**: fix failing azure e2e test
Fixes #
```release-note
NONE
```
> fix azure blob storage access in e2e tests

- .prow/config.yaml
- sdk/python/feast/loaders/file.py
- sdk/python/feast/pyspark/launchers/k8s/k8s.py
- sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
- sdk/python/feast/staging/storage_client.py
**What this PR does / why we need it**: fix azure e2e test
Fixes #
```release-note
NONE
```
> change azure https to wasbs and add azure creds to spark

- infra/docker/ci/Dockerfile
- sdk/python/feast/contrib/validation/ge.py
- sdk/python/feast/job_service.py
- sdk/python/feast/staging/entities.py
For some GE expectations - list of unexpected ids is not available. Instead we will report observed value.
Fixes #
```release-note
NONE
```
> Report observed value for aggregated checks in pre-ingestion feature validation

- sdk/python/feast/pyspark/launchers/aws/emr.py
Fix jar path handling in 0.8
```release-note
Fix jar path handling in EMR spark job launcher
```
> fix jar path handling in EMR launcher

- tests/e2e/test_online_features.py
Fixes #
```release-note
NONE
```
> Use Batch Ingestion in list_jobs test for simplicity

- CHANGELOG.md
- datatypes/java/README.md
- docs/advanced/audit-logging.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jobservice/Chart.yaml
- infra/charts/feast/charts/feast-jobservice/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/charts/prometheus-statsd-exporter/README.md
- infra/charts/feast/requirements.lock
- infra/charts/feast/requirements.yaml
- pom.xml
- spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Fixes #
```release-note
NONE
```
> Bump version to 0.9.0 & add changelog

- datatypes/java/README.md
- docs/advanced/audit-logging.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-jobservice/Chart.yaml
- infra/charts/feast/charts/feast-jobservice/README.md
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/charts/prometheus-statsd-exporter/README.md
- infra/charts/feast/requirements.lock
- infra/charts/feast/requirements.yaml
- pom.xml
- spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Fixes #
```release-note
NONE
```
> Bump version to 0.10.0-SNAPSHOT

- CHANGELOG.md
- docs/advanced/audit-logging.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-core/values.yaml
- infra/charts/feast/charts/feast-jobservice/Chart.yaml
- infra/charts/feast/charts/feast-jobservice/README.md
- infra/charts/feast/charts/feast-jobservice/values.yaml
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-jupyter/values.yaml
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/charts/feast-serving/values.yaml
- infra/charts/feast/charts/prometheus-statsd-exporter/README.md
- infra/charts/feast/requirements.lock
- infra/charts/feast/requirements.yaml
- pom.xml
- sdk/python/requirements-dev.txt
- sdk/python/setup.py
Fixes #
```release-note
NONE
```
> Bump version to 0.9.2

- sdk/python/feast/client.py
**What this PR does / why we need it**: catch potential error when getting sdk version and only get sdk version for telemetry
Fixes #
```release-note
NONE
```
> Fix client version method

- docs/concepts/entities.md
note -> not.
Fixes documentation typo.
N/A
```release-note
NONE
```
> Fixes typo in entities.md

- docs/README.md
- docs/concepts/architecture.md
Fixes a minor typo in docs as well as a missing hyperlink.
No.
```release-note
NONE
```
> Fix typo and link to concepts section

- common-test/pom.xml
- protos/feast/core/JobService.proto
Currently, list jobs api does not support project filter, and this may result in potential feature table name collisions across different feast projects. This PR updates list jobs proto.
Fixes #
```release-note
```
> Add project filter to list jobs proto

- docs/getting-started/install-feast/README.md
- docs/getting-started/install-feast/ibm-cloud-iks-with-helm.md
I am starting this PR to document Feast installation on a IKS cluster.
> Add IKS installation instruction

- docs/README.md
> Fix markdown emphasis

- docs/SUMMARY.md
- docs/getting-started/install-feast/README.md
- docs/getting-started/install-feast/kubernetes-azure-aks-with-helm.md
Installation guide for Feast on AKS. Have completed the whole process by working with @jklegar .
Provide installation guide for Feast on Azure Kubernetes Service (AKS)
Fixes #
None
No
```release-note
Add installation guide for Feast on Azure Kubernetes Service (AKS)
```
> Add installation guide for Feast on Azure Kubernetes Service (AKS)

- .github/workflows/master_only.yaml
- .github/workflows/release.yml
- infra/docker/jupyter/Dockerfile
Fixes a problem where `get_historical_features()` is not available in the latest release of the Python SDK (master)
```release-note
None
```
> Pin Jupyter Docker image Python SDK version to 0.9

- docs/specs/offline_store_format.md
Signed-off-by: Oleg Avdeev <oleg.v.avdeev@gmail.com>
Spec on offline store format, BigQuery only for now
```release-note
NONE
```
> Add offline store spec

- examples/hello-world/feast-hello-world.ipynb
This adds a notebook that walks the user through offline and online feature store usage. It shows the features of Feast with minimum yet clear (hopefully) commentary. Maybe it'll ease the learning for someone.
Disclaimer: probably I won't have time to polish it more, so if you don't like it as it is - sorry. ;)
EDIT: added a short example of online store usage.
```release-note
NONE
```
> Add a simple example notebook

- docs/getting-started/install-feast/README.md
Will let us get feedback from users on deployment options
Fixes #
```release-note
NONE
```
> Add feedback link to install docs page

- Makefile
- sdk/python/feast/client.py
- sdk/python/feast/data_format.py
- sdk/python/feast/data_source.py
- sdk/python/feast/entity.py
- sdk/python/feast/feature.py
- sdk/python/feast/feature_table.py
- sdk/python/feast/feature_view.py
- sdk/python/feast/infra/gcp.py
- sdk/python/feast/infra/key_encoding_utils.py
- sdk/python/feast/infra/local_sqlite.py
- sdk/python/feast/infra/provider.py
- sdk/python/feast/online_response.py
- sdk/python/feast/registry.py
- sdk/python/feast/type_map.py
- sdk/python/pyproject.toml
- sdk/python/setup.cfg
- sdk/python/tests/cli/online_read_write_test.py
- sdk/python/tests/feast_core_server.py
- sdk/python/tests/feast_serving_server.py
- sdk/python/tests/test_client.py
- sdk/python/tests/test_entity.py
- sdk/python/tests/test_feature_table.py
Reorgnize proto module in Python SDK to nest the protos in their own folder.
```release-note
None
```
> Move Python proto package into submodule

- sdk/python/docs/conf.py
- sdk/python/setup.py
Removes Kubernetes dependency and bumps GCS
```release-note
The Python Google Cloud Storage version must now be >= 2.0.0
```
> Update Python SDK dependencies

- docs/advanced/metrics.md
Fixed old urls that no longer work.
NONE
NONE
```release-note
```
> Fixed old urls in documentation

- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/gcp.py
- sdk/python/feast/infra/local_sqlite.py
- sdk/python/feast/infra/provider.py
- sdk/python/feast/repo_operations.py
- sdk/python/tests/cli/online_read_write_test.py
- sdk/python/tests/cli/test_cli_local.py
- sdk/python/tests/cli/test_datastore.py
- sdk/python/tests/cli/test_partial_apply.py
Make SDK apply call actually create underlying infra. 
```release-note
NONE
```
> Make partial apply create infra

- protos/feast/core/FeatureView.proto
- sdk/python/feast/feature_store.py
- sdk/python/feast/feature_view.py
- sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
**What this PR does / why we need it**: Add materialize_incremental method to materialize into online store from most recent end date
Fixes #
```release-note
Adds materialize_incremental method to materialize into online store from most recent end date
```
> Add materialize_incremental method

- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/gcp.py
- sdk/python/feast/infra/local_sqlite.py
- sdk/python/feast/infra/provider.py
- sdk/python/tests/cli/online_read_write_test.py
- sdk/python/tests/cli/test_online_retrieval.py
- sdk/python/tests/online_write_benchmark.py
* Use a transaction per (mini)batch of data, to improve write performance.
* Use a thread pool when writing.
* Make sure to retry failed transactions.
* Add a script to benchmark the performance.
Fixes #
```release-note
NONE
```
> Firestore ingestion perf improvements + benchmark script

- sdk/python/tests/test_feature_store.py
**What this PR does / why we need it**: Fixes test_feature_store fixture that was causing flaky errors
Fixes #
```release-note
NONE
```
> Fix flaky test_feature_store fixture

- sdk/python/requirements-ci.txt
- sdk/python/requirements-dev.txt
> Peg mypy dependencies version

- .github/workflows/complete.yml
- common-test/pom.xml
- infra/docker/ci/Dockerfile
- sdk/python/setup.cfg
> Fix failing tests

- CHANGELOG.md
- datatypes/java/README.md
- docs/contributing/development-guide.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feast-core/Chart.yaml
- infra/charts/feast/charts/feast-core/README.md
- infra/charts/feast/charts/feast-core/values.yaml
- infra/charts/feast/charts/feast-jobservice/Chart.yaml
- infra/charts/feast/charts/feast-jobservice/README.md
- infra/charts/feast/charts/feast-jobservice/values.yaml
- infra/charts/feast/charts/feast-jupyter/Chart.yaml
- infra/charts/feast/charts/feast-jupyter/README.md
- infra/charts/feast/charts/feast-jupyter/values.yaml
- infra/charts/feast/charts/feast-serving/Chart.yaml
- infra/charts/feast/charts/feast-serving/README.md
- infra/charts/feast/charts/feast-serving/values.yaml
- infra/charts/feast/requirements.lock
- infra/charts/feast/requirements.yaml
- infra/docker-compose/.env.sample
- pom.xml
Update v0.9-branch prior to tagging v0.9.5.
Fixes #
```release-note
NONE
```
> Update Changelog and Bump version to 0.9.5

- sdk/python/feast/data_source.py
- sdk/python/feast/feature_view.py
- sdk/python/feast/telemetry.py
- sdk/python/tests/test_feature_store.py
Ensures that proto conversion during registry save doesnt result in lost or corrupted state.
```release-note
NONE
```
> Add test to ensure saving and loading from registry is safe

- docs/quickstart.md
Fix docs
Fixes #
```release-note
```
> Remove duped pic

- CONTRIBUTING.md
**What this PR does / why we need it**: Fixes a typo in the instructions for contributing to the project.
Fixes #
```release-note
NONE
```
> pre-commit command typo fix in CONTRIBUTING.md

- sdk/python/setup.py
Fixes #
```release-note
NONE
```
> remove unnecessay path join in setup.py

- sdk/python/feast/feature_store.py
Signed-off-by: Jules Damji <dmatrix@comcast.net>
Minor fix to reference the correct Python retrieved job instance object in the example snippet API code
Fixes #
**Does this PR introduce a user-facing change?**: NONE
```release-note
```
> Minor doc fix in the code snippet: Fix to reference the right instance for the retrieved job instance object

- Makefile
- sdk/python/setup.py
Makes test go faster
Fixes #
```release-note
NONE
```
> Run python unit tests in parallel

- infra/charts/README.md
- infra/terraform/aws/helm.tf
- infra/terraform/azure/helm.tf
Adding feast jupyter link to chart's README.
+ Fix the helm 'feast-serving' name in aws/azure terraform.
Fixes #
None
NONE
> Update charts README

- sdk/python/feast/feature_store.py
- sdk/python/feast/inference.py
- sdk/python/feast/repo_operations.py
- sdk/python/tests/test_inference.py
Signed-off-by: David Y Liu <davidyliuliu@gmail.com>
Made inferencing methods more consistent with each other. Grouped inferencing statements together in apply methods for easier readability
Fixes #
```release-note
None
```
> Grouped inferencing statements together in apply methods for easier readability

- docs/SUMMARY.md
Fixes #
```release-note
NONE
```
> Link to offline and online store specs in docs summary

- sdk/python/setup.py
Fixes #1738 
```release-note
NONE
```
> Bump dependency on pyyaml

- docs/SUMMARY.md
Fixes #
```release-note
NONE
```
> Add Feature Service to the concepts group

- protos/feast/core/FeatureService.proto
- sdk/python/feast/feature_service.py
- sdk/python/tests/unit/test_feature_service.py
Fixes #1770 
```release-note
Added a description field to the Feature Service class and proto
```
> Add a description field the Feature Service class and proto

- examples/quickstart/quickstart.ipynb
This syncs the quickstart colab with the recent quickstart page updates.
See https://colab.research.google.com/drive/1A-OEdXArayNwG_F5iew51shV7AoFhpyP#scrollTo=a-PUsUWUxoH9 for this notebook in a notebook environment.
```release-note
NONE
```
> Updating quickstart colab to explain more concepts and highlight value prop of Feast

- .github/CODEOWNERS
**What this PR does / why we need it**: Add Felix & Danny to code owners file
Fixes #
```release-note
NONE
```
> Add Felix & Danny to code owners file

- sdk/python/feast/cli.py
The description of the on demand feature view CLI group says "feature view" and was missing the experimental tag.
Fixes #
```release-note
NONE
```
> Fixing odfv cli group description

- sdk/python/feast/feature_store.py
This PR saves the provider instance, and as such the offline and the online store instances. This will reduce the amount of time spent in functions involving them, as re-instantiation of these objects is no longer necessary. 
None
```release-note
None
```
> cache provider in feature store instance

- docs/SUMMARY.md
- docs/getting-started/architecture-and-components/overview.md
- docs/getting-started/concepts/feature-view.md
- docs/getting-started/faq.md
- docs/how-to-guides/adding-or-reusing-tests.md
- docs/reference/alpha-stream-ingestion.md
- docs/roadmap.md
GitBook's integration with documentation is no longer working well with our protected branch setup. In the meanwhile, this ports over changes that add basic documentation about how users can push streaming data into Feast
Fixes #
```release-note
NONE
```
> Adding stream ingestion alpha documentation

- CHANGELOG.md
Add changelog for v0.15.0
Fixes #
```release-note
NONE
```
> Add changelog for v0.15.0

- docs/getting-started/third-party-integrations.md
**What this PR does / why we need it**: This PR adds documentation on the standards for plugin repos. 
Fixes #
```release-note
NONE
```
> GitBook: [#1] Plugin standards documentation

- .github/workflows/pr_integration_tests.yml
**What this PR does / why we need it**: Once this PR lands, all subsequent approved PRs will upload AWS Lambda feature server docker images to ECR.
Fixes #
```release-note
NONE
```
> Upload feature server docker image to ECR on approved PRs

- .github/workflows/java_complete.yml
Needed for #2043 
Fixes #
```release-note
NONE
```
> Run java integration test with real google cloud and aws

- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
Fixes #
```release-note
NONE
```
> Dedicated workflow for java PRs

- Makefile
- sdk/python/feast/infra/provider.py
This isn't really needed and doesn't offer any meaningful performance benefit or change behaviour. To me this refactor is more readable, however, and makes it more clear exactly how the different elements are being dealt with.
Fixes #
```release-note
None
```
> Refactor `_convert_arrow_to_proto`

- docs/getting-started/concepts/feature-view.md
Fix a typo in the documentation for the FeatureView example.
NONE
NONE
```release-note
Fix typos in doc
```
> Fix typo in FeatureView example (doc)

- .github/workflows/java_master_only.yml
- .github/workflows/master_only.yml
- README.md
We have new java integration tests as well as a new workflow file for the existing integration tests / continuous build. This updates the workflow names and READMEs to reflect these changes.
Fixes #
```release-note
NONE
```
> Fix README to reflect new integration test suites

- protos/feast/core/InfraObjects.proto
- sdk/python/feast/infra/infra_objects.py
**What this PR does / why we need it**: This PR introduces the `Infra` and `InfraObject` classes, as well as associated proto objects, as part of the implementation of `feast plan`.
Fixes #
```release-note
NONE
```
> Add Infra and InfraObjects classes

- sdk/python/feast/infra/online_stores/dynamodb.py
When deleting dynamo table project name is not used, that leads to leakage in dynamo tables.
Fixes #
```release-note
none
```
> Use correct name when deleting dynamo table

- java/infra/docker/feature-server/Dockerfile
- java/storage/api/pom.xml
- java/storage/connectors/pom.xml
The docker image build on master is currently broken.
Fixes #
```release-note
none
```
> Fix issues with java docker building

- CHANGELOG.md
- infra/charts/feast/charts/feature-server/README.md
- infra/charts/feast/charts/feature-server/values.yaml
- infra/charts/feast/charts/transformation-service/README.md
- infra/charts/feast/charts/transformation-service/values.yaml
Update changelog for 0.17.0 and update helm charts
Fixes #
```release-note
none
```
> Update CHANGELOG for v0.17.0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Making the issue templates on GitHub automatically add kind/bug and kind/feature
Fixes #
```release-note
NONE
```
> Modify issue templates to automatically attach labels

- .github/ISSUE_TEMPLATE/bug_report.md
This will make all bug reports have a priority/p2 tag by default. Priorities can be adjusted manually afterwards.
Fixes #
```release-note
NONE
```
> Add default priority for bug reports

- sdk/python/setup.py
Fixes  #2223
```release-note
None
```
> Correct inconsistent dependency

- java/serving/src/main/java/feast/serving/registry/S3RegistryFile.java
…y with Java Feast Server
Signed-off-by: NalinGHub <nalinm01@gmail.com>
modify registry.db s3 object initialization to work in S3 subdirectories with Java Feast Server
Fixes https://github.com/feast-dev/feast/issues/2239
```release-note
NONE
```
> modify registry.db s3 object initialization to work in S3 subdirectory with Java Feast Server

- CHANGELOG.md
- infra/charts/feast-python-server/Chart.yaml
- infra/charts/feast-python-server/README.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feature-server/Chart.yaml
- infra/charts/feast/charts/feature-server/README.md
- infra/charts/feast/charts/feature-server/values.yaml
- infra/charts/feast/charts/transformation-service/Chart.yaml
- infra/charts/feast/charts/transformation-service/README.md
- infra/charts/feast/charts/transformation-service/values.yaml
- infra/charts/feast/requirements.yaml
- java/pom.xml
**What this PR does / why we need it**: Necessary for version bump
Fixes #
```release-note
NONE
```
> Update CHANGELOG.md and pom.xml for v0.18

- README.md
- docs/getting-started/third-party-integrations.md
- docs/roadmap.md
Fixes typos in docs
Fixes #
```release-note
NONE
```
> fix typos in markdown files

- sdk/python/feast/repo_operations.py
Fixes #2324
```release-note
Fix logging when running feast apply
```
> Switch order of views to keep/delete to fix apply logging

- infra/scripts/create-cluster.sh
Move scripts/create-cluster to the right place and add a hashbang.
Fixes #
```release-note
NONE
```
> refactor: Move create cluster script

- java/serving/src/test/java/feast/serving/util/DataGenerator.java
- protos/feast/core/Entity.proto
- sdk/python/feast/entity.py
- sdk/python/tests/integration/e2e/test_usage_e2e.py
- sdk/python/tests/integration/registration/test_feature_store.py
- sdk/python/tests/integration/registration/test_registry.py
- sdk/python/tests/unit/test_entity.py
**What this PR does / why we need it**: This PR adds the `owner` field to `Entity`. It also renames `labels` to `tags`, and cleans up some unused methods.
Fixes #
```release-note
Owner field added to Entity, and labels renamed to tags
```
> feat: Add owner field to Entity and rename labels to tags

- sdk/python/feast/infra/online_stores/dynamodb.py
User using a `DynamoDBOnlineStore` should be aware that he/she can load a lot of data at a time without worrying about it, because the implementation uses [BatchWriter](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/dynamodb.html#batch-writing) under the hood. 
Fixes #2346 
```release-note
NONE
```
> docs: Document DynamoDBOnlineStore public methods

- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
> chore: Adding basic usage tracking to Spark contrib plugin

- .github/workflows/pr_integration_tests.yml
**What this PR does / why we need it**: This PR ensures that a `lgtm` label triggers PR tests properly. 
Fixes #
> ci: Ensure lgtm triggers PR tests

- .releaserc.js
**What this PR does / why we need it**: This PR ensures that breaking changes (denoted by a prefix containing `!`, such as `feat!`) trigger minor releases, not major releases.
Fixes #
> ci: Modify release script to only do minor release for breaking changes

- sdk/python/feast/feature_store.py
Signed-off-by: Benjamin Tan <benjamintanweihao@gmail.com>
Fixes some inconsistencies in the docs and comments in the code.
> fix: Fix some inconsistencies in the docs and comments in the code

- sdk/python/feast/base_feature_view.py
- sdk/python/feast/feature_view.py
**What this PR does / why we need it**: This PR removes unnecessary methods from `FeatureView`.
Fixes #
> chore: Remove unnecessary methods from FeatureView

- OWNERS
- go/internal/feast/featurestore.go
@kevjumba isn't able to approve or lgtm changes
Fixes #
> chore: Add Kevin as an approver and reviewer

- go/internal/feast/featurestore.go
- sdk/python/feast/feature_store.py
> fix: Add inlined data sources to the top level registry

- docs/reference/data-sources/README.md
- docs/reference/data-sources/push.md
- sdk/python/docs/source/index.rst
Last piece in making push sources
Fixes #
> docs: Add docs for the push source

- java/serving/pom.xml
- java/serving/src/test/resources/docker-compose/feast10/definitions.py
The API was changed in #2442. This reference needs to be updated as well.
Fixes #
> fix: Fix the feature repo fixture used by java tests 

- go/internal/feast/ondemandfeatureview.go
- protos/feast/core/DataSource.proto
- sdk/python/feast/data_source.py
- sdk/python/feast/infra/offline_stores/bigquery_source.py
- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
- sdk/python/feast/infra/offline_stores/file_source.py
- sdk/python/feast/infra/offline_stores/redshift_source.py
- sdk/python/feast/infra/offline_stores/snowflake_source.py
This PR adds the description, tags, and owner fields to all data source classes: DataSource, KafkaSource, KinesisSource, SparkSource, BigQuerySource, SnowflakeSource, RedshiftSource, PushSource, RequestDataSource, and FileSource. 
DOES NOT BREAK current users as new api parameters are all optional.
Fixes #
> feat: Data Source Api Update

- sdk/python/feast/base_feature_view.py
- sdk/python/feast/feature_view.py
- sdk/python/feast/on_demand_feature_view.py
Kwargs are the preferred way to structure APIs for forwards/backwards compatibility reasons.
Fixes #
> fix: Update feature view APIs to prefer keyword args

- .github/workflows/publish.yml
The indentation was malformed.
Fixes #
> ci: Fix publish workflow yaml

- sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
We discovered that this was a red herring when investigating earlier failures. It was an issue in 0.19.1 of Feast, but was fixed 0.19.2+.
Fixes #
> fix: Remove spark from the AWS Lambda dockerfile

- .github/workflows/master_only.yml
- .github/workflows/publish.yml
- Makefile
- go.mod
- go.sum
- sdk/python/setup.py
Since we packaging python SDK with binary part (Go emebedded library) we need to publish package for each supported platform.
Fixes #
> chore: Build platform specific python package

- sdk/python/feast/feature_view.py
- sdk/python/tests/integration/feature_repos/universal/feature_views.py
> chore: Support passing list of Entities to a feature view definition

- .github/workflows/unit_tests.yml
- go/embedded/online_features.go
- sdk/python/tests/conftest.py
- sdk/python/tests/integration/feature_repos/repo_configuration.py
- sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/catalog/memory.properties
- sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/spark_data_source_creator.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/trino.py
This should help with testing #2517 
Fixes #
> chore: Update Trino data source creator to use testcontainers

- .github/workflows/unit_tests.yml
- sdk/python/tests/conftest.py
I think this is what's been blocking all other actions
Fixes #
> fix: Remove docker step from unit test workflow

- .releaserc.js
> ci: Fix release workflow by adding a comma

- java/serving/src/test/resources/docker-compose/feast10/definitions.py
Fixes PR #2509, since the java docker container pulls feast from latest master. We can only make the RequestSource change after merging into master.
Fixes #
> fix: Fix definitions.py with new definition

- infra/scripts/release/bump_file_versions.py
> fix: Bump the number of versions bumps expected to 27

- sdk/python/feast/type_map.py
Fixes data mapping errors for Snowflakes Variant data type
Fixes # None Filed
> fix: Fixed data mapping errors for Snowflake

- Makefile
- sdk/python/tests/conftest.py
> fix: Teardown trino container correctly after tests

- sdk/python/feast/repo_operations.py
> fix: Use cwd when getting module path

- sdk/python/feast/cli.py
Signed-off-by: Benjamin Tan <benjamin.tan@tech.jago.com>
Fix tiny typo in the CLI help.
> fix: Small typo in CLI

- docs/getting-started/faq.md
- docs/how-to-guides/running-feast-in-production.md
- docs/reference/alpha-aws-lambda-feature-server.md
- docs/reference/feast-cli-commands.md
> docs: Fix broken links in documentation

- docs/getting-started/faq.md
> docs: Fix broken FAQ link to push sources

- .github/workflows/publish.yml
> chore: Removing no telemetry release since it gives an InvalidMacaroon error

- sdk/python/feast/templates/aws/bootstrap.py
> fix: Fix AWS bootstrap template

- sdk/python/tests/integration/e2e/test_universal_e2e.py
> ci: Add some assertions in tests 

- sdk/python/feast/infra/passthrough_provider.py
- sdk/python/feast/repo_config.py
- sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
- sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
> chore: Make loading online and offline classes lazy

- sdk/python/feast/entity.py
- sdk/python/tests/example_repos/example_feature_repo_2.py
- sdk/python/tests/example_repos/example_feature_repo_version_0_19.py
- sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
- sdk/python/tests/integration/online_store/test_e2e_local.py
**What this PR does / why we need it**: This PR adds a feature repo that uses the SDK from version 0.19 and uses it in a test. The feature repo does not use a `FeatureService` or data sources other than a `FileSource`.
Fixes #
> chore: Add feature repo for version 0.19

- sdk/python/feast/diff/registry_diff.py
- sdk/python/feast/infra/offline_stores/file.py
> fix: Delete data sources from registry when using the diffing logic

- .github/workflows/pr_integration_tests.yml
> ci: Allow pr_integration_tests to also run on lgtm

- README.md
- infra/templates/README.md.jinja2
> chore: Fix README template to include Web UI command

- .github/workflows/unit_tests.yml
> ci: Run fewer macOS unit tests

- MANIFEST.in
- sdk/python/MANIFEST.in
- setup.py
verified by building an sdist using `python3 -m build` and checking in the listed files in the archive.
Fixes #
> fix: Include the ui/build directory, and remove package data

- .github/workflows/publish.yml
- setup.py
After all wheels are built we run additional step to install each wheel and verify that installed package is fully operational.
Fixes #
> chore: Test all wheels for basic functionality before publishing to pypi

- infra/charts/feast/Chart.yaml
- infra/scripts/release/bump_file_versions.py
> chore: Fix the version checker for upcoming release

- README.md
- docs/getting-started/architecture-and-components/online-store.md
- docs/getting-started/architecture-and-components/overview.md
- docs/getting-started/quickstart.md
- docs/roadmap.md
> fix: Fix broken roadmap links

- .github/workflows/master_only.yml
- .github/workflows/pr_integration_tests.yml
- Makefile
> ci: Use buildx for docker builds when changes merged into master

- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.7-ci-requirements.txt
- sdk/python/requirements/py3.7-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.8-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- setup.py
See https://docs.dask.org/en/stable/install.html for details. This is relevant if you use a FileSource that points to an S3 bucket.
This made it necessary to cap some versions of packages like boto + gcsfs because of conflicting downstream package dependencies with botocore versions.
Fixes #
> fix: Add S3FS dependency (which Dask depends on for S3 files)

- CONTRIBUTING.md
- Makefile
> ci: Use buildx for docker builds in remaining places as well

- Makefile
> chore: Build python protos inplace instead of build directory (for development)

- sdk/python/tests/integration/e2e/test_go_feature_server.py
- sdk/python/tests/integration/feature_repos/repo_configuration.py
Infer correct feature status in feature logging e2e test.
Fixes #
> fix: Correct feature statuses during feature logging test

- sdk/python/docs/Makefile
- sdk/python/docs/index.rst
- sdk/python/docs/requirements.txt
- sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.rst
- sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.tests.rst
- sdk/python/docs/source/feast.infra.offline_stores.contrib.spark_offline_store.rst
- sdk/python/docs/source/feast.infra.offline_stores.contrib.spark_offline_store.tests.rst
- sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.rst
- sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.tests.rst
- sdk/python/docs/source/feast.infra.online_stores.contrib.hbase_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.contrib.rst
- sdk/python/docs/source/feast.infra.utils.rst
- sdk/python/docs/source/feast.protos.feast.rst
- sdk/python/docs/source/feast.protos.feast.types.rst
- sdk/python/docs/source/feast.rst
- sdk/python/docs/source/feast.ui.rst
- sdk/python/docs/source/index.rst
Fix broken Python documentation, which occurred when setup.py got moved. (See https://readthedocs.org/projects/feast/builds/)
Also adds Postgres Registry Store + moves RequestSource / PushSource as subpages under data source
Also fixes `make html` to use the current environment so it can generate a preview of the html docs properly (respecting pyenv)
Fixes #
> chore: Fix RTD and update from make build-sphinx

- docs/SUMMARY.md
- docs/getting-started/feast-workshop.md
This adds the workshop link to getting-started
Fixes #
> docs: Add reference to workshop

- .github/workflows/unit_tests.yml
- sdk/python/feast/data_source.py
- sdk/python/feast/on_demand_feature_view.py
- sdk/python/tests/example_repos/example_feature_repo_version_0_19.py
- sdk/python/tests/integration/online_store/test_e2e_local.py
> chore: Add request source and ODFV to version 0.19 test repo

- .gitpod.yml
> chore: Fix gitpod init commands to generate go code

- docs/reference/feature-servers/go-feature-retrieval.md
- sdk/python/feast/cli.py
- sdk/python/feast/dqm/profilers/ge_profiler.py
- sdk/python/feast/embedded_go/online_features_service.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/feature_servers/aws_lambda/config.py
- sdk/python/feast/infra/feature_servers/base_config.py
- sdk/python/feast/infra/feature_servers/gcp_cloudrun/config.py
- sdk/python/feast/infra/feature_servers/local_process/config.py
- sdk/python/feast/repo_config.py
- sdk/python/feast/utils.py
- sdk/python/tests/integration/e2e/test_go_feature_server.py
- sdk/python/tests/integration/feature_repos/repo_configuration.py
All feature server configs now inherit base config, which include `feature_logging` property. Example:
```
feature_server:
enabled: True
feature_logging:
enabled: True
flush_interval_secs: 60
write_to_disk_interval_secs: 10
queue_capacity: 1000
emit_timeout_micro_secs: 10000
```
All fields in feature logging config are optional.
Fixes #
> chore: Configure feature logging via feature_store.yaml

- go/types/typeconversion.go
- sdk/python/feast/dqm/profilers/ge_profiler.py
- sdk/python/feast/dqm/profilers/profiler.py
- sdk/python/tests/integration/e2e/test_validation.py
1. Support null-type column in arrow to proto conversion
2. Set value to NaN for not found features when preparing dataset for validation
3. Add more useful information to validation result
Fixes #
> chore: Collection of small improvements for feature validation

- .github/workflows/pr_integration_tests.yml
- .github/workflows/unit_tests.yml
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/registry_stores/sql.py
- sdk/python/feast/registry.py
This PR introduces a base class for the methods that the Registry should support, and leaving the other methods in the current Registry class as implementation details.
Fixes #
> chore: Create a registry base class

- java/pom.xml
Updates Lombok to a newer version in order to address the error message described in https://stackoverflow.com/questions/66801256/java-lang-illegalaccesserror-class-lombok-javac-apt-lombokprocessor-cannot-acce 
N/A
> chore: Update Lombok to 1.18.24

- README.md
- docs/getting-started/third-party-integrations.md
- docs/roadmap.md
- sdk/python/docs/index.rst
- sdk/python/docs/source/feast.infra.registry_stores.rst
- sdk/python/docs/source/feast.infra.rst
- sdk/python/docs/source/feast.protos.feast.core.rst
- sdk/python/docs/source/feast.rst
- sdk/python/docs/source/index.rst
Add Cassandra plugin to roadmap + fix python docs for StreamFeatureView / SqlRegistry
Fixes #
> chore: Add Cassandra plugin to roadmap + fix docs for StreamFeatureView / SqlRegistry

- sdk/python/feast/infra/contrib/spark_kafka_processor.py
- sdk/python/feast/infra/contrib/stream_processor.py
**What this PR does / why we need it**: This PR adds the `StreamProcessor` ABC and the `SparkKafkaProcessor` implementation under `infra/contrib`. 
Fixes #
> feat: Add StreamProcessor and SparkKafkaProcessor as contrib

- java/common/src/main/java/feast/common/logging/entry/MessageAuditLogEntry.java
- java/common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
- java/sdk/src/main/java/dev/feast/RequestUtil.java
- java/serving/src/main/java/feast/serving/registry/LocalRegistryFile.java
- java/serving/src/main/java/feast/serving/registry/Registry.java
- java/serving/src/main/java/feast/serving/service/OnlineTransformationService.java
- java/storage/api/src/main/java/feast/storage/api/retriever/AvroFeature.java
Signed-off-by: yanghua <yanghua1127@gmail.com>
Refactor some minor issues when reading some java related modules.
Fixes #
> chore: Refactor some minor issues in Java modules

- docs/SUMMARY.md
- docs/getting-started/concepts/README.md
- docs/getting-started/concepts/registry.md
- docs/tutorials/tutorials-overview.md
- docs/tutorials/using-scalable-registry.md
- sdk/python/feast/infra/offline_stores/file.py
> docs: Add docs for SQL Registry

- go/internal/feast/featurestore.go
- go/internal/feast/model/featureview.go
- go/internal/feast/registry/registry.go
- sdk/python/feast/feature_store.py
- sdk/python/feast/inference.py
- sdk/python/feast/registry.py
- sdk/python/feast/stream_feature_view.py
- sdk/python/tests/integration/feature_repos/universal/feature_views.py
- sdk/python/tests/integration/online_store/test_universal_online.py
- sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
- sdk/python/tests/unit/test_feature_view.py
- sdk/python/tests/unit/test_feature_views.py
This reverts commit a06700dd81c9893e98f6709b82a6faa32be49915.
**What this PR does / why we need it**: This PR reverts #2798, which passed but causes tests to be extremely flaky, and is therefore currently blocking other PRs. I will take a closer look at #2798 and rewrite the testing logic so we can avoid causing more test flakiness.
Fixes #
> fix: Revert "feat: Enable stream feature view materialization (#2798)"

- docs/SUMMARY.md
- docs/getting-started/concepts/README.md
- docs/getting-started/concepts/stream-feature-view.md
- docs/reference/data-sources/README.md
- docs/reference/data-sources/kafka.md
- docs/reference/data-sources/kinesis.md
- docs/reference/data-sources/push.md
- docs/tutorials/building-streaming-features.md
> docs: Add docs for stream feature views and stream data sources

- README.md
- docs/roadmap.md
> fix: Update roadmap with stream feature view rfc

- sdk/python/feast/infra/registry_stores/sql.py
> chore: Fix unused lock from SqlRegistry

- README.md
- docs/roadmap.md
> chore: Update docs for stream transformations

- sdk/python/feast/errors.py
- sdk/python/feast/on_demand_feature_view.py
> chore: Improve SpecifiedFeaturesNotPresentError error message

- CHANGELOG.md
- infra/charts/feast-python-server/Chart.yaml
- infra/charts/feast-python-server/README.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feature-server/Chart.yaml
- infra/charts/feast/charts/feature-server/README.md
- infra/charts/feast/charts/feature-server/values.yaml
- infra/charts/feast/charts/transformation-service/Chart.yaml
- infra/charts/feast/charts/transformation-service/README.md
- infra/charts/feast/charts/transformation-service/values.yaml
- infra/charts/feast/requirements.yaml
- java/pom.xml
This reverts commit 327abd0274ff3acf701cac9b4fba65721eb387ce.
Fixes #
> fix: Revert "chore(release): release 0.22.0"

- .github/workflows/publish.yml
> ci: Fix publish workflow

- CHANGELOG.md
- infra/charts/feast-python-server/Chart.yaml
- infra/charts/feast-python-server/README.md
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feature-server/Chart.yaml
- infra/charts/feast/charts/feature-server/README.md
- infra/charts/feast/charts/feature-server/values.yaml
- infra/charts/feast/charts/transformation-service/Chart.yaml
- infra/charts/feast/charts/transformation-service/README.md
- infra/charts/feast/charts/transformation-service/values.yaml
- infra/charts/feast/requirements.yaml
- java/pom.xml
This reverts commit 73a482cbc7a870480a2da997bb6b44a147cc4321.
Fixes #
> chore: Revert "chore(release): release 0.22.0"

- .github/workflows/publish.yml
> ci: Disable Go for Python 3.10 release

- .github/workflows/publish.yml
> ci: Remove smoke test for Go for Python 3.10

- .github/workflows/publish.yml
> fix: Sync publish and build_wheels workflow to fix verify wheel error.

- .github/workflows/build_wheels.yml
- .github/workflows/publish.yml
> ci: Run git status before and after build to detect dirtyfiles

- go.mod
- go.sum
> ci: Update go.mod and go.sum

- .github/workflows/build_wheels.yml
- .github/workflows/publish.yml
Evidence of the process working: https://github.com/kevjumba/feast/actions/runs/2579509448
Fixes #
> chore: Reusable workflows to reuse build_wheels workflow in publish

- .github/workflows/build_wheels.yml
https://github.com/achals/feast/runs/7104820041?check_suite_focus=true
>   error: pathspec 'go.tar.gz' did not match any file(s) known to git
Fixes #
> ci: Restore specific files during build_wheels only

- java/CONTRIBUTING.md
- java/README.md
Just fixing broken links to feast documentation on java readme and contribution.
Fixes #
> fix: Fixing broken links to feast documentation on java readme and contribution

- java/pom.xml
https://mvnrepository.com/artifact/dev.feast/feast-datatypes/0.22.0 links to https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908 which is an issue with Guava. Simple enough to fix.
Fixes #
> fix: Bump version of Guava to mitigate cve

- sdk/python/tests/integration/feature_repos/repo_configuration.py
**What this PR does / why we need it**: Bug fix
Fixes #
> fix: Fix snowflake offline testing

- protos/feast/core/StreamFeatureView.proto
- sdk/python/feast/feature_view.py
- sdk/python/feast/stream_feature_view.py
Why duplicate code if we don't need to 
Fixes #
> chore: Refactor StreamFeatureViewMeta to FeatureViewMeta and dedupe

- sdk/python/feast/ui/package.json
- sdk/python/feast/ui/yarn.lock
- ui/package.json
I pushed a new NPM release for the UI model to fix recent issues. This updates Feast to use that new npm module (though strictly speaking, this isn't necessary because "^" includes newer patch releases
Fixes #
> chore: Update Feast UI dependency to reflect recent changes

- README.md
**What this PR does / why we need it**: to beautify README document on github view.
**Which issue(s) this PR fixes**: simply add a space between brackets
> fix: Resolve small typo in README file

- go/README.md
- go/embedded/online_features.go
- go/internal/feast/featurestore.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/server/logging/memorybuffer.go
- go/internal/feast/server/logging/memorybuffer_test.go
- sdk/python/feast/embedded_go/online_features_service.py
> chore: Fixes and Readme for python<>go interface

- .github/workflows/linter.yml
- go.mod
- go.sum
Related to this issue: https://github.com/actions/runner/issues/1997
Pending upstream changes https://github.com/go-python/gopy/pull/293 here. Will use fork for gopy for now.
Fixes #
> fix: Update gopy to point to fork to resolve github annotation errors.

- sdk/python/feast/repo_upgrade.py
> chore: More automated upgrades in repo definitions

- .github/workflows/pr_local_integration_tests.yml
- Makefile
- protos/feast/core/Registry.proto
- sdk/python/docs/source/feast.infra.materialization.rst
- sdk/python/docs/source/feast.infra.rst
- sdk/python/docs/source/feast.rst
- sdk/python/feast/driver_test_data.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/registry_stores/sql.py
- sdk/python/feast/project_metadata.py
- sdk/python/feast/registry.py
- sdk/python/feast/templates/gcp/driver_repo.py
- sdk/python/feast/templates/hbase/example.py
- sdk/python/feast/templates/local/example.py
- sdk/python/feast/usage.py
- sdk/python/tests/integration/feature_repos/repo_configuration.py
- sdk/python/tests/integration/registration/test_registry.py
- sdk/python/tests/integration/registration/test_sql_registry.py
Initial scaffolding of storing project level metadata in the registry
Fixes #
> chore: Add project metadata to registry

- .github/workflows/pr_local_integration_tests.yml
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/offline_stores/bigquery.py
- sdk/python/feast/utils.py
- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.8-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
- setup.py
Signed-off-by: Abhin Chhabra <abhin.chhabra@shopify.com>
I'm pulling out the GCP upgrades out of #2928 since that PR was going to get gnarly. This PR just focuses on GCP upgrades.
Partially completes #2906
> chore: Upgrade GCP dependencies

- .github/workflows/pr_local_integration_tests.yml
- sdk/python/tests/integration/offline_store/test_offline_write.py
> ci: Remove code coverage for now to keep from blocking other prs

- CONTRIBUTING.md
**What this PR does / why we need it**: fix a small typo in CONTRIBUTING.md
> fix: Fix typo in CONTRIBUTING.md

- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/offline_stores/bigquery.py
- sdk/python/feast/usage.py
- sdk/python/tests/integration/offline_store/test_offline_write.py
> chore: Fix test asserts for offline store write and improve some errors

- .github/workflows/build_wheels.yml
- sdk/python/feast/cli.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/repo_config.py
- sdk/python/tests/conftest.py
- sdk/python/tests/integration/e2e/test_go_feature_server.py
- sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
- sdk/python/tests/integration/feature_repos/repo_configuration.py
> chore: Add separate `go_feature_serving` flag

- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
…ps://github.com/feast-dev/feast/issues/2605)
Signed-off-by: leonpeng <kfiring@163.com>
Fixes #2605
> fix: Spark source support table with pattern "db.table"

- sdk/python/tests/integration/registration/test_sql_registry.py
> fix: Switch mysql log string to use regex

- README.md
- docs/README.md
This updates the intro Feast documentation page to clarify on:
- What Feast is
- What Feast doesn't fully do
- Who Feast is built for
- Example use cases
Fixes #
> docs: Update intro documentation page

- docs/getting-started/quickstart.md
The quickstart is missing an import.
Just updates the quickstart notebook.
> docs: Updated quickstart docs to import FeatureService

- sdk/python/feast/infra/online_stores/snowflake.py
- sdk/python/feast/templates/snowflake/feature_store.yaml
missed a line of code related to serialization
Fixes #
> fix: Snowflake_online_read fix

- docs/SUMMARY.md
- docs/getting-started/architecture-and-components/batch-materialization-engine.md
- docs/getting-started/architecture-and-components/overview.md
- docs/getting-started/architecture-and-components/stream-processor.md
- docs/how-to-guides/automated-feast-upgrade.md
> docs: Add docs for repo-upgrade and update architecture stuff

- CONTRIBUTING.md
updating CONTRIBUTION.md docs, it was missing `make` from `go build` which was preventing me from building the go client properly.
Fixes #
> docs: Updating CONTRIBUTION.md docs

- docs/SUMMARY.md
- docs/reference/offline-stores/overview.md
> docs: Small doc fixes

- Makefile
- docs/getting-started/concepts/feature-view.md
- docs/getting-started/quickstart.md
- docs/reference/feature-repository.md
- docs/reference/feature-repository/README.md
- go/internal/test/feature_repo/example.py
- java/serving/src/test/resources/docker-compose/feast10/definitions.py
- sdk/python/feast/entity.py
- sdk/python/tests/example_repos/example_feature_repo_version_0_19.py
- sdk/python/tests/example_repos/example_feature_repo_with_ttl_0.py
- sdk/python/tests/integration/materialization/test_lambda.py
- sdk/python/tests/unit/infra/test_inference_unit_tests.py
- sdk/python/tests/unit/infra/test_provider.py
- sdk/python/tests/unit/test_entity.py
- ui/feature_repo/features.py
> chore: Delete unused code in entity

- sdk/python/tests/integration/registration/test_sql_registry.py
> ci: Add example test for sql registry using in-memory sqlite

- Makefile
- docs/how-to-guides/adding-or-reusing-tests.md
- sdk/python/tests/unit/test_sql_registry.py
> chore: Update testing docs

- protos/feast/core/DataSource.proto
- sdk/python/feast/__init__.py
- sdk/python/feast/data_source.py
- sdk/python/feast/infra/offline_stores/bigquery_source.py
- sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py
- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
- sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
- sdk/python/feast/infra/offline_stores/file_source.py
- sdk/python/feast/infra/offline_stores/redshift_source.py
- sdk/python/feast/infra/offline_stores/snowflake_source.py
- sdk/python/tests/integration/feature_repos/universal/feature_views.py
- sdk/python/tests/integration/registration/test_feature_store.py
- sdk/python/tests/unit/infra/test_inference_unit_tests.py
- sdk/python/tests/unit/infra/test_local_registry.py
- sdk/python/tests/unit/local_feast_tests/test_e2e_local.py
- sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
- sdk/python/tests/unit/test_data_sources.py
- sdk/python/tests/unit/test_sql_registry.py
> chore: Delete unused code in data source

- .releaserc.js
> ci: Fix release process to find breaking changes

- docs/getting-started/concepts/feature-view.md
- docs/getting-started/concepts/point-in-time-joins.md
- docs/getting-started/quickstart.md
- docs/how-to-guides/automated-feast-upgrade.md
- docs/reference/data-sources/push.md
- docs/reference/feature-repository.md
- docs/reference/feature-repository/README.md
> docs: Change feature view docs to reflect new parameters

- sdk/python/feast/data_source.py
Fixes #
BREAKING CHANGE: Deprecate `RequestDataSource`.
> chore!: Deprecate request data source

- sdk/python/feast/errors.py
- sdk/python/feast/feature_store.py
- sdk/python/tests/unit/cli/test_cli_apply_duplicates.py
> chore: Remove outdated error message

- .github/fork_workflows/fork_pr_integration_tests_aws.yml
- .github/fork_workflows/fork_pr_integration_tests_gcp.yml
- .github/fork_workflows/fork_pr_integration_tests_snowflake.yml
- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
- .github/workflows/lint_pr.yml
- .github/workflows/master_only.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/publish.yml
- .github/workflows/unit_tests.yml
- CONTRIBUTING.md
- docs/SUMMARY.md
- docs/project/development-guide.md
- docs/project/maintainers.md
- sdk/python/tests/integration/feature_repos/repo_configuration.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
> chore: Add documentation for maintainer development

- sdk/python/feast/usage.py
> chore: Fix error where all calls register as test calls because typeguard imports unittest

- CONTRIBUTING.md
- docs/project/maintainers.md
- sdk/python/feast/infra/offline_stores/bigquery.py
> chore: Update maintainer docs with up to date instructions

- ui/CONTRIBUTING.md
- ui/src/custom-tabs/data-tab/DataQuery.tsx
- ui/src/custom-tabs/data-tab/DataTab.tsx
- ui/src/pages/feature-services/FeatureServiceListingTable.tsx
- ui/src/pages/feature-services/FeatureServiceOverviewTab.tsx
- ui/src/parsers/feastFeatureServices.ts
- ui/src/parsers/feastODFVS.ts
This is caused by the SQL registry not populating the created timestamp for feature services.
Also cleans some unused imports
Fixes #
> fix: Fixing Web UI, which fails for the SQL registry

- .github/workflows/java_pr.yml
- java/infra/docker/feature-server/Dockerfile
> ci: Fix build and ensure that building the java feature server is part of PR CI

- .github/workflows/java_pr.yml
> ci: Fix docker image java workflow to read from the right maven cache

- sdk/python/feast/infra/offline_stores/snowflake.py
> fix: Check if on_demand_feature_views is an empty list rather than None for snowflake provider

- sdk/python/feast/infra/passthrough_provider.py
- sdk/python/feast/infra/provider.py
> chore: Update provider docstrings

- sdk/python/feast/infra/offline_stores/snowflake.py
- sdk/python/feast/infra/offline_stores/snowflake_source.py
- sdk/python/feast/infra/online_stores/snowflake.py
- sdk/python/feast/infra/utils/snowflake_utils.py
Signed-off-by: Lisa Aiken <laiken@manifold.ai>
Fixes #
> feat: Add authentication option for snowflake connector

- sdk/python/feast/feature_service.py
- sdk/python/tests/unit/test_feature_service.py
Fixes #
BREAKING CHANGE: Deprecate the option to use positional arguments in feature services.
> chore!: Deprecate positional arguments for feature services

- docs/project/release-process.md
There are some missing pieces of the release notes. Also added more verification steps and documentation on how to maintain maintenance releases (older branches)
Fixes #
> docs: Improve release process notes

- .github/workflows/nightly-ci.yml
- infra/scripts/cleanup_dynamo_ci.py
This is to patch fix the random leaking DynamoDB tables in CI.
Fixes #
> ci: In nightly CI, cleanup dynamo tables related to integration tests

- sdk/python/feast/infra/offline_stores/bigquery.py
- sdk/python/feast/infra/online_stores/datastore.py
- sdk/python/feast/infra/online_stores/dynamodb.py
- sdk/python/feast/infra/utils/aws_utils.py
- sdk/python/feast/usage.py
This helps attribute cloud usage to Feast for partners
Fixes #
> chore: Add user agents for GCP/AWS services

- sdk/python/feast/infra/materialization/batch_materialization_engine.py
> chore: Update docstrings for batch materialization engine

- sdk/python/feast/feature_store.py
> chore: Update feature store docstrings

- sdk/python/docs/source/index.rst
> docs: Fix RTD

- sdk/python/tests/integration/materialization/test_snowflake.py
> fix: Teardown tables for Snowflake Materialization testing

- .github/workflows/nightly-ci.yml
Missing dep is causing failures in the nightly workflow
Fixes #
> ci: Fix dynamo cleanup workflow failure because of tqdm

- sdk/python/feast/infra/materialization/snowflake_engine.py
- sdk/python/feast/infra/offline_stores/snowflake.py
- sdk/python/feast/infra/offline_stores/snowflake_source.py
- sdk/python/feast/infra/online_stores/snowflake.py
- sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
- sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_creation.sql
- sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_deletion.sql
- sdk/python/feast/repo_config.py
- sdk/python/feast/templates/snowflake/bootstrap.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
> chore: Snowflake code cleanup

- docs/SUMMARY.md
- docs/reference/data-sources/README.md
- docs/reference/data-sources/bigquery.md
- docs/reference/data-sources/file.md
- docs/reference/data-sources/overview.md
- docs/reference/data-sources/postgres.md
- docs/reference/data-sources/redshift.md
- docs/reference/data-sources/snowflake.md
- docs/reference/data-sources/spark.md
- docs/reference/data-sources/trino.md
- docs/reference/offline-stores/README.md
- docs/reference/type-system.md
> docs: Add type system docs and add details to data source docs

- CONTRIBUTING.md
> chore: Update contrib docs

- sdk/python/docs/index.rst
> chore: Reorganize RTD docs

- sdk/python/docs/source/feast.infra.rst
- sdk/python/docs/source/feast.infra.transformation_servers.rst
- sdk/python/docs/source/index.rst
> chore: Add missing docs

- go/embedded/online_features.go
- go/internal/feast/onlineserving/serving.go
- go/internal/feast/transformation/transformation.go
- java/infra/docker/feature-server/Dockerfile
`maven:3.6-jdk-11` has been yanked from dockerhub: https://hub.docker.com/_/maven
Fixes #
> ci: Fix java feature server Dockerfile to use updated builder

- java/serving/src/main/java/feast/serving/service/config/ApplicationProperties.java
- java/serving/src/main/java/feast/serving/service/config/ApplicationPropertiesModule.java
The rest setting was not being used since the java server moved to being gRPC only. Specifying it is only likely to cause warnings/errors and confusion.
Should be a better solution instead of #3151 
Fixes #
> chore: Remove rest settings from java app properties

- .releaserc.js
- docs/how-to-guides/running-feast-in-production.md
- infra/charts/feast-feature-server/README.md
- infra/charts/feast-feature-server/README.md.gotmpl
- infra/charts/feast/README.md
- infra/charts/feast/README.md.gotmpl
> docs: Link to tutorials in helm charts

- docs/SUMMARY.md
- docs/how-to-guides/running-feast-in-production.md
- infra/charts/feast-feature-server/README.md
- infra/charts/feast-feature-server/README.md.gotmpl
> chore: Add more references to kubernetes for SEO for k8s

- sdk/python/feast/templates/aws/feature_repo/example_repo.py
- sdk/python/feast/templates/aws/feature_repo/test_workflow.py
- sdk/python/feast/templates/cassandra/feature_repo/example_repo.py
- sdk/python/feast/templates/cassandra/feature_repo/test_workflow.py
- sdk/python/feast/templates/gcp/feature_repo/example_repo.py
- sdk/python/feast/templates/gcp/feature_repo/test_workflow.py
- sdk/python/feast/templates/hbase/feature_repo/example_repo.py
- sdk/python/feast/templates/hbase/feature_repo/test_workflow.py
- sdk/python/feast/templates/local/README.md
- sdk/python/feast/templates/local/feature_repo/example_repo.py
- sdk/python/feast/templates/local/feature_repo/test_workflow.py
- sdk/python/feast/templates/postgres/feature_repo/example_repo.py
- sdk/python/feast/templates/postgres/feature_repo/test_workflow.py
- sdk/python/feast/templates/snowflake/README.md
- sdk/python/feast/templates/snowflake/feature_repo/driver_repo.py
- sdk/python/feast/templates/snowflake/test_workflow.py
> chore: Use push source in templates

- sdk/python/tests/integration/e2e/test_universal_e2e.py
- sdk/python/tests/utils/e2e_test_validation.py
I can't reproduce the error but I am pretty sure the error is due to requesting online features before the data is fully materialized.
Fixes #
> ci: Fix e2e test consistency flake

- sdk/python/feast/infra/materialization/snowflake_engine.py
- sdk/python/feast/infra/offline_stores/snowflake.py
- sdk/python/feast/infra/online_stores/snowflake.py
> fix: Snowflake config file search error

- infra/charts/feast/README.md
- infra/charts/feast/README.md.gotmpl
> docs: Update Java helm chart to point to up to date configuration

- sdk/python/feast/feature_server.py
Signed-off-by: Rob Howley
* add a /health endpoint to python feature server
* it returns 200 and nothing else
* for those not using helm, this is an easy uptime monitoring endpoint
Fixes #
> feat: Add health endpoint to py server

- docs/reference/online-stores/snowflake.md
> fix: Update Snowflake Online docs

- docs/getting-started/concepts/feature-retrieval.md
- docs/how-to-guides/running-feast-in-production.md
- sdk/python/feast/errors.py
- sdk/python/feast/infra/offline_stores/bigquery.py
- sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssql.py
- sdk/python/feast/infra/offline_stores/snowflake.py
- sdk/python/feast/templates/aws/feature_repo/test_workflow.py
- sdk/python/feast/templates/gcp/feature_repo/test_workflow.py
- sdk/python/feast/templates/snowflake/test_workflow.py
Tested this on the 3 quickstart templates I modified. Also added documentation changes to make this more clear
Fixes #
> chore: Add example of getting historical features with entity SQL

- infra/scripts/release/files_to_bump.txt
> chore: Fix bump files

- sdk/python/feast/infra/materialization/snowflake_engine.py
Signed-off-by: Miles <miles.adkins@snowflake.com>
Fixes #
> fix: Update snowflake materialization messages

- docs/getting-started/concepts/feature-retrieval.md
> chore: Fix header levels in feature retrieval page

- setup.py
Signed-off-by: miles.adkins <miles.adkins@snowflake.com>
Fixes #3237
> chore: Update snowflake dependencies

- sdk/python/feast/infra/online_stores/contrib/postgres.py
Signed-off-by: Steve Tran <NhuanTDBK@users.noreply.github.com>
Fixes #3173
> feat: Filter subset features in postgres #3174

- Makefile
- sdk/python/feast/data_source.py
- sdk/python/tests/unit/diff/test_registry_diff.py
Fixes #
https://github.com/feast-dev/feast/issues/3207
> fix: Enable users to upgrade a batch source into a push source

- OWNERS
- README.md
> chore: Add other maintainers to the OWNERS file for /lgtm commands

- docs/reference/offline-stores/bigquery.md
- docs/reference/offline-stores/mssql.md
- docs/reference/offline-stores/postgres.md
- docs/reference/offline-stores/redshift.md
- docs/reference/offline-stores/snowflake.md
- docs/reference/offline-stores/spark.md
- docs/reference/offline-stores/trino.md
- docs/reference/online-stores/cassandra.md
- docs/reference/online-stores/datastore.md
- docs/reference/online-stores/dynamodb.md
- docs/reference/online-stores/mysql.md
- docs/reference/online-stores/postgres.md
- docs/reference/online-stores/redis.md
- docs/reference/online-stores/snowflake.md
- docs/reference/providers/amazon-web-services.md
- docs/reference/providers/azure.md
- docs/reference/providers/google-cloud-platform.md
> docs: Add references to the extras users need to install and quickstarts

- sdk/python/feast/cli.py
- sdk/python/feast/constants.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/aws.py
- sdk/python/feast/infra/materialization/aws_lambda/lambda_engine.py
- sdk/python/feast/utils.py
- sdk/python/tests/unit/cli/test_cli.py
Signed-off-by: arcabucero <arcabucero@gmail.com>
Fixes #
> feat: Add possibility to define feature_store.yaml path with env variable

- sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
Signed-off-by: arcabucero <arcabucero@gmail.com>
Fixes #
> feat: Add request_timeout setting for cassandra online store adapter

- ui/public/registry.json
- ui/src/custom-tabs/TabsRegistryContext.tsx
- ui/src/custom-tabs/stream-fv-demo-tab/DemoCustomTab.tsx
- ui/src/custom-tabs/stream-fv-demo-tab/useDemoQuery.tsx
- ui/src/custom-tabs/types.ts
- ui/src/index.tsx
- ui/src/pages/feature-views/FeatureViewInstance.tsx
- ui/src/pages/feature-views/FeatureViewListingTable.tsx
- ui/src/pages/feature-views/StreamFeatureViewInstance.tsx
- ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx
- ui/src/pages/feature-views/useLoadFeatureView.ts
- ui/src/parsers/feastRegistry.ts
- ui/src/parsers/feastSFVS.ts
- ui/src/parsers/mergedFVTypes.ts
- ui/src/parsers/parseEntityRelationships.ts
- ui/src/queries/useLoadRegistry.ts
- ui/src/utils/custom-tabs/StreamFeatureViewCustomTabLoadingWrapper.tsx
Show stream feature view in Feast UI
Fixes #
> fix: Add stream feature view in the Web UI

- examples/quickstart/quickstart.ipynb
…
Signed-off-by: Francisco Javier Arceo <franciscojavierarceo@users.noreply.github.com>
Updated quickstart notebook to patch an incorrect reference to an outdated featureview name
Quickstart will fail because it's referencing outdated feature view
Fixes #
> fix: Updated quickstart notebook to patch an incorrect reference to an outdated featureview name

- .releaserc.js
- Makefile
- sdk/python/feast/ui/package.json
- sdk/python/feast/ui/yarn.lock
> fix: Fix Feast UI release process to update the feast-ui package 

- ui/src/pages/data-sources/DataSourcesListingTable.tsx
UI: Fixes bad datasource type in DataSource index view
> fix: Wrong UI data source type display

- setup.py
> chore: Update the minimum Python requirement on PyPI

- docs/reference/online-stores/redis.md
> docs: Add docs for redis ttl feature

- docs/reference/alpha-on-demand-feature-view.md
Fix docs for On-demand feature view
Missing import for on_demand_feature_view decorator
> docs: Add import for on_demand_feature_view

- docs/README.md
> docs: Fix broken hero image

- sdk/python/feast/templates/athena/feature_repo/feature_store.yaml
- sdk/python/feast/templates/athena/feature_repo/test_workflow.py
Signed-off-by: Youngkyu OH [toping4445@gmail.com]
Updated AWS Athena Template
> fix: Updated AWS Athena template

- docs/reference/feature-servers/python-feature-server.md
> docs: Fix docs on push API in feature server

- .github/workflows/master_only.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/unit_tests.yml
**What this PR does / why we need it**: The code coverage GH action is flaky. It has recently been failing a lot, which has blocked PRs from merging. We also do not use code coverage at all.
Fixes #
> ci: Remove code coverage upload

- docs/reference/batch-materialization/spark.md
- sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
See https://github.com/feast-dev/feast/issues/3331 for details
Fixes #
> fix: Enable Spark materialization on Yarn

- README.md
- infra/scripts/helm/validate-helm-chart-versions.sh
There was reformatting that made some references to the version on the same file line
Fixes #
> fix: Update the version counts

- sdk/python/feast/type_map.py
Signed-off-by: Hai Nguyen <quanghai.ng1512@gmail.com>
**What this PR does / why we need it**: This PR helps ODFV able to handle `boolean` native dtype from Pandas Dataframe
**Which issue(s) this PR fixes**: #3382
Fixes #3382
> fix: ODFV able to handle boolean pandas type

- .github/fork_workflows/fork_pr_integration_tests_gcp.yml
- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
- .github/workflows/master_only.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/publish.yml
- docs/project/maintainers.md
Otherwise, setting up gcloud fails because it's searching for a python SDK
Fixes #
> ci: Fix gcloud CI to have python installed

- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
- .github/workflows/master_only.yml
- .github/workflows/publish.yml
- infra/scripts/test-java-serving.sh
> ci: Remove need to download maven cache in CI

- .github/fork_workflows/fork_pr_integration_tests_gcp.yml
- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
- .github/workflows/master_only.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/publish.yml
- docs/project/maintainers.md
To fix issues with CI around:
"unrecognized arguments: --cred-file (did you mean '--flags-file'?)"
Fixes #
> ci: Fix workflows to use newer gcloud SDK

- sdk/python/feast/infra/registry/sql.py
- sdk/python/tests/unit/test_sql_registry.py
Note this only applies when provider="local"
Fixes #3292
> fix: Fix bug where SQL registry was incorrectly writing infra config around online stores

- docs/tutorials/using-scalable-registry.md
Per discussion in #3386, adding documentation on the additional steps required to use the registry with a Feast compatible backend that speaks a different SQLAlchemy dialect, with an aside explaining why such intervention isn't necessary for the online/offline stores.
Fixes #
> docs: Use registry with SQLAlchemy external dialect

- .devcontainer/devcontainer.json
Make it easier for people to develop feast
Fixes #
> feat: Add template for Github Codespaces

- docs/project/development-guide.md
Fix the expired link in the documentation.
It's a simple and very obvious fix. No specific issue ticket.
> docs: Update the expired link of the black coding style.

- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/registry/base_registry.py
- sdk/python/feast/infra/registry/registry.py
- sdk/python/feast/infra/registry/sql.py
> fix: Update registry.refresh to have a default arg

- ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx
Signed-off-by: hao-affirm <104030690+hao-affirm@users.noreply.github.com>
Fixes #
> fix: Stream feature view UI shows transformation issue

- OWNERS
> chore: Add gbmarc1 to OWNERs

- go.mod
- go.sum
Should supercede #3511 and #3508
> fix: Update go dependencies

- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
- .github/workflows/linter.yml
- .github/workflows/master_only.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/pr_local_integration_tests.yml
- .github/workflows/unit_tests.yml
- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
- setup.py
The pinned version of pip seems like it's incompatible with the version of pip-tools that we're using.
Fixes #
> chore: Update python dependencies and use the latest pip

- sdk/python/feast/cli.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/repo_config.py
- sdk/python/tests/conftest.py
- sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
- sdk/python/tests/integration/feature_repos/repo_configuration.py
- sdk/python/tests/integration/online_store/test_universal_online.py
- setup.py
As title. This cleans up dead/unused code from Feast.
Fixes #
> chore: Remove go server references

- .github/workflows/release.yml
> chore: Make publishing the UI to NPM optional

- sdk/python/feast/infra/offline_stores/file_source.py
> fix: Use pyarrow in a way that works across versions

- .github/workflows/build_wheels.yml
- .github/workflows/release.yml
Title. Going to CP this to v0.30-branch and cut a patch 
Fixes #
> fix(cI): Install coreutils in mac github workers for smoke test

- .github/workflows/release.yml
> chore: Fix invalid github action syntax

- sdk/python/feast/feast_object.py
Adds StreamFeatureViewSpec proto object to convenience type.  Adding this to make the convenience type complete.
> fix: Add StreamFeatureViewSpec to FeastObjectSpecProto convenience type

- docs/reference/online-stores/cassandra.md
- docs/reference/online-stores/overview.md
**What this PR does / why we need it**: Adds trivial URL to the documentation for providing better clarity
**Which issue(s) this PR fixes**: n/a
> docs: Trivial updates to documentation for better clarity

- sdk/python/feast/templates/snowflake/test_workflow.py
Fixes snowflake template so feature store instantiation happens after feast apply
Fixes #
> fix: Fix Snowflake template

- setup.py
Allows users to install Rockset specific packages with pip
Fixes #
> ci: Add 'rockset' as feast pip install extra

- protos/feast/serving/ServingService.proto
> docs: Fix proto docstring typo

- docs/reference/offline-stores/snowflake.md
- docs/reference/registry/snowflake.md
> docs: Add Snowflake registry bolierplate

- sdk/python/feast/infra/offline_stores/snowflake.py
> fix: Make snowflake to remote tables temporary

- ui/package.json
- ui/src/pages/data-sources/BatchSourcePropertiesView.tsx
- ui/yarn.lock
**What this PR does / why we need it**: to make bigquery data source more comprehensive
Fixes #3599
> feat: Show bigquery datasource table and query on UI

- sdk/python/feast/infra/online_stores/bigtable.py
SSIA
Without this, every time we call `FeatureStore.get_online_features()` a client is created and authentication runs which takes several seconds.
Client caching is done with other online stores as well. See [Datastore](https://github.com/feast-dev/feast/blob/v0.30.2/sdk/python/feast/infra/online_stores/datastore.py#L146-L151).
```
DEBUG:google.auth._default:Checking None for explicit credentials as part of auth process...
DEBUG:google.auth._default:Checking Cloud SDK credentials as part of auth process...
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 …
```
> feat: Cache Bigtable client

- .github/workflows/release.yml
> ci: Add dry run capability to web UI release

- .github/workflows/release.yml
> ci: Move `publish_ui` flag to correct location

- docs/project/development-guide.md
- java/CONTRIBUTING.md
- java/datatypes/pom.xml
- java/pom.xml
> docs: Updating contributing guide and also fixing some issues around M1 dev

- .github/workflows/unit_tests.yml
> ci: Fix MySQL installation issue on macOS

- sdk/python/feast/infra/utils/aws_utils.py
(simple modify) This pr is for passing argument to athena query execution
Fixes #
> fix: Missing Catalog argument in athena connector

- sdk/python/feast/infra/online_stores/redis.py
Manage the redis pipeline context of entity deletion.
Fixes #
> fix: Manage redis pipe's context

- sdk/python/feast/infra/offline_stores/bigquery.py
**What this PR does / why we need it**: Reduce bytes processed to 0 when retrieving entity df schema from BigQuery sql
Fixes #
> fix: Optimize bytes processed when retrieving entity df schema to 0

- .github/workflows/build_wheels.yml
> Switch from `macos-10.15` to `macos-latest`

- .github/fork_workflows/fork_pr_integration_tests_aws.yml
- .github/fork_workflows/fork_pr_integration_tests_gcp.yml
- .github/fork_workflows/fork_pr_integration_tests_snowflake.yml
- .github/workflows/build_wheels.yml
- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
- .github/workflows/linter.yml
- .github/workflows/master_only.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/pr_local_integration_tests.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/unit_tests.yml
> ci: Upgrade `checkout` Github Action

- .github/workflows/build_wheels.yml
- .github/workflows/release.yml
- .github/workflows/unit_tests.yml
> ci: Upgrade `setup-node` Github Action

- .github/workflows/build_wheels.yml
- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
> ci: Upgrade `upload-artifact` Github Action

- .github/workflows/build_wheels.yml
> ci: Temporarily disable smoke tests

- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.8-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
> fix: Update py3.8 ci requirements for cython 3.0 release

- sdk/python/feast/type_map.py
> fix: Add NUMERIC to bq_to_feast type map

- sdk/python/feast/cli.py
- sdk/python/feast/infra/offline_stores/file_source.py
- sdk/python/feast/proto_json.py
- sdk/python/feast/ui_server.py
- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.8-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- setup.py
Remove references to pkg_resources to remove those warnings, and fix a parquetdataset warning. Also remove the spammy info log level
Fixes #
> fix: Fix warnings from deprecated paths and update default log level

- sdk/python/feast/ui_server.py
to serve ui project successfully 
Fixes #3765
> fix: UI project cannot handle fallback routes

- java/pom.xml
- java/serving/src/main/java/feast/serving/service/config/ServingServiceV2Module.java
Should fix java integration tests
Fixes #
> fix: Update jackson and remove unnecessary logging

- java/pom.xml
- sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py
- setup.py
**What this PR does / why we need it**: support gcs file for bytewax materialization job to process
Fixes #
> feat: Support GCS filesystem for bytewax engine

- docs/project/development-guide.md
The development guide documentation omits compiling the protos but after building the source package you will observe a failure. It's sufficient to compile the protos so I have added this to the documentation.
Fixes #
> docs: Updated development guide to include compiling the protos

- setup.py
**What this PR does / why we need it**: `moto` package just recently released version 5.0.0 with some [breaking changes](https://github.com/getmoto/moto/blob/master/CHANGELOG.md), which potentially break our integration tests, so that the upper bound for the package is needed
N/A
**Note**: no need to re-compile requirements files since moto is still <5
> chore: Set upper bound for moto package

- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.8-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- setup.py
(I'm not sure the project has a super consistent pattern for when to specify a maximum version, but was going for the smallest possible change.)
> chore: Loosen fsspec requirements to allow recent releases

- sdk/python/feast/infra/materialization/snowflake_engine.py
- sdk/python/tests/integration/materialization/test_snowflake.py
**What this PR does / why we need it**: When using an entityless featureview with a Snowflake offline store it fails to materialize correctly.
Fixes # 3960
> fix: Fix for materializing entityless feature views in Snowflake

- sdk/python/feast/infra/offline_stores/file.py
- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.8-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- sdk/python/tests/integration/e2e/test_validation.py
- sdk/python/tests/integration/offline_store/test_feature_logging.py
- sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
- setup.py
Resume works from #3928
Fixes #3709
> feat: Pandas v2 compatibility

- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
**What this PR does / why we need it**: Remove a not used anywhere parameter when init SparkSource 
Fixes #
> fix: remove not use input parameter in spark source

- docs/reference/alpha-web-ui.md
- ui/README.md
It clarifies what type of values registryPath parameter in `projects-list.json` are supported.
Added a note in Feast Webui reference in regard to supported registryPath values
Related to #3974
> fix: Added registryPath parameter documentation in WebUI reference

- .github/workflows/unit_tests.yml
* Update unit_tests.yml to no longer run for Python 3.8
Fixes #
> feat: Dropping unit tests for Python 3.8

- .github/workflows/pr_integration_tests.yml
- .github/workflows/pr_local_integration_tests.yml
* Dropping Python 3.8 from local integration tests and integration tests
Fixes #
> feat: Dropping Python 3.8 from local integration tests and integration tests

- sdk/python/feast/infra/offline_stores/snowflake.py
- setup.py
**What this PR does / why we need it**: change in snowflake signature `fetch_arrow_all` in snowflake-connector-python 3.7. 
This fixes linting issues and forces users to use the updated method.
Refer to #3952 and upstream fix: https://github.com/snowflakedb/snowflake-connector-python/issues/1800
Fixes #
> chore: Increase snowflake-connector-python dependency to 3.7

- .github/workflows/pr_integration_tests.yml
> fix: Update actions/setup-python from v3 to v4

- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
**What this PR does / why we need it**:Raise error when not able read of file source spark source
Fixes #
> fix: Raise error when not able read of file source spark source

- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.8-ci-requirements.txt
- sdk/python/requirements/py3.8-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- setup.py
Having this pinned to an exact version increases the likelihood of conflict with user code or other libraries.
Changelog: https://github.com/nipunn1313/mypy-protobuf/blob/main/CHANGELOG.md
> chore: Loosen mypy-protobuf version constraint

- pyproject.toml
- setup.py
Update pyproject.toml to use Python 3.9 as default.
Fixes #
> feat: Update pyproject.toml to use Python 3.9 as default

- sdk/python/feast/usage.py
We get md5 error if the environment is FIPS enabled for python >=3.9. The error is 
```
Traceback (most recent call last):
File "/root/.local/bin/feast", line 5, in <module>
from feast.cli import cli
File "/root/.local/lib/python3.10/site-packages/feast/__init__.py", line 7, in <module>
from feast.infra.offline_stores.bigquery_source import BigQuerySource
File "/root/.local/lib/python3.10/site-packages/feast/infra/offline_stores/bigquery_source.py", line 6, in <module>
from feast.data_source import DataSource
File "/root/.local/lib/python3.10/site-packages/feast/data_source.py", line 28, in <module>
from feast.repo_config import RepoConfig, get_data_source_class_from_type
File "/root/.local/lib/python3.10/site-packages/feast/repo_config.py", line …
```
> fix: Hashlib md5 errors in FIPS for python 3.9+

- docs/reference/offline-stores/spark.md
- sdk/python/feast/templates/spark/feature_repo/feature_store.yaml
**What this PR does / why we need it**: When to_df for Spark Retrieval Job, we will need to transfer from spark dataframe to pandas dataframe, to be better handle this transfer process, I add a config to spark session, refer to https://docs.databricks.com/en/pandas/pyspark-pandas-conversion.html
Fixes #
> feat: Enable Arrow-based columnar data transfers 

- sdk/python/feast/infra/registry/contrib/postgres/postgres_registry_store.py
> chore: Deprecate PostgreSQLRegistryStore

- sdk/python/feast/infra/registry/sql.py
**Which issue(s) this PR fixes:**
Fixes https://github.com/feast-dev/feast/issues/4027
> fix: SqlRegistry _apply_object update statement

- sdk/python/tests/unit/test_on_demand_feature_view.py
Fixing type error in unit test
Fixes #
> feat: Update odfv test

- infra/charts/feast/requirements.yaml
> feat: Bumping requirements

- infra/charts/feast/requirements.yaml
> revert: Reverting bumping requirements

- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
Fixes the python feature server image startup issue
https://github.com/feast-dev/feast/issues/4095
> fix: Feature Server image startup in OpenShift clusters

- docs/reference/online-stores/hazelcast.md
Minor updates to Hazelcast documentation.    Removed references to alpha status and Viridian
> docs: Updated hazelcast docs

- docs/how-to-guides/customizing-feast/adding-a-new-offline-store.md
- docs/how-to-guides/customizing-feast/adding-support-for-a-new-online-store.md
This PR fixes command to run python tests in some parts of documentation.
> docs: Fix command to run python tests on documentation

- setup.py
change numpy version to <2 to avoid installation error
Fixes #4084
> fix: Change numpy version <1.25 dependency to <2 in setup.py

- docs/reference/online-stores/postgres.md
> fix: Update doc

- README.md
- docs/reference/beta-on-demand-feature-view.md
- docs/roadmap.md
- sdk/python/tests/unit/test_on_demand_python_transformation.py
- Updated the docs for the latest changes for ODFVs
- Move ODFVs to Beta from Alpha
- Update test case to explicitly test demo
> docs: Update on demand feature view documentation

- docs/SUMMARY.md
- docs/reference/data-sources/file.md
- docs/reference/data-sources/overview.md
- docs/reference/offline-stores/README.md
- docs/reference/offline-stores/duckdb.md
- docs/reference/offline-stores/overview.md
Add information about duckdb offline store to docs
> docs: Add DuckDB offline store

- Makefile
- README.md
- docs/reference/offline-stores/redshift.md
- sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/tests/data_source.py
- sdk/python/tests/integration/feature_repos/repo_configuration.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
- sdk/python/tests/integration/registration/test_feature_store.py
- sdk/python/tests/integration/registration/test_registry.py
- sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
Updates needed in code following AWS credential swap in Action secrets for CI executions.
> chore: Update CI-related AWS settings due to cred swap & global namespace issues

- sdk/python/feast/infra/offline_stores/duckdb.py
- sdk/python/feast/infra/offline_stores/ibis.py
This PR refactors ibis and duckdb codebase. FileSource-specific code has been extracted from ibis and migrated to duckdb.
> chore: Move FileSource handling from ibis to duckdb

- docs/reference/alpha-vector-database.md
Add the instruction document for vector database
> fix: Add vector database doc

- infra/charts/feast-feature-server/Chart.yaml
- infra/charts/feast-feature-server/README.md
- infra/charts/feast-feature-server/values.yaml
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feature-server/Chart.yaml
- infra/charts/feast/charts/feature-server/README.md
- infra/charts/feast/charts/feature-server/values.yaml
- infra/charts/feast/charts/transformation-service/Chart.yaml
- infra/charts/feast/charts/transformation-service/README.md
- infra/charts/feast/charts/transformation-service/values.yaml
- infra/charts/feast/requirements.yaml
- infra/feast-operator/Makefile
- infra/feast-operator/config/manager/kustomization.yaml
- infra/scripts/release/bump_file_versions.py
- java/pom.xml
- ui/package.json
```python
python infra/scripts/release/bump_file_versions.py 0.37.1 0.37.0 
```
Using script from https://github.com/feast-dev/feast/pull/4221
> chore: Revert 371 bump

- OWNERS
> chore: Add tokoko to OWNERS

- sdk/python/tests/utils/e2e_test_validation.py
> fix: Remove self assignment code line.

- sdk/python/feast/cli.py
Fix: Python feature server  no_feature_log argument error
Fixes #4254
> fix: Feature server no_feature_log argument error

- .github/fork_workflows/fork_pr_integration_tests_aws.yml
- .github/workflows/build_wheels.yml
- .github/workflows/master_only.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/publish.yml
Remove lambda feature server image from ci. This PR is needed to allow #4272 to proceed.
> chore: Remove lambda feature server image from ci

- .gitpod.Dockerfile
- .gitpod.yml
- .pre-commit-config.yaml
- Makefile
- sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/tests/data_source.py
- sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/tests/data_source.py
- sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/data_source.py
- sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
- sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/data_source.py
- sdk/python/tests/integration/feature_repos/repo_configuration.py
- sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
- sdk/python/tests/integration/feature_repos/universal/feature_views.py
- sdk/python/tests/integration/feature_repos/universal/online_store/elasticsearch.py
- sdk/python/tests/integration/feature_repos/universal/online_store/postgres.py
- sdk/python/tests/integration/feature_repos/universal/online_store_creator.py
- Updates gitpod.yaml to use uv/pixi
- fix bunch of linter issues under tests folder
- precommit now runs linter and formatter only for python (drops java)
> chore: Update gitpod.yaml with uv

- sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
> fix: Minor typo in the unit test.

- sdk/python/feast/offline_server.py
This PR adds parameters validation to the remote offline store server.
Which issue(s) this PR fixes:
Enhances https://github.com/feast-dev/feast/issues/4032
> refactor: Add parameters validation to OfflineServer

- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/materialization/kubernetes/k8s_materialization_engine.py
- sdk/python/feast/infra/online_stores/online_store.py
- sdk/python/feast/infra/passthrough_provider.py
- sdk/python/feast/infra/provider.py
- sdk/python/tests/foo_provider.py
- sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
> feat: Move get_online_features to OnlineStore interface

- infra/scripts/pixi/pixi.lock
- infra/scripts/pixi/pixi.toml
- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.11-ci-requirements.txt
- sdk/python/requirements/py3.11-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
Updating `sqlite_vec` package.
> chore: Upgrading sqlite_vec to latest package

- community/maintainers.md
Adding Tornike to maintainers.md.
> feat: Add Tornike to maintainers.md

- docs/reference/feature-servers/README.md
> fix: Remove typo.

- sdk/python/feast/repo_operations.py
- setup.py
> chore: Remove distutils

- docs/getting-started/faq.md
> docs: Update faq.md

- docs/getting-started/architecture-and-components/README.md
> docs: Update README.md to fix typo

- docs/SUMMARY.md
- docs/getting-started/architecture-and-components/README.md
Architecture page on our docs has a broken URL because of a typo in `language`
> chore: Update README.md to fix typo

- docs/getting-started/architecture-and-components/feature-transformetion.md
- sdk/python/feast/infra/materialization/snowflake_engine.py
- sdk/python/feast/infra/offline_stores/snowflake.py
- sdk/python/feast/infra/online_stores/snowflake.py
- sdk/python/feast/infra/registry/snowflake.py
- sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
> chore: Update feature-transformetion.md

- docs/getting-started/architecture/README.md
> chore: Update arch/README.md

- docs/getting-started/architecture/language.md
> chore: Update language.md

- community/ADOPTERS.md
Adding an adopters page to outline some companies that are using Feast. Would be good to get a full list similar to what's on the website.
> feat: Create ADOPTERS.md

- docs/SUMMARY.md
- docs/getting-started/architecture/README.md
- docs/getting-started/architecture/feature-transformation.md
- docs/getting-started/architecture/model-inference.md
- docs/getting-started/architecture/overview.md
Updating documentation on model inference. 
https://github.com/feast-dev/feast/issues/4414
> feat: Updating docs to include model inference guidelines

- Makefile
- docs/project/development-guide.md
> chore: Auto-detect python version in Makefile

- sdk/python/feast/registry_server.py
Adds health check service to remote registry service. Helps to deploy the registry service where health check endpoints are necessary.
> feat: Add health check service to registry server

- sdk/python/feast/infra/materialization/kubernetes/Dockerfile
- sdk/python/feast/repo_config.py
Fixes typos related to kubernetes materialization engine.
> fix: Typos related to k8s

- sdk/python/feast/templates/postgres/feature_repo/test_workflow.py
This PR changes tests so that it can properly locate `feature_store.yaml` from `__file__` instead of CWD, which only works when running `cd feature_ropo && python ./test_workflow.py`, but does not work when running `python feature_ropo/test_workflow.py`.
Not reported as an issue
> fix: Locate feature_store.yaml from __file__

- docs/roadmap.md
> feat: Update roadmap.md

- sdk/python/feast/templates/postgres/feature_repo/test_workflow.py
This PR add `--chdir` flag to test_workflow.py so that `python feature_ropo/test_workflow.py` would work.
Similar to #4443 but this PR fixes subprocesses
> fix: Add --chdir to test_workflow.py

- CODEOWNERS
Removes former contributors from CODEOWNERS
> chore: Cleanup CODEOWNERS

- sdk/python/feast/infra/registry/sql.py
- sdk/python/tests/integration/registration/test_universal_registry.py
… usecases
AWS Aurora provided various types of [endpoints](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html). Without reading from Reader Endpoints all the Reader Instances are Idle and all the traffic goes to Writer Instance only. This helps to redirect reads to Reader Instances and writes to Writer Instance. 
Can't exactly reproduce the usecase with multiple endpoints for tests so using two different kind of credentials for writes and reads to ensure the feature is working as expected.
> feat: Added support for reading from Reader  Endpoints for AWS Aurora use cases

- sdk/python/feast/infra/utils/postgres/connection_utils.py
> fix: Fix the mypy type check issue.

- examples/rbac-local/01.1-start-keycloak.ipynb
- examples/rbac-local/01.2-setup-keycloak.ipynb
- examples/rbac-local/01.3-setup-feast.ipynb
- examples/rbac-local/02-registry_server.ipynb
- examples/rbac-local/03-online_server.ipynb
- examples/rbac-local/04-offline_server.ipynb
- examples/rbac-local/README.md
- examples/rbac-local/client.ipynb
- examples/rbac-local/client/feature_store.yaml
A guided series of notebooks to showcase the RBAC feature in a local environment.
* Build an OIDC server
* A Feast sample repo
* A distributed Feast servers topology
* A test client to validate the RBAC permissions for the configured users
Second part of #4450
> chore: A full, minimal, reproducible example of the RBAC feature

- infra/charts/feast-feature-server/templates/deployment.yaml
- infra/charts/feast-feature-server/values.yaml
- sdk/python/feast/permissions/auth/kubernetes_token_parser.py
- sdk/python/feast/permissions/auth/oidc_token_parser.py
- sdk/python/feast/permissions/client/intra_comm_authentication_client_manager.py
- sdk/python/feast/permissions/enforcer.py
- sdk/python/feast/permissions/server/arrow.py
- sdk/python/feast/permissions/server/grpc.py
- sdk/python/feast/permissions/server/utils.py
Added Logger settings for feature servers and updated logger for permission flow
> fix: Logger settings for feature servers and updated logger for permission flow

- sdk/python/feast/infra/registry/snowflake.py
- sdk/python/feast/infra/registry/sql.py
Deletes data from feast_metadata table when we delete project
> fix: Deleting data from feast_metadata when we delete project

- docs/reference/alpha-vector-database.md
- docs/reference/online-stores/postgres.md
- sdk/python/feast/infra/online_stores/contrib/elasticsearch.py
- sdk/python/feast/infra/online_stores/contrib/postgres.py
- sdk/python/feast/infra/online_stores/sqlite.py
- sdk/python/feast/infra/online_stores/vector_store.py
- sdk/python/tests/integration/feature_repos/universal/online_store/postgres.py
- sdk/python/tests/unit/online_store/test_online_retrieval.py
Make all vector db config in one place and unify the config fields
> fix: Fix vector store config

- sdk/python/tests/unit/online_store/test_online_writes.py
> chore: Updated unit test

- sdk/python/tests/unit/online_store/test_online_writes.py
> chore: Updated test to include join_key

- sdk/python/feast/infra/materialization/snowflake_engine.py
- sdk/python/feast/infra/offline_stores/snowflake.py
- sdk/python/feast/infra/online_stores/snowflake.py
- sdk/python/feast/infra/registry/snowflake.py
Add the `connection_name` field to Snowflake config so that the configuration can be loaded from the canonical `connections.toml` file used by Snowflake connector for Python.
Fixes #4592
> feat: Add connection_name field to Snowflake config

- sdk/python/feast/feature_view.py
- sdk/python/tests/unit/test_on_demand_python_transformation.py
Testing post apply behavior for entity_columns and the returned Field
N/A
> chore: Adding additional dummy entity field test

- sdk/python/tests/integration/materialization/test_snowflake.py
> chore: Fix sf integration test

- docs/reference/beta-on-demand-feature-view.md
Update On Demand Feature View docs to outline transformation is on read.
> chore: Update beta-on-demand-feature-view.md

- infra/templates/README.md.jinja2
Adds star history to README https://star-history.com/#feast-dev/feast&Date
> chore: Update README to add star history

- README.md
> chore: Update compiled README

- docs/reference/beta-on-demand-feature-view.md
Adding documentation for On Demand Feature Transformations with writes
https://github.com/feast-dev/feast/issues/4376
Corresponds with https://github.com/feast-dev/feast/pull/4585
> feat: Adding documentation for On Demand Feature Transformations with writes

- community/ADOPTERS.md
> chore: Update Adopters to include myself

- sdk/python/feast/field.py
This PR updates the Field.__repr__() function to be inline with official python recommendations: https://docs.python.org/3/reference/datamodel.html#object.__repr__
"Called by the [repr()](https://docs.python.org/3/library/functions.html#repr) built-in function to compute the “official” string representation of an object. If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment)."
> chore: Change Field.__repr__ print format

- sdk/python/feast/feature_server.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/online_stores/online_store.py
- sdk/python/feast/infra/passthrough_provider.py
- sdk/python/feast/infra/provider.py
- sdk/python/tests/foo_provider.py
- sdk/python/tests/unit/test_feature_server.py
* make the /push endpoint async
* if pushing `to` online and async writes for the `OnlineStore` are supported, will call `await store.push`
* offline writes in the async codepaths utilize `run_in_threadpool`
* this pr only adds the calls and interface, there are no online stores that support async write
* added tests for when async vs sync calls of `store.push` happen in the server
> perf: Make /push async

- sdk/python/feast/entity.py
- sdk/python/feast/feature.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/field.py
This PR adds additional repr methods to several classes to make debugging easier.
> feat: Add more __repr__ methods

- sdk/python/tests/unit/test_repo_operations_validate_feast_project_name.py
Fix project name test
Broken master
> fix: Fix Feast project name test

- sdk/python/tests/integration/online_store/test_python_feature_server.py
- sdk/python/tests/integration/online_store/test_universal_online.py
> chore: Fix async get/push test setup

- docs/reference/feature-servers/python-feature-server.md
- docs/reference/online-stores/remote.md
- sdk/python/feast/cli.py
- sdk/python/feast/feature_server.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/online_stores/remote.py
- sdk/python/tests/integration/online_store/test_remote_online_store.py
- sdk/python/tests/utils/auth_permissions_util.py
- sdk/python/tests/utils/generate_self_signed_certifcate_util.py
Adding TLS(SSL) support for feast online server AKA feature server.
> feat: Adding SSL support for online server

- .github/workflows/build_wheels.yml
> chore: Update github action to remove make install-protoc-dependencies

- docs/reference/alpha-vector-database.md
Fixes typo in `docs/reference/alpha-vector-database.md`.
Changes " feature_tore.yaml" to " feature_store.yaml".
> docs: Fix typo feature_tore.yaml -> feature_store.yaml

- docs/project/release-process.md
chore: Update release process docs
> chore: Update release process docs

- .github/workflows/release.yml
- infra/feast-operator/bundle/manifests/feast-operator.clusterserviceversion.yaml
This will ensure future feast releases will properly build and version operator-specific release files.
> chore: Operator-specific release CI

- sdk/python/feast/infra/registry/registry.py
Support registry instantiation for read-only users. I'll add the test case in the next PR. 
Fixes #4715
> fix: Support registry instantiation for read-only users

- docs/reference/feature-servers/offline-feature-server.md
- docs/reference/feature-servers/python-feature-server.md
- docs/reference/online-stores/remote.md
- sdk/python/feast/cli.py
- sdk/python/feast/feature_server.py
- sdk/python/feast/feature_store.py
- sdk/python/feast/infra/online_stores/remote.py
- sdk/python/feast/infra/registry/remote.py
- sdk/python/feast/registry_server.py
- sdk/python/tests/conftest.py
- sdk/python/tests/integration/online_store/test_remote_online_store.py
- sdk/python/tests/unit/permissions/auth/server/test_auth_registry_server.py
- sdk/python/tests/utils/auth_permissions_util.py
Adding SSL(TLS) Support for registry server and remote registry client
> feat: Adding ssl support for registry server.

- sdk/python/feast/feature_server.py
fixes permissions assertion in `/materialize` and `/materialize-incremental`, see attached git issue
Fixes #4726
> fix: Incorrect type passed to assert_permissions in materialize endpoints

- docs/reference/beta-on-demand-feature-view.md
Adding docs outlining native Python transformations on singletons
N/A
https://github.com/feast-dev/feast/pull/4724
> feat: Adding docs outlining native Python transformations on singletons

- docs/getting-started/concepts/data-ingestion.md
> fix: Update data-ingestion.md

- docs/getting-started/concepts/dataset.md
- docs/getting-started/concepts/feature-view.md
- docs/getting-started/faq.md
- docs/tutorials/validating-historical-features.md
> chore: Updating broken links for on demand transformation

- sdk/python/feast/repo_config.py
> fix: Fix the config issue for postgres

- infra/feast-operator/Makefile
- infra/feast-operator/test/e2e/e2e_test.go
building the feast image as part of operator E2E testing.
> feat: Building the feast image

- Makefile
> fix: Fixing PGVector integration tests

- sdk/python/feast/driver_test_data.py
- sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
- sdk/python/feast/registry_server.py
- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.11-ci-requirements.txt
- sdk/python/requirements/py3.11-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- sdk/python/tests/data/data_creator.py
- sdk/python/tests/integration/online_store/test_remote_online_store.py
- sdk/python/tests/unit/cli/test_cli_apply_duplicates.py
- sdk/python/tests/unit/infra/offline_stores/test_snowflake.py
- sdk/python/tests/utils/cli_repo_creator.py
- setup.py
* Update a bunch of libraries so that I can update `testcontainers` so we can support `MilvusContainer` 
* Fix newly raised linter issues
N/A
N/A
> chore: Update packages and fix lint issues

- .github/workflows/build_wheels.yml
- .github/workflows/java_master_only.yml
- .github/workflows/java_pr.yml
Updating Upload Artifacts to v4
> chore: Updating Upload Artifacts to v4

- .github/workflows/publish.yml
> chore: Update publish to allow for manual trigger

- sdk/python/feast/cli.py
- sdk/python/feast/templates/couchbase/feature_repo/feature_store.yaml
- sdk/python/feast/templates/couchbase/gitignore
Adds a very basic template for bootstrapping Couchbase Online Store, to maintain consistency with the [docs page](https://docs.feast.dev/reference/online-stores/couchbase)
N/A
Will update this with Couchbase Offline Store, when its ready 🙂
> chore: Add Template for Couchbase Online Store

- sdk/python/feast/infra/online_stores/milvus_online_store/milvus_repo_configuration.py
- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.11-ci-requirements.txt
- sdk/python/requirements/py3.11-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- sdk/python/tests/integration/feature_repos/universal/online_store/milvus.py
- setup.py
This PR adds the libraries for Milvus, the container for testing it, and updates the requirements files.
N/A
> feat: Adding packages for Milvus Online Store

- sdk/python/docs/source/feast.infra.online_stores.cassandra_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.couchbase_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.elasticsearch_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.hazelcast_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.hbase_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.ikv_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.milvus_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.mysql_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.postgres_online_store.rst
- sdk/python/docs/source/feast.infra.online_stores.qdrant_online_store.rst
> chore: Update sphinx docs

- infra/feast-operator/dist/install.yaml
fix image version to match branch... this change failed during the last release push
> chore: Fix 0.42.0 operator image version

- infra/feast-operator/dist/install.yaml
fix operator image version
fix image version to match branch... this change failed during the last release push
> chore: Fix 0.42.0 operator image version (#4859)

- docs/SUMMARY.md
- docs/getting-started/components/README.md
- docs/getting-started/components/feature-server.md
- docs/getting-started/components/overview.md
> feat: Adding Feature Server to components docs

- .github/workflows/unit_tests.yml
chore: Update unit_tests.yml to use latest Mac OS
N/A
N/A
> chore: Update unit_tests.yml to use latest Mac OS

- sdk/python/tests/integration/feature_repos/repo_configuration.py
- sdk/python/tests/integration/online_store/test_universal_online.py
Commenting out Milvus tests and removing from integration tests configuration
NA
> chore: Commenting out Milvus tests and removing from integration tests configuration

- .github/workflows/pr_integration_tests.yml
> revert: Revert "chore: Add Milvus to pr_integration_tests.yml"

- infra/charts/feast-feature-server/Chart.yaml
- infra/charts/feast-feature-server/README.md
- infra/charts/feast-feature-server/templates/route.yaml
- infra/charts/feast-feature-server/values.yaml
We want to expose Feast UI to be able to access it from outside of the cluster and in OpenShift land, creating a Route object is one way to achieve that. That's why we added route template and updated values file accordingly.
> 🍭 ADD - Route definition

- infra/feast-operator/Makefile
`--load` flag is required
without it, this warning is displayed and the push fails -
```shell
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```
> fix: Fix integration operator push

- .github/workflows/java_master_only.yml
- .github/workflows/master_only.yml
We no longer need google cloud during the build stage of the `master_only.yml` workflow. Also, the retagged `feature-server-dev` CI image push is failing.
> fix: Remove unnecessary google cloud steps & upgrade docker action versions

- .github/workflows/master_only.yml
`feature-server-dev` image push component still failing
> fix: Change image push to use --all-tags option

- .github/workflows/build_wheels.yml
- .github/workflows/publish.yml
- .github/workflows/publish_helm_charts.yml
- .github/workflows/publish_images.yml
- .github/workflows/publish_java_sdk.yml
- .github/workflows/publish_python_sdk.yml
> fix: Updating release workflows to refer to yml instead of yaml

- .github/workflows/release.yml
- .releaserc.js
Ensures that the Operator release includes necessary versioned & generated manfests
> chore: Fix operator release workflow

- .github/workflows/release.yml
- .releaserc.js
Ensures that the Operator release includes necessary versioned & generated manfests
related to https://github.com/feast-dev/feast/pull/4936
> chore: Fix operator release workflow (v0.43-branch)

- infra/feast-operator/bundle/manifests/feast-operator.clusterserviceversion.yaml
- infra/feast-operator/dist/install.yaml
Relates to https://github.com/feast-dev/feast/pull/4937
> chore: Fix operator release for 0.43.0 (v0.43-branch)

- infra/feast-operator/Makefile
- infra/feast-operator/config/default/kustomization.yaml
- infra/feast-operator/config/default/related_image_fs_patch.tmpl
- infra/feast-operator/config/default/related_image_fs_patch.yaml
- infra/feast-operator/config/default/related_image_grpc_patch.yaml
- infra/feast-operator/internal/controller/services/services_types.go
- infra/feast-operator/internal/controller/services/util.go
- infra/feast-operator/test/e2e/e2e_test.go
- infra/scripts/release/files_to_bump.txt
Related to https://github.com/feast-dev/feast/pull/4940
> chore: Add ability to change default feature-server image during Operator deploy (v0.43-branch)

- infra/feast-operator/test/e2e/test_util.go
- infra/feast-operator/test/testdata/feast_integration_test_crs/v1alpha1_default_featurestore.yaml
- infra/feast-operator/test/testdata/feast_integration_test_crs/v1alpha1_remote_registry_featurestore.yaml
Relates to https://github.com/feast-dev/feast/pull/4940
> chore: Remove CR image from e2e samples

- .github/workflows/publish_images.yml
> chore: Fix publish, versions issue

- .github/workflows/build_wheels.yml
> fix publish, versions issue

- .github/workflows/publish_python_sdk.yml
> chore: Fix python-sdk workflow

- .github/actions/get-semantic-release-version/action.yml
- .github/workflows/build_wheels.yml
> chore: Remove checkout from get-version action

- .github/workflows/build_wheels.yml
> chore: Fixing build wheels pre-release image build

- infra/feast-operator/config/samples/kustomization.yaml
Add back the following simplistic sample to the bundle kustomization template.
```yaml
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
name: sample
spec:
feastProject: my_project
```
> chore: Operator bundle sample

- infra/feast-operator/config/overlays/odh/kustomization.yaml
- infra/feast-operator/config/overlays/odh/params.env
- infra/scripts/release/files_to_bump.txt
Update manifest to add feature server image for odh
> fix: Update manifest to add feature server image for odh

- infra/feast-operator/config/default/kustomization.yaml
- infra/feast-operator/config/default/related_image_grpc_patch.yaml
- infra/feast-operator/config/manager/manager.yaml
- infra/feast-operator/dist/install.yaml
- infra/feast-operator/internal/controller/featurestore_controller_test.go
- infra/feast-operator/internal/controller/services/services.go
- infra/feast-operator/internal/controller/services/services_types.go
- infra/feast-operator/internal/controller/services/util.go
Removing this grpcurl image dependency as it's unnecessary and, if possible, we should avoid third party deps.
Relates to https://github.com/feast-dev/feast/pull/4972
> fix: Remove grpcurl dependency (v0.43-branch)

- infra/feast-operator/config/overlays/odh/kustomization.yaml
- infra/feast-operator/config/overlays/odh/params.env
- infra/scripts/release/files_to_bump.txt
similar to #4973
* fix: update manifest to add feature server image for odh
* Update infra/scripts/release/files_to_bump.txt
---------
> fix: Update manifest to add feature server image for odh (v0.43)

- infra/feast-operator/Dockerfile
- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Switching to ubi8 for builder image OS
> chore: Switch base builder images to ubi8

- OWNERS
Added OWNERS file for OpenshiftCI
> feat: Added OWNERS file for OpenshiftCI

- docs/reference/feature-servers/python-feature-server.md
- sdk/python/feast/feature_server.py
Add retrieve_online_documents to REST API
> feat: Adding retrieve_online_documents endpoint

- .releaserc.js
Relates to https://github.com/feast-dev/feast/pull/5006
> chore: Ignore infra/feast-operator/bin during release

- .github/workflows/release.yml
- .releaserc.js
Relates to https://github.com/feast-dev/feast/pull/5006
> chore: Cleanup infra/feast-operator/bin during release

- .github/workflows/release.yml
Removed the dry-run flag to test and we will add it back later.
> fix: Removed the dry-run flag to test and we will add it back later.

- .github/workflows/release.yml
Changing refresh stable branch from step to a job. Using github credentials bot so that we can push the changes.
> feat: Changing refresh stable branch from step to a job. Using github credentials bot so that we can push the changes.

- .github/workflows/release.yml
setting the github_token explicitly to see if that solves the problem.
> fix: Setting the github_token explicitly to see if that solves the problem.

- .github/workflows/publish.yml
- community/maintainers.md
Remove java release from publish workflow as no one has asked for it and it hasn't worked in a while.
> chore: Remove java release from publish workflow

- community/maintainers.md
- Graduating some maintainers to Emeritus
> chore: Graduating some maintainers to Emeritus

- infra/feast-operator/config/component_metadata.yaml
- infra/scripts/release/files_to_bump.txt
added component_metadata file to show feast latest release in ODH operator
> chore: Added component_metadata file to show Feast latest release in ODH operator

- sdk/python/requirements/py3.10-ci-requirements.txt
- sdk/python/requirements/py3.10-requirements.txt
- sdk/python/requirements/py3.11-ci-requirements.txt
- sdk/python/requirements/py3.11-requirements.txt
- sdk/python/requirements/py3.9-ci-requirements.txt
- sdk/python/requirements/py3.9-requirements.txt
- setup.py
> chore: Updating sqlite-vec

- community/ADOPTERS.md
> chore: Update adopters list

- docs/README.md
- docs/getting-started/components/offline-store.md
Some broken/incorrect links were fixed.
> doc: Fix links

- sdk/python/feast/infra/feature_servers/local_process/config.py
> fix: Add transformation_service_endpoit to support Go feature server.

- infra/scripts/release/files_to_bump.txt
- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
> chore: Add value to version arg for feature-server image builds

- infra/scripts/release/files_to_bump.txt
- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
Relates to https://github.com/feast-dev/feast/pull/5069
> chore: Add value to version arg for feature-server image builds (stable branch)

- infra/feast-operator/test/utils/test_util.go
Made some changes to e2e tests for openshiftci
Needed for openshiftci to run the all the e2e tests correctly
> test: Fixes to e2e tests for openshiftci

- README.md
Build templates to sync the README with the latest roadmap.md changes, to avoid issues when using pre-push git hook for other contributers. 
N/A
Noticed it automatically did this when I tried to push after rebasing recently, figured I'd put it in a separate PR.
> chore: Sync README.md with roadmap.md

- Makefile
- infra/scripts/release/files_to_bump.txt
- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
- sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
Changes feature-server image Dockerfile to use a `requirements.txt` file for the installation.
> chore: Change the feature-server release container image to use a `requirements.txt` file for install

- Makefile
- infra/scripts/release/files_to_bump.txt
- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
- sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
Relates to https://github.com/feast-dev/feast/pull/5099
> chore: Change the feature-server release container image to use a `requirements.txt` file for install (stable)

- sdk/python/feast/infra/online_stores/singlestore_online_store/singlestore.py
This PR adds connector name to SingleStore's connection attributes for improved telemetry
> chore: Add connection attributes for SingleStore Online Store 

- docs/reference/alpha-vector-database.md
> Fix typo alpha-vector-database.md

- infra/feast-helm-operator/Makefile
> ci: Load docker build for helm-operator

- infra/feast-helm-operator/Makefile
> ci: Load docker build for helm-operator (cherry-pick)

- .releaserc.js
- sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
> ci: Add multicloud requirements file to release CI (cherry-pick)

- .releaserc.js
- sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
> ci: Add multicloud requirements file to release CI

- .github/workflows/build_wheels.yml
- .github/workflows/master_only.yml
- .releaserc.js
- infra/feast-helm-operator/Makefile
- sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
> ci: Build fixes (stable branch)

- infra/feast-operator/internal/controller/services/services.go
fix: Operator route creation for Feast UI in OpenShift
> fix: Operator route creation for Feast UI in OpenShift

- sdk/python/feast/infra/online_stores/dynamodb.py
Establishing http connections to DynamoDB is a time-consuming operation that can take significant amounts of time. See also "Reuse connections" in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TroubleshootingLatency.html. 
Manual testing suggests that DynamoDB keeps http connections alive for roughly 90s. This is in contrast to the 12s defined as a default in aiobotocore (cf. https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/config.py#L24). Note that the comment in the linked code section that references 20s appears to be incorrect.
This PR exposes a `keepalive_timeout` field that can be added to the configuration of DynamoDB online stores, which allows to override the default keep-alive timeout set by aiobotocore. In practice this allows the user to set a …
> feat: Make keep-alive timeout configurable for async DynamoDB connections

- ui/src/FeastUISansProviders.tsx
- ui/src/pages/Sidebar.tsx
- ui/src/pages/features/FeatureListPage.tsx
- ui/src/queries/useLoadRegistry.ts
Add UI page to see list of all features. This will allow users to see list of all features and make a search for it.
Screenshot :
> feat: Added UI for Features list

- README.md
- docs/SUMMARY.md
update the doc to add link for examples
added link offline server and registry server
removed the link for go-feature-server
> fix: Update the doc

- .github/workflows/linter.yml
Reverts unnecessary linter CI changes which have broken the PR "Auto-Merge" capability.
Relates to changes made in https://github.com/feast-dev/feast/pull/5193
> ci: Revert matrix changes to linter GH Action

- infra/website/src/styles/global.css
fixing the style of the integation logos 
after post [comment](https://github.com/feast-dev/feast/pull/5221#issuecomment-2779566625)
> fix: Styling

- docs/SUMMARY.md
- docs/getting-started/use-cases.md
- docs/tutorials/rag-with-docling.md
This PR adds documentation on the Milvus / Docling demo.
> feat: Add RAG tutorial and Use Cases documentation

- infra/feast-operator/config/overlays/rhoai/params.env
This is a requirement for RHOAI integration. It ensures we're using the exact same image build every time.
Relates to https://github.com/red-hat-data-services/RHOAI-Build-Config/pull/4312#issuecomment-2785267959
> chore: In operator `rhoai` overlay, use digest for cronjob image declaration

- .github/workflows/release.yml
> ci: Set release "next version" to 0.48.1

- CHANGELOG.md
- infra/charts/feast-feature-server/Chart.yaml
- infra/charts/feast-feature-server/README.md
- infra/charts/feast-feature-server/values.yaml
- infra/charts/feast/Chart.yaml
- infra/charts/feast/README.md
- infra/charts/feast/charts/feature-server/Chart.yaml
- infra/charts/feast/charts/feature-server/README.md
- infra/charts/feast/charts/feature-server/values.yaml
- infra/charts/feast/charts/transformation-service/Chart.yaml
- infra/charts/feast/charts/transformation-service/README.md
- infra/charts/feast/charts/transformation-service/values.yaml
- infra/charts/feast/requirements.yaml
- infra/feast-operator/Makefile
- infra/feast-operator/api/feastversion/version.go
- infra/feast-operator/bundle/manifests/feast-operator.clusterserviceversion.yaml
- infra/feast-operator/config/component_metadata.yaml
- infra/feast-operator/config/default/related_image_fs_patch.yaml
- infra/feast-operator/config/manager/kustomization.yaml
- infra/feast-operator/config/overlays/odh/params.env
- infra/feast-operator/config/overlays/rhoai/params.env
- infra/feast-operator/dist/install.yaml
- java/pom.xml
- sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
- sdk/python/feast/ui/package.json
- sdk/python/feast/ui/yarn.lock
- ui/package.json
* Fix milvus online_read ([#5233](https://github.com/feast-dev/feast/issues/5233)) ([4b91f26](https://github.com/feast-dev/feast/commit/4b91f26ded28c709a8aeb220c2a7ce34fbc91a7b))
* Resolve `no pq wrapper` import issue ([#5240](https://github.com/feast-dev/feast/issues/5240)) ([d5906f1](https://github.com/feast-dev/feast/commit/d5906f13125a4e63e3ae1f3a6c3830dda2c66d51))
This PR iteratores the version to 0.48.1 to match the latest release.
> chore: Cherry-pick release 0.48.1

- infra/scripts/offline-binary-build.sh
- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.binary
- sdk/python/feast/infra/feature_servers/multicloud/offline/pip_install_binary_exceptions.txt
This adds a script demonstrating an offline binary build.
> chore: Support "offline" binary builds of the `feature-server` image

- .github/workflows/operator-e2e-integration-tests.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/pr_local_integration_tests.yml
- .github/workflows/pr_remote_rbac_integration_tests.yml
- .github/workflows/smoke_tests.yml
- .github/workflows/unit_tests.yml
> chore: Fix tests so docs dont hold up merge

- .github/workflows/java_pr.yml
- .github/workflows/operator-e2e-integration-tests.yml
- .github/workflows/operator_pr.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/pr_local_integration_tests.yml
- .github/workflows/pr_remote_rbac_integration_tests.yml
- .github/workflows/smoke_tests.yml
> chore: Fix actions to not run and give passing status on doc changes

- examples/rag-docling/docling-quickstart.ipynb
Updating example demo with new skip transformation on write
> chore: Updating example demo with new skip transformation on write

- docs/getting-started/architecture/write-patterns.md
- docs/getting-started/concepts/data-ingestion.md
- docs/reference/beta-on-demand-feature-view.md
> docs: Update documentation for transform_on_write functionality

- docs/how-to-guides/running-feast-in-production.md
- docs/reference/feature-servers/offline-feature-server.md
- docs/reference/feature-servers/python-feature-server.md
- docs/roadmap.md
- infra/feast-operator/README.md
- infra/feast-operator/config/samples/kustomization.yaml
- infra/feast-operator/config/samples/v1alpha1_featurestore_all_remote_servers.yaml
- infra/feast-operator/config/samples/v1alpha1_featurestore_with_ui.yaml
This PR adds some initial Operator related docs to the existing how-to guides. It also switches several helm chart deployment doc references to using the operator instead.
> docs: Improve Operator-related docs in how-to guides

- docs/how-to-guides/running-feast-in-production.md
- docs/reference/feature-servers/offline-feature-server.md
- docs/reference/feature-servers/python-feature-server.md
Docs page handles link formatting differently than basic Markdown.
> docs: Minor link fixes

- infra/feast-operator/Dockerfile
- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
- sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.builder.yarn
- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.builder.yum
Relates to https://github.com/feast-dev/feast/issues/4920
> chore: Upgrade operator and feature-server images to ubi9

- infra/scripts/offline-binary-release-build.sh
- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.binary.release
- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.builder.yarn
- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.builder.yum
The switch to a ubi9 base image broke the offline feature-server build scripts.
Relates to https://github.com/feast-dev/feast/pull/5306
> chore: Fix ubi9 offline builds

- README.md
- docs/how-to-guides/customizing-feast/creating-a-custom-materialization-engine.md
Updating the `creating-a-custom-materialization-engine.md` docs such that they work with the latest module structure. Currently this code is misleading and does not work with a `0.49.0` install.
N/a
N/a
> docs: updating the creating-a-custom-materialization-engine.md docs to work with the latest import paths

- ui/src/components/GlobalSearchShortcut.tsx
- ui/src/components/RegistrySearch.tsx
- ui/src/pages/Layout.tsx
- ui/src/pages/ProjectOverviewPage.tsx
This Pull Request introduces multiple enhancements and updates to improve user experience, particularly focusing on global search functionality and registry search. Below is a detailed summary of the changes:
---
1. **Global Search Shortcut**:
- A new `GlobalSearchShortcut` component has been added to enable a quick search experience across the application.
- Users can now press a shortcut (`⌘K`) to quickly open a global search modal.
2. **Enhanced Registry Search**:
- The `RegistrySearch` component is now equipped with:
- A `forwardRef` for imperative handle-based interactions.
- A method to programmatically focus the search input (`focusSearchInput`).
- Additional styling and layout improvements:
- Sticky page headers for search results.
- Clearer visual hierarchy for search results …
> chore: Improved search UI fix

- sdk/python/feast/infra/offline_stores/dask.py
- sdk/python/tests/utils/feature_records.py
Fixes dask condition to pull latest data point. 
Fixes #5228
> fix: Dask pulling of latest data

- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.builder.yum
- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.sdist
- sdk/python/feast/infra/feature_servers/multicloud/offline/Dockerfile.sdist.release
- sdk/python/feast/infra/feature_servers/multicloud/offline/artifacts.lock.yaml
- sdk/python/feast/infra/feature_servers/multicloud/offline/hermeto-generic-artifacts.sh
- sdk/python/feast/infra/feature_servers/multicloud/offline/offline-binary-build.sh
- sdk/python/feast/infra/feature_servers/multicloud/offline/offline-binary-release-build.sh
- sdk/python/feast/infra/feature_servers/multicloud/offline/offline-build.sh
- sdk/python/feast/infra/feature_servers/multicloud/offline/offline-release-build.sh
- sdk/python/feast/infra/feature_servers/multicloud/offline/rpms.lock.yaml
- Upgrade `hermeto` to v0.25.0
- Pre-fetch rpms w/ new `sdk/python/feast/infra/feature_servers/multicloud/offline/rpms.lock.yaml` file... generated from https://github.com/red-hat-data-services/rpm-lockfile-runner/tree/feast
- Pre-fetches wheels for `milvus-lite` & `ibis-framework`.
Relates to https://github.com/feast-dev/feast/pull/5193
> chore: Add rpms & milvus-lite / ibis binaries to hermeto fetcher for offline builds

- infra/feast-operator/config/samples/v1alpha1_featurestore_gcs.yaml
This PR provides an Operator sample for users who leverage GCS.
Relates to https://github.com/feast-dev/feast/discussions/5335
> docs: Add GCS example to Operator samples dir

- infra/templates/README.md.jinja2
- sdk/python/docs/source/conf.py
- sdk/python/docs/source/feast.api.registry.rest.rst
- sdk/python/docs/source/feast.api.registry.rst
- sdk/python/docs/source/feast.api.rst
- sdk/python/docs/source/feast.cli.rst
- sdk/python/docs/source/feast.infra.common.rst
- sdk/python/docs/source/feast.infra.compute_engines.local.backends.rst
- sdk/python/docs/source/feast.infra.compute_engines.local.rst
- sdk/python/docs/source/feast.infra.compute_engines.rst
- sdk/python/docs/source/feast.infra.compute_engines.spark.rst
- sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
- sdk/python/docs/source/feast.infra.rst
- sdk/python/docs/source/feast.infra.utils.rst
- sdk/python/docs/source/feast.rst
- sdk/python/docs/source/feast.transformation.rst
Updated readthedocs python API documentation - https://rtd.feast.dev/en/master/
> chore: Updated python documentation

- sdk/python/feast/infra/offline_stores/contrib/clickhouse_offline_store/clickhouse.py
- sdk/python/feast/repo_config.py
This PR adds Clickhous offline store to OFFLINE_STORE_CLASS_FOR_TYPE map.
> fix: Add clickhouse to OFFLINE_STORE_CLASS_FOR_TYPE map

- sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
> Revert "fix: Update milvus connect function to work with remote instance"

- sdk/python/feast/infra/materialization/aws_lambda/lambda_engine.py
While working with the Lambda materialization engine we had to make a couple of changes to make it work for us.
1. The read timeout for the Lambda client is increased to the Lambda timeout + 10 s. The default value is 60 s which caused failures when Lambda functions were running longer than the read timeout.
2. The case is handled when no feature updates and thus no files are exported for the given time range. Before, an exception was raised because `ThreadPoolExecutor` does not accept `max_workers=0`.
3. Functionality to retry invocation of Lambda functions is added in case that a function times out. Such timeouts were observed when new features are materialized initially with a large number of historical feature updates. DynamoDB, which we use as online store, cannot handle the write …
> feat: Improvements to Lambda materialization engine

- ui/package-lock.json
- ui/package.json
- ui/yarn.lock
> chore: Fix some UI package issues

- README.md
- examples/operator-rbac-openshift-tls/1-setup-operator-rbac.ipynb
- examples/operator-rbac-openshift-tls/2-client-rbac-test-pod.ipynb
- examples/operator-rbac-openshift-tls/3-uninstall.ipynb
- examples/operator-rbac-openshift-tls/README.md
- examples/operator-rbac-openshift-tls/client/admin_user_deployment_tls.yaml
- examples/operator-rbac-openshift-tls/client/feature_repo/feature_store.yaml
- examples/operator-rbac-openshift-tls/client/feature_repo/test.py
- examples/operator-rbac-openshift-tls/client/readonly_user_deployment_tls.yaml
- examples/operator-rbac-openshift-tls/client/unauthorized_user_deployment_tls.yaml
- examples/operator-rbac-openshift-tls/permissions_apply.py
- examples/operator-rbac/3-client-rbac-test-local.ipynb
- infra/feast-operator/config/samples/v1alpha1_featurestore_all_openshift_non_tls.yaml
> docs: Feast Operator documentation showing feature-server API interaction

- infra/feast-operator/test/utils/test_util.go
Providing polling mechanism and Increasing timeout for E2E Test TestApplyAndMaterializeFeastDefinitions
> fix: Fix polling mechanism for TestApplyAndMaterialize

- sdk/python/feast/rag_retriever.py
This PR makes necessary updates to the generate_answer function in the FeastRagRetriever. In testing a jupyter notebook example I noticed that a numpy array was expected by the retrieve function but a tensor was being passed in. This is now fixed, has been tested and works correctly.
N/A
@franciscojavierarceo please take a look.
> fix: Update generate_answer function to provide correct parameter format for retrieve function

- OWNERS
Adding myself and @jyejare to red hat CI approvers.
> chore: Added ntkathole and jyejare to red hat CI approvers

- .github/workflows/build_wheels.yml
> chore: Removing 3.9 from build-wheels

- sdk/python/feast/infra/compute_engines/local/backends/polars_backend.py
Currently materialization fails when using the `PolarsBackend` as the `columns` method has no implementation. Worse still, rather than raising a `NotImplementedError` it fails silently by returning nothing which gets interpreted as `None`.
This provides a valid implementation that allows the `feast materialize ...` command to run successfully.
N/a
N/a
> fix: Correct column list polars materialization engine

- .github/workflows/registry-rest-api-tests.yml
- sdk/python/tests/registry_rest_api_tests/conftest.py
- sdk/python/tests/registry_rest_api_tests/resource/feast-registry-nginx.yaml
- sdk/python/tests/registry_rest_api_tests/resource/feast_config_credit_scoring.yaml
- sdk/python/tests/registry_rest_api_tests/resource/feast_config_driver_ranking.yaml
- sdk/python/tests/registry_rest_api_tests/resource/feast_config_rhoai.yaml
- sdk/python/tests/registry_rest_api_tests/resource/postgres.yaml
- sdk/python/tests/registry_rest_api_tests/resource/redis.yaml
- sdk/python/tests/registry_rest_api_tests/support.py
- sdk/python/tests/registry_rest_api_tests/test_feast_registry.py
Added Feast Registry Server Rest Tests
- Added test setup for both openshift and kind cluster environment setup 
- Configured Feature store instances via feast operator with multiple projects setup
- Configure s3 registry setup for openshift cluster env setup
> test: Add Feast Registry Server Rest Test
