sdk/python/feast/driver_test_data.py
**What this PR does / why we need it**: This ensures the get_historical_features call in the quickstart doesn't return NaNs
Fixes #
```release-note
NONE
```
=> Add a fixed timestamp to quickstart data

docs/quickstart.md, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/setup.py
**What this PR does / why we need it**: Move GCP-specific packages into feast[gcp]
Fixes #
```release-note
`pip install feast` now has fewer requirements, and in order to use Feast with GCP the user will need to install the GCP-specific requirements with `pip install feast[gcp]`
```
=> Make gcp imports optional

sdk/python/feast/cli.py
**What this PR does / why we need it**: Adds opt-out telemetry to `feast init`, `feast apply`, `feast teardown`, and `feast registry-dump` which were not covered by existing opt-out telemetry.
Fixes #
```release-note
Opt-out telemetry (usage logging) added to several feast CLI commands. To opt out, see https://docs.feast.dev/v/master/feast-on-kubernetes/advanced-1/telemetry
```
=> Add optional telemetry to other CLI commands

.github/pull_request_template.md
Update broken urls in the github pr template file
NONE
=> Update broken urls in the github pr template file

sdk/python/setup.py
Feast pins the grpcio dependency version to 1.31.0, which makes hard to use with other packages that requires higher version. (In our case it's Dagster , that requires >=1.32.0 ) 
This PR changes the grpcio version from 1.31.0 to 1.32. (Happy to change it even further) 
Haven't opened an issue, but happy to do if you want. 
Fixes #
NONE
=> Upgrade grpcio version in python SDK

docs/roadmap.md
Adds our current roadmap to Feast our documentation
```release-note
NONE
```
=> Add roadmap to documentation

sdk/python/feast/data_source.py, sdk/python/feast/feature_view.py, sdk/python/feast/type_map.py, sdk/python/tests/example_feature_repo_with_inference.py, sdk/python/tests/fixtures/data_source_fixtures.py, sdk/python/tests/test_feature_store.py
Test cases written and also tested by running with CLI. 
**What this PR does / why we need it**: 
Milestone 1 of https://docs.google.com/document/d/1MkWvexE4e5nYWcQLELFnJ5o9OlJDKC2rn_USHMDT9dg/edit
Fixes #1500
```release-note
Feast will be able to infer the features to register if no features are included in the FeatureView definition, and also infer the event timestamp column of DataSources if that parameter is left out. This is milestone 1 of https://docs.google.com/document/d/1MkWvexE4e5nYWcQLELFnJ5o9OlJDKC2rn_USHMDT9dg/edit#heading=h.pqhio4s5uw2s
```
=> Inferencing of Features in FeatureView and timestamp column of DataSource

docs/specs/offline_store_format.md
**What this PR does / why we need it**: Documentation update
Fixes #
```release-note
NONE
```
=> BigQuery type to Feast type conversion chart update

sdk/python/feast/infra/provider.py, sdk/python/feast/type_map.py, sdk/python/tests/test_offline_online_store_consistency.py
Signed-off-by: qooba <dev@qooba.net>
This pull request fixes the issue during materialize view.
If in input data there is a None value feast can't parse its type in python_type_to_feast_value_type method
Fixes #1480
```release-note
Added support for materializing sources with None types.
```
=> Fix materialize for None

sdk/python/feast/cli.py, sdk/python/tests/test_cli_chdir.py
Specify a feature repo path using `feat --chdir path-to-a-feature-repository  COMMAND ..`
Possibly Fixes #1507
yes
```release-note
The --chdir or -c option allows users to run a feast command outside of a feature repo directory. 
```
=> Add path option to cli

.github/workflows/integration_tests.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/unit_tests.yml, Makefile, sdk/python/setup.py
* Adds code coverage reporting using https://codecov.io/
* Removes integration tests for MacOs (unable to use Docker)
```release-note
NONE
```
=> Add test coverage and remove MacOS integration tests

sdk/python/docs/requirements.txt, sdk/python/setup.py
Sphinx 4.0.0 breaks documentation building on master (also seen here https://github.com/datalad/datalad/issues/5650). This PR prevents 4.0.0 from being used.
```release-note
NONE
```
=> Fix Sphinx documentation building

sdk/python/feast/errors.py, sdk/python/feast/infra/gcp.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/helpers.py, sdk/python/feast/registry.py
If no `gcloud` account is specified, then users today are not provided with a useful exception. Instead, the exception is hidden behind a failure due to an anonymous client not having access to their resources.
```release-note
NONE
```
=> Improve GCP exception handling

CONTRIBUTING.md, docs/SUMMARY.md, docs/feast-on-kubernetes/getting-started/install-feast/README.md, docs/feast-on-kubernetes/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md, docs/getting-started/install-feast/README.md, docs/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md
Add instruction for install Feast on IKS and OpenShift on IBM Cloud using Kustomize.
Remove instruction for install Feast on IKS with helm
Update urls in README, CONTRIBUTOR, and SUMMARY md files.
NONE
=> Add instruction for install Feast on IKS and OpenShift using Kustomize

sdk/python/feast/cli.py
Fixes #1531
```release-note
NONE
```
=> Update default cli no option help message

sdk/python/feast/repo_operations.py
Validate project and project directory names contain only alphanumerical values and underscores.
Fixes #1545
```release-note
Validate project and repository names for apply and init commands
```
=> Validate project and repo names for apply and init commands

sdk/python/feast/infra/offline_stores/bigquery.py
**What this PR does / why we need it**: In bigquery.py, first call `client.get_dataset` and only call `client.create_dataset` if it doesn't exist. This way users can manually create the dataset and only grant `bigquery.datasets.get` permission (not `bigquery.datasets.create`) to Feast.
Fixes #
```release-note
Require just `bigquery.datasets.get` permission (not `bigquery.datasets.create`) if the BigQuery dataset defined by `offline_store->dataset` is already created by the user.
```
=> Don't create bigquery dataset if it already exists

sdk/python/feast/infra/offline_stores/offline_store.py
Both file and BigQuery are supported right ? Not only BigQuery.
None
```release-note
None
```
=> Change OfflineStore class description

sdk/python/feast/infra/gcp.py, sdk/python/feast/repo_config.py
* Disables unnecessary indexing in Datastore
* Provides ability to set concurrency (amount of threads to use) as well as batch sizes being written
Fixes #1575 
```release-note
Added a write_concurrency option to Datastore
```
=> Fix contention issue

sdk/python/feast/type_map.py
Fixes #1574 
```release-note
Fixed bug where entity "0" caused materialization to fail.
```
=> Ensure that only None types fail predicate

sdk/python/feast/cli.py
We log start and time information in the CLI, before converting the timestamps into tz-aware datetime objects. This results in a confusion when running `feast materialize-incremental` which only takes in an end_ts argument. The end_ts argument is tz-naive, but start_ts is tz-aware, which causes the time range that's logged to the console to be messed up.
This PR changes the behaviour to add tz information at the boundary of the CLI so that log messages in the deeper classes as well as in the CLI are consistent.
```
$ feast materialize 2021-05-12 2021-05-13
Materializing 1 feature views from 2021-05-11 17:00:00-07:00 to 2021-05-12 17:00:00-07:00 into the sqlite online store.
driver_hourly_stats: …
```
=> Make start and end timestamps tz aware in the CLI

sdk/python/tests/test_historical_retrieval.py
Becuase of the way we construct same dataset name in test_historical_retrival, when running a matrix test there's the possiblity of two different tests constructing the same dataset name, and hence stomping over each other.
This PR adds the python version to the name of the dataset - this should be sufficient since the test matrix tests different python versions. An alternative would be to use the github action run id, but that ties the test a little bit closer to github than seems necessary.
Fixes #
```release-note
NONE
```
=> Append nanoseconds to dataset name in test_historical_retrival to prevent tests stomping over each other

sdk/python/feast/repo_operations.py
Only `feast apply` works with custom providers. Other CLI commands that depend on the provider don't work with custom ones.
This is because the current directory is append to the SYS PATH only during `feast apply`
Fixes https://github.com/feast-dev/feast/issues/1589
```release-note
Append current directory in sys path for all CLI commands that depend on a provider
```
=> Add current directory in sys path for CLI commands that might depend on custom providers

sdk/python/feast/infra/offline_stores/bigquery.py
In order to calculate a unique ID for each row of the entity dataframe, we compute the following
```sql
SELECT ROW_NUMBER() OVER() AS row_number, edf.* FROM {{ left_table_query_string }} as edf
```
The problem is that BigQuery will need to send all the data to a single worker in order to properly calculate the row number of each row. For our use case, we end up with a OOM error
The solution is to calculate a **deterministic** funcyion that will act as a unique identifier.
Because the entity_dataframe should contain all entity keys, I use `CONCAT()` that will compute a deterministic string for a given input. This hash is computed in a distributed fashion as it only needs the datapoints of a given row.
```sql
WITH …
```
=> Use CONCAT() instead of ROW_NUMBER()

.pre-commit-config.yaml, sdk/python/feast/data_source.py, sdk/python/feast/type_map.py
Currently, Inferring features fails on columns of type timestamp[ms, tz=UTC] or other tz. This diff attempts to fix using a regex instead of enumerating all the different possibilities. 
An option is to use the pandas type instead of the string representation, but this is probably good enough.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html
Fixes #
```release-note
Fix Inferring features columns of pandas timestamp types.
```
=> Update type conversion from pandas to timestamp to support various the timestamp types

sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/registry.py
This PR validate join keys when materializing from file sources, to make sure that the join keys are present in the dataframe columns. Additionally, we dedupe column names when extracting columns from the pandas dataframe. This should specifically catch the case of `event_timestamp_column` and `created_timestamp_column` pointing to the same column name.
Additionally, this fixes a bug where the `EntityNotFoundException` was instantiated with the entity name and project name switched.
Fixes #
```release-note
Add validations when materializing from file sources 
```
=> Add validations when materializing from file sources

sdk/python/feast/infra/offline_stores/file.py
`df.drop_duplicates()` is much faster than `groupby() + reset_index()`.
You can test it with the below codes (You can change the number of unique number for each column):
```
df = pd.DataFrame({
"a": [np.random.randint(0, 100) for _ in range(1000)],
"b": [np.random.randint(0, 100) for _ in range(1000)],
"c": [np.random.randint(0, 100) for _ in range(1000)],
})
%%timeit
df.groupby(['a', 'b']).last().reset_index()
%%timeit
df.drop_duplicates(['a', 'b'], keep="last", ignore_index=True, inplace=True)
```
No issues related. It's sort of a little performance improvement
```release-note
NONE
```
=> Use drop_duplicates() instead of groupby (about 1.5~2x faster)

sdk/python/tests/test_historical_retrieval.py
Fixes failing e2e test
```release-note
NONE
```
=> Fix failing historical retrieval assertion

sdk/python/feast/feature_store.py, sdk/python/feast/feature_view.py, sdk/python/feast/infra/gcp.py, sdk/python/feast/infra/local.py, sdk/python/feast/registry.py, sdk/python/feast/utils.py, sdk/python/tests/test_feature_store.py
Fixes #
```release-note
NONE
```
=> Don't lose materialization interval tracking when re-applying feature views

sdk/python/feast/feature_view.py
Fix `ttl_duration` when TTL is None
Fixes #
NONE
```release-note
Fix ttl_duration when ttl is None
```
=> Fix ttl duration when ttl is None

sdk/python/feast/repo_operations.py, sdk/python/tests/test_init.py
Address comments in PR #1558
```release-note
feast apply or init commands will exit if project or repo name start with an underscore.
```
/cc @woop @dmatrix
=> Repo and project names should not start with an underscore

.github/auto_assign-issues.yml, .github/workflows/integration_tests.yml, .github/workflows/pr_integration_tests.yml
**What this PR does / why we need it**: Adds authenticating in Feast's AWS account using Github actions. This will unlock integration tests using S3, Dynamo, Redshift.
Fixes #
```release-note
NONE
```
=> Add AWS authentication using github actions

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/tests/test_historical_retrieval.py
The current SQL template to perform historical retrieval of BigQuery datasets could be more efficient.
As a former data scientist, I often realized that big data engines (Spark, BigQuery, Presto, etc.) are often much more efficient with a series of GROUP BY rather than a Window function. Moreover, we should avoid ORDER BY operations as much as possible.
So this PR comes with a new approach to compute the point in time join. This is solely compose of JOINs and GROUP BYs
Here are the results of my benchmark:
**Context**
The api call is the following
```python
result = store.get_historical_features(
entity_df="""
SELECT user_id, TIMESTAMP '2021-01-01' AS observed_at
FROM `my_dataset`
LIMIT 100000000 -- 100M
""", …
```
=> Optimize historical retrieval with BigQuery offline store

.github/workflows/integration_tests.yml, .github/workflows/pr_integration_tests.yml, sdk/python/feast/feature_store.py, sdk/python/feast/infra/gcp.py, sdk/python/feast/infra/local.py, sdk/python/feast/infra/provider.py, sdk/python/feast/infra/redis.py, sdk/python/feast/infra/redis_provider.py, sdk/python/feast/repo_config.py, sdk/python/setup.py, sdk/python/tests/foo_provider.py, sdk/python/tests/test_cli_redis.py, sdk/python/tests/test_offline_online_store_consistency.py
PR adds Redis and RedisCluster support as online store. As described in https://github.com/feast-dev/feast/issues/1497 it is backward compatible with Feast 0.9 thus it can be used for migration to 0.10
Fixes #1497
```release-note
Redis and RedisCluster online stores support added. Format is compatible with Feast 0.9.
```
=> Add support for Redis and Redis Cluster

sdk/python/feast/errors.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/tests/example_feature_repo_with_entity_join_key.py, sdk/python/tests/test_e2e_local.py
Follow up from #1615 based on the comment in #1614 . Also adds test and removed an empty file.
Fixes #
```release-note
NONE
```
=> Add a specific error for missing columns during materialization

sdk/python/feast/infra/offline_stores/bigquery.py
**What this PR does / why we need it**: In `BigQueryOfflineStore.get_historical_features` Feast calls `entity_df_job.result()` which causes the entity data frame to be loaded in memory. We only need to wait for the job to be done and for the schema to be returned, while not changing the existing query (because the results of the query are being used for joining with offline feature data). This PR changes the call to `entity_df_job.result(max_results=0)`, which at the same time:
1. Executes the same query in BigQuery, so the table that gets joined does not change
2. Does not load any of the query rows in memory
3. Still allows the schema to be acquired from the resulting object
I checked all other places where we call `.result()` in the …
=> Don't load entire bigquery query results in memory

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/repo_config.py
**What this PR does / why we need it**: Follow up on #1638, which failed to fix the OOM issue.
Fixes #
```release-note
NONE
```
=> Don't use .result() in BigQueryOfflineStore, since it still leads to OOM

sdk/python/setup.py
Bumps fastavro 
Fixes #1584 
```release-note
Bump fastavro version from '>=0.22.11,<0.23' to '>=1.1.0'
```
=> Bump fastavro version

sdk/python/tests/example_feature_repo_1.py, sdk/python/tests/test_partial_apply.py
**What this PR does / why we need it**: I added a public dataset under feast-oss with 3 empty tables: drivers, customers, and customer_driver:
Subsequently, I replaced all mentions of `rh_prod.ride_hailing_co` by `feast-oss.public`. This should unblock #1627.
Fixes #
```release-note
NONE
```
=> Fix table_refs in BigQuerySource definitions

sdk/python/feast/feature_store.py, sdk/python/feast/online_response.py, sdk/python/tests/test_online_retrieval.py
Convert online response to Panda dataframe
Fixes #1613
```release-note
Users can convert online feature response to Panda dataframe
```
=> Add to_df() to convert get_online_feature response to pandas dataframe

sdk/python/feast/data_source.py, sdk/python/feast/errors.py, sdk/python/feast/feature_store.py, sdk/python/feast/feature_view.py, sdk/python/feast/inference.py, sdk/python/feast/repo_operations.py, sdk/python/tests/test_inference.py, sdk/python/tests/utils/data_source_utils.py
https://github.com/feast-dev/feast/issues/1645
Fixes #1645
```release-note
None
```
=> Schema Inferencing should happen at apply time

sdk/python/feast/errors.py, sdk/python/feast/infra/online_stores/datastore.py, sdk/python/feast/infra/online_stores/helpers.py, sdk/python/feast/infra/online_stores/redis.py, sdk/python/feast/infra/online_stores/sqlite.py, sdk/python/feast/infra/provider.py, sdk/python/feast/repo_config.py, sdk/python/feast/repo_operations.py, sdk/python/telemetry_tests/test_telemetry.py, sdk/python/tests/foo_provider.py, sdk/python/tests/test_feature_store.py, sdk/python/tests/test_historical_retrieval.py, sdk/python/tests/test_offline_online_store_consistency.py, sdk/python/tests/test_repo_config.py
This PR:
- introduces a new pydantic base class for Config classes to extend
- moves the online store config classes into the corresponding modules
- adds logic to dynamically load the `OnlineStoreConfig` classes (and also the `OnlineStore` classes in a second pass).
- Keeps tests basically the same (and adding more tests for the dynamic classes)
Part 1 for #1605 
```release-note
Allow OnlineStore implementations to be loaded dynamically.
```
=> Refactor OnlineStoreConfig classes into owning modules

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/repo_config.py
Add the possibility to specify a GCP project for the temporary datasets created.
For example, with the config file and a ServiceAccount coming from the project `ml-adhoc`
```yaml
[...]
offline_store:
type: bigquery
project: ml-production
```
```
>>> from google.cloud import bigquery
>>>from feast.feature_store import FeatureStore
>>> store = FeatureStore()
>>> store.config.offline_store.project
'ml-production'
>>> bigquery.Client().project
'ml-adhoc'
```
Which means that the ServiceAccount `ml-adhoc` will write into the BQ project `ml-production` (_names are just for examples_)
Fixes https://github.com/feast-dev/feast/issues/1655
NONE
```release-note
Possibility to …
```
=> Allow BigQuery project to be configured

sdk/python/feast/errors.py, sdk/python/feast/importer.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/helpers.py, sdk/python/feast/infra/online_stores/helpers.py, sdk/python/feast/infra/online_stores/sqlite.py, sdk/python/feast/infra/provider.py, sdk/python/feast/repo_config.py, sdk/python/feast/repo_operations.py, sdk/python/tests/test_cli_local.py, sdk/python/tests/test_historical_retrieval.py, sdk/python/tests/test_repo_config.py
Follow up from #1649. This refactors the OfflineStoreConfig in the same exact way so that things are loaded dynamically instead of hardcoding in the `repo_config.py` module.
Part 2 for #1605
```release-note
Allow OfflineStore implementations to be loaded dynamically.
```
=> Refactor OfflineStoreConfig classes into their owning modules

docs/reference/providers/local.md
.
Signed-off-by: Nel Swanepoel <c.swanepoel@ucl.ac.uk>
This is a simple documentation update to include Redis in the list of online stores options for the local provider.
```release-note
NONE
```
=> Small reference documentation update

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/tests/test_historical_retrieval.py
This PR gives the user more freedom to set configuration options for the `to_bigquery` call (on a BigQueryRetrievalJob following a `get_historical_features` call). For example, the user can specify a destination `project.dataset.tableName`, an expiration timestamp for the table, and also an option for replace/overwrite vs fail if already exists.
Fixes #1654
```release-note
* User should supply to_bigquery() with a bigquery.QueryJobConfig.
* User can also call to_sql() to get/modify the SQL directly (i.e. to set expiration_timestamp)
```
**References**
- [google.cloud.bigquery.job.QueryJobConfig](https://googleapis.dev/python …
=> Provide the user with more options for setting the to_bigquery config

sdk/python/feast/feature_store.py, sdk/python/feast/infra/gcp.py, sdk/python/feast/infra/local.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/provider.py, sdk/python/tests/foo_provider.py, sdk/python/tests/test_historical_retrieval.py
We should add a notion of "OfflineJob" so that it will be easier to add new methods as well as accessible useful information.
For example, when you build a custom Provider, you might want to access the query coming from `pull_latest_from_table_or_query()` without executing it (as it will be executed differently)
Fixes #
```release-note
pull_latest_from_table_or_query() now returns an RetrievalJob object
Add method to_table() to RetrievalJob object
```
=> Add to_table() to RetrievalJob object

sdk/python/feast/errors.py, sdk/python/feast/infra/offline_stores/bigquery.py
Signed-off-by: Matt Delacour <matt.delacour@shopify.com>
The current function `_block_until_done()` has a flaw as if the timedout hits (aka `stop_after_delay(1800)`), then the job will still run in BigQuery and won't be cancelled.
An alternative would be the possibility to add a timedout argument to the [BQ config job](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJobConfig.html) but could not find anything useful
Fixes #
```release-note
NONE
```
=> Cancel BigQuery job if timeout hits

docs/concepts/data-model-and-concepts.md
Fix Feature References example by passing `entity_rows` to `get_online_features()`
Fixes typo in docs.
N/A
NONE
```release-note
```
=> Docs: Fix Feature References example

sdk/python/feast/repo_config.py, sdk/python/tests/test_repo_config.py
This allows the offline_store or online_store to be specified as a top level string instead of a dict.
Fixes #
```release-note
Allow strings for online/offline store instead of dicts
```
=> Allow strings for online/offline store instead of dicts

sdk/python/feast/driver_test_data.py, sdk/python/tests/test_historical_retrieval.py, sdk/python/tests/test_offline_online_store_consistency.py
**What this PR does / why we need it**: Pandas 1.3.0 release yesterday (https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html) and it broke our unit tests. Looks like the new pandas version fixed some bugs and some of our tests were depending on those bugs :) For example we were using pandas_df.append in one place, which was incorrectly casting types from float32 to float64 in earlier pandas versions. I replaced it with pandas.concat which behaves correctly in both old and new versions.
Fixes #
```release-note
NONE
```
=> Fix unit tests that got broken by Pandas 1.3.0 release

.github/workflows/integration_tests.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/unit_tests.yml, Makefile
**What this PR does / why we need it**: Currently only unit tests are parallelized. Also, parallelize integration tests. Increase parallelism from 4 -> 8 (especially for integration tests where there's a lot of waiting). Finally, remove the coverage flags from make command, because it significantly slows down pytest. Note, that github actions will still run the coverage report.
Fixes #
```release-note
NONE 
```
=> Parallelize integration tests

sdk/python/feast/infra/offline_stores/bigquery.py
Signed-off-by: Matt Delacour <matt.delacour@shopify.com>
If the query failed before starting, its state will be `FAILURE`. So we should raise the BQ exceptions first otherwise we will end up seeing "BigQueryJobCancelled" errors even though it's not accurate
Fixes #
```release-note
Fix exception order when BigQuery failures occur
```
=> BQ exception should be raised first before we check the timedout

sdk/python/feast/feature_view.py
Fixes a typo
```release-note
None
```
=> Remove debug logging 

sdk/python/feast/type_map.py
Something in our deps seems to have broken lint.
https://github.com/feast-dev/feast/runs/3034670734?check_suite_focus=true
Fixes #
```release-note
NONE
```
=> Stringify WhichOneof to make mypy happy

sdk/python/feast/infra/offline_stores/bigquery.py
In PR #1661, I accidentally switched the order of the `dry_run` output and `_block_until_done` ([these lines](https://github.com/feast-dev/feast/pull/1661/files#diff-14f38fcbdc2240bb60b9f558d133b174f5b6059cfcd959eef8b9c49bb5be8838L239-L245)) in `BigQueryRetrievalJob.to_bigquery` that was making any `dry_run` call to hang. I fix it here.
(Not large enough for issue)
```release-note
NONE
```
=> Fix dry_run bug that was making to_bigquery hang indefinitely

sdk/python/feast/client.py, sdk/python/feast/config.py, sdk/python/feast/entity.py, sdk/python/feast/feature_table.py, sdk/python/feast/infra/provider.py, sdk/python/tests/feast_serving_server.py, sdk/python/tests/test_client.py, sdk/python/tests/test_offline_online_store_consistency.py
Type comments are no longer needed given that we support 3.7+. Also, they break mypy as of python 3.9. This PR removes all the instances of `type: Blah` from the codebase.
(Too small for issue)
```release-note
NONE
```
=> Remove type comments

sdk/python/feast/feature_store.py, sdk/python/tests/test_offline_online_store_consistency.py
The `test_offline_online_store_consistency.py` integration test didn't tear down any infrastructure after running. This led to an issue where we ran past the number of dynamo tables allowed for an account: https://github.com/feast-dev/feast/runs/3014392319?check_suite_focus=true
This PR changes the integration test to tear down the infrastructure set up by the fixtures. 
Fixes #1696. 
```release-note
NONE
```
=> Teardown infrastructure after integration tests

sdk/python/tests/test_historical_retrieval.py
**What this PR does / why we need it**: Fixes a bug in the test_timestamp_bound_inference_from_entity_df_using_bigquery integration test where different runs of the test would point to the same BQ table, resulting in errors. 
Fixes #
```release-note
NONE
```
=> Add randomness to bigquery table name

sdk/python/feast/infra/online_stores/redis.py, sdk/python/tests/test_cli_redis.py
The Redis connection string is a comma-separated string, where each additional parameter in addition to host and port is in the format `key=value`. 
This proposal fixing the parsing in cases where the parameter values contain the `=` symbol, for example `localhost:6379,password=my=password`
None
```release-note
NONE
```
=> Update redis options parsing 

sdk/python/feast/errors.py, sdk/python/feast/infra/offline_stores/bigquery.py
If a user decides to abort a `to_bigquery` run (like via a `ctrl-c`), the job should also be cancelled. The PR also fixes the retry logic of getting the bq_job state, and raises a better exception on timeout.
(Not large enough for issue)
```release-note
NONE
```
=> Cancel BigQuery job if block_until_done call times out or is interrupted

sdk/python/tests/test_offline_online_store_consistency.py
As found earlier, integration tests fail because of race conditions which cause the tests to create/rely on tables with the same name. We started seeing this again with Redshift as well:
https://github.com/feast-dev/feast/runs/3089135542?check_suite_focus=true
Applying the same mitigation we used then, which was to use nanosecond precision, and add an additional random integer for high entropy.
Fixes #
```release-note
NONE
```
=> Append ns time and random integer to redshift test tables

sdk/python/feast/cli.py, sdk/python/feast/repo_operations.py
Signed-off-by: David Y Liu <davidyliuliu@gmail.com>
Companies that have permission controls may make validation impossible since one user may not have access to all the tables of the data sources, and therefore can't run `feast apply`. 
Example error msg upon running `feast apply`
`google.api_core.exceptions.Forbidden: 403 GET https://bigquery.googleapis.com/bigquery/v2/projects/twttr-gcp-aggregates-vteam-stg/datasets/wtf/tables/country_candidate_user_aggregates_v1?prettyPrint=false: Access Denied: Table twttr-gcp-aggregates-vteam-stg:wtf.country_candidate_user_aggregates_v1: Permission bigquery.tables.get denied on table twttr-gcp-aggregates-vteam-stg:wtf.country_candidate_user_aggregates_v1 (or it may not exist).` …
=> Added --skip-source-validation flag to feast apply

sdk/python/feast/feature_store.py, sdk/python/feast/registry.py, sdk/python/feast/repo_operations.py, sdk/python/tests/test_registry.py
**What this PR does / why we need it**: make Registry updates more efficient. Right now, Registry updates are done by looping through FeatureViews and Entities and applying them one at a time. Applying an update to the Registry forces the underlying RegistryStore to update the underlying RegistryProto and write it (either to disk, GCS, or S3, depending on the backend of choice). Thus, looped writes are highly inefficient.
Current design: the Registry current has a cache to improve reading speed. Writes always go through to the backend, but not through the cache. Thus, the cache is not always up-to-date with the ground truth in the backend. The user is granted a lot of optionality around the cache: they may choose not to use the cache, thus …
=> Increase efficiency of Registry updates

.gitbook.yaml
**What this PR does / why we need it**: Previous, Feast docs used the following link: https://docs.feast.dev/reference/telemetry. Since we have started using 'usage' instead of 'telemetry', the link no longer works, so we set up a redirect to https://docs.feast.dev/reference/telemetry.
Fixes #
```release-note
NONE
```
=> Redirect telemetry to usage

sdk/python/feast/infra/offline_stores/bigquery.py
The problem is that if we ask for historical features coming from multiple entities that have a 1:many relationship between them, then we encounter skewed join
That's basically how the JOIN is performed with the current template
Imagine that driver_id=1 contains millions of rides
And that's what this PR is proposing
Let's have a look about the statistics of the SQL template on our use case (4 FeatureViews, 2 entities, _entity_dataframe_ containing 100M rows)
**SQL template currently in production**
I cancelled the query as it was still running after 25min
> 9:14 AM Query has been running for 25 min
**SQL template of this PR**
**Elapsed time** 2 min 34 sec
**Slot time consumed** 1 day 21 hr
**Bytes shuffled** 3.27 TB
**Bytes spilled to disk** 0 B …
=> Avoid skewed join between entity_df & feature views

sdk/python/feast/feature_store.py, sdk/python/feast/registry.py, sdk/python/feast/repo_operations.py, sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py, sdk/python/tests/integration/offline_store/test_historical_retrieval.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_registry.py
**What this PR does / why we need it**: As of right now, registries do not get cleaned up during teardown. This is especially bad for GCS and S3 registries. This PR ensures that registries get cleaned up during teardown. 
Fixes #
```release-note
NONE
```
=> Registry teardown

sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/utils/data_source_utils.py
Fix the test warning feast/sdk/python/feast/infra/offline_stores/file_source.py:48: UserWarning: Argument "file_url" is being deprecated. Please use the "path" argument.
```release-note
NONE
```
=> Fix unit test warnings related to file_url

sdk/python/setup.py
In feast.registry.Registy.get_registry_proto the gcs method
`download_blob_to_file` is called with the timeout param which does not
exist until version 1.34.
n/a
No.
```release-note
NONE
```
=> Fix GCS version

sdk/python/tests/integration/offline_store/test_historical_retrieval.py
Similar to #1697. 
Fixes #
```release-note
NONE
```
=> Teardown integration tests resources for aws

docs/getting-started/create-a-feature-repository.md, docs/getting-started/install-feast.md, docs/reference/data-sources/README.md, docs/reference/data-sources/redshift.md, docs/reference/offline-stores/README.md, docs/reference/offline-stores/redshift.md, docs/reference/online-stores/README.md, docs/reference/online-stores/dynamodb.md, docs/reference/providers/README.md, docs/reference/providers/amazon-web-services.md
Fixes #
```release-note
Document AWS Provider (including DynamoDB & Redshift)
```
=> Add AWS documentation (DynamoDB, Redshift)

sdk/python/docs/source/index.rst, sdk/python/feast/data_source.py, sdk/python/feast/entity.py, sdk/python/feast/feature.py, sdk/python/feast/feature_service.py, sdk/python/feast/feature_store.py, sdk/python/feast/feature_table.py, sdk/python/feast/feature_view.py, sdk/python/feast/inference.py
**What this PR does / why we need it**: This PR adds docstrings to public methods in public-facing classes (FeatureStore, FeatureView, Entity, etc.), and improves existing documentation. 
Fixes #1610 
```release-note
Added docstrings
```
=> Docstrings

sdk/python/feast/feature_store.py, sdk/python/feast/feature_view.py, sdk/python/tests/integration/registration/test_feature_store.py
**What this PR does / why we need it**: #1691 allows for specifying FeatureServices in FeatureStore methods, but introduced a breaking change by renaming `feature_refs` to `features`. This PR ensures the change is not breaking, and inserts the appropriate DeprecationWarning. 
Fixes #
```release-note
Makes features an optional parameter in get_historical_features, instead of required
```
=> Restore feature refs

sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/utils/aws_utils.py
Fixes #
```release-note
NONE
```
=> Document how pandas deals with missing values

sdk/python/feast/feature_view.py
**What this PR does / why we need it**: Fixes a warning printed during `feast materialize-incremental`
Fixes #
```release-note
NONE
```
=> Fix warning in FeatureView.from_proto

sdk/python/feast/feature_store.py, sdk/python/feast/registry.py, sdk/python/feast/repo_operations.py
**What this PR does / why we need it**: This fixes 2 bugs during `feast apply`.
1. We always initialized the empty registry (instead of loading the existing registry). This means that if during 1st apply we deployed infra for FeatureView A, and in the 2nd apply we renamed FeatureView A -> B, `feast apply` would create the table for B, but wouldn't remove the table for A.
2. The `registry.commit()` happened before the infra update call on the provider. This means that if the infra update fails (for example bad permissions), the registry still got updated. Which means that during the next apply, Feast wouldn't do anything because it'll think that everything is up to date in the registry. I moved the commit at the very end of apply_total …
=> Fix `feast apply` bugs

sdk/python/feast/feature_store.py, sdk/python/feast/repo_operations.py
Moves the feast CLI's apply method (`feast apply`) to use the SDK FeatureStore class more. Note that because the feast CLI's apply is a total apply whereas the SDK apply is partial, there is still leftover business logic (in particular for deleting entities / FVs that don't match the repo).
```release-note
NONE
```
=> Updating CLI apply to use FeatureStore

docs/reference/feature-repository/feature-store-yaml.md
Unfortunately I had accidentally specified a project name with a dash. The error that popped up was from sqlite (following a `store.apply` call when trying to create tables in the online store.):
```
sqlite3.OperationalError: near “-”: syntax error
```
which actually took me some extra debugging to figure out what my issue was.
N/A. Too small for a PR, but it could be related to overall validation or more docs specifying naming limitations.
```release-note
NONE
```
=> Adding small note for project naming convention

Makefile, sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/utils/aws_utils.py, sdk/python/tests/doctest/test_all.py
**What this PR does / why we need it**: Most of our important user-facing methods (`apply`, `get_historical_features`, etc.) have docstrings with interactive examples. This PR introduces tests for these interactive examples.
Fixes #
```release-note
NONE
```
=> Docstring tests

sdk/python/feast/repo_config.py, sdk/python/tests/data/data_creator.py, sdk/python/tests/integration/e2e/test_universal_e2e.py, sdk/python/tests/integration/feature_repos/test_repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py, sdk/python/tests/integration/feature_repos/universal/entities.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
This PR that implements some of the basis of the universal feature repo  as described in the the [RFC](https://docs.google.com/document/d/1QyaDFZ7yM1SclgFbsho1MjWZvjrkTmtERDpnr1jvgUs/edit#)
It adds a special decorator, `parametrize_e2e_test`, that makes it easy to tag tests to that should be executed against parameterized feature stores that are constructed by the testing framework. This means that users can add e2e tests and have them run against all supported combinations with a single decorator.
Fixes #
```release-note
NONE
```
=> Add the foundation of the universal feature repo and a test that uses it

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/tests/integration/offline_store/test_historical_retrieval.py
There is bug about finding the "latest" values when the rows have been backfilled (when _created_timestamp_ and _event_timestamp_ don't follow the same order).
The problem is that the `ANY_VALUE` strategy does not work here because it will take the first occurrence it sees. 
For example, the following example would fail
```markdown
| driver_id | value | event_timestamp | created_at |
|-----------|-------|-----------------|------------|
| 1         | 10    | today           | tomorrow   |
| 1         | 20    | tomorrow        | today      |
```
The JOIN happening later would consist of the entity_dataframe with the `__latest` CTE where created_at and event_timestamp got mixed
```markdown
| driver_id | value | event_timestamp | created_at | …
```
=> Fix BQ historical retrieval with rows that got backfilled

sdk/python/feast/driver_test_data.py, sdk/python/tests/integration/e2e/test_universal_e2e.py, sdk/python/tests/integration/feature_repos/test_repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py, sdk/python/tests/integration/feature_repos/universal/entities.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py, sdk/python/tests/integration/offline_store/test_historical_retrieval.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
We wanna start parameterizing over all the possible combinations when reading feature values from the offline feature store. This PR introduces the decorator needed to set up the underlying tables as needed, updates the historical integration test to operate on an Environment object.
```
$ FEAST_TELEMETRY=False pytest --cov=./ --cov-report=xml --color=yes -s --integration sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py -n 8
======================================================================================= test session starts =======================================================================================
platform darwin -- Python 3.7.11, pytest-6.0.0, …
```
=> Add offline retrival integration tests using the universal repo

sdk/python/feast/repo_config.py, sdk/python/tests/integration/scaffolding/test_repo_config.py
Check invalid project name
Fixes #1755
```release-note
User will get an error upon running feast.apply with invalid project name.
```
=> Validate project name upon feast.apply

sdk/python/tests/integration/feature_repos/test_repo_configuration.py
Fixes #
```release-note
none
```
=> Add Redis to the universal integration tests

Makefile, sdk/python/setup.py
With our working on increasing out integration test coverage, we are at higher risk of test failures because of flakes. To address this, this PR introduces a pytest-rerunfailures to try and alleviate the issue with failed tests.
Fixes #
```release-note
none
```
=> Rerun failed python integration tests

sdk/python/tests/integration/feature_repos/test_repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/online_store/test_universal_online.py
Fixes #
```release-note
NONE
```
=> Add online feature retrieval integration test using the universal repo

sdk/python/feast/usage.py
**What this PR does / why we need it**: Telemetry for `get_online_features` currently has a bug where telemetry is being logged during every call to `get_online_features`, instead of every 10000 calls. This PR fixes that bug. 
Fixes #
```release-note
NONE
```
=> Fix get_online_features telemetry to only log every 10000 times

Makefile, sdk/python/setup.py
This undoes #1785 to identify the flaky tests so that we can address them more direclty.
Fixes #
```release-note
none
```
=> Disable integration test reruns to identify flaky tests

protos/feast/serving/ServingService.proto, protos/feast/types/Value.proto, sdk/python/feast/cli.py, sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py, sdk/python/feast/proto_json.py, sdk/python/feast/type_map.py, sdk/python/setup.py, sdk/python/tests/unit/test_proto_json.py
**What this PR does / why we need it**: Implements the local HTTP feature consumption server.
RFCs for context:
* [RFC: Feature Consumption Server](https://docs.google.com/document/d/1iXvFhAsJ5jgAhPOpTdB3j-Wj1S9x3Ev_Wr6ZpnLzER4/edit#)
* [RFC: Feast Cloud Architecture](https://docs.google.com/document/d/17TDdtd3GhChfEyah6dppFxD6Ce9fOmIpNdV0b6SEr5o/edit#heading=h.d7e4zxvwrgt1)
From one terminal tab we can run `feast serve`:
```bash
$ feast serve
INFO:     Started server process [13615]
08/12/2021 09:29:36 PM INFO:Started server process [13615]
INFO:     Waiting for application startup.
08/12/2021 09:29:36 PM INFO:Waiting for application startup.
INFO:     Application startup complete.
08/12/2021 09:29:36 PM INFO:Application startup complete. …
```
=> Local feature server implementation (HTTP endpoint)

infra/terraform/azure/helm.tf
Helm chart for Feast in the Terraform installation changed to
point to the location referenced in the Azure Helm installation
documentation (https://docs.feast.dev/feast-on-kubernetes-1/getting-started/install-feast/kubernetes-azure-aks-with-helm)
Fixes #1792 
```release-note
NONE
```
=> Fix Azure Terraform installation.

sdk/python/feast/usage.py, sdk/python/usage_tests/test_usage.py
**What this PR does / why we need it**: A few places in the codebase still refer to telemetry. This PR renames "telemetry" to "usage".
Fixes #
```release-note
NONE
```
=> Rename telemetry to usage

sdk/python/feast/infra/offline_stores/redshift.py
Currently it's not possible to use `ANY_VALUE` with Redshift Spectrum (when querying features on S3). This PR changes `ANY_VALUE` to `MAX`
```release-note
Fixed a bug in Redshift training dataset generation where queries failed on external tables
```
=> Fix Redshift query for external tables

sdk/python/feast/infra/provider.py, sdk/python/tests/foo_provider.py
This PR adds an abstract `__init__` as part of the base class for Providers. Currently no such method exists which has led to custom providers and built in providers having different initialization contracts.
https://github.com/feast-dev/feast/blob/745a1b43d20c0169b675b1f28039854205fb8180/sdk/python/feast/infra/provider.py#L146
vs 
https://github.com/feast-dev/feast/blob/745a1b43d20c0169b675b1f28039854205fb8180/sdk/python/feast/infra/provider.py#L164
```release-note
All custom providers must now provide an initialization method and won't receive a repo_path argument
```
=> Add init to Provider contract

sdk/python/feast/feature_store.py, sdk/python/tests/doctest/test_all.py
**What this PR does / why we need it**: Occasionally docstring tests are not cleaned up properly. This test ensures they always teardown correctly.
Fixes #
```release-note
NONE
```
=> Ensure docstring tests always teardown

sdk/python/feast/infra/online_stores/datastore.py
get is a wrapper around get_multi, and get_multi reduces the network costs involved.
Fixes #1759 
```release-note
Use a batch lookup API for Google Datastore. Users should see lower latencies for `get_online_features` when using Datastore as the online store.
```
=> Use get_multi instead of get for datastore reads

sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
Generating unique BQ datasets for the offline_online_store_consistency to avoid ACL issues with updating existing datasets
Fixes #1760
```release-note
NONE
```
=> Randomly generating new BQ dataset for offline_online_store_consistency test

sdk/python/feast/infra/online_stores/datastore.py
Fixes #
```release-note
none
```
=> Refactor the datastore online_read method to be slightly more efficient

protos/feast/core/FeatureView.proto, protos/feast/core/OnDemandFeatureView.proto, protos/feast/core/Registry.proto, sdk/python/feast/__init__.py, sdk/python/feast/errors.py, sdk/python/feast/feature_store.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/registry.py, sdk/python/feast/repo_operations.py, sdk/python/setup.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/online_store/test_universal_online.py
Sets up initial storage and scaffolding for on demand feature view, and supports online fetching. This does not yet support offline feature fetching or request data.
Fixes #
```release-note
Add support for row-level on-demand transformations of feature view features in get_online_features
```
=> Initial scaffolding for on demand feature view

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/provider.py, sdk/python/feast/on_demand_feature_view.py
Sets up a limited on demand transform for historical retrieval for to_df (not to_arrow yet)
Fixes #
```release-note
- Add support for row-level on-demand transformations of feature view features in get_offline_features.
- Requires offline store implementations to now also have full_feature_name and on_demand_feature_views properties
```
=> Implementing initial on demand transforms for historical retrieval to_df

sdk/python/feast/cli.py, sdk/python/feast/errors.py, sdk/python/feast/feature_store.py, sdk/python/feast/registry.py
Fixes #
```release-note
Add Registry and CLI operations for on demand feature views
```
=> Add Registry and CLI operations for on demand feature views

README.md
Signed-off-by: Benn Ma <bennmsg@gmail.com>
Fix wrong links in README
Fixes #
```release-note
NONE
```
=> Fix wrong links in README

sdk/python/tests/integration/feature_repos/repo_configuration.py
In tests that need the environment but don't apply any items, the `feature_store.teardown` method raises an exception since the registry hasn't been applied.
Fixes #
```release-note
none
```
=> Init registry during create_test_environment

.github/workflows/integration_tests.yml, .github/workflows/pr_integration_tests.yml, Makefile, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/tests/integration/feature_repos/repo_configuration.py
From some quick logging, a hotspot when running integration tests lies in uploading entity_df for BQ related tests. This reduces the polling interval from 10 seconds to 0.1 seconds in test environments (and also reduce the prod environment interval to 1s since the main cost is catching a raised Exception, but there's nothing else happening on this thread)
Fixes #
```release-note
NONE
```
=> Reducing wait interval for BQ integration tests

sdk/python/feast/infra/utils/aws_utils.py
I've seen this error very often:
```
E           botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://redshift-data.us-west-2.amazonaws.com/".
```
Examples:
https://github.com/feast-dev/feast/pull/1833/checks?check_run_id=3507137476
https://github.com/feast-dev/feast/runs/3490830039?check_suite_focus=true
https://github.com/feast-dev/feast/runs/3490830012?check_suite_focus=true
Fixes #
```release-note
Retry submitting queries to redshift on connection errors.
```
=> Fix flaky connection to redshift data API

sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/online_store/test_universal_online.py
Tests are good
Fixes #
```release-note
none
```
=> Update historical retrieval integration test for on demand feature views

sdk/python/feast/type_map.py
The `_python_value_to_proto_value` is spaghetti - but it's basically a mechanical look up. This simplifies things greatly.
Fixes #
```release-note
none
```
=> Simplify _python_value_to_proto_value by looking up values in a dict

sdk/python/feast/feature_store.py, sdk/python/tests/integration/registration/test_cli_apply_duplicated_featureview_names.py, sdk/python/tests/integration/registration/test_feature_store.py
CockroachDB's table names and the materialization jobs using dataflow need feature view names to be lowercase. (CRDB is an online store we're trying to use.) We can transform the names downstream / on our end, but we would like the collision check to happen at `feast apply` time.
It's such a small change that no issue created.
```release-note
FeatureView names must now be *case-insensitively* unique
```
=> Enforce case-insensitively unique feature view names

sdk/python/feast/infra/offline_stores/bigquery.py
Fixes Issue 1842 of job_id not found when querying bigquery job status from outside of US. 
Fixes #1842
```release-note
NONE
```
=> Pass bigquery job object to get_job

.pre-commit-config.yaml, CONTRIBUTING.md, Makefile, README.md, docs/feast-on-kubernetes/getting-started/README.md, docs/roadmap.md, infra/scripts/compile-templates.py, infra/templates/README.md.jinja2
Moves the roadmap to our README.md and restructures it.
=> Add roadmap to README.md

sdk/python/feast/feature_store.py
This is a follow up of https://github.com/feast-dev/feast/pull/1804/ and addresses changes from this comment: https://github.com/feast-dev/feast/pull/1804/files/b767eb7d42a4ae3d244693fee5fafe7ea9e4143c#r705519160
Basically, if we only apply the dummy_id at FeatureStore.init time, it might get erased in future apply calls by the user. It would be persisted by moving it to `apply` time.
Small bug fix for #1737
```release-note
NONE
```
=> Move apply(dummy_entity) to apply time to ensure it persists in FeatureStore

sdk/python/feast/feature_service.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/online_store/test_universal_online.py
Fixes #
```release-note
Support on demand feature views in feature services
```
=> Support on demand feature views in feature services

docs/SUMMARY.md, docs/reference/feature-server.md, sdk/python/feast/cli.py, sdk/python/feast/feature_server.py
**What this PR does / why we need it**: This adds the feature server documentation to Feast. We also make a couple of small changes to the local server. Namely:
1. Change GET to POST request
2. Change routing from `/get-online-features/` to `/get-online-features`, which doesn't change anything for the local server, but fixes a very ambiguous bug when using this server with AWS Lambda (which is WIP).
3. Add experimental warning on `feast serve` and add it in the CLI message as well.
Fixes #
```release-note
Document local feature server (experimental)
```
=> Add feature server docs & small changes in local server

protos/feast/core/DataSource.proto, protos/feast/core/OnDemandFeatureView.proto, sdk/python/feast/data_source.py, sdk/python/feast/errors.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
Supports adding request data as a dependency in on demand transforms. This validates when if the entity_df or entity_rows don't have the required request data features.
Fixes #
```release-note
NONE
```
=> Support adding request data in on demand transforms

sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/utils/aws_utils.py
Add MVP support for on demand transforms for AWS to_s3 and to_redshift
Tested with a local repo that uploaded to s3 + to_redshift and inspected results to see on demand transform properly applied into a new column
Fixes #
```release-note
NONE
```
=> Add MVP support for on demand transforms for AWS to_s3 and to_redshift

sdk/python/feast/infra/offline_stores/bigquery.py
Add MVP support for on demand transforms for bigquery
Verified this works properly with an on demand transform that calls to_bigquery. Examined resulting BQ table and observed correct transformation applied.
Fixes #
```release-note
NONE
```
=> Add MVP support for on demand transforms for bigquery

sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/online_stores/helpers.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/online_store/test_universal_online.py
**What this PR does / why we need it**: The current Redshift historical retrieval query does not support using multiple entities. This PR fixes that.
Fixes #1816 
```release-note
Users can now use multiple entities for historical retrieval on Redshift
```
=> Add support for multiple entities in Redshift

sdk/python/feast/infra/feature_servers/Dockerfile, sdk/python/feast/infra/feature_servers/app.py, sdk/python/feast/infra/feature_servers/requirements.txt, sdk/python/setup.py
**What this PR does / why we need it**: This PR creates an initial dockerfile for AWS lambda feature server.
Fixes #
```release-note
NONE
```
=> Initial docker image for aws lambda feature server

sdk/python/feast/errors.py, sdk/python/feast/infra/feature_servers/aws_lambda/app.py, sdk/python/feast/infra/feature_servers/aws_lambda/config.py, sdk/python/feast/repo_config.py
**What this PR does / why we need it**: This PR adds the option to add a feature server configuration to `feature_store.yaml`. Right now, only AWS lambda is supported.
Fixes #
```release-note
The user can now define a feature server in `feature_store.yaml`.
```
=> Add feature server configuration for AWS lambda

sdk/python/feast/infra/feature_servers/app.py
**What this PR does / why we need it**: We want to read registry (binary) and config (feature_store.yaml) via base64-encoded environment variables. They'll be set during `feast apply` when deploying AWS Lambda resource.
Fixes #
```release-note
NONE
```
=> Read registry & config from env variables in AWS Lambda feature server

sdk/python/tests/conftest.py
Fixes a bug. Additionally, remove test items instead of skipping them. This makes `--collect-only` more useful, since that flag doesn't filter out skipped flags. 
Fixes #
```release-note
none
```
=> Fix pytest_collection_modifyitems to select benchmark tests only

sdk/python/feast/infra/aws.py, sdk/python/feast/infra/gcp.py, sdk/python/feast/infra/local.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py
Currently, the AWS, GCP and Local providers have the exact same implementation - and the implementation only defers actual business logic of setting up infrastructure and materializing data to the offline/online store interfaces.
This is confusing for users, and is unnecessary code to maintain. Instead, this PR refactors the implementations into a single implementation, with a dummy subclass for the 3 existing providers for backwards compatibility.
Fixes #
```release-note
none
```
=> Refactor providers to remove duplicate implementations

sdk/python/feast/feature_store.py, sdk/python/feast/usage.py
Adding telemetry for on demand feature views and making existing usage calls async
Tested this locally to ensure the events are logged correctly and that the get_online_features logs only trigger once every 10k requests.
Fixes #
```release-note
NONE
```
=> Adding telemetry for on demand feature views and making existing usage calls async

.github/workflows/integration_tests.yml, .github/workflows/pr_integration_tests.yml
It's useful for us to be able to identify slow tests so that we can speed them up.
Fixes #
```release-note
none
```
=> Add durations to list the slowest tests

sdk/python/docs/source/index.rst, sdk/python/feast/cli.py, sdk/python/feast/on_demand_feature_view.py
Adds some experimental tags to on demand feature view related docs. Also including it in autogenerated python reference.
Fixes #
```release-note
NONE
```
=> Add on demand feature view experimental docs

CONTRIBUTING.md
Adds extra details around testing + making PRs. This pulls some info from https://docs.feast.dev/project/development-guide and adds other instructions.
Fixes #
```release-note
NONE
```
=> Adding more details to the CONTRIBUTING.md

sdk/python/setup.py
`dill` is imported by `sdk/python/feast/on_demand_feature_view.py` and
so is needed as a main dependency.
Fixes #
```release-note
Fix import error caused by missing dependency.
```
=> Add `dill` to main dependencies

sdk/python/feast/type_map.py
I noticed a comment saying this needed to be changed after #1520 was merged so I changed it. 😛 
Fixes #
```release-note
Parse BQ `DATETIME` and `TIMESTAMP` to `ValueType.UNIX_TIMESTAMP`. 
```
=> Parse BQ `DATETIME` and `TIMESTAMP`

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/type_map.py, sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py, sdk/python/tests/integration/offline_store/test_historical_retrieval.py, sdk/python/tests/integration/registration/test_universal_types.py, sdk/python/tests/utils/data_source_utils.py
Should have been using this option from the start but the docs on it are very lacking. Took me an hour or two to find it. This should make BQ behave like the other data store with `pyarrow` lists instead of the weird `{list: {item: value}}`.
Some concerns about this being incompatible with already existing tables? Though I think really this is important as the transformation after the fact is slow and this it the 'right' fix.
Fixes #1839
```release-note
Fix list feature format for BigQuery offline datasources. 
```
=> Fix list feature format for BigQuery offline datasources. 

sdk/python/feast/feature.py, sdk/python/feast/online_response.py, sdk/python/feast/type_map.py, sdk/python/tests/data/data_creator.py, sdk/python/tests/integration/registration/test_universal_types.py
This PR deals with multiple issues around empty list features regarding type inference.
It is my opinion that these fixes should be somewhat of a stop gap and that really the way that types are dealt with should be overhauled in Feast.
Fixes #
```release-note
Fix issue which prevented empty lists being materialized into online stores or retrieved from historical stores.
```
=> Handle case where`_LIST` type is empty

sdk/python/feast/infra/utils/aws_utils.py, sdk/python/feast/online_response.py, sdk/python/feast/type_map.py, sdk/python/feast/value_type.py
This PR fixes this simple case:
```python
from datetime import datetime, timedelta
from feast import Entity, Feature, FeatureStore, FeatureView, FileSource, ValueType
import numpy as np
import pandas as pd
from pathlib import Path
df = pd.DataFrame(columns=["device_type", "encoding", "datetime"])
df["device_type"] = ["A", "B", "C", "D"]
df["encoding"] = [[0, 1, 0], [1, 0, 0], None, [0, 0, 0]]
df["rank"] = np.array([1, None, 3, 4], dtype=np.float64)
df["datetime"] = pd.to_datetime([datetime.now()] * 4)
device_encodings_path_str = "data/device_encodings.parquet"
device_encodings_path = Path(device_encodings_path_str)
device_encodings_abs_path_str = …
```
=> Add `ValueType.NULL`

sdk/python/feast/usage.py
Our usage handling doesn't handle calls to `usage` annotated events *within* the implementation of `get_online_features`. So, e.g., calling `get_feature_views` within `get_online_features` would always get called, which would result in bad performance. 
This fixes that by maintaining the call stack and making sure any call path that includes `get_online_features` is only sampled.
Fixes #
```release-note
none
```
=> Use contextvars to maintain a call stack during the usage calls

sdk/python/feast/repo_config.py
The feature_store.yaml file allows Feast users to enter connection strings for offline and online stores. For example:
```yaml
registry:
path: ./registry.db
project: production
provider: local
online_store:
type: redis
connection_string: my-secret-connection-string
```
This means that a connection string can sit in a plain text file, which makes CI/CD impossible.
This PR allows Feast users to hide the connection string in the YAML file by using environment variables. For example:
```yaml
registry:
path: ./registry.db
project: production
provider: local
online_store:
type: redis
connection_string: ${CONN_STRING_ENV_VAR}
```
Here the environment variable `CONN_STRING_ENV_VAR` is resolved in repo_config.load_repo_config method. This aids CI/CD flows …
=> resolve environment variables in repo config

sdk/python/feast/entity.py, sdk/python/feast/feature_service.py, sdk/python/feast/feature_store.py, sdk/python/feast/feature_table.py, sdk/python/feast/feature_view.py, sdk/python/feast/importer.py, sdk/python/feast/infra/online_stores/redis.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/repo_operations.py, sdk/python/tests/unit/test_entity.py
Fixes #1895 
```release-note
none
```
=> Fix issue with feature views being detected as duplicated when imported

sdk/python/feast/type_map.py, sdk/python/tests/integration/online_store/test_e2e_local.py, sdk/python/tests/integration/online_store/test_universal_online.py
Float features are erroneously materialized to online stores as doubles. This bug could drastically affect the memory and  storage usage of online stores.
Fixes #1904
```release-note
NONE
```
=> Respect specified ValueTypes for features during materialization

sdk/python/feast/entity.py, sdk/python/feast/feature_service.py, sdk/python/feast/feature_table.py, sdk/python/feast/feature_view.py, sdk/python/feast/importer.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/repo_operations.py, sdk/python/tests/integration/registration/test_cli_apply_duplicated_featureview_names.py, sdk/python/tests/unit/test_entity.py
#1905 didn't solve the problem - so this is a simpler approach that is probably more robust.
Fixes #
```release-note
none
```
=> Use set when parsing repos to prevent duplicates

sdk/python/feast/infra/utils/aws_utils.py
Fixes #1841 
```release-note
Sets a 5 minute limit for redshift statement execution.
```
=> Set a 5 minute limit for redshift statement execution

Makefile
First-time contributor here.  I noticed that when I was running through the list of things in CONTRIBUTORS.md to set up my dev environment, I ran `make lint` and `make format` and a whole bunch of files were changes.  Turns out that the black being used in my local setup was not the same the version of the one installed with dev dependencies.  Since `black` is called directly as a CLI command rather than as a python module in the make command, it uses my system default rather than the one installed via `pip install -e 'sdk/python[ci]'`.  This would also apply to the other python linting tools utilized in the make file as well (ie mypy, isort, etc).  So to ensure that the correct versions of everything are used I changed the makefile to execute black …
=> Update makefile to use pip installed dependencies

.github/workflows/integration_tests.yml, .github/workflows/linter.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/unit_tests.yml, sdk/python/tests/conftest.py, sdk/python/tests/utils/online_read_write_test.py
Github has a way of caching dependencies on a per-job level, which can be used to speed up actions/builds by caching dependencies and builds. 
Our dependencies don't change that often - so we can cache the step of installing and setting up our python environment. 
Example:
- Before Caching: https://github.com/feast-dev/feast/runs/3773858745?check_suite_focus=true
- After Caching: https://github.com/feast-dev/feast/runs/3773917413?check_suite_focus=true
`Install Dependencies` went from 1m19s to 25s.
Fixes #
```release-note
none
```
=> Add a caching step to our github actions

sdk/python/feast/infra/offline_stores/bigquery.py
Currently, the BigQueryOfflineStore default to the 'us' GCP region and does provide a configuration to change the region. This PR adds a config to BigQueryOfflineStoreConfig that allows defining a GCP region for a BigQueryOfflineStore.
The default behavior (defaulting to region 'us') is maintained (ie. no location/region specified in the offline store configuration).
Fixes #1728 
```release-note
Add location configuration to BigQueryOfflineStore
```
=> Add location to BigQueryOfflineStoreConfig

sdk/python/feast/infra/online_stores/redis.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/e2e/test_universal_e2e.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/utils/online_read_write_test.py
Signed-off-by: Vitaly Sergeyev <vsergeyev@better.com>
Several parts here mostly for discussion then can break into smaller PRs:
1. check the event timestamp before writing the features
the use case here comes into play when there are multiple ways to ingest into the OnlineStore (i.e. materialization, direct/streaming ingestion) so timing could be different in different scenarios so we are checking the even timestamp to make sure only the latest features are written
2. using redis pipelines to limit the amount of network calls 
if there are a lot of entities to lookup in Redis then the number of network calls to Redis may be the bottleneck. Tested this with >1000 entities and it's slow without using pipelines.
3. (**removed from this PR**)  support expiring records in the Redis -- probably …
=> eventtime check before writing features, use pipelines, ttl

sdk/python/feast/cli.py, sdk/python/feast/constants.py, sdk/python/feast/infra/aws.py
**What this PR does / why we need it**: This PR fixes or improves a couple of things
1. Docker push command was failing for me without any errors in Python, which took quite some time to debug. With this change I make it possible to print out docker command outputs. This is logged on the debug level, so you'll need to run it with `--log-level=debug`, for example `feast --log-level=debug apply`. Also, looks like log-level flag was not working correctly, so I also fixed that.
2. We shouldn't try docker image download/upload if the image is already in ECR. So I made a change that first checks this image in ECR and only runs the docker logic if necessary. This also means that from the 2nd `feast apply`, users won't need to have docker daemon …
=> Improve aws lambda deployment (logging, idempotency, etc)

sdk/python/setup.py
Signed-off-by: Yusuke Nishioka <yusuke.nishioka.0713@gmail.com>
`proto-plus==1.19.7` requires `protobuf>=3.19.0`, which conflicts with the version required by `google-api-core[grpc]`.
Also, `setup_requires` tries to install the latest version of `mypy-protobuf` because the version is not specified and it requires `protobuf>=3.18.0`.
The error log is like this:
```console
$ pipenv install -e "sdk/python[gcp]"
...
There are incompatible versions in the resolved dependencies:
protobuf>=3.10 (from -r /tmp/pipenvu4bjkllirequirements/pipenv-sxv104g1-constraints.txt (line 21))
protobuf<3.18.0,>=3.12.0 (from google-api-core[grpc]==1.31.3->-r /tmp/pipenvu4bjkllirequirements/pipenv-sxv104g1-constraints.txt (line 5))
protobuf<4.0dev,>=3.5.0.post1 (from …
```
=> Fix protobuf version conflict in [gcp] and [ci] packages

sdk/python/feast/feature_store.py, sdk/python/feast/registry.py, sdk/python/feast/repo_operations.py, sdk/python/tests/integration/registration/test_registry.py
**What this PR does / why we need it**: This PR removes the duplicate `update_infra` call in `feast apply`. It also cleans up `apply_total`, by ensuring that entities and ODFVs are also being deleted.
Fixes #1795 
```release-note
feast apply only calls update_infra once
```
=> Fix duplicate update infra

sdk/python/feast/type_map.py
Twitter uses this BOOLEAN legacy sql data type for Big Query.
=> Update bq_to_feast_value_type with BOOLEAN type as a legacy sql data type

docs/getting-started/concepts/feature-view.md
This adds public documentation for entity aliasing functionality to the [concepts/feature-view](https://docs.feast.dev/getting-started/concepts/feature-view) page. (Also, this is my first time contributing the public docs - not sure what the process is / if it's ok to do it through a PR like this.)
Fixes #1762
```release-note
NONE
```
=> Add public docs for entity aliasing

sdk/python/feast/type_map.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
* When the DataFrame returned by an ODFV UDF uses dtypes like `pd.Int64Dtype()` type mapping fails.
Fixes #
```release-note
```
=> Fix bug where using some Pandas dtypes in the output of an ODFV fails

sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/transformation_server.py
I've run into a problem where when an ODFV depends on two FV which have colliding feature names the ODFV will always want the full feature names. However, it only gets them when `full_feature_names` is set when requesting the features.
This PR ensures that both full and partial feature names are always passed to ODFVs.
Fixes #
```release-note
Always pass full and partial feature names to ODFV.
```
=> Always pass full and partial feature names to ODFV

Makefile, sdk/python/feast/feature_store.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/online_store/test_universal_online.py
For get_online_features, removing request data (that isn't specified by a request feature view) and odfv dependencies (that aren't otherwise requested) from the online response. It also adds in dependent feature views when specified in odfvs, so users no longer need to specify dependencies in the get_online_features request.
This also adds a rule (make test-python-universal-local) that will run local only integration tests for convenience for devs.
Related issues: #1999  and #1998 
Fixes #
```release-note
Removes need to specify on demand feature view dependencies in get_online_features
```
=> get_online_features on demand transform bug fixes + local integration test mode

sdk/python/tests/integration/e2e/test_usage_e2e.py
This PR fixes flaky e2e tests for usage module.
Fixes #
```release-note
NONE
```
=> Correct cleanup after usage e2e tests

sdk/python/tests/integration/feature_repos/repo_configuration.py
**What this PR does / why we need it**: Tests have been failing in PT due to timezone issues. This PR fixes those issues. 
Fixes #
```release-note
NONE
```
=> Change Environment timestamps to be in UTC

.github/workflows/unit_tests.yml, CONTRIBUTING.md, README.md, sdk/python/setup.py
This removes some of the duplicates of packages in the setup.py, to make sure we use consistent versions.
Additionally, when packages are not compatible we should an error like this:
```
$ pip-compile --dry-run sdk/python/setup.py --extra dev
ERROR: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ERROR: grpcio-reflection 1.42.0rc1 requires grpcio>=1.42.0rc1, but you have grpcio 1.41.1 which is incompatible.
Could not find a version that matches grpcio<1.40,<2.0dev,>=1.34.0,>=1.38.1,>=1.41.1 (from feast (sdk/python/setup.py))
Tried: 0.13.0, 0.13.1, 0.14.0, 0.15.0, 1.0.0, 1.0.1, …
```
=> Remove duplicates in setup.py and run rudimentary verifications

.github/workflows/pr_integration_tests.yml
**What this PR does / why we need it**: Looks like by default docker image build & push step checks out master branch, which is not what we want. Instead, we want to check out the PR branch and build the docker image from that codebase.
Fixes #
```release-note
NONE
```
=> Fix checked out branch for PR docker image build workflow

sdk/python/setup.py
Fixes #2030 
```release-note
none
```
=> Add missing comma in setup.py

CHANGELOG.md
**What this PR does / why we need it**: Adds changelog for v0.15.1.
Fixes #
```release-note
NONE
```
=> Update CHANGELOG for Feast v0.15.1

sdk/python/feast/registry.py, sdk/python/tests/integration/registration/test_registry.py
When changing existing on-demand-feature-views, the existing proto in the registry needs to be replaced by the new one. In this step, the existing proto has been deleted from the wrong container. The existing implementation always deletes the proto of the given index from the REGULAR feature-view container, not the odfv container.
This leads to:
1. **Unexpected deletion** of feature views
2. Index error when there are more odfv than regular feature views.
```release-note
NONE
```
=> Fix unexpected feature view deletion when applying edited odfv

sdk/python/feast/repo_operations.py
When running `feast registry-dump`, the whole registry is printed as one json.
I intentionally kept all the logic in repo_operations.py instead of adding a method to the Registry class since this is for debugging only.
**Changes**
The current implementation will print the json representation of each entity and feature view but none of the other objects such as feature services and on demand feature views. It is also not obvious which type each json represents.
```json
{
"spec": {
"name": "driver_id",
"valueType": "INT64",
"description": "driver id",
"joinKey": "driver_id"
},
"meta": {}
}
{
"spec": {
"name": "driver_hourly_stats",
"entities": [
"driver_id"
],
"features": [
{
"name": "conv_rate",
"valueType": "FLOAT"
},
{
"name": "acc_rate", …
```
=> Make `feast registry-dump` print the whole registry as one json

sdk/python/feast/feature_store.py, sdk/python/feast/repo_operations.py
The `FeatureStore.apply` method will call `update_infra` for the provider without
offering a dry run, so invoking it without committing should not be
an option. It would make all the infra updates but not update the
registry causing them to be out of sync.
Added `commit=False` to `apply_feature_service` and `apply_feature_table` in the
`apply` method.
When calling `feast apply` and adding a feature table or feature service
the registry will get updated even if the update_infra call fails.
This PR makes the only registry commit happen after the call to update_infra
has completed successfully.
```release-note
NONE
```
=> Don't allow FeatureStore.apply with commit=False

sdk/python/tests/integration/e2e/test_universal_e2e.py
There's some flakiness in this error and I can't figure out why - hoping that additional context will help debug.
```release-note
none
```
=> Add detailed error messages for test_univerisal_e2e failures

sdk/python/feast/feature_store.py, sdk/python/feast/feature_view.py, sdk/python/feast/inference.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_inference.py
```release-note
Fix to correctly exclude entity columns from being considered features when using feature inference during registration.
```
=> Properly exclude entities from feature inference

sdk/python/feast/feature_store.py, sdk/python/feast/infra/transformation_servers/app.py
Currently cached registry could expire by preconfigured TTL and will be lazy reloaded on next request, which might affect performance of transformation service.
This PR proposes to run background thread that will periodically refresh registry instead.
Fixes #
```release-note
NONE
```
=> Asynchronously refresh registry in transformation service

sdk/python/tests/integration/feature_repos/repo_configuration.py
**What this PR does / why we need it**: Previously when the full repo configs module could not be imported, the error was suppressed and the integration tests continued with the default repo configs. This makes it difficult for users who are trying to extend the test suite to realize the issue is an import error.
Fixes #
```release-note
NONE
```
=> Raise import error when repo configs module cannot be imported

.github/workflows/java_pr.yml, .github/workflows/java_release.yml, java/serving/src/main/java/feast/serving/config/RegistryConfig.java
This has been broken for a few commits now: https://github.com/feast-dev/feast/actions/workflows/java_release.yml
Fixes #
```release-note
none
```
=> Fix java_release workflow by removing step without users/with

sdk/python/feast/feature_store.py, sdk/python/feast/registry.py
Fixes #2051 
```release-note
Use cached registry to speed up direct writes to the online store
```
=> Allow using cached registry when writing to the online store

sdk/python/tests/integration/feature_repos/repo_configuration.py
We have dynamodb resources that are being leaked during integration tests. This should help figure out which runs is causing this.
Fixes #
```release-note
none
```
=> Add github run id into the integration test projects for debugging

docs/reference/alpha-on-demand-feature-view.md
Fixing typo: The correct CLI command is 'feast alpha enable on_demand_transforms' - not 'feast alpha enable enable_on_demand_transforms'
Fixes a typo in the docs.
NONE
=> Fixing typo enabling on_demand_transforms

sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py
I have run memory usage into issues on initial materialization of a large FeatureView with approaching 10 million rows and 30 columns. Acquiring the Arrow table succeeds but the conversion to Protobuf seems to require duplicating the whole dataset in memory which is not practical.
This initial improvement batches the table returned by `to_arrow` into RecordBatches which improves the situation. Looking forward I think that there should be the option (or requirement?) for RetrievalJobs to yield these RecordBatches directly to further reduce memory requirements.
This PR improves the situation from #2071 but I do not believe is enough to close it.
Fixes #
```release-note …
```
=> Optimize memory usage during materialization

examples/quickstart/quickstart.ipynb
Fixes a broken link in the quickstart python notebook
Fixes #
```release-note
NONE
```
=> Fixing broken entity key link in quickstart

sdk/python/feast/cli.py, sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py
Signed-off-by: Gunnar Sv Sigurbjörnsson <gunnar.sigurbjornsson@gmail.com>
Today the value is hardcoded to 127.0.0.1. This will enable users to
specify the host that they want to use for feast serve.
```release-note
NONE
```
=> Add --host as an option for feast serve

sdk/python/feast/registry.py, sdk/python/feast/repo_operations.py, sdk/python/tests/integration/registration/test_cli.py
**What this PR does / why we need it**: This PR ensures that the dummy entity does not get deleted on `feast apply`.
Fixes #
```release-note
NONE
```
=> Duplicate feast apply bug

sdk/python/feast/feature_store.py
**What this PR does / why we need it**: This PR refactors some of the ODFV logic in `get_online_features`.
Fixes #
```release-note
NONE
```
=> Odfv logic

sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/registration/test_universal_types.py
Fixes #
```release-note
none
```
=> Use request.addfinalizer instead of the yield based approach in integ tests

docs/getting-started/concepts/feature-retrieval.md
Fix a typo (I think) in feature retrieval doc. I am not sure why we talk about "entity timestamp" when we refer to "event timestamp" everywhere else in the paragraph.
N/A
NONE
```release-note
Fix typo in feature retrieval doc
```
=> Fix typo in feature retrieval doc

sdk/python/feast/value_type.py
Recently tensorflow_metadata protos was deleted: #2063.
This PR does additional clean-up.
Fixes #
```release-note
NONE
```
=> Remove tfx schema from ValueType

sdk/python/feast/repo_operations.py
Signed-off-by: David Y Liu <davidyliuliu@gmail.com>
```release-note
Have apply_total use the repo_config that's passed in as a parameter rather than re-producing the repo config from the repo path. 
```
=> Have apply_total use the repo_config that's passed in as a parameter (makes it more compatible with custom wrapper code)

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift.py
**What this PR does / why we need it**: This PR ensures that we do not attempt to compute ODFVs in `RetrievalJobs` when there are no ODFVs.
Fixes #2072
```release-note
NONE
```
=> Do not attempt to compute ODFVs when there are no ODFVs

sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/tests/integration/e2e/test_universal_e2e.py
test_universal_e2e::test_e2e_consistency is flaky since test records' timestamps and materialization boundaries (start and end times) are generated independently. So materialization is inconsistent, most of the time it writes 3 rows, but in some moments it could materialize the whole test dataframe (5 rows) in one go, which is not expected behavior.
Fixes #
```release-note
NONE
```
=> Fix integration test that is unstable due to incorrect materialization boundaries

sdk/python/feast/feature_store.py
Currently, even if `online=False` is set on a FeatureView `feast materialize` will try to materialize the FeatureView.
This PR prevents this.
Fixes #
```release-note
Correct behavior of non-online FeatureViews.
```
=> Don't materialize FeatureViews where `online is False`

CONTRIBUTING.md, sdk/python/setup.py
Broadens dependency on google-cloud-core. The limitation to 1.4.* seems tighter than it needs to be. The version 1.7.2 (which is the latest before 2.0.0) passes unit tests and makes feast more interoperable as a library with other systems.
Relates to https://github.com/feast-dev/feast/issues/928
```release-note
NONE
```
=> Broaden google-cloud-core dependency

.github/CODEOWNERS
Fixes #
```release-note
none
```
=> Use the maintainers group in Codeowners instead of individuals

sdk/python/feast/infra/passthrough_provider.py
`OnlineStore.online_read()` has a parameter `requested_features`. Similarly, `PassthroughProvider.online_read()` also has a parameter `requested_features`.
`PassthroughProvider.online_read()`  calls `OnlineStore.online_read()` but doesn't pass on the `requested_features` variable.
In this PR, the `requested_features` variable is passed on to `OnlineStore.online_read()`
Fixes #2106 
None
```release-note
requested_features is passed to online_read from passthrough_provider
```
=> requested_features is passed to online_read from passthrough_provider

sdk/python/setup.py
Fix feast setup script for Windows.
`README.md` contains emojis resulting character encoding issues in the package long description. This PR sets package long description encoding to UTF-8.
Fixes #2110
```release-note
NONE
```
=> Set package long description encoding to UTF-8

.github/workflows/master_only.yml, .github/workflows/release.yml
The new pip-tools way of building feast requires a python version to be passed as an argument to the makefile rule. In the release, we were not doing this.
Also the make-build-X-docker image rule had a typo that didn't include the -docker suffix.
Fixes #
```release-note
NONE
```
=> Fix release workflow to pass the python version and docker build targets

Makefile
For the lambda feature server makefile commands, the ECR_VERSION variable was not properly being generated. This fixes that so the workflows should work properly.
Fixes #
```release-note
NONE
```
=> Fix Makefile to properly create the ECR_VERSION

sdk/python/feast/feature_store.py
This argument was scheduled for removal in 0.14 according the
deprecation warning.
Fixes #
```release-note
Remove `feature_refs` argument from `get_historical_features` and `get_online_features`.
```
=> Remove  argument `feature_refs`

.github/workflows/master_only.yml, .github/workflows/release.yml, Makefile, docs/reference/alpha-aws-lambda-feature-server.md, sdk/python/feast/constants.py
This updates the lambda image to be feastdev/feature-server-python-aws instead of feastdev/feature-server-aws for more consistent naming with feature-server-java
Fixes #
```release-note
NONE
```
=> Updating lambda docker image to feature-server-python-aws

.github/workflows/release.yml
There's an outdated action that fails on running the publish helm charts. Switching the release workflow to be consistent with our other workflows, which uses the new action.
Fixes #
```release-note
NONE
```
=> Fix release workflow to use the new GCP action

CHANGELOG.md, infra/charts/feast/charts/feature-server/README.md, infra/charts/feast/charts/feature-server/values.yaml, infra/charts/feast/charts/transformation-service/README.md, infra/charts/feast/charts/transformation-service/values.yaml
Update changelog for 0.16.1 and update helm charts
Fixes #
```release-note
NONE
```
=> Update changelog for 0.16.1 and update helm charts

protos/feast/core/DynamoDBTable.proto, protos/feast/core/InfraObject.proto, sdk/python/feast/infra/infra_object.py, sdk/python/feast/infra/online_stores/dynamodb.py
**What this PR does / why we need it**: This PR adds DynamoDB tables as `InfraObject`s.
Fixes #
```release-note
NONE
```
=> Dynamodb infra object

.github/workflows/pr_integration_tests.yml
We've decided to reduce concurrency of PR integration tests so shore up their stability a bit. We will run integration tests for all the python versions on merging to master instead to keep track of this signal.
```release-note
none
```
=> Run PR integration tests only on python 3.7

Makefile, infra/templates/README.md.jinja2
The initial assumption about ECR not supporting periods isn't true, so we should be able simplify some of the release logic. Also, the README was updated without updating the template, which this PR fixes.
Fixes #2136 
```release-note
none
```
=> Remove underscores from ECR docker versions

sdk/python/tests/integration/registration/test_cli.py
**What this PR does / why we need it**: Recently we have been leaking DynamoDB tables. Upon closer inspection, I noticed that tests often leak `test_universal_cli` tables. This PR aims to ensure that those tables are always torn down.
Fixes #
```release-note
NONE
```
=> Ensure that universal CLI test tears down infrastructure

.github/workflows/pr_integration_tests.yml
**What this PR does / why we need it**: This PR ensures that we only run benchmarks upon merging to master.
Fixes #
```release-note
NONE
```
=> Do not run benchmarks on pull requests

protos/feast/core/DatastoreTable.proto, sdk/python/feast/infra/online_stores/datastore.py
**What this PR does / why we need it**: This PR adds an `InfraObject` for Datastore tables, as part of the `feast plan` implementation.
Fixes #
```release-note
NONE
```
=> Add DatastoreTable infra object

sdk/python/feast/diff/FcoDiff.py, sdk/python/feast/registry.py, sdk/python/feast/repo_operations.py
Fixes #
```release-note
`feast plan` and `feast apply` output produces property-level diffs for objects changed in-place.
```
=> Compute property-level diffs for repo objects

sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/transformation_server.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Fixes #2143
```release-note
Respect `full_feature_names` for ODFVs in `get_historical_features`.
```
=> Respect `full_feature_names` for ODFVs

protos/feast/core/InfraObject.proto, protos/feast/core/SqliteTable.proto, sdk/python/feast/infra/online_stores/sqlite.py
**What this PR does / why we need it**: This PR adds SQLite as an `InfraObject`, as part of the `feast plan` implementation.
Fixes #
```release-note
NONE
```
=> Add SqliteTable as an InfraObject

sdk/python/feast/cli.py, sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py, sdk/python/feast/registry.py
Signed-off-by: Gunnar Sv Sigurbjörnsson <gunnar.sigurbjornsson@gmail.com>
When an endpoint is async, everything happens on the event loop thread.
This is great for functionality that is IO heavy since the job can be
awaited and other requests processed in the meantime. But if there are
no awaits, then everything happens synchronously on one thread which
means that while we're waiting for a response from a DB or API call,
nothing else gets processed.
To address this I've removed the async keyword from the endpoint.
This makes FastAPI process each request on a thread in a thread pool.
Testing this with postgres as the online store, running everything locally,
and 1 worker, req/sec went from 200 to 800. …
=> Change the feast serve endpoint to be sync rather than async.

sdk/python/feast/infra/local.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/online_stores/sqlite.py, sdk/python/feast/utils.py
This allows BigQuery to take advantage of Partitions when querying
historical features.
Fixes #2083 (doesn't necessarily completely fix but does fix in at least one case)
```release-note
None
```
=> Pre compute the timestamp range for feature views

sdk/python/tests/unit/diff/test_fco_diff.py
This PR just adds tests for a fairly critical piece of code.
Fixes #
```release-note
none
```
=> Add a unit test for the tag_proto_objects method

sdk/python/feast/type_map.py
For `_LIST` type features this implementation is up to 7x faster in my testing. 
For serializing and deserializing 10k rows of 3 columns `DOUBLE`, 3 columns `FLOAT_LIST`.
Old implementation:
New implementation:
Fixes #
```release-note
None
```
=> Improve online deserialization latency

sdk/python/feast/infra/provider.py, sdk/python/feast/type_map.py
Similar quick pass as the deserialize PR (#2164). A definite improvement but not as drastic as the other one. Looks like between 20-30% improvement. This is achieved by avoiding memory copies as much as possible by using Numpy and allowing Protobuf to handle that more sensibly than copying to convert to Python object then copying back again to create Protobuf Message.
Same benchmark as the deserialize PR:
On `master`:
With changes:
Fixes #
```release-note
None
```
=> Improve serialization performance

sdk/python/setup.py
The feast[aws] pin boto3 to 1.17.* which create forward compatibles issue.
Removing the pin to undo the issue.
Fixes #
```release-note
Unpin dependency on boto3
```
=> unpin boto dependency in setup

sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/type_map.py, sdk/python/tests/integration/registration/test_inference.py
Fixes #2053 
```release-note
none
```
=> Fix issue with numpy datetimes in feast_value_type_to_pandas_type

.github/workflows/master_only.yml, .github/workflows/release.yml, infra/scripts/helm/validate-helm-chart-versions.sh
Fixes #2152 and also [failing helm publishing](https://github.com/feast-dev/feast/runs/4493547143?check_suite_focus=true)
```release-note
none
```
=> Push docker image after build in GH workflow

sdk/python/feast/feature_store.py, sdk/python/feast/infra/provider.py, sdk/python/feast/online_response.py, sdk/python/feast/type_map.py
Packing python native values (or NumPy arrays) into proto objects (generated proto classes) takes roughly 80% of the time during materialization (not counting offline / online storage part). Ironically protobuf serialization itself takes around 10% of the time.
This PR refactors `python_values_to_proto_values` function to process data in bulk (essentially column by column), which improves performance by running all type checks only once (per batch / column). According to my analysis, this move will decrease packing time roughly by 50% without introducing significant changes (see first comment).
Fixes # …
=> Convert python values into proto values in bulk

infra/charts/feast/charts/feature-server/templates/deployment.yaml, infra/docker-compose/docker-compose.yml, java/serving/src/main/java/feast/serving/ServingGuiceApplication.java, java/serving/src/main/java/feast/serving/config/ApplicationProperties.java, java/serving/src/main/java/feast/serving/config/ApplicationPropertiesModule.java, java/serving/src/main/java/feast/serving/config/ServerModule.java
After the recent deletion of Spring in Java feature server we have some functionality degradation:
* Multiple configuration files are not supported
* Default configuration (stored in classpath) cannot be loaded
Also `ApplicationProperties$Store` class cannot be deserialized (bug) due to the absense of the default constructor.
This PR addresses all those issues and returns back the possibility to override configurations.
Also helm chart and docker-compose were updated to new expected CMD format.
Fixes #
```release-note
None
```
=> Support multiple application properties files (incl from classpath)

sdk/python/feast/infra/online_stores/datastore.py
Fixes runtime exception when feature values are larger than 1500 bytes in Datastore.
Datastore indexes values as well as keys so by default it disallows large payloads (error: `google.api_core.exceptions.InvalidArgument: 400 The value of property _ is longer than 1500 bytes.`). This PR ensures that values will not be indexed, which seems to be the intent of the original code.
Fixes #1633 
```release-note
NONE
```
**Testing**
There is not yet a test harness for changes of this sort. The issue is demonstratable in master & fixed in this branch with the following steps (you'll want to change some of them):
`echo '{"entity": "entity1", "event_timestamp": …
=> Fixes large payload runtime exception in Datastore (issue 1633)

sdk/python/feast/feature_store.py
Fixes #2184
```release-note
None
```
=> Avoid requesting features from OnlineStore twice

sdk/python/feast/registry.py, sdk/python/tests/integration/registration/test_cli.py
**What this PR does / why we need it**: #1952 was recently merged and is currently breaking integration tests on master. Specifically, by setting `created_timestamp` for feature views, the `test_universal_cli` test breaks because the second `feast apply` changes FV metadata, causing the registry to be changed. This PR ensures that when registry contents are compared after the first and second calls to `feast plan`, only specs of the FCOs are compared, and metadata is excluded. This allows the test to pass.
Fixes #
```release-note
NONE
```
=> Compare only specs in integration tests

sdk/python/feast/online_response.py
Gives a latency benefit.
New:
Old:
Fixes #
```release-note
None
```
=> Refactor `OnlineResponse.to_dict()`

sdk/python/feast/registry.py
The deletion of on demand feature views is broken as it is not covered in `registry.delete_feature_view`. 
This is a small fix to cover deletion of odfv the same way it is done for standard or request feature views. 
```release-note
NONE
```
=> Add on demand feature views deletion

sdk/python/feast/errors.py, sdk/python/feast/importer.py, sdk/python/feast/infra/infra_object.py, sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/feast/infra/online_stores/helpers.py, sdk/python/feast/infra/provider.py, sdk/python/feast/registry.py, sdk/python/feast/repo_config.py, sdk/python/tests/integration/registration/test_cli.py
**What this PR does / why we need it**: This PR takes all importer logic and refactors it so that all importer logic belongs to a single method, `get_class_from_module`, in `feast.importer`.
Fixes #
```release-note
NONE
```
=> Refactor all importer logic to belong in feast.importer

sdk/python/feast/diff/infra_diff.py, sdk/python/feast/infra/infra_object.py, sdk/python/feast/infra/online_stores/datastore.py, sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/feast/infra/online_stores/sqlite.py, sdk/python/tests/unit/diff/test_infra_diff.py
**What this PR does / why we need it**: This PR implements the `diff_infra_protos`, which will compute the difference between two `InfraProto` objects, for `feast plan`.
Fixes #
```release-note
NONE
```
=> Implement diff_infra_protos method for feast plan

sdk/python/requirements/py3.7-ci-requirements.txt, sdk/python/requirements/py3.7-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, sdk/python/setup.py
Updates click from 7.x to 8.x - https://click.palletsprojects.com/en/8.0.x/upgrading/
```release-note
NONE
```
=> Updates to click==8.*

sdk/python/feast/diff/FcoDiff.py, sdk/python/feast/diff/infra_diff.py, sdk/python/feast/errors.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/infra_object.py, sdk/python/feast/infra/local.py, sdk/python/feast/infra/online_stores/datastore.py, sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/feast/infra/online_stores/online_store.py, sdk/python/feast/infra/online_stores/sqlite.py, sdk/python/feast/infra/provider.py, sdk/python/feast/repo_operations.py
**What this PR does / why we need it**: This PR modifies `feature_store.plan` to produce an `InfraDiff` object, which will be used to modify infrastructure as part of `feast plan`.
Fixes #
```release-note
NONE
```
=> Modify feature_store.plan to produce an InfraDiff

sdk/python/feast/feature_server.py, sdk/python/feast/feature_view.py, sdk/python/tests/conftest.py, sdk/python/tests/example_repos/example_feature_repo_with_duplicated_featureview_names.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/online_store/test_universal_online.py
We've run into issues debugging the lambda test, so introducing a local feature server that is instantiated on tests that have python_feature_server=True on a local provider.
This also logs the stack trace on the feature server. This was useful in debugging https://github.com/feast-dev/feast/pull/2202
Fixes #
```release-note
NONE
```
=> Adding a local feature server test

java/infra/docker/feature-server/Dockerfile
Fixes docker file for Java feature server.
Fixes #
```release-note
none
```
=> Docker build fails for java feature server

sdk/python/feast/repo_operations.py
Need a way to pass a user-defined repo to the apply_total method. Added a new method which `apply_total` will now call that takes a RepoContents arg
Fixes #2128
```release-note
1. Added functionality
2. No User action required
3. added method: apply_total_with_repo_instance()
4. See #2128 
```
=> Split apply total parse repo

infra/charts/feast/charts/feature-server/templates/deployment.yaml
Helm install fails on feature-server helm chart.
Fixes #2232 
```release-note
none
```
=> Feature server helm chart produces invalid YAML

sdk/python/feast/diff/FcoDiff.py, sdk/python/feast/feature_service.py, sdk/python/feast/feature_store.py, sdk/python/feast/registry.py, sdk/python/feast/repo_contents.py, sdk/python/feast/repo_operations.py, sdk/python/tests/integration/e2e/test_usage_e2e.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/unit/diff/test_fco_diff.py
**What this PR does / why we need it**: This PR switches `Registry.diff_between` and other helper methods to compare registry objects as Python objects instead of proto objects.
Fixes #
```release-note
NONE
```
=> Compare Python objects instead of proto objects

docs/SUMMARY.md, docs/getting-started/concepts/README.md, docs/getting-started/concepts/dataset.md, protos/feast/core/Registry.proto, protos/feast/core/SavedDataset.proto, sdk/python/feast/errors.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/feast/registry.py, sdk/python/feast/saved_dataset.py, sdk/python/tests/foo_provider.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
This PR introduces persisting results of historical retrieval. This feature is required by Data Quality Monitoring and described in the [DQM RFC](https://docs.google.com/document/d/110F72d4NTv80p35wDSONxhhPBqWRwbZXG4f9mNEMd98/edit#heading=h.9gaqqtox9jg6). The difference with RFC, though, is that this PR proposes to persist datasets in configured offline store (currently supported Redshift / BigQuery / File) instead of always writing it to cloud storage as parquet files.
Example of usage:
```
from feast.infra.offline_stores.bigquery_source import SavedDatasetBigQueryStorage
job = store.get_historical_features(...)
ds = store.create_saved_dataset(
from_=job,
name='my_persisted_ds', …
```
=> Persisting results of historical retrieval

sdk/python/feast/type_map.py, sdk/python/tests/data/data_creator.py, sdk/python/tests/integration/registration/test_universal_types.py
Fixes #2209
```release-note
Fix ValueType.UNIX_TIMESTAMP conversions
```
=> Fix ValueType.UNIX_TIMESTAMP conversions

sdk/python/feast/diff/FcoDiff.py, sdk/python/feast/diff/infra_diff.py, sdk/python/feast/feature_store.py, sdk/python/feast/registry.py, sdk/python/feast/repo_operations.py
**What this PR does / why we need it**: This PR modifies `FeatureStore` to execute `feast apply` logic by applying the appropriate `RegistryDiff` and `InfraDiff` generated from `FeatureStore._plan`. Right now, this logic is only activated for the local provider.
Fixes #
```release-note
feast plan works:
$ feast plan
Unchanged entity driver_id
Unchanged feature view driver_hourly_stats
Unchanged sqlite table adjusted_raven_driver_hourly_stats
```
=> Implement feature_store._apply_diffs to handle registry and infra diffs

sdk/python/feast/infra/offline_stores/bigquery.py
GCP Project IDs which include a hyphen followed immediately by a number are valid (such as `project-001`), however these need to be escaped with backticks when used in a BQ query as a table reference. This PR adds backticks around the table reference in the MULTIPLE_FEATURE_VIEW_POINT_IN_TIME_JOIN template so that BigQuery doesn't throw an error.
Fixes #
```release-note
NONE
```
=> Add backticks to left_table_query_string

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/redis.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/online_store/test_universal_online.py
This PR adds the test for the use case described in #2150 as well as the fix for it.
Fixes #2150 
```release-note
NONE
```
=> Delete entity key from Redis only when all attached feature views are gone

.github/workflows/master_only.yml, .github/workflows/pr_integration_tests.yml
Need to allow integration tests to talk to snowflake, this PR injects the snowflake secrets onto the test infra
Fixes #
```release-note
NONE
```
=> Add snowflake environment variables to allow testing on snowflake infra

sdk/python/feast/type_map.py, sdk/python/tests/integration/registration/test_universal_types.py
Title is pretty self explanatory. However, it should also be noted that before this PR the `unix_timestamp_val` and `unix_timestamp_list_val` attributes of `Value` were never set. So there was a Proto type which was, as far as I can tell, stored incorrectly.
Because this fixes a bug in how `UNIX_TIMESTAMP` types are represented in the OnlineStore this change could result in a mix of Python types being returned for `UNIX_TIMESTAMP` features in existing OnlineStores.
Fixes #
```release-note
Return `UNIX_TIMESTAMP` as Python `datetime`
```
=> Return `UNIX_TIMESTAMP` as Python `datetime`

sdk/python/feast/diff/FcoDiff.py, sdk/python/feast/diff/infra_diff.py, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/feature_store.py, sdk/python/feast/inference.py, sdk/python/feast/repo_operations.py, sdk/python/tests/integration/e2e/test_usage_e2e.py, sdk/python/tests/unit/diff/test_registry_diff.py
**What this PR does / why we need it**: This PR cleans up `feast plan`. Specifically:
1. `Fco` is renamed to `FeastObject`.
2. Unchanged objects are no longer logged.
first `feast apply`:
then `feast plan`:
3. Validation and inference are run during `feast plan`.
Fixes #
```release-note
feast plan output only includes changed objects
```
=> Feast plan clean up

sdk/python/feast/type_map.py, sdk/python/tests/integration/registration/test_universal_types.py
This refactoring is intented to make it more difficult
to forget to add conversion for LIST versions of
non-LIST types.
Fixes #
```release-note
None
```
=> Refactor `pa_to_feast_value_type`

sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/type_map.py
BigQuery arrays are currently handled incorrectly for many cases in feature type inference.
This PR is a subset of #2028. Some of the other issues that PR dealt with have subsequently been fixed.
Fixes #
```release-note
Fix inference of BigQuery ARRAY types.
```
=> Fix inference of BigQuery ARRAY types.

java/serving/src/test/java/feast/serving/it/ServingBaseTests.java, java/serving/src/test/java/feast/serving/it/ServingBenchmarkIT.java, java/serving/src/test/resources/docker-compose/feast10/definitions.py, java/serving/src/test/resources/docker-compose/feast10/materialize.py, java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/EntityKeySerializerV2.java
Fixes #2253 
```release-note
NONE
```
=> Fix Redis key serialization in java feature server

sdk/python/feast/registry.py
Use `datetime.now` has the potential for timezone issues, especially when persisting the data to the Registry. 
Use `datetime.utcnow`instead.
Fixes #
```release-note
None
```
=> Use `datetime.utcnow()` to avoid timezone issues

docs/tutorials/driver-stats-using-snowflake.md
**What this PR does / why we need it**: This PR fixes the Snowflake docs to accurately reflect the fact that Snowflake is being used as an offline store, and not an online store.
Fixes #
```release-note
NONE
```
=> Fix Snowflake docs

infra/charts/feast-python-server/Chart.yaml, infra/charts/feast-python-server/README.md, infra/charts/feast/Chart.yaml, infra/charts/feast/requirements.yaml, infra/scripts/helm/push-helm-charts.sh, infra/scripts/helm/validate-helm-chart-versions.sh
The existing script does not successfully run for a variety of reasons. Also, it does not package and push the python feature server. This fixes those (though requires we remove old versions of the helm chart for the java feature server due to weird versioning issues)
Fixes #
```release-note
NONE
```
=> Fix / update helm chart workflows to push the feast python server

infra/charts/feast/README.md, infra/charts/feast/charts/feature-server/Chart.yaml, infra/charts/feast/charts/feature-server/README.md, infra/charts/feast/charts/transformation-service/Chart.yaml, infra/charts/feast/charts/transformation-service/README.md, infra/scripts/helm/push-helm-charts.sh, infra/scripts/helm/validate-helm-chart-versions.sh
Fixes #
```release-note
NONE
```
=> Unify all helm charts versions

.github/workflows/release.yml, sdk/python/feast/constants.py, sdk/python/feast/usage.py
There will be two python packages `feast` and `feast-no-telemetry`. The last one will have `FEAST_USAGE` set to False by default.
To minimize maintenance costs as much as possible I solved this issue on the last possible stage - GH workflow job.
Fixes #2235 
```release-note
NONE
```
=> Publish alternative python package with FEAST_USAGE=False by default

java/serving/README.md
Removes old documentation for Feast Serving and adds new instructions for debugging locally
Fixes #
```release-note
NONE
```
=> Update Feast Serving documentation with ways to run and debug locally

docs/getting-started/concepts/dataset.md, docs/tutorials/tutorials-overview.md, docs/tutorials/validating-historical-features.md
Fixes #
```release-note
NONE
```
=> Tutorial on validation of historical features

README.md, docs/getting-started/third-party-integrations.md, docs/roadmap.md
Fixes #
```release-note
NONE
```
=> Add link to community plugin for Spark offline store

.github/workflows/release.yml, infra/scripts/publish-java-sdk.sh
Upgrades the helm version used in releases since helm v3 is required for api version v2 in the python helm chart. Also changing the java sdk publish script which got broken because of some directory refactoring
Fixes #
```release-note
NONE
```
=> Upgrade helm version and fix incorrect java sdk publish script

sdk/python/feast/type_map.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/integration/registration/test_universal_types.py
Several issues addressed in this PR:
1. Test environment time range (start and end dates) was instantiated once on tests start. Which could be an issue when tests are started at the end of the hour and then continued to the next hour. So there will be difference between generated datasets boundaries and environment start and end timestamps.
2. In `test_online_store_cleanup` some online stores (like dynamo) can have eventual consistency of schema. So when table was deleted it might need some time before it can be recreated.
3. Bug with inferring feature type when all values are empty list.
Fixes #
```release-note …
```
=> Fix flaky tests (test_online_store_cleanup & test_feature_get_online_features_types_match)

java/pom.xml
Fixes #
```release-note
NONE
```
=> Add -SNAPSHOT suffix to pom.xml version

.github/workflows/unit_tests.yml
Signed-off-by: sfc-gh-madkins <miles.adkins@snowflake.com>
Exposes snowflake credentials as environment variables so that unit testing can happen
Fixes #
```release-note
NONE
```
=> Expose snowflake credentials  for unit testing

sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
Signed-off-by: sfc-gh-madkins <miles.adkins@snowflake.com>
Aligns our snowflake testing code with the snowflake testing environment
Fixes #
```release-note
NONE
```
=> Use an OFFLINE schema for Snowflake offline store tests

sdk/python/feast/infra/online_stores/redis.py
Signed-off-by: DvirDukhan <dvir@redis.com>
This PR avoids using Transactions in redis-py pipelines when on a single instance mode. 
redis-py pipelines are created by default as transactions https://github.com/redis/redis-py/blob/24cdd70761c7c275d5010f628f83d919bf35fc90/redis/client.py#L1020
However, on cluster mode, redis-py pipeline is built with `transaction=None` https://github.com/redis/redis-py/blob/045d5ed15305ccc44a0330e6f65f669998815598/redis/cluster.py#L698
from https://redis.io/topics/transactions :
```
All the commands in a transaction are serialized and executed sequentially.
It can never happen that a request issued by another client is served in the middle of the execution of a Redis transaction.
This guarantees that the commands are …
```
=> avoid using transactions on OSS Redis

infra/charts/feast/charts/feature-server/README.md, infra/charts/feast/charts/feature-server/templates/deployment.yaml, infra/charts/feast/charts/feature-server/values.yaml
This PR adds the possibility of a user passing arbitrary `podAnnotations` Values to the feature-server chart.
Reference: https://tectonfeast.slack.com/archives/C01MSKCMB37/p1644600405847739
=> podAnnotations Values in the feature-server chart

sdk/python/feast/cli.py, sdk/python/feast/feature_server.py
We removed the need for a flag, but still have warnings that print when running `feast serve`. This removes those warnings.
Fixes #
```release-note
NONE
```
=> Remove old flag warning with the python feature server

sdk/python/feast/infra/utils/snowflake_utils.py
The import should be handled like in `aws_utils`
Fixes #
```release-note
None
```
=> Don't require `snowflake` to always be installed

.github/workflows/master_only.yml
Fixes issue with master integration test where the redis cluster never spins up. 
Fixes #
```release-note
NONE
```
=> Add redis cluster initialziation to master github workflow

sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/repo_configuration.py
**What this PR does / why we need it**: This PR (temporarily) disables all Redis cluster tests. Recently Redis cluster tests were added in #2311 and #2317, but since the current Redis cluster logic is broken, these tests are failing and blocking other PRs. 
Fixes #
```release-note
NONE
```
=> Disable Redis cluster tests

protos/feast/core/FeatureService.proto, sdk/python/feast/feature_service.py, sdk/python/feast/feature_view_projection.py
**What this PR does / why we need it**: This PR adds the `owner` field to `FeatureService`. It also cleans up `FeatureService` and `FeatureViewProjection`.
Fixes #
```release-note
NONE
```
=> Add owner field to FeatureService

.prow/plugins.yaml
Ensures the Prow auto-updater actually updates config.yaml
Fixes #
```release-note
NONE
```
=> ci: Fix broken Prow plugin which ignores config.yaml

.gitignore, java/serving/src/main/java/feast/serving/config/ApplicationProperties.java, java/serving/src/test/java/feast/serving/it/TestUtils.java, java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml, java/serving/src/test/resources/docker-compose/feast10/feature_store.yaml, java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterClient.java, java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterStoreConfig.java
This is a partial forward port of https://github.com/feast-dev/feast-java-old/pull/44 to enable auth for Redis in the Java feature server (Python already handles this)
Fixes # https://github.com/feast-dev/feast/issues/2285
```release-note
Java feature server now supports SSL and password based authentication for Redis
```
=> feat: Allowing password based authentication and SSL for Redis in Java feature server

sdk/python/feast/base_feature_view.py, sdk/python/feast/data_source.py, sdk/python/feast/entity.py, sdk/python/feast/feature_service.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/registry.py
**What this PR does / why we need it**: This PR deletes unnecessary properties, and instead makes the attributes public.
Fixes #
```release-note
NONE
```
=> refactor: Delete properties

sdk/python/requirements/py3.7-ci-requirements.txt, sdk/python/requirements/py3.7-requirements.txt, sdk/python/setup.py
See https://github.com/dask/dask/pull/8572 which dropped Python 3.7 support in Dask for the last 2 releases.
Fixes #
```release-note
NONE
```
=> ci: Capping the dask dependency since Dask dropped Python 3.7 support

sdk/python/feast/infra/online_stores/redis.py, sdk/python/tests/integration/online_store/test_universal_online.py
Signed-off-by: Vitaly Sergeyev <vsergeyev@better.com>
TTL feature for Redis online store in order to expire entity keys after some time.
Some thoughts and discussions here:
https://docs.google.com/document/d/1K8k756lgsG-YoIiEyHMOOBEejQerurhfMIABlu8Cir4/edit#heading=h.gjdgxs
Issue:
https://github.com/feast-dev/feast/issues/1988
This implementation is explicitly for the Redis Online store. In the future, this may be better as a `FeatureView` or `Entity` ttl param but it would need some more development to be able to handle across different OnlineStore providers.
```release-note
Python Redis online store allows TTL expiration on entity keys
```
=> feat: Key ttl setting for redis online store

sdk/python/feast/feature_store.py
Only the SQLite local provider supports _plan and _apply_diffs. Updated
the _should_use_plan method to only return true for that setup so that other local providers don't need to implement these methods right now.
Signed-off-by: Gunnar Sv Sigurbjörnsson <gunnar.sigurbjornsson@gmail.com>
Only the SQLite provider supports _plan and _apply_diffs today. Before this can be added to other providers there needs to be some discussion around the InfraObject and how the update and teardown is performed.
My main worry at the moment is that the InfraObject can be constructed from a proto and then the update method can be called. This requires all the connection information and credentials to be present in the infra object proto.
**Does this PR introduce a …
=> fix: Method _should_use_plan only returns true for local sqlite provider

sdk/python/feast/__init__.py, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/feast_object.py, sdk/python/feast/feature_store.py, sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/e2e/test_validation.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/offline_store/test_s3_custom_endpoint.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
Before, the test data and test objects used for the universal test suite tended to be a Dict[str, Any] with hardcoded keys. This converts those into data classes which allows for much better IDE integrations.
Fixes #
```release-note
NONE
```
=> refactor: Refactor universal test data to have more well defined types

.github/workflows/pr_integration_tests.yml, sdk/python/tests/integration/feature_repos/repo_configuration.py
We want to point redis client at a port other than 6379 and point the redis cluster at 6379. Therefore I'm starting another redis client to make sure the two don't intersect. 
Redis single node clients are somehow connecting to the redis cluster node and the intersection is causing issues. Therefore, this PR starts up another redis node that we can connect to for the tests. 
Left the redis image in just in case we need to revert this change in the event of breaking changes.
Fixes #
```release-note
NONE
```
=> fix: Update github workflow to prevent redis from overlapping ports.

.github/workflows/master_only.yml, sdk/python/tests/integration/registration/test_cli.py
There is still redis client of some sort and it may still be because of this random excess client so I'm going to remove it.
It is not used anymore anyway since the current build is stable in master using 12345 as the port. 
Fixes #
```release-note
NONE
```
=> fix: Remove redis service to prevent more conflicts and add redis node to master_only

.github/workflows/publish.yml, .github/workflows/release.yml, .releaserc.js, infra/scripts/validate-release.sh
**What this PR does**
* Adds support for https://semantic-release.gitbook.io.
* Allows us to cut releases through a manually triggered workflow.
* Updates the changelog
* Creates a commit
* Creates a tag
* Pushes tag to GitHub
* Creates a GitHub release
* Triggers `publish.yml` to build and publish artifacts
* Supports both minor and patch releases.
**What this PR doesn't do**
* Does not backport commits. 
* Does not forward port changelogs from release branch to master branch (but that's ok)
```release-note
NONE
```
=> ci: Add support for semantic release

sdk/python/feast/infra/utils/aws_utils.py
**What this PR does / why we need it**: We currently stop waiting for the Redshift statements to finish executing if they take over 5 minutes to finish. This can lead to unexpected behaviors, for example executing another concurrent Redshift statement that can interfere with the former one.
Fixes #
```release-note
NONE
```
=> fix: Fix Redshift bug that stops waiting on statements after 5 minutes

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/redis.py, sdk/python/feast/online_response.py, sdk/python/tests/integration/online_store/test_universal_online.py
```release-note
* ability to pull event timestamps from OnlineResponse
* fix small event timestamps bugs (proto reference bug + potential timezone bug)
```
=> feat: Event timestamps response

protos/feast/core/DataSource.proto, protos/feast/core/OnDemandFeatureView.proto, protos/feast/core/Registry.proto, protos/feast/core/RequestFeatureView.proto, protos/feast/core/SavedDataset.proto, protos/feast/core/ValidationProfile.proto, protos/feast/storage/Redis.proto, sdk/python/feast/cli.py, sdk/python/feast/data_source.py, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/errors.py, sdk/python/feast/feast_object.py, sdk/python/feast/feature_store.py, sdk/python/feast/inference.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/registry.py, sdk/python/feast/repo_contents.py, sdk/python/feast/repo_operations.py, sdk/python/feast/saved_dataset.py, sdk/python/tests/example_repos/example_feature_repo_1.py, sdk/python/tests/example_repos/example_repo_duplicate_data_source_names.py, sdk/python/tests/integration/registration/test_cli.py, sdk/python/tests/integration/registration/test_cli_apply_duplicates.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/utils/data_source_utils.py
Key changes:
- Data sources are now registered in the registry at the top level and can be queried. They need to have names specified (defaulting to the table ref). Note that we move the request data source's name into the top level name instead. They also now have projects attached to them
- Removing unused fields in protos
- `feast registry-dump` becomes more official as a way of dumping data for the Web UI
- Saved datasets can optionally also reference a feature service if they were generated from a feature service.
Fixes #
```release-note
Data sources are now discoverable from the CLI and are attached to projects.
```
=> feat: Metadata changes & making data sources top level objects to power Feast UI

sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py
Overriding __eq__ in sources requires us to also provide a __hash__ method.
Fixes #2368
```release-note
NONE
```
=> fix: Fix unhashable Snowflake and Redshift sources

.github/workflows/pr_integration_tests.yml
This PR needs to land before go subprocess tests can be enabled for #2339. The default version of go is too old.
```release-note
none
```
=> ci: Set up go in the pr integration test workflow

docs/reference/data-sources/spark.md, sdk/python/feast/__init__.py, sdk/python/feast/feature_store.py, sdk/python/feast/inference.py, sdk/python/setup.py
There were two issues introduced related to dependencies:
1. Great expectations was being force imported in feature_store.py, which makes a default feast installation fail to run methods like feast apply
2. Similarly, the feast __init__.py referenced a SparkSource, which imported pyspark, which isn't included unless the user installs the spark extra.
This PR removes both of those dependencies (one was an unused arg).
Fixes #
=> fix: Fix default feast apply path without any extras

CONTRIBUTING.md, docs/how-to-guides/adding-or-reusing-tests.md
Add some documentation on a way to test changes to github actions workflows in feast.
Fixes #
```release-note
NONE
```
=> docs: Add short section about github actions

sdk/python/feast/infra/aws.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/online_store/test_universal_online.py
`sdk/python/tests/integration/online_store/test_universal_online.py::test_online_retrieval` has been failling consistently for a few PRs now. This PR should address the underlying issue.
Fixes #
=> fix: Use the correct dockerhub image tag when building feature servers

sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/tests/integration/registration/test_inference.py
https://github.com/feast-dev/feast/pull/2336 introduced a change that would be breaking (forcing the first parameter of a DataSource to be a name). This pushes that to the end as an optional parameter and also outputs a warning for a future version where we require a name if users use a query in a data source.
Fixes #
=> fix: Making a name for data sources not a breaking change

ui/src/pages/entities/EntityOverviewTab.tsx, ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx, ui/src/parsers/feastEntities.ts, ui/src/parsers/feastFeatureViews.ts, ui/src/parsers/parseEntityRelationships.ts
Signed-off-by: Yun Nan Liu <yunnanl@twitter.com>
The UI parser expects some fields to be mandatory even though the feast source api's do not, this PR makes the following fields optional:
- featureViews.meta.lastUpdatedTimestamp
- featureViews.meta.createdTimestamp
- featureViews.spec.batchSource.name
- entities.meta.createdTimestamp
- entities.meta.lastUpdatedTimestamp
Screenshots for how the UI looks when the above fields are missing vs when present
Fixes #
```release-note
None
```
=> fix: Update some fields optional in UI parser

sdk/python/feast/infra/online_stores/datastore.py
Properly closes threadpool resources.
Without this PR, large materializations produce `RuntimeError: can't start new thread`, because `threading.active_count()` infinitely increases toward system limit.  With properly closed resources, `threading.active_count()` stays low.
No open issue.
=> fix: Properly close threadpool resources

sdk/python/feast/templates/spark/bootstrap.py, sdk/python/feast/templates/spark/example.py
This includes not using SparkSessions to generate the test data (which generates a pickle exception as is) and also dynamically generating timestamps so feature view TTLs don't expire
Fixes #
=> fix: Fix Spark template to work correctly on feast init -t spark

.github/workflows/java_pr.yml, .github/workflows/pr_integration_tests.yml
**What this PR does / why we need it**: Recently #2385 ensured that Python integration tests run when a PR is given the lgtm label, but did not make the same change for Java integration tests. This PR applies the same change for Java integration tests.
Fixes #
=> ci: Ensure lgtm also triggers Java PR tests and fix YAML formatting

sdk/python/feast/infra/online_stores/dynamodb.py
Sets the dynamodb online store's table names based on a template, which can be changed in config. 
Fixes #
=> feat: Add templating for dynamodb table name

.github/workflows/master_only.yml, .github/workflows/pr_integration_tests.yml
We moved this to a github action in #2350 and #2354 but this change wasn't needed. I'd like to move the tests back to using the standard redis port so that the tests can be run while developing locally without any changes.
Corresponding test changes to use this redis instance and remove the old one will be in a followup PR.
Fixes #
=> ci: Reintroduce redis services at 6379

.github/workflows/master_only.yml, .github/workflows/pr_integration_tests.yml, sdk/python/tests/integration/feature_repos/repo_configuration.py
=> ci: Use the default redis port for tests and remove unnecessary action

sdk/python/feast/inference.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/registration/test_inference.py
`RedshiftSource` is a supported `data_source`, but the `update_data_sources_with_inferred_event_timestamp_col()` method omits it as a valid value in the assertion. This was causing the assertion to fail when using a `RedshiftSource`
Fixes #
=> fix: Added Redshift and Spark typecheck to data_source event_timestamp_col inference

sdk/python/feast/feature_store.py, sdk/python/tests/example_repos/example_feature_repo_1.py, sdk/python/tests/integration/e2e/test_universal_e2e.py, sdk/python/tests/integration/online_store/test_online_retrieval.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/utils/online_read_write_test.py
Join Key of Entity should be used when passing `entity_rows` to `get_online_features` in Python SDK. Thus, request would be consistent with response, which already uses join keys and not entity names.
Usage of entity names is deprecated and will be disabled soon.
Fixes #
=> feat: Allow using entity's join_key in get_online_features

.github/pull_request_template.md, CONTRIBUTING.md, docs/community.md, docs/project/contributing.md
Since many users look at CONTRIBUTING.md, adding more details there on the biggest ways we see users getting involved. 
Fixes #
=> chore: Adding documentation on community calendar + newsletter + updating CONTRIBUTING.md

sdk/python/setup.py
This should unblock the issue when mypy is typechecking our code in python 3.7. https://github.com/feast-dev/feast/pull/2405#discussion_r831751241
Fixes #
=> fix: Ensure that __init__ files exist in proto dirs

ui/src/pages/ProjectOverviewPage.tsx
The error message in the Feast UI refers to `feature_store.json` while in the example (and most feature store repos I've seen so far) are using `feature_store.yaml` instead.
=> fix: Typos in Feast UI error message

Makefile, sdk/python/MANIFEST.in, sdk/python/feast/go_server.py, sdk/python/feast/transformation_server.py, sdk/python/setup.cfg
Feast is not PEP 561 compliant which means that mypy won't infer types from feast even though the library is fully typed. This can easily be fixed by including a `py.typed` marker file at the root of the package.
References:
- https://peps.python.org/pep-0561/
- https://mypy.readthedocs.io/en/stable/installed_packages.html#using-installed-packages-with-mypy-pep-561
Signed-off-by: Tomas Pereira de Vasconcelos <tomasvasconcelos1@gmail.com>
=> feat: Make feast PEP 561 compliant

.github/workflows/java_master_only.yml, .github/workflows/master_only.yml, .github/workflows/publish.yml
**What this PR does / why we need it**: Tests on master were recently failing due to the `setup-gcloud` action being pinned to `master`. In the near future, `master` will be renamed to `main`; moreover, we should not be pinning to `master` anyways. This PR pins the `setup-gcloud` action to `v0` instead.
Fixes #
=> ci: Pin setup-gcloud actions to v0 instead of master

docs/how-to-guides/adding-a-new-offline-store.md, sdk/python/feast/infra/offline_stores/offline_store.py
Add some documentation on adding offline stores.
Fixes #2411
=> chore: Add documentation for custom offline stores

Makefile
Without the `cd`, the makefile commands generates the python/proto code with the wrong path since we rely on `os.getcwd()`.
Fixes #
=> fix: Update Makefile to cd into python dir before running commands

sdk/python/feast/infra/online_stores/dynamodb.py
Links this code to #2438.
Fixes #
=> chore: Mark DynamoDB's templating logic experimental and add a TODO

protos/feast/core/FeatureView.proto, protos/feast/core/OnDemandFeatureView.proto, protos/feast/core/RequestFeatureView.proto, sdk/python/feast/base_feature_view.py, sdk/python/feast/entity.py, sdk/python/feast/feature_view.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/request_feature_view.py
**What this PR does / why we need it**: This PR adds the `description`, `tags`, and `owner` fields to all feature view classes: `FeatureView`, `OnDemandFeatureView`, and `RequestFeatureView`.
Fixes #
=> feat: Add description, tags, owner fields to all feature view classes

go/internal/feast/featurestore.go, go/internal/feast/registry.go
Fixes the issue of registry proto caching not working at all. Added refreshes so calling any retrieval getter like list_entities actually looks into the cache to refresh before retrieving possible stale cache entities(quite a major bug that was left in the code). 
Fixes #
=> fix: Fix registry proto

sdk/python/setup.py
Calling `python setup.py build_go_lib` fails with error
```
distutils.errors.DistutilsGetoptError: invalid negative alias 'no-compile': option 'no-compile' not defined
make: *** [compile-go-lib] Error 1
```
Fixes #
=> fix: Building of go extension fails

sdk/python/feast/feature_view.py
**What this PR does / why we need it**: #2427 deprecated the option to pass in a `Duration` object for the `ttl` parameter during `FeatureView` initialization. This PR ensures that `FeatureView.from_proto` constructs a `FeatureView` using a `timedelta` object instead of a `Duration` object.
Fixes #
=> chore: Construct FeatureView with timedelta instead of Duration object

sdk/python/setup.py
Solving typo from https://github.com/feast-dev/feast/pull/2342. See https://github.com/feast-dev/feast/pull/2342#discussion_r816177367
=> fix: Relax click python requirement to >=7

sdk/python/feast/feature_view.py
**What this PR does / why we need it**: #2440 mistakenly changed the order of the `FeatureView` parameters, which could potentially break users who are defining `FeatureView`s using positional arguments. This PR ensures that the order of the parameters does not change.
Fixes #
=> chore: Reorder feature view parameters

docs/getting-started/concepts/entity.md, docs/getting-started/concepts/feature-retrieval.md, docs/getting-started/quickstart.md, docs/how-to-guides/feast-snowflake-gcp-aws/read-features-from-the-online-store.md, docs/tutorials/driver-stats-on-snowflake.md
=> chore: Updating documentation for entity's join key

sdk/python/feast/cli.py
This lets us pass time formats more flexibly
Fixes #
=> fix: Use dateutil parser to parse materialization times

go/internal/feast/ondemandfeatureview.go, sdk/python/feast/entity.py, sdk/python/tests/unit/test_entity.py
This change is backwards compatible, but produces a deprecation warning if the name is specified as a positional arg to the `__init__` method.
Fixes #
=> fix: Make name a keyword arg for the Entity class

docs/reference/data-sources/file.md, java/serving/src/test/java/feast/serving/util/DataGenerator.java, protos/feast/core/DataSource.proto, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/file_source.py
Change file options param file_url to uri. Deprecates file_url immediately because file_url is not user facing and is only used in FileSource.
DOES NOT update the API for java(i.e java still uses fileurl).
Fixes #
=> fix: Update file api

sdk/python/feast/feature.py, sdk/python/feast/types.py, sdk/python/tests/unit/test_types.py
**What this PR does / why we need it**: This PR adds the `FeastType` ABC, along with associated types, in preparation for changing the Feast type system. Specifically, this PR prepares for introducing a `Field` class which will replace the existing `Feature` class; the new `Field` class will allow user to specify types through `FeastType`s, instead of through the existing `ValueType` enum. Note that the user interface for specifying types will change, but the underlying proto representation will remain the same.
Fixes #
=> feat: Add Feast types in preparation for changing type system

protos/feast/core/DataSource.proto, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/templates/aws/bootstrap.py, sdk/python/feast/templates/aws/driver_repo.py, sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
Updates the redshift api to accept database as a parameter.
Fixes #
=> fix: Update redshift api

protos/feast/core/DataSource.proto, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/templates/snowflake/bootstrap.py, sdk/python/feast/templates/snowflake/driver_repo.py, sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
Updates snowflake source api to take `warehouse` parameter specified instead of needing to take it through `feature_store.yaml`
Fixes #
=> fix: Snowflake api update

CONTRIBUTING.md
The link to the python SDK header in the contrib document was incorrect.
I didn't create an issue for this, since it seemed like an overkill for such a trivial fix.
=> fix: Minor link fix in `CONTRIBUTING.md`

sdk/python/feast/data_source.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py
As reported in [slack](https://tectonfeast.slack.com/archives/C01N20T57C4/p1649065139586929), there's strange behavior when using [feast-hive](https://github.com/baineng/feast-hive) on feast 0.19. To summarize, this is incorrect in 0.19:
```
print(store.get_feature_view('sample_feasture'))   
"batchSource": {
"type": "CUSTOM_SOURCE",
"eventTimestampColumn": "created_timestamp",
"customOptions": {
```
when sdk v0.17 is set it gets correct output.
```
"batchSource": {
"type": "CUSTOM_SOURCE",
"eventTimestampColumn": "event_timestamp",
"createdTimestampColumn": "created_timestamp",
"customOptions": {
```
This is because `name` was added a positional arg before other args [here](https://github.com/feast-dev/feast/commit/43da2302dfcbf3b5e56ed068021b5821d5 …
=> fix: Fix DataSource constructor to unbreak custom data sources

sdk/python/feast/types.py, sdk/python/tests/unit/test_types.py
**What this PR does / why we need it**: #2475 added a new type system but did not include a method to convert from the existing type system enums (`ValueTypeProto.Enum`) to the new type system. This PR adds that conversion method.
Fixes #
=> chore: Add conversion from ValueTypeProto.Enum to new Feast type system

docs/getting-started/concepts/feature-view.md, examples/java-demo/feature_repo/driver_repo.py, java/serving/src/test/resources/docker-compose/feast10/definitions.py, sdk/python/feast/data_source.py, sdk/python/feast/feature_store.py, sdk/python/feast/inference.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/request_feature_view.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py, sdk/python/tests/unit/test_data_sources.py, ui/feature_repo/features.py
Update `RequestDataSource` and change the name to `RequestSource`
Fixes #
=> fix: Request data api update

examples/java-demo/feature_repo/driver_repo.py, java/serving/src/test/resources/docker-compose/feast10/definitions.py
Fixing java integration on master
Fixes #
=> fix: Fix Java Master

java/serving/src/test/java/feast/serving/util/DataGenerator.java, protos/feast/core/DataSource.proto, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/templates/gcp/driver_repo.py, sdk/python/tests/example_repos/example_feature_repo_1.py, sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/integration/scaffolding/test_partial_apply.py, sdk/python/tests/utils/data_source_utils.py
**What this PR does / why we need it**: The `table_ref` parameter was scheduled for deprecation in Feast 0.20 in #2336. This PR deprecates the parameter.
Fixes #
=> chore: Deprecate `table_ref` parameter for BigQuerySource

sdk/python/feast/field.py, sdk/python/feast/types.py
**What this PR does / why we need it**: This PR adds the `Field` class, which will replace the `Feature` class. The difference between `Field` and `Feature` is essentially cosmetic; `Field` will be stored under the hood using the existing protobuf structure for `Feature`.
Fixes #
=> feat: Add Field class

CONTRIBUTING.md, Makefile, sdk/python/setup.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/integration_test_repo_config.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py, sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py, sdk/python/tests/integration/feature_repos/universal/data_sources/spark_data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/online_store/datastore.py, sdk/python/tests/integration/feature_repos/universal/online_store/redis.py, sdk/python/tests/integration/feature_repos/universal/online_store_creator.py
Running integration tests for contributors has been challenging since they don't always have access to GCP or AWS. This makes development or contributions harder than they need to be.
Additionally, there's some infrastructure that's needed to run tests locally - such as redis. This shouldn't have to be installed by contributors explicitly if it's not necessary.
Fixes #
=> ci: Use testcontainers to spin up redis and datastore instances 

sdk/python/feast/field.py, sdk/python/feast/types.py, sdk/python/tests/unit/test_types.py
**What this PR does / why we need it**: #2489 added a conversion method from the new `FeastType`s to to `ValueTypeProto.Enum`. This conversion method is slightly awkward since it relies on a proto class, `ValueTypeProto.Enum`, instead of `ValueType`, the corresponding Python enum. This PR switches the conversion method to rely on `ValueType` instead of `ValueTypeProto.Enum`.
Fixes #
=> chore: Switch new type system to use ValueType instead of ValueTypeProto.Enum

sdk/python/feast/infra/utils/snowflake_utils.py
Adds ability for key-pair auth for Snowflake
Fixes #2482
=> fix: Added private_key auth for Snowflake

sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py, sdk/python/tests/utils/online_store_utils.py
Signed-off-by: Miguel Trejo <armando.trejo.marrufo@gmail.com>
The `DynamoDBOnlineStore` batch writer can raise the following error if duplicate primary keys `entity_id` appear 
> BatchWriteItem operation: Provided list of item keys contains duplicates
This Merge Request deduplicate the write batch request on `entity_id` primary key,
Fixes #2483
=> fix: Dynamodb deduplicate batch write request by partition keys

sdk/python/feast/feature_server.py
This PR adds a `/write-to-online-store` HTTP POST method to the python feature server.
**Example:** using curl to push fresh feature vectors to the online store:
```shell
curl -X POST "http://localhost:6566/write-to-online-store" -d '{
"feature_view_name": "driver_hourly_stats",
"df": {
"driver_id": [1001],
"event_timestamp": ["2022-05-13 10:59:42"],
"created": ["2022-05-13 10:59:42"],
"conv_rate": [1.0],
"acc_rate": [1.0],
"avg_daily_trips": [1000]
}
}'
```
Check the table below for the output difference of the `/get-online-features` before and after the operation above:
```shell
$ curl -X POST "http://localhost:6566/get-online-features" -d '{
"features": [
"driver_hourly_stats:conv_rate",
"driver_hourly_stats:acc_rate",
"driver_hourly_stats:avg_daily_trips"
],
"entities": {
"driver_id": …
```
=> feat: Add `/write-to-online-store` method to the python feature server

sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py
**What this PR does / why we need it**: Recently the `sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py::test_online_retrieval` test has been failing on master with the following error: `RuntimeError: key driver_id is missing in provided entity rows`. This PR fixes the bug.
Fixes #
=> fix: Fix entity row to use join key instead of name

go/embedded/online_features.go, protos/feast/core/DataSource.proto, sdk/python/feast/data_source.py, sdk/python/tests/unit/test_data_sources.py
Similar to the PushSource, we want to is to fold in batch source as a field in streaming sources, since they are used for semantically for "backfill". 
Fixes #
=> fix: Support passing batch source to streaming sources for backfills

sdk/python/feast/data_source.py, sdk/python/feast/feature_view.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py
Building off https://github.com/feast-dev/feast/pull/2523 , this PR adds a new `source` field to the `FeatureView` API.
Fixes #
=> chore: Add a source field in the feature view API

docs/getting-started/concepts/feature-view.md, docs/getting-started/concepts/point-in-time-joins.md, docs/getting-started/quickstart.md, docs/reference/alpha-on-demand-feature-view.md, docs/reference/data-sources/push.md, docs/reference/feature-repository.md, docs/reference/feature-repository/README.md, docs/tutorials/validating-historical-features.md, sdk/python/feast/__init__.py, sdk/python/feast/templates/aws/driver_repo.py, sdk/python/feast/templates/gcp/driver_repo.py, sdk/python/feast/templates/local/example.py, sdk/python/feast/templates/snowflake/driver_repo.py, sdk/python/feast/templates/spark/example.py, sdk/python/tests/doctest/test_all.py, sdk/python/tests/example_repos/example_feature_repo_1.py, sdk/python/tests/example_repos/example_feature_repo_2.py, sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py, sdk/python/tests/integration/scaffolding/test_partial_apply.py
**What this PR does / why we need it**: This PR removes `Array` and `String` and other Feast types as top-level objects, so that users must do `from feast.types import Array, String` instead of `feast import Array, String`.
Fixes #
=> chore: Fix typing

sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py, sdk/python/tests/integration/feature_repos/repo_configuration.py
**What this PR does / why we need it**: This PR allows the local feature server to use the embedded Go feature server, if it is enabled.
Fixes #
=> feat: Allow local feature server to use Go feature server if enabled

sdk/python/tests/integration/feature_repos/repo_configuration.py
**What this PR does / why we need it**: This PR disables the Go + Python feature server test since it is currently too flaky and is therefore blocking other tests. This issue is being tracked in #2544.
Fixes #
=> chore: Disable the Go + Python feature server test

sdk/python/setup.py
`python3` is misleading because it may refer to a differnet executable on the path from the one currently in use, specially if anyone has as many pyenvs as I do.
Fixes #
=> fix: Update build_go_protos to use a consistent python path

README.md, docs/SUMMARY.md, docs/getting-started/third-party-integrations.md, docs/roadmap.md, examples/quickstart/quickstart.ipynb, sdk/python/feast/templates/aws/driver_repo.py, sdk/python/feast/templates/gcp/driver_repo.py, sdk/python/feast/templates/local/example.py, sdk/python/feast/templates/snowflake/driver_repo.py, sdk/python/feast/templates/spark/example.py, sdk/python/tests/utils/online_write_benchmark.py
This also updates some example repos to use source instead of batch_source
Fixes #
=> chore: Updating quickstart and fixing roadmap + broken links to old alpha docs

.github/workflows/publish.yml, Makefile, sdk/python/setup.py
Currently we cannot upload platform specific wheels generated by `wheel`. It produces not-portable wheels (see [PEP-600](https://peps.python.org/pep-0600/)), which are not accepted anymore by PyPi.
This PR reworks our packaging process.
Fixes #
=> fix: Build platform specific python packages with ci-build-wheel

sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
=> chore: Add Snowflake to AWS Lambda feature server Dockerfile

CONTRIBUTING.md, sdk/python/feast/batch_feature_view.py, sdk/python/feast/stream_feature_view.py, sdk/python/tests/unit/test_feature_views.py
in prep for upcoming streaming work
Fixes #
=> feat: Create stream and batch feature view abstractions

sdk/python/feast/entity.py, sdk/python/feast/inference.py, sdk/python/tests/integration/registration/test_inference.py
**What this PR does / why we need it**: This PR adds support for entity fields in the feature view `schema` parameter. As of now, these fields are dropped during inference. A followup PR will deprecate `value_type` in entities, at which point entity fields will actually matter for inference.
Fixes #
=> feat: Support entity fields in feature view `schema` parameter by dropping them

.github/workflows/publish.yml, infra/scripts/release/bump_file_versions.py, ui/package.json
=> ci: Fix npm push workflow

sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/feast/infra/online_stores/online_store.py, sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
Before this, having an unknown entity (e.g. such as is commonly the case in the feast-benchmarks repo) in a batch would result in an exception because 
https://github.com/feast-dev/feast/blob/master/sdk/python/feast/feature_store.py#L1789-L1789 
expects that the number of response rows is equal to the number of requested entities. Dynamo will only return values for entities that are found, so there could be a mismatch and that causes protobuf to complain because we mix None values and Value values.
This also reverts the change to allow users to not sort feature values. Feast expects the results to be in the original order to return the correct values in a GetOnlineFeatures response.
Fixes #
=> fix: Fix DynamoDB fetches when there are entities that are not found

sdk/python/feast/base_feature_view.py, sdk/python/feast/data_source.py, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/entity.py, sdk/python/feast/feature_service.py, sdk/python/feast/feature_store.py, sdk/python/feast/feature_view.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/registry.py, sdk/python/feast/repo_contents.py, sdk/python/feast/repo_operations.py, sdk/python/feast/saved_dataset.py, sdk/python/tests/example_repos/example_feature_repo_with_duplicated_featureview_names.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/unit/test_data_sources.py, sdk/python/tests/unit/test_entity.py, sdk/python/tests/unit/test_feature_service.py, sdk/python/tests/unit/test_feature_view.py, sdk/python/tests/unit/test_on_demand_feature_view.py
**What this PR does / why we need it**: This PR fixes the broken `__hash__` methods in all Feast objects.
Fixes #2506
=> fix: Fix `__hash__` methods

sdk/python/feast/feature_service.py, sdk/python/tests/unit/test_feature_service.py
Enforce kw args in feature service for convergence.
Fixes #
=> fix: Enforce kw args featureservice

docs/getting-started/concepts/entity.md, docs/getting-started/concepts/feature-view.md, docs/getting-started/quickstart.md, docs/tutorials/validating-historical-features.md, sdk/python/feast/feature_view.py, sdk/python/feast/inference.py, sdk/python/feast/templates/aws/driver_repo.py, sdk/python/feast/templates/gcp/driver_repo.py, sdk/python/feast/templates/local/example.py, sdk/python/feast/templates/snowflake/driver_repo.py, sdk/python/tests/example_repos/example_feature_repo_1.py, sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py, sdk/python/tests/integration/feature_repos/universal/entities.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_inference.py
=> fix: Switch from `join_key` to `join_keys` in tests and docs

.releaserc.js
=> ci: Fix release process to also commit package.json from the web ui

docs/reference/feature-servers/go-feature-retrieval.md, sdk/python/setup.py
In order for Python to fully interop with Go we might need to install some extra python packages. This PR adds new dependency group `go` to `setup.py`.
Fixes #
=> chore: Extra dependencies in setup.py for Go <-> Python interop

go/types/typeconversion.go, sdk/python/feast/embedded_go/online_features_service.py
Timestamp type stored in online store should be parsed with resolution "seconds".
Fixes #
=> fix: Feature with timestamp type is incorrectly interpreted by Go FS

go/types/typeconversion.go, sdk/python/feast/embedded_go/online_features_service.py, sdk/python/feast/embedded_go/type_map.py
To be compatible with conversion of arrow -> various offline store formats we should use timestamp and not time. 
Fixes #
=> fix: Use timestamp type when converting unixtimestamp feature type to arrow

docs/tutorials/validating-historical-features.md, examples/java-demo/feature_repo/driver_repo.py, sdk/python/feast/__init__.py, sdk/python/feast/feature_view.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py, sdk/python/tests/unit/test_on_demand_feature_view.py
=> fix: Update on demand feature view api

go/cmd/server/logging/feature_repo/example.py, sdk/python/feast/data_source.py, sdk/python/feast/inference.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/data_sources/trino.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/unit/diff/test_registry_diff.py, sdk/python/tests/unit/test_data_sources.py, sdk/python/tests/unit/test_feature_views.py, sdk/python/tests/utils/data_source_utils.py
**What this PR does / why we need it**: The Redshift and Snowflake data sources did not implement conversion to and from protos correctly. This PR fixes that logic and adds tests. It also cleans up a bunch of data source classes by removing unnecessary properties.
Fixes #2581
=> fix: Fix broken proto conversion methods for data sources

java/serving/src/test/java/feast/serving/util/DataGenerator.java, protos/feast/core/Feature.proto, protos/feast/types/Field.proto, sdk/python/feast/feature.py, sdk/python/feast/field.py
=> fix: Update field api to add tag parameter corresponding to labels in Feature.

sdk/python/feast/infra/transformation_servers/Dockerfile, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.7-ci-requirements.txt, sdk/python/requirements/py3.7-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, sdk/python/setup.py
Also, this PR pins numpy to continue python 3.7 support from the Feast side.
Fixes #
=> fix: Remove ci extra from the feature transformation server dockerfile

sdk/python/tests/integration/feature_repos/repo_configuration.py
This will allow generating custom repo configs in specific test modules based on available online and offline stores.
Fixes #
=> chore: List of avaliable online and offline stores exposed in test configuration

go.mod, go.sum, go/embedded/online_features.go, go/internal/feast/server/grpc_server.go, sdk/python/feast/embedded_go/online_features_service.py, sdk/python/tests/integration/e2e/test_go_feature_server.py
Very basic test (but better than nothing) that starts go feature server (GRPC) in a separate thread (since it's blocking) and checks (via grpc client) that it responses on GetOnlineFeatures requests.
Fixes #
=> chore: Basic e2e test for go grpc server

go/embedded/online_features.go, go/internal/feast/server/logging/filelogsink.go, go/internal/feast/server/logging/logger.go, go/internal/feast/server/logging/logger_test.go, go/internal/feast/server/logging/memorybuffer.go, go/internal/feast/server/logging/memorybuffer_test.go, go/internal/feast/server/logging/offlinestoresink.go, go/internal/feast/server/logging/service.go, go/internal/test/go_integration_test_utils.go, sdk/python/feast/embedded_go/online_features_service.py, sdk/python/feast/feature_logging.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/feast/infra/utils/aws_utils.py, sdk/python/feast/infra/utils/snowflake_utils.py, sdk/python/feast/templates/snowflake/bootstrap.py, sdk/python/tests/foo_provider.py, sdk/python/tests/integration/e2e/test_go_feature_server.py, sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py, sdk/python/tests/integration/offline_store/test_feature_logging.py
Following previous PRs (#2574 and #2614) this PR finalizes integration between producing logs in Go feature server and writing them to an offline store via python implementation.
Here I added end-to-end test that starts go gRPC server and check that offline store has received served features.
Fixes #
=> feat: Write logged features to Offline Store (Go - Python integration)

sdk/python/feast/inference.py
=> fix: Update data source timestamp inference error message to make sense

sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py, sdk/python/feast/infra/online_stores/contrib/postgres.py
=> chore: Update new contrib plugins to include usage

java/serving/src/test/java/feast/serving/it/ServingEnvironment.java, java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml
=> fix: Update java integration tests and add more logging

java/serving/src/test/java/feast/serving/it/ServingEnvironment.java, java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml, java/serving/src/test/resources/docker-compose/feast10/Dockerfile, java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh
Mount root repo directory in docker compose to install latest Python code. This will allow Python and Java code to be in sync during integration tests.
Fixes #
=> chore: Use latest Python code in Java Integration Tests

CONTRIBUTING.md, Makefile, sdk/python/feast/infra/offline_stores/contrib/postgres_repo_configuration.py, sdk/python/feast/infra/online_stores/contrib/postgres.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/universal/data_sources/postgres.py, setup.py
=> ci: Update postgres tests to use testcontainers

docs/getting-started/quickstart.md, sdk/python/feast/templates/aws/driver_repo.py, sdk/python/feast/templates/gcp/driver_repo.py, sdk/python/feast/templates/local/example.py, sdk/python/feast/templates/snowflake/driver_repo.py, sdk/python/feast/templates/spark/example.py
=> fix: Feature service to templates

infra/charts/feast/Chart.yaml, infra/charts/feast/charts/transformation-service/templates/deployment.yaml, infra/charts/feast/charts/transformation-service/values.yaml
Signed-off-by: Alvaro Duran Tovar <hermesdt@gmail.com>
Allow to pass secrets and environment variables to transformation service. Without this I can't use a GCS registry.
Fixes #2631
=> feat: Allow to pass secrets and environment variables to transformation service

docs/reference/offline-stores/postgres.md, docs/reference/online-stores/postgres.md, sdk/python/feast/infra/registry_stores/contrib/postgres/registry_store.py, sdk/python/feast/infra/utils/postgres/connection_utils.py, sdk/python/feast/infra/utils/postgres/postgres_config.py
Without these changes we cannot connect to Postgres instances that require SSL
Fixes #
=> feat: Adding SSL options for Postgres

sdk/python/feast/feature_service.py, sdk/python/feast/feature_store.py, sdk/python/tests/integration/registration/test_inference.py
If a feature service depends on a feature view that doesn't have a schema (i.e. relying on feature inference), the feature service does not inherit the inferred schema.
This results in a particularly weird error for FileSources suggesting that pandas dataframes do not have a "persist()" method (like Dask dataframes do)
Fixes #
=> fix: Infer features for feature services when they depend on feature views without schemas

sdk/python/feast/feature_logging.py
Redshift requires the order of fields in parquet file (produced in Go) to exactly match schema (generated from feature service in Python). Even in field ordering. This PR fixes field ordering in schema generated in Python.
Fixes #
=> fix: Feature logging to Redshift is broken

.github/workflows/java_pr.yml, .github/workflows/pr_integration_tests.yml
**What this PR does / why we need it**: Currently we trigger integration tests on `lgtm`, which is unnecessary since `lgtm` is already a requirement for merging. This PR stops triggering integration tests on `lgtm`, so we avoid the scenario where a PR has already passed all integration tests, only for the tests to be retriggered once someone stamps it.
Fixes #
=> ci: Do not retrigger integration tests on lgtm

Makefile, sdk/python/feast/infra/offline_stores/contrib/contrib_repo_configuration.py, sdk/python/feast/infra/offline_stores/contrib/postgres_repo_configuration.py, sdk/python/feast/infra/online_stores/datastore.py, sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/e2e/test_go_feature_server.py, sdk/python/tests/integration/e2e/test_python_feature_server.py, sdk/python/tests/integration/e2e/test_universal_e2e.py, sdk/python/tests/integration/e2e/test_validation.py, sdk/python/tests/integration/feature_repos/integration_test_repo_config.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/offline_store/test_feature_logging.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/online_store/test_push_online_retrieval.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/integration/registration/test_cli.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py, sdk/python/tests/integration/registration/test_universal_types.py
Test environment is being generated individually for each integration test based on its markers and/or requested fixtures. This allows us to drop some unnecessary use cases (eg, looping various online stores against test_historical_features) and shorten total run time. 
The main change is `pytest_generate_tests` function in `conftest.py` that replaces static declaration of repo configs. It generates environments for each test and retrieves them from configs cache, so that environments could be shared between different tests.
Fixes #
=> chore: Generate environments for each individual test based on its markers/fixtures

sdk/python/feast/feature_store.py, sdk/python/tests/example_repos/example_feature_repo_with_ttl_0.py, sdk/python/tests/integration/online_store/test_e2e_local.py
=> fix: Fix materialization with ttl=0 bug

sdk/python/feast/cli.py, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/entity.py, sdk/python/feast/feature_store.py, sdk/python/feast/feature_view.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/on_demand_feature_view.py
=> fix: Punt deprecation warnings and clean up some warnings.

.github/workflows/publish.yml, ui/feature_repo/features.py, ui/public/registry.json, ui/src/components/TagsDisplay.tsx, ui/src/index.tsx, ui/src/pages/data-sources/BatchSourcePropertiesView.tsx, ui/src/pages/data-sources/DataSourceOverviewTab.tsx, ui/src/pages/feature-views/OnDemandFeatureViewOverviewTab.tsx, ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx, ui/src/parsers/feastDatasources.ts, ui/src/parsers/feastFeatureViews.ts, ui/src/parsers/feastODFVS.ts, ui/src/parsers/parseEntityRelationships.ts
This makes the Web UI compatible with the latest Feast APIs
Fixes #
=> fix: Fix Feast UI parser to work with new APIs

sdk/python/feast/feature_store.py, sdk/python/feast/feature_view_projection.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/online_store/test_universal_online.py
Signed-off-by: Abhin Chhabra <abhin.chhabra@shopify.com>
Increase the scope of validations provided by `_group_feature_refs` to also check if the features are part of the feature view. It also adds a `get_feature` method to the `FeatureViewProjection` class that could be useful in other cases too. 
In the event of an invalid feature being requested, a `KeyError` is raised, which is consistent with the existing behaviour when completely non-existent features are requested in `get_historical_features`.
Fixes #2576
=> fix: Reject undefined features when using `get_historical_features` or `get_online_features`

sdk/python/feast/cli.py, sdk/python/feast/feature_store.py, sdk/python/feast/ui/package.json, sdk/python/feast/ui_server.py, ui/package.json, ui/src/index.tsx
Also allows adding host + port names in the `feast ui` command, removes some unnecessary files, reverts an accidental change to the public demo in ui/, and bumps version numbers
https://github.com/feast-dev/feast/issues/2353
Fixes #
=> fix: Asynchronously refresh registry for the feast ui command

sdk/python/tests/integration/feature_repos/repo_configuration.py
Convert previous format for setting up test environments (via creating `FULL_REPO_CONFIGS`) into `AVAILABLE_ONLINE_STORES` and `AVAILABLE_OFFLINE_STORES` required by current integration tests.
Fixes #
=> chore: Backward compatibility for test repo configurations

sdk/python/feast/__init__.py
This configures logging for all applications may just be interested in importing the feast package, which is incorrect. We should only configure logging at the application level, so things like the CLI, or or webservers.
Fixes #2664
=> fix: Remove incorrect call to logging.basicConfig

sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/repo_operations.py
- dill only can properly serialize a function if the module is __main__.
- Otherwise, when you deserialize, it looks for the presence of the exact module the ODFV was defined in (e.g. so if you don’t have the feature repo handy, using odfvs will fail)
- Forcing the udf to be __main__ resolves this issue. This should otherwise be fine since we expect the udf to be able to execute in arbitrary environments.
- Fixing duplicate data source conflict between push source and batch source which occurs if you depend on both a push source and a batch source. 
Fixes #
=> fix: Forcing ODFV udfs to be __main__ module and fixing false positive duplicate data source warning

sdk/python/feast/ui/package.json, sdk/python/feast/ui/yarn.lock, ui/package.json, ui/src/FeastUISansProviders.tsx, ui/src/custom-tabs/TabsRegistryContext.tsx
Also allow projectListPromise to be passed without a tabs registry
Continuing with #2353 
Fixes #
=> fix: Fix case where on demand feature view tab is broken if no custom tabs are passed. 

sdk/python/feast/infra/offline_stores/file_source.py
Updates File Schema inference in offline stores to use ParquetDataset instead of ParquetFile to do schema inference.  This supports both single files and directories of partitioned parquet datasets.
Fixes #2685
=> fix: Use ParquetDataset for Schema Inference

.github/workflows/pr_integration_tests.yml, Makefile, infra/scripts/release/bump_file_versions.py, infra/scripts/release/files_to_bump.txt, sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile, sdk/python/feast/infra/feature_servers/gcp_cloudrun/Dockerfile, sdk/python/feast/infra/transformation_servers/Dockerfile
Running locally is smooth:
```
$ python ./infra/scripts/release/bump_file_versions.py 0.21.0 0.22.0
Updated 12 files with new version 0.22.0
[13/05/22 3:10:09] (python-3.8.12) ~/tecton/feast   achal/update-version-bump-script ● 
$ git st
On branch achal/update-version-bump-script
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   infra/charts/feast-python-server/Chart.yaml
modified:   infra/charts/feast-python-server/README.md
modified:   infra/charts/feast/Chart.yaml
modified:   infra/charts/feast/README.md
modified:   infra/charts/feast/charts/feature-server/Chart.yaml
modified: …
```
=> ci: Make version bumping script more robust

sdk/python/feast/ui/README.md, sdk/python/feast/ui/public/projects-list.json, sdk/python/feast/ui/src/index.tsx, sdk/python/feast/ui_server.py
Changes the JS to look for a fixed projects-list.json (aka the default), and now `feast ui` will write to that json file so we can configure the host + port appropriately.
Before, this was hard-coded so users could not actually control the host / port.
Fixes #
=> fix: Fix issue when user specifies a port for feast ui 

sdk/python/feast/stream_feature_view.py, sdk/python/tests/unit/test_feature_views.py
=> fix: Support push sources in stream feature views

sdk/python/tests/conftest.py
This PR adds better verification that port is open before python server is started and freed in the end.
Fixes #
=> fix: Python server is not correctly starting in integration tests

sdk/python/feast/dqm/profilers/ge_profiler.py, sdk/python/feast/feature_logging.py, sdk/python/feast/feature_store.py, sdk/python/feast/feature_view.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/tests/integration/e2e/test_validation.py, sdk/python/tests/integration/offline_store/test_feature_logging.py, sdk/python/tests/utils/logged_features.py
This PR adds `FeatureStore.validate_logged_features` method that utilizes previously created infrastructure to load logged features and validate them against reference (saved) dataset via GE profiler. 
Fixes #
=> feat: Validating logged features via Python SDK

sdk/python/feast/on_demand_feature_view.py, sdk/python/tests/example_repos/on_demand_feature_view_repo.py, sdk/python/tests/integration/registration/test_cli.py, sdk/python/tests/integration/registration/test_registry.py
Feast did schema inference on on demand transforms by passing in an empty dataframe to the UDF with the same expected columns.
This can cause a crash though if it uses dataframe.apply. Example:
```bash
File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3602, in __setitem__
self._set_item_frame_value(key, value)
File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3742, in _set_item_frame_value
self._set_item_mgr(key, arraylike)
File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3754, in _set_item_mgr
self._mgr.insert(len(self._info_axis), key, value)
File …
```
=> fix: Fix on demand feature view crash from inference when it uses df.apply

go/embedded/online_features.go, go/internal/feast/server/grpc_server.go, go/internal/feast/server/http_server.go, go/internal/feast/server/http_server_test.go, go/internal/feast/server/logging/logger.go, go/internal/feast/server/logging/logger_test.go, sdk/python/feast/cli.py, sdk/python/feast/embedded_go/online_features_service.py, sdk/python/feast/feature_store.py, sdk/python/tests/integration/e2e/test_go_feature_server.py
**What this PR does / why we need it**: This PR adds an HTTP endpoint to the Go feature server. We also add a flag to the CLI that will allow us to launch either HTTP or gRPC server.
Fixes #
=> feat: Add http endpoint to the Go feature server

docs/getting-started/quickstart.md
fix for #2694 
adding the example code from the Google Codelab notebook
moving the image below the yaml and example.py explanation 
Signed-off-by: ssge <george.kremenliev@gmail.com>
**What this PR does / why we need it**: improving the docs
Fixes #2694
=> chore: Local data inspection

go/embedded/online_features.go, protos/feast/core/FeatureService.proto, protos/feast/core/Registry.proto, protos/feast/core/ValidationProfile.proto, sdk/python/feast/cli.py, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/dqm/profilers/ge_profiler.py, sdk/python/feast/dqm/profilers/profiler.py, sdk/python/feast/errors.py, sdk/python/feast/feast_object.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/registry.py, sdk/python/feast/saved_dataset.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.7-ci-requirements.txt, sdk/python/requirements/py3.7-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, sdk/python/setup.cfg, sdk/python/tests/conftest.py, sdk/python/tests/integration/e2e/test_go_feature_server.py, sdk/python/tests/integration/e2e/test_validation.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/utils/cli_utils.py, sdk/python/tests/utils/logged_features.py, setup.py
Validation of logged features can be called via CLI interface:
```
feast validate --feature-service <service_name> --reference <reference_name> <start_ts> <end_ts>
```
This PR also includes storing / retrieving of validation reference to / from the registry.
Fixes #
=> feat: CLI interface for validation of logged features

.gitpod.Dockerfile, .gitpod.yml
gitpod prebuilds lose information about `pip install`'d modules when prebuild is turned on. This change is inspired by [gitpod-io/gitpod/issues/7078#issuecomment-997139674](https://github.com/gitpod-io/gitpod/issues/7078#issuecomment-997139674) to preserve the module information.
Fixes #
=> chore: Fix gitpod init commands to preserve pip modules

setup.py
If we set something like PYTHONUSERBASE for gitpod builds, then the site-packages for python are located in a non-standard location and modules cannot be located. This fixes that by inheriting the python process' environment.
Fixes #
=> chore: Respect environment variables when calling check_call

sdk/python/feast/data_source.py
The [python API docs for `data_source`](https://rtd.feast.dev/en/master/#module-feast.data_source) have a confusing typo.
Based on the docs, it's unclear what the recommended path forward is. It looks like the recommendation is to use `timestamp_field`.
Signed-off-by: Abhin Chhabra <abhin.chhabra@shopify.com>
Fixes #
=> chore: Fix minor documentation typo

java/serving/src/test/java/feast/serving/it/ServingBaseTests.java
Try to reuse `LocalRegistryFile` for the test.
Fixes #
=> fix: Refactor test to reuse LocalRegistryFile

protos/feast/core/Aggregation.proto, protos/feast/core/DataSource.proto, sdk/python/feast/aggregation.py, sdk/python/feast/data_source.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
=> feat: Update stream fcos to have watermark and sliding interval

sdk/python/feast/base_feature_view.py, sdk/python/feast/feature_service.py, sdk/python/feast/feature_view_projection.py, sdk/python/feast/field.py, sdk/python/feast/inference.py, sdk/python/tests/integration/registration/test_inference.py
=> fix: Fix feature view __getitem__ for feature services

ui/feature_repo/features.py, ui/feature_repo/test_get_features.py, ui/src/parsers/feastEntities.ts
Also handles some lint issues that somehow weren't caught before.
Fixes #
=> fix: Fix Feast UI failure with new way of specifying entities

sdk/python/feast/infra/registry_stores/sql.py
=> fix: Implement apply_materialization and infra methods in sql registry

sdk/python/feast/data_source.py, sdk/python/feast/stream_feature_view.py, sdk/python/tests/integration/registration/test_stream_feature_view_apply.py, sdk/python/tests/unit/test_feature_views.py
=> fix: Update udf tests and add base functions to streaming fcos and fix some nonetype errors

sdk/python/feast/infra/registry_stores/sql.py
=> fix: Hydrate infra object in the sql registry proto() method 

docs/how-to-guides/running-feast-in-production.md, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
Because it was unclear to me you could do this, and there was another question in Slack, I've added a section to the docs to explain you can do this:
```yaml
project: my_project
registry: data/registry.db
provider: local
online_store:
type: redis
connection_string: ${REDIS_CONNECTION_STRING}
```
=> chore: Added docs section on env vars in yaml

sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py
=> feat: Scaffold for unified push api

sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
Signed-off-by: Andrew Pope <apope@nursefly.com>
This PR fixes an issue with getting online features from DynamoDB. If an entity at the end of request batch 2+ is missing from the DynamoDB table, it will get dropped in the response, which results in the following error:
```
Traceback (most recent call last):
File "src/tmp.py", line 26, in <module>
feature_df = store.get_online_features(
File "/Users/apope/nursefly-analytics/predict/talent_pool/venv/lib/python3.8/site-packages/feast/usage.py", line 280, in wrapper
raise exc.with_traceback(traceback)
File "/Users/apope/nursefly-analytics/predict/talent_pool/venv/lib/python3.8/site-packages/feast/usage.py", line 269, in wrapper
return func(*args, **kwargs)
File …
```
=> fix: Dynamodb drops missing entities when batching

.github/workflows/java_master_only.yml, .github/workflows/java_pr.yml, .github/workflows/linter.yml, .github/workflows/master_only.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/unit_tests.yml
Python 3.7  is approaching EoL, and isn't used by a lot of feast users. It's also not a great experience on M1 Macs per @kevjumba. Let's remove it to speed up CI time. We still support 3.7 as the minimum python version, and don't prevent users installing feast on py 3.7, just that we should run tests on newer versions.
Fixes #
=> ci: Stop running tests for python 3.7

java/serving/src/test/java/feast/serving/util/DataGenerator.java, protos/feast/core/DataSource.proto, sdk/python/feast/data_source.py, sdk/python/feast/infra/contrib/spark_kafka_processor.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/integration/registration/test_stream_feature_view_apply.py, sdk/python/tests/unit/test_data_sources.py, sdk/python/tests/unit/test_feature_views.py
**What this PR does / why we need it**: This PR renames `bootstrap_servers` to `kafka_bootstrap_servers` and `watermark` to `watermark_delay_threshold` for `KafkaSource`. It also deprecates the `date_partition_column` for all data sources.
Fixes #
=> chore: Rename stream data source parameters

sdk/python/feast/cli.py, sdk/python/feast/data_source.py, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/entity.py, sdk/python/feast/feature_service.py, sdk/python/feast/feature_store.py, sdk/python/feast/feature_view.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/unit/test_data_sources.py
**What this PR does / why we need it**: This PR bumps the deprecation of all Feast object parameters, and related logic, from 0.23 to 0.24.
Fixes #
=> chore: Bump deprecation version from 0.23 to 0.24

sdk/python/feast/type_map.py, sdk/python/tests/unit/test_type_map.py
Signed-off-by: Andrew Pope <apope@nursefly.com>
Currently, the python to proto function converts a null timestamp to the value -9223372036854775808, which then fails when converting back to python type. This fixes the conversion of null UnixTimestamp values from proto to python by checking for that value and converting it to null.
Fixes # https://github.com/feast-dev/feast/issues/2803
=> fix: Conversion of null timestamp from proto to python

sdk/python/feast/embedded_go/online_features_service.py, sdk/python/tests/integration/e2e/test_go_feature_server.py, sdk/python/tests/integration/online_store/test_universal_online.py
This is going to only be enabled if the embedded go fs component is instantiated.
Fixes #
=> fix: Enable faulthandler and disable flaky tests

.github/workflows/master_only.yml, .github/workflows/pr_integration_tests.yml
https://pypi.org/project/pytest-timeout/
> Now you can run the test suite while setting a timeout in seconds, any individual test which takes longer than the given duration will be terminated:
This should help us get an idea why tests are hanging in CI right now.
Fixes #
=> ci: Add a test timeout and print thread stack trace on timeouts

Makefile, go.mod, go.sum, sdk/python/tests/integration/online_store/test_e2e_local.py, sdk/python/tests/utils/cli_utils.py, setup.py
In `go.mod`, we're replacing `go-python/gopy` with `feast-dev/gopy`, but for whatever reason we don't do the same thing in `setup.py` or `Makefile`. This results in us using a different version of gopy from the one that will actually work (i.e. our fork). 
This was made worse by the face the the upstream repo landed a bunch of commits and the new version of that project totally borked our build process.
I *think* this should fix the release pipeline (https://github.com/feast-dev/feast/runs/6993658741?check_suite_focus=true) as well as the flaky test (#2830)
Fixes #
=> fix: Prefer installing gopy from feast's fork as opposed to upstream

go/embedded/online_features.go, sdk/python/feast/embedded_go/online_features_service.py, sdk/python/tests/integration/e2e/test_go_feature_server.py, sdk/python/tests/integration/online_store/test_universal_online.py
Also convert bool params when calling the transformation callback, since typeguard doesn't like type-unsafe funny business.
Fixes #
=> fix: Explicitly translate errors when instantiating the go fs 

CHANGELOG.md, infra/charts/feast-python-server/Chart.yaml, infra/charts/feast-python-server/README.md, infra/charts/feast/Chart.yaml, infra/charts/feast/README.md, infra/charts/feast/charts/feature-server/Chart.yaml, infra/charts/feast/charts/feature-server/README.md, infra/charts/feast/charts/feature-server/values.yaml, infra/charts/feast/charts/transformation-service/Chart.yaml, infra/charts/feast/charts/transformation-service/README.md, infra/charts/feast/charts/transformation-service/values.yaml, infra/charts/feast/requirements.yaml, java/pom.xml
This reverts commit be3e3178e2af80d48fbfc34449f67d964421159f.
**What this PR does / why we need it**: The 0.22.0 release was broken. Since we want to redo the release, this PR reverts the previous release commit.
Fixes #
=> chore: Revert "chore(release): release 0.22.0"

sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py
Signed-off-by: alex.eijssen <alex.eijssen@energyessentials.nl>
This PR ensures the projects-list.json is generated correctly when calling feast ui and using Postgres as a data source, by adding name=self.name to to_proto(). It also adds description, tags and owner to the Postgres source which were previously missing.
Fixes #2843
=> fix: Correctly generate projects-list.json when calling feast ui and using postgres as a source

sdk/python/feast/cli.py, sdk/python/feast/repo_upgrade.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
This PR introduces a new `feast` command, `feast repo-upgrade`. The intention is for feast to be able to upgrade existing feature repos to the newest API that feast supports, as far as possible.
First pass of solving #2629
=> feat: Add feast repo-upgrade for automated repo upgrades

setup.py
This fixes a problem similar to https://github.com/pypa/cibuildwheel/issues/189#issuecomment-549933912.
Running `go mod tidy` was updating `go.mod` and `go.sum`, which was causeing cibuildwheel to produce dirty builds. This comamnd isn't really even needed, so nixing it.
Fixes #
=> fix: Stop running go mod tidy in setup.py

.github/workflows/build_wheels.yml, go.mod, go.sum
=> ci: Update go.mod and go.sum but git restore before building

.github/workflows/build_wheels.yml
Same fix as #2885 but for sdists
Fixes #
=> ci: Restore specific files during sdist builds

go/internal/feast/onlinestore/redisonlinestore.go, go/internal/feast/onlinestore/redisonlinestore_test.go
This will allow users to append ',ssl=True' to their connection string in order to enable TLS/SSL support in the Go Redis client. It looks like this was an intended feature that just hasn't been implemented yet.
Per the go-redis docs: 'To enable TLS/SSL, you need to provide an empty tls.Config.' https://redis.uptrace.dev/guide/go-redis.html#using-tls
=> feat: Add simple TLS support in Go RedisOnlineStore

.github/workflows/build_wheels.yml
Workflow that worked: https://github.com/kevjumba/feast/runs/7117446862?check_suite_focus=true
Also fixes issue where cibuildwheel installs the wheel to macos 10.9 when the environment is 10.15. Issue is here: https://github.com/pypa/cibuildwheel/issues/952
Fixes #
=> fix: Fix macos wheel version for 310 and also checkout edited go files

java/serving/src/test/resources/docker-compose/feast10/Dockerfile, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
Dependabot cannot update numpy to a non-vulnerable version because the numpy version is pinned on setup.py, and it looks like numpy version was wrongly pinned by a recent change introduced on PR https://github.com/feast-dev/feast/pull/2647
Fixes #
=> fix: Change numpy version on setup.py and upgrade it to resolve dependabot warning

java/serving/src/main/java/feast/serving/registry/Registry.java, java/serving/src/main/java/feast/serving/registry/RegistryRepository.java, java/serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java, java/serving/src/test/java/feast/serving/it/ServingBaseTests.java, java/serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
Currently Java Feature Server doesn't support retrieval from multiple feature views with different join keys. For each gPRC request, `OnlineServingServiceV2` calls `OnlineRetriever` once and only once. In this call the former sends all join keys in the original request to the latter, and the latter simply sorts and concatenates all join keys to make a Redis key.
This PR supports retrieval from multiple feature views with different join keys. For each gPRC request, it groups feature references by join keys and for each group it makes a call to `OnlineRetriever`.
Fixes #
=> feat: Support retrieval from multiple feature views with different join keys

sdk/python/feast/feature_store.py, sdk/python/feast/infra/contrib/spark_kafka_processor.py, sdk/python/feast/infra/contrib/stream_processor.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/tests/integration/e2e/test_python_feature_server.py, sdk/python/tests/integration/offline_store/test_offline_write.py, sdk/python/tests/integration/offline_store/test_push_offline_retrieval.py, sdk/python/tests/integration/online_store/test_push_online_retrieval.py
**What this PR does / why we need it**: In addition to adding column reordering logic, this PR adds logic for extracting the latest feature values into the `SparkKafkaProcessor`.
Fixes #
=> feat: Add column reordering to `write_to_offline_store`

ui/src/FeastUISansProviders.test.tsx, ui/src/FeastUISansProviders.tsx, ui/src/components/FeaturesListDisplay.tsx, ui/src/components/TagSearch.tsx, ui/src/custom-tabs/TabsRegistryContext.tsx, ui/src/custom-tabs/feature-demo-tab/DemoCustomTab.tsx, ui/src/custom-tabs/feature-demo-tab/useDemoQuery.tsx, ui/src/custom-tabs/types.ts, ui/src/graphics/FeatureIcon.tsx, ui/src/index.tsx, ui/src/pages/feature-views/OnDemandFeatureViewOverviewTab.tsx, ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx, ui/src/pages/features/FeatureInstance.tsx, ui/src/pages/features/FeatureOverviewTab.tsx, ui/src/pages/features/FeatureRawData.tsx, ui/src/pages/features/useLoadFeature.ts, ui/src/parsers/feastFeatures.ts, ui/src/parsers/jsonType.ts, ui/src/utils/custom-tabs/FeatureCustomTabLoadingWrapper.tsx
Hello! This is a small change to Feast's UI that adds pages for individual Features to the UI, just like individual FeatureViews, Entities, etc. all have pages. Feature pages are linked in the Feature table for every FeatureView, and each Feature page links back to its original FeatureView. The URL for features is `/p/<project>/feature-view/<feature view>/feature/<feature>`. These Feature pages are integrated into the custom tab interface just like the other pages, but do not have their own index.
Note: we may need to create a new icon for Features; I have a placeholder for now.
=> feat: Add pages for individual Features to the Feast UI

sdk/python/feast/infra/online_stores/snowflake.py, sdk/python/feast/infra/utils/snowflake_utils.py, sdk/python/tests/integration/feature_repos/repo_configuration.py
**What this PR does / why we need it**: Adds support for using snowflake as an online store
Fixes #
=> feat: Add snowflake online store

sdk/python/feast/feature_store.py, sdk/python/feast/repo_operations.py
Signed-off-by: Breno Costa <brenocosta0901@gmail.com>
According to issue #2895 , the private method `FeatureStore._plan` should be refactored to the public method `FeatureStore.plan` because methods that back a CLI operation should have a public facing programatic API.
Fixes #2895
=> fix: Change the feature store plan method to public modifier

sdk/python/feast/infra/materialization/__init__.py, sdk/python/feast/infra/materialization/batch_materialization_engine.py, sdk/python/feast/infra/materialization/local_engine.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/feast/repo_config.py, sdk/python/feast/utils.py, sdk/python/tests/unit/infra/test_provider.py, sdk/python/tests/utils/online_write_benchmark.py
This is the first pass implementation of the proposal in [RFC-037](https://docs.google.com/document/d/1J7XdwwgQ9dY_uoV9zkRVGQjK9Sy43WISEW6D5V9qzGo/edit#). It's purely interfaces and refactoring without any new logic. The engine is also currently hard coded to the Local engine, which is the same materialization logic as in use today. In a subequent PR, this will be made pluggable.
Fixes #
=> feat: Add interfaces for batch materialization engine

sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Follow up to #2901 , as defined in [RFC-037](https://docs.google.com/document/d/1J7XdwwgQ9dY_uoV9zkRVGQjK9Sy43WISEW6D5V9qzGo/edit#)
Fixes #
=> feat: Add to_remote_storage method to RetrievalJob

.github/workflows/pr_local_integration_tests.yml, CONTRIBUTING.md, Makefile, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/online_store/datastore.py, sdk/python/tests/integration/feature_repos/universal/online_store/dynamodb.py, sdk/python/tests/integration/feature_repos/universal/online_store/hbase.py, sdk/python/tests/integration/feature_repos/universal/online_store/redis.py, sdk/python/tests/integration/registration/test_registry.py
This changes the local integration test flow to use the test containers. 
- It also extends the timeout for test containers because I was seeing flakiness locally.
- It also checks for the docker daemon in the commands and fails if it's not running
- It makes the local integration tests also run on PRs. This does not setup any cloud credentials and should work (emulates the dev workflow).
Fixes #
=> ci: Fixing local integration tests, defaulting to test containers

.github/workflows/build_wheels.yml, .github/workflows/pr_local_integration_tests.yml
=> fix: Fix build wheels workflow to install apache-arrow correctly

.github/workflows/build_wheels.yml, .github/workflows/nightly-ci.yml, .github/workflows/pr_integration_tests.yml
=> ci: Add a nightly CI job for integration tests

sdk/python/feast/infra/aws.py, sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile, sdk/python/feast/infra/materialization/lambda/Dockerfile, sdk/python/feast/infra/materialization/lambda/__init__.py, sdk/python/feast/infra/materialization/lambda/app.py, sdk/python/feast/infra/materialization/lambda/lambda_engine.py, sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/repo_config.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/integration_test_repo_config.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/materialization/test_lambda.py
=> feat: Add an experimental lambda-based materialization engine

examples/quickstart/quickstart.ipynb
since Colab only supports Python 3.7 (and Feast deprecated Python 3.7). This means Colab isn't installing the latest versions of Feast (which fix issues in the UI).
Fixes #
=> chore: Remove UI from quickstart colab 

protos/feast/core/SavedDataset.proto
I am implementing a custom OfflineStore and found that I couldn't use CustomSourceOptions in
SavedDatasetStorage: currently you'd have to try to fit your custom options into one of the
existing implemented Options structs.
=> feat: Add CustomSourceOptions to SavedDatasetStorage

sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/tests/unit/infra/test_key_encoding_utils.py
Signed-off-by: Ivan Krizanic <ikrizanic75@gmail.com>
Fixes missing alias in subquery when using `pull_all_from_table_or_query()` method.
Fixes #2954
=> fix: Add dummy alias to pull_all_from_table_or_query

sdk/python/feast/data_source.py, sdk/python/tests/unit/test_data_sources.py
=> fix: Do not allow same column to be reused in data sources

sdk/python/feast/cli.py
=> feat: Add Go option to `feast serve` command

docs/how-to-guides/adding-a-new-offline-store.md, docs/how-to-guides/adding-support-for-a-new-online-store.md
=> chore: Update docs for offline and online stores

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
… max entity-DF event timestamps in the Spark offline store.
Signed-off-by: Lev Pickovsky <lev.pickovsky@ironsrc.com>
This PR is meant to fix the returned order of elements when calculating the timestamp range of an entity-DF in the _get_entity_df_event_timestamp_range method of the Spark offline store class in case the entity-DF is provided as a string. This method returns a tuple with 2 elements - the min and max timestamps encountered in the entity-DF. Currently, in case the entity-DF is a string, it returns the max as the first element and the min as the second, but the code that uses these values later on seems to expect the min element to be the first one (and it can also be observed that the min is the first one to be returned when the …
=> fix: Fixing Spark min / max entity df event timestamps range return order

.github/workflows/pr_integration_tests.yml, .github/workflows/unit_tests.yml, CONTRIBUTING.md, README.md, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py, sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_registry.py, setup.py
=> fix: Remove hard-coded integration test setup for AWS & GCP

sdk/python/feast/infra/offline_stores/file.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
=> fix: Fix file offline store logic for feature views without ttl

docs/SUMMARY.md, docs/reference/offline-stores/snowflake.md, docs/reference/online-stores/README.md, docs/reference/online-stores/snowflake.md, docs/roadmap.md, docs/tutorials/driver-stats-on-snowflake.md, sdk/python/docs/source/conf.py, sdk/python/docs/source/feast.infra.online_stores.rst, sdk/python/docs/source/index.rst, sdk/python/feast/infra/online_stores/snowflake.py, sdk/python/feast/infra/utils/snowflake_utils.py, sdk/python/feast/templates/snowflake/bootstrap.py, sdk/python/feast/templates/snowflake/driver_repo.py, sdk/python/feast/templates/snowflake/feature_store.yaml, sdk/python/tests/integration/feature_repos/repo_configuration.py
**What this PR does / why we need it**: Adds snowflake to online store options
Fixes #
=> feat: Add Snowflake online store (again)

Makefile, sdk/python/tests/example_repos/empty_feature_repo.py, sdk/python/tests/example_repos/example_feature_repo_1.py, sdk/python/tests/example_repos/example_feature_repo_with_driver_stats_feature_view.py, sdk/python/tests/example_repos/example_feature_repo_with_feature_service.py, sdk/python/tests/integration/e2e/test_universal_e2e.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/online_store/test_online_retrieval.py, sdk/python/tests/integration/registration/test_universal_cli.py, sdk/python/tests/unit/cli/test_cli_apply_duplicates.py, sdk/python/tests/unit/local_feast_tests/test_e2e_local.py, sdk/python/tests/unit/local_feast_tests/test_feature_service_apply.py, sdk/python/tests/unit/local_feast_tests/test_feature_service_read.py, sdk/python/tests/unit/local_feast_tests/test_stream_feature_view_apply.py, sdk/python/tests/unit/online_store/test_online_retrieval.py, sdk/python/tests/utils/basic_read_write_test.py
**What this PR does / why we need it**: This PR allows unit tests to be run (`make test`) without any GCP credentials, which were previously required. It also adds several new example feature repos, as previously many tests would share the same feature repo, making it very hard to reason about how each test used the repo.
Fixes #
=> chore: Remove gcp requirement for local tests

.github/workflows/build_wheels.yml, Makefile, README.md, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt
=> fix: Move gcp back to 1.47.0 since grpcio-tools 1.48.0 got yanked from pypi

README.md, infra/templates/README.md.jinja2
=> chore: Update main README including template

sdk/python/feast/errors.py, sdk/python/feast/repo_config.py
This PR adds more explicit error messages to validation checks (for better Pydantic error messages).
Fixes #2696
=> fix: More explicit error messages

CONTRIBUTING.md, Makefile, sdk/python/feast/infra/offline_stores/contrib/spark_repo_configuration.py, sdk/python/feast/infra/offline_stores/contrib/trino_repo_configuration.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/utils/e2e_test_validation.py
Formerly, the integration test commands were slightly broken:
- The local integration tests would pull in GCP dependencies
- The Spark + Trino integration tests were coupled together and did not exclude all the right tests
- The CONTRIBUTING.md did not hint at how to run contrib tests
Fixes #
=> chore: Fix integration test commands for contrib plugins + local integration tests.

sdk/python/feast/infra/registry_stores/sql.py
=> fix: Return an empty infra object from sql registry when it doesn't exist

examples/java-demo/feature_repo/application-override.yaml, examples/java-demo/feature_repo/driver_repo.py, examples/java-demo/feature_repo/feature_store.yaml, examples/java-demo/feature_repo/test_python_fetch.py, java/serving/README.md, java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/EntityKeySerializerV2.java, sdk/python/feast/feature_store.py
Verified the fix locally works now (previously didn't fetch features from Redis in Java when v2 was enabled)
This also updates the java-demo repo to not use BatchFeatureView (which has a bug where it doesn't apply) and also removes RequestFeatureView (which creates a bug)
Fixes #
=> fix: Fix Feast Java inconsistency with int64 serialization vs python

.github/workflows/pr_local_integration_tests.yml, protos/feast/core/StreamFeatureView.proto, sdk/python/feast/driver_test_data.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/stream_feature_view.py, sdk/python/tests/integration/e2e/test_usage_e2e.py, sdk/python/tests/integration/e2e/test_validation.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/materialization/test_lambda.py, sdk/python/tests/integration/registration/test_feature_store.py, sdk/python/tests/integration/registration/test_inference.py, sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py, sdk/python/tests/unit/infra/scaffolding/test_repo_config.py, sdk/python/tests/unit/infra/test_inference_unit_tests.py, sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py, sdk/python/tests/unit/online_store/test_online_retrieval.py, sdk/python/tests/utils/cli_repo_creator.py, sdk/python/tests/utils/e2e_test_validation.py, sdk/python/tests/utils/feature_records.py
The `make test-python` and `make test-python-integration-local` commands were littered with warnings. This suppresses that to make for a better testing experience.
**Note:** test_lambda fails when switching to entity_key_serialization_version=2 so this temporarily keeps it at 1 for that test
=> chore: Suppress alpha warnings in test. Fix entity serialization in test

sdk/python/feast/infra/registry_stores/sql.py, sdk/python/tests/unit/test_sql_registry.py
=> chore: Add types hints and set created_timestamp in sql registry

sdk/python/feast/feature_view.py, sdk/python/feast/stream_feature_view.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/unit/diff/test_registry_diff.py
=> chore: Add default ttl for feature views

docs/getting-started/concepts/data-ingestion.md, docs/getting-started/concepts/feast-types.md, docs/getting-started/concepts/feature-repo.md, docs/getting-started/concepts/feature-view.md, docs/getting-started/faq.md, docs/tutorials/using-scalable-registry.md
=> docs: Feature Repo, Types and FAQ doc updates

.github/workflows/java_pr.yml
=> ci: Make java build only work on feast-dev/feast because it uses Feast secrets

.github/workflows/publish.yml, .github/workflows/release.yml, .releaserc.js
There was an issue now that the release publishes new NPM packages for the UI as part of the flow. Roughly it's:
1. Semantic release bumps file versions (including ui package version) and creates a tagged commit. 
2. When building the wheel, it needs to compile the Feast UI to bundle into the release. This updates the `yarn.lock` file because now there's a new published NPM version of the Feast UI.
3. Because now the client is dirty with local changes, the built wheel is a dev wheel instead of a clean wheel (see https://github.com/pypa/setuptools_scm/#default-versioning-scheme).
This change instead now will publish the NPM release before running semantic release:
- Find the new release with a dry run of the semantic release to get the old / new …
=> ci: Auto update yarn.lock as part of release

protos/feast/core/OnDemandFeatureView.proto, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/registry.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/unit/test_on_demand_feature_view.py
Before, `feast plan` would always show a change in on demand feature views because the serialization isn't deterministic. Now we store the actual source code (which also can be used to display in the Web UI).
<!--
*Automatically closes linked issue when PR is merged.
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
--
=> fix: Fix on demand feature view output in feast plan + Web UI crash

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/snowflake.py
=> chore: Update docstrings for offline stores and retrieval jobs

sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py
=> ci: Change positional arg to kwarg

sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/online_store/test_universal_online.py
=> chore: Add fixture so that benchmark test is also tested in integration tests

Makefile, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py, sdk/python/feast/infra/offline_stores/contrib/postgres_repo_configuration.py, sdk/python/feast/infra/online_stores/contrib/postgres_repo_configuration.py
Allows users to save datasets in postgres.
Fixes #2995
=> feat: Adding saved dataset capabilities for Postgres 

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
Fixes some integration tests related to the spark offline store. Specifically when empty list data is converted from a spark data frame to arrow. This PR fixes 5 failing tests.
The current implementation converts from spark df --> pandas --> arrow.
The new implementation writes the data temporarily to parquet and then loads it with arrow.
None
=> fix: Fix Spark offline store type conversion to arrow

sdk/python/feast/inference.py
Fixed a bug where field mappings to timestamp and createdstamp were not being skipped over when registering query result as features/entities
Fixes #
=> fix: Fix field mapping logic during feature inference

Makefile, setup.py
Unclear why tests passed before, but the Go unit tests run the Feast Python CLI, which relies on Python protos being built. The original `make test-go` command does not build those Python protos.
Fixes #
=> ci: Fix go unit tests failure

CONTRIBUTING.md, docs/SUMMARY.md, docs/reference/codebase-structure.md
=> docs: Codebase structure

Makefile, docs/how-to-guides/customizing-feast/adding-a-new-offline-store.md, docs/how-to-guides/customizing-feast/adding-support-for-a-new-online-store.md
=> chore: Update offline and online store docs

docs/reference/batch-materialization/README.md, docs/reference/batch-materialization/bytewax.md, sdk/python/docs/index.rst, sdk/python/docs/source/feast.infra.materialization.contrib.bytewax.rst, sdk/python/docs/source/feast.infra.materialization.contrib.rst, sdk/python/docs/source/index.rst, sdk/python/feast/infra/materialization/contrib/bytewax/__init__.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_job.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_task.py, sdk/python/feast/repo_config.py, sdk/python/tests/integration/materialization/contrib/bytewax/README.md, sdk/python/tests/integration/materialization/contrib/bytewax/eks-config.yaml, sdk/python/tests/integration/materialization/contrib/bytewax/test_bytewax.py, setup.py
This PR adds a Bytewax batch materialization engine.
Fixes #
=> feat: Initial Bytewax materialization engine

docs/tutorials/structuring-feature-repos.md, java/serving/src/test/resources/docker-compose/feast10/setup_it.py, sdk/python/feast/cli.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/provider.py, sdk/python/feast/repo_config.py, sdk/python/feast/repo_operations.py, sdk/python/tests/unit/cli/test_cli.py, sdk/python/tests/unit/infra/scaffolding/test_repo_config.py
=> feat: Allow passing repo config path via flag

sdk/python/feast/infra/utils/snowflake_utils.py
Forces all Snowflake sessions to retrieve timestamp data in UTC timezone.
Fixes #2793
=> fix: Force Snowflake Session to Timezone UTC

sdk/python/feast/repo_operations.py, sdk/python/tests/example_repos/example_feature_repo_with_bfvs.py, sdk/python/tests/unit/local_feast_tests/test_e2e_local.py, sdk/python/tests/utils/cli_repo_creator.py
=> fix: Register BatchFeatureView in feature repos correctly

sdk/python/feast/infra/registry/sql.py, sdk/python/tests/unit/test_sql_registry.py
Signed-off-by: Hao Xu <hao.xu@affirm.com>
Fix a bug that `name = name or obj.name if hasattr(obj, "name") else None` has wrong order sequence.
Fixes #
=> fix: Update sql.py

sdk/python/feast/feast_object.py, sdk/python/feast/feature_store.py, sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
Missed this in #3092 .
Fixes #3082 for realsies
=> fix: FeatureStore.apply applies BatchFeatureView correctly

docs/reference/batch-materialization/bytewax.md, sdk/python/feast/infra/materialization/contrib/bytewax/Dockerfile, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py, sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py, sdk/python/feast/infra/materialization/contrib/bytewax/entrypoint.sh
This PR adds the ability to create a custom image to run in Kubernetes when using the Bytewax materialization engine.
Fixes #
=> feat: Custom Docker image for Bytewax batch materialization

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
* Create `offline_write_batch` method for spark offline store
* Replace spark testing data sets with a file-based parquet format instead of a temporary view
This PR resolves a further set of failing integration tests.
None
=> feat: Implement spark offline store `offline_write_batch` method

.github/workflows/pr_local_integration_tests.yml, docs/reference/batch-materialization/README.md, docs/reference/batch-materialization/snowflake.md, docs/reference/offline-stores/snowflake.md, docs/tutorials/tutorials-overview/driver-stats-on-snowflake.md, sdk/python/docs/source/feast.infra.materialization.rst, sdk/python/docs/source/feast.infra.utils.rst, sdk/python/feast/infra/materialization/snowflake_engine.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/infra/online_stores/snowflake.py, sdk/python/feast/infra/utils/snowflake/snowflake_utils.py, sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_creation.sql, sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_deletion.sql, sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_udfs.py, sdk/python/feast/repo_config.py, sdk/python/feast/templates/snowflake/bootstrap.py, sdk/python/feast/templates/snowflake/driver_repo.py, sdk/python/feast/templates/snowflake/feature_store.yaml, sdk/python/feast/type_map.py, sdk/python/setup.cfg, sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py, sdk/python/tests/integration/materialization/test_snowflake.py
Allows Snowflake to be a materialization option when Snowflake is used as an offline store
Fixes #2633
=> feat: Add Snowflake materialization engine

sdk/python/feast/proto_json.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
=> chore: Relax protobuf constraints

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/snowflake.py
=> chore: Check configs and data sources in all offline store methods

sdk/python/feast/infra/materialization/lambda/lambda_engine.py, sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/tests/integration/materialization/test_lambda.py
consistent reads will also help with the lambda integration tests, since the flakes are likley because of eventually consistent reads after materialization.
Fixes #
=> chore: Support consistent reads in dynamodb

sdk/python/feast/inference.py
Updates a dummy entity join key only once even if `update_feature_views_with_inferred_features_and_entities` is called multiple times in `feast.apply()`
Fixes #3114
=> fix: Make infer dummy entity join key idempotent

sdk/python/feast/infra/online_stores/datastore.py, sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/feast/infra/online_stores/online_store.py, sdk/python/feast/infra/online_stores/redis.py, sdk/python/feast/infra/online_stores/sqlite.py
=> chore: Update online store docstrings

docs/SUMMARY.md, docs/how-to-guides/running-feast-in-production.md, docs/how-to-guides/scaling-feast.md, docs/how-to-guides/structuring-repos.md
=> docs: Docs on structuring repos and scaling feast

sdk/python/docs/conf.py, sdk/python/docs/source/conf.py, sdk/python/docs/source/feast.infra.offline_stores.contrib.mssql_offline_store.rst, sdk/python/docs/source/feast.infra.offline_stores.contrib.mssql_offline_store.tests.rst, sdk/python/docs/source/feast.infra.offline_stores.contrib.rst, sdk/python/docs/source/feast.protos.feast.serving.rst, sdk/python/docs/source/feast.rst
=> chore: Build Python protos during sphinx build

ui/src/parsers/feastSavedDataset.ts
Signed-off-by: alex.eijssen <alex.eijssen@energyessentials.nl>
This PR fixes a loading issue encountered when you have a saved dataset in your registry. The compiler: https://github.com/feast-dev/feast/blob/master/ui/src/parsers/feastSavedDataset.ts, enforces certain variables to be there, which generally aren't. It's a very crude fix, but at least saving a dataset doesn't crash the whole ui anymore.
Fixes #2996
=> fix: UI error when saved dataset is present in registry.

sdk/python/feast/base_feature_view.py, sdk/python/feast/batch_feature_view.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena_source.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/stream_feature_view.py, sdk/python/tests/unit/test_feature_views.py
**What this PR does / why we need it**: These docstrings are necessary for RTD.
Fixes #
=> chore: Add docstrings

.github/workflows/build_wheels.yml, .github/workflows/release.yml
This PR fixes a couple of issues. The smoke test doesn't work anymore because of `feast init` change where `feature_repo` is now located inside the repo. 
Also removes the ui build temporarily since 0.24.0 is already released. Will add back in future pr. 
Fixes #
=> fix: Fix release workflow to release 0.24.0

Makefile, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena_source.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/tests/data_source.py, sdk/python/feast/infra/offline_stores/contrib/athena_repo_configuration.py, sdk/python/feast/infra/utils/aws_utils.py
This PR is for allowing users to specify Athena workgroup in offline store config of the file `feature_store.yaml`.  In addition, this PR also fixed feast module import error, so that athena universal tests can be successfully run.
Run two tests:
1. unit tests (test-python): 135 passed, 471 warnings, 2 errors
2. universal tests (test-python-universal-athena): 2 failed, 61 passed, 15 skipped, 5 warnings, 2 errors
```
For unit tests:
ERROR sdk/python/tests/integration/e2e/test_go_feature_server.py
ERROR sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
```
```
For universal tests:
FAILED sdk/python/tests/integration/offline_store/test_push_features_to_offline_store.py::test_push_features_and_r
ead[AWS:Athena:sqlite:python_fs:False:go_fs:False]
FAILED …
```
=> feat: Add workgroup to athena offline store config

.github/workflows/build_wheels.yml, .github/workflows/release.yml, infra/scripts/helm/validate-helm-chart-versions.sh
=> fix: Fix release workflow

sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_udfs.py
=> chore: Add tagging for snowflake engine

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
`get_table_column_names_and_types` of `SparkSource` returns non-string data type for complex Spark types.
For example, if a feature view contains a feature of type `ArrayType(DoubleType(), False)`, current implementation would return a dictionary such as
```
{'type': 'array', 'elementType': 'double', 'containsNull': False}
```
With this fix, the returning data type would be `array<double>`.
This PR ensures that all Spark types are serialized as strings.
Fixes #
=> fix: Handle complex Spark data types in SparkSource

sdk/python/feast/entity.py, sdk/python/feast/feature_view.py, sdk/python/feast/inference.py
=> chore: Remove `join_keys` attribute

sdk/python/feast/entity.py, sdk/python/feast/feature_view.py, sdk/python/feast/inference.py, sdk/python/tests/unit/infra/test_inference_unit_tests.py, sdk/python/tests/unit/test_feature_views.py
=> chore: Add `value_type` parameter back to entities

docs/SUMMARY.md, docs/getting-started/architecture-and-components/online-store.md, docs/reference/online-stores/README.md, docs/reference/online-stores/cassandra.md, docs/reference/online-stores/datastore.md, docs/reference/online-stores/dynamodb.md, docs/reference/online-stores/overview.md, docs/reference/online-stores/postgres.md, docs/reference/online-stores/redis.md, docs/reference/online-stores/snowflake.md, docs/reference/online-stores/sqlite.md, sdk/python/docs/index.rst, sdk/python/docs/source/index.rst
=> docs: Functionality matrix for online stores

Makefile, README.md, docs/reference/data-sources/push.md, docs/roadmap.md, infra/charts/feast/README.md, infra/charts/feast/README.md.gotmpl, sdk/python/feast/feature_store.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py
This issue showed up with pushing to the online store using Snowflake as an offline store. The bug being:
1001 in Snowflake is an Int64. In pandas, it is an Int32. Feast stores inferred entity types in the feature view, not the entity, and so this was causing the Snowflake quickstart's `push` call to not know that 1001 should be an int64, so it never coerces it. This resulted in it looking like `push` calls never impacted the online store
This also updates the roadmap
Fixes #3171
=> fix: Fix push API to respect feature view's already inferred entity types
