feast-dev/feast

serving/src/main/java/feast/serving/grpc/ServingGrpcService.java

Avoid returning error to caller when the query is successful but returns empty result.

Empty response handling in serving api

---

cli/feast/cmd/apply.go
cli/feast/cmd/jobs.go
cli/feast/cmd/list.go
cli/feast/cmd/root.go
cli/feast/cmd/version.go
cli/feast/main.go
cli/feast/pkg/printer/job.go
core/src/main/java/feast/core/grpc/CoreServiceImpl.java
core/src/main/java/feast/core/job/ScheduledJobMonitor.java
core/src/main/java/feast/core/log/Action.java
core/src/main/java/feast/core/log/AuditLogger.java
core/src/main/java/feast/core/log/Resource.java
core/src/main/java/feast/core/model/EntityInfo.java
core/src/main/java/feast/core/model/FeatureGroupInfo.java
core/src/main/java/feast/core/model/FeatureInfo.java
core/src/main/java/feast/core/model/StorageInfo.java
core/src/main/java/feast/core/service/JobExecutionService.java
core/src/main/java/feast/core/service/JobManagementService.java
core/src/main/java/feast/core/service/SpecService.java
core/src/main/java/feast/core/storage/BigQueryStorageManager.java
core/src/main/java/feast/core/storage/BigTableStorageManager.java
core/src/main/java/feast/core/storage/PostgresStorageManager.java
core/src/test/java/feast/core/model/EntityInfoTest.java
core/src/test/java/feast/core/model/FeatureGroupInfoTest.java
core/src/test/java/feast/core/model/FeatureInfoTest.java
core/src/test/java/feast/core/model/StorageInfoTest.java
core/src/test/java/feast/core/service/SpecServiceTest.java
go-feast-proto/feast/core/CoreService.pb.go
protos/feast/core/CoreService.proto

Change register API to apply. 
If you apply a spec for a resource that doesn't already exist in the system, it will be created. If not, then the resource will be updated to match the new spec provided. Note that only fields without dependencies can be updated; i.e. changes to ids, storage sinks, or value types are not allowed. If you apply a spec that has no changes without throwing an error.
Updated the CLI to reflect these changes as well.

Change register to apply

---

ingestion/pom.xml
ingestion/src/main/java/feast/ingestion/ImportJob.java
ingestion/src/main/java/feast/ingestion/deserializer/FeatureRowDeserializer.java
ingestion/src/main/java/feast/ingestion/deserializer/FeatureRowKeyDeserializer.java
ingestion/src/main/java/feast/ingestion/options/ImportJobOptions.java
ingestion/src/main/java/feast/ingestion/transform/FeatureEnums.java
ingestion/src/main/java/feast/ingestion/transform/FeatureRowKafkaIO.java
ingestion/src/main/java/feast/ingestion/transform/ReadFeaturesTransform.java
ingestion/src/test/java/feast/ingestion/deserializer/KafkaFeatureRowDeserializerTest.java
protos/feast/types/FeatureRow.proto

- Support for reading message from kafka topics as FeatureRow using Apache Beam's KafkaIO implementation
- Profiles to building ingestion jar for specific runners (flink, dataflow and direct)
- Minor refactoring

KafkaIO implementation for feast

---

rfcs/0000-python-sdk.md

This pull request adds an RFC for a Python SDK

Added RFC for Feast Python SDK

---

ingestion/src/main/java/feast/storage/noop/NoOpWarehouseStore.java

This is related to issue #5
If the core api was to return a store spec with "noop" as it's type, then ingestion will ignore data sent to that store.

Return same type string for warehouse and serving NoOp stores

---

ingestion/src/main/java/feast/ingestion/ImportJob.java
ingestion/src/main/java/feast/ingestion/deserializer/FeatureRowDeserializer.java
ingestion/src/main/java/feast/ingestion/deserializer/FeatureRowKeyDeserializer.java
ingestion/src/main/java/feast/ingestion/options/ImportJobOptions.java
ingestion/src/main/java/feast/ingestion/transform/FeatureRowKafkaIO.java
ingestion/src/test/java/feast/ingestion/deserializer/KafkaFeatureRowDeserializerTest.java

Kafka IO fixes

---

ingestion/pom.xml

Remove packaging ingestion as separate profile (fix #28)

---

.gitignore
Makefile
testing/Makefile
testing/README.md
testing/prow/config.yaml
testing/prow/plugins.yaml
testing/test-image/Dockerfile
testing/test-image/run.sh
testing/tf/gcs/backend.tf
testing/tf/gcs/main.tf
testing/tf/k8s-cluster/backend.tf
testing/tf/k8s-cluster/main.tf
testing/tf/k8s-cluster/output.tf
testing/tf/k8s-cluster/provider.tf
testing/tf/k8s-cluster/variables.tf
testing/tf/terraform.tfvars

This PR sets up unit testing using Prow, for issue #2

Add testing folder for deploying test infrastructure and running tests

---

ingestion/src/main/java/feast/ingestion/deserializer/FeatureRowDeserializer.java
ingestion/src/main/java/feast/ingestion/deserializer/FeatureRowKeyDeserializer.java
ingestion/src/test/java/feast/ingestion/deserializer/KafkaFeatureRowDeserializerTest.java

This fixes the error being thrown by the test, which breaks the build, although the test passes.

Fixes #31 - errors during kafka deserializer (passing) test execution

---

CONTRIBUTING.md

skeleton contributing guide

---

ingestion/pom.xml

Upgrade Beam SDK to 2.9.0. 
As a result following dependencies are update as well:
1. bigtable-hbase-beam: 1.6.0 -> 1.8.0
2. io.grpc.grpc-netty: 1.2.0 -> 1.13.1
3. io.grpc.grpc-stub: 1.2.0 -> 1.13.1
4. io.grpc.grpc-protobuf: 1.2.0 -> 1.13.1
Fix #42

Bump Beam SDK to 2.9.0

---

docker/core/Dockerfile
docker/serving/Dockerfile
testing/tf/cloud-build/cloud-build.tf
testing/tf/cloud-build/cloudbuild.yaml
testing/tf/cloud-build/variables.tf

For #55.
Adds trigger to google cloud builds watching for semver tag pushes. The images are then pushed to gcr.

Build push

---

ingestion/src/main/java/feast/ingestion/model/Specs.java

Deduplicate storage ids before we fetch them

---

core/src/main/java/feast/core/service/SpecService.java
core/src/test/java/feast/core/service/SpecServiceTest.java

Check the size of result against deduplicated request

---

core/src/main/java/feast/core/validators/SpecValidator.java
core/src/test/java/feast/core/validators/SpecValidatorTest.java

Allow registration of feature without warehouse store

---

ingestion/src/main/java/feast/ingestion/transform/SplitOutputByStore.java
ingestion/src/test/java/feast/ingestion/transform/SplitOutputByStoreTest.java

Avoid error thrown when no storage for warehouse/serving is registered

---

ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowsDoFn.java
ingestion/src/test/java/feast/ingestion/ImportJobCSVTest.java
ingestion/src/test/resources/core_specs/feature/testEntity.none.testInt64NoWarehouse.json
ingestion/src/test/resources/core_specs/feature/testEntity.none.testStringNoWarehouse.json

Fix validating feature row when the associated feature spec has no warehouse store

---

core/src/main/java/feast/core/validators/SpecValidator.java
core/src/test/java/feast/core/validators/SpecValidatorTest.java

Fix for the submission validation bug mentioned in #22.

Allow submission of kafka jobs

---

cli/feast/pkg/printer/printer_test.go
cli/feast/pkg/util/utils.go

Fix go test

---

core/src/main/java/feast/core/service/SpecService.java
core/src/test/java/feast/core/service/SpecServiceTest.java

add logging when error on request feature

---

core/src/main/resources/log4j2.xml

This disables JSON logging by default, but allows the user to enable it by setting LOG_TYPE=JSON
Fix #104

Added LOG_TYPE environmental variable

---

sdk/python/feast/sdk/client.py

This commit fixes a bug where the key is being passed to the `_apply_feature` method, instead of the object. This causes a failure when trying to register that feature with Feast.
Fix #134

Fix Python SDK importer's ability to apply features

---

sdk/python/feast/sdk/importer.py
sdk/python/tests/sdk/test_importer.py

Fix import spec created from Importer.from_csv

---

core/src/main/java/feast/core/storage/BigQueryStorageManager.java
core/src/test/java/feast/core/storage/BigQueryStorageManagerTest.java
ingestion/src/main/java/feast/store/warehouse/bigquery/FeatureRowToBigQueryTableRowDoFn.java

Add job identifier to FeatureRow 

---

serving/pom.xml
serving/src/main/java/feast/serving/config/ServingApiConfiguration.java
serving/src/main/java/feast/serving/service/CachedSpecStorage.java
serving/src/main/resources/application.properties
serving/src/test/java/feast/serving/service/CachedSpecStorageTest.java

This PR change 2 behaviour in serving component:
1. All spec (feature spec, storage spec, and entity spec) is retrieved from Core and loaded to cache during start up.
2. The cache refresh is now asynchronous and take place in a separate thread as the request's thread.
Fix #151

Preload spec in serving cache

---

Gopkg.lock
Gopkg.toml
cli/README.md
protos/generated/go/feast/core/CoreService.pb.go
protos/generated/go/feast/core/DatasetService.pb.go
protos/generated/go/feast/core/JobService.pb.go
protos/generated/go/feast/core/UIService.pb.go
protos/generated/go/feast/serving/Serving.pb.go
protos/generated/go/feast/specs/EntitySpec.pb.go
protos/generated/go/feast/specs/FeatureGroupSpec.pb.go
protos/generated/go/feast/specs/FeatureSpec.pb.go
protos/generated/go/feast/specs/ImportSpec.pb.go
protos/generated/go/feast/specs/StorageSpec.pb.go
protos/generated/go/feast/storage/BigTable.pb.go
protos/generated/go/feast/storage/Redis.pb.go
protos/generated/go/feast/types/Feature.pb.go
protos/generated/go/feast/types/FeatureRow.pb.go
protos/generated/go/feast/types/FeatureRowExtended.pb.go
protos/generated/go/feast/types/Granularity.pb.go
protos/generated/go/feast/types/Value.pb.go

Try to reduce the complexity of getting the development dependencies necessary for building the CLI and update the README with these new steps.

Simplify and document CLI building steps

---

ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowsDoFn.java

Add validity check to event timestamp of a Feature Row so that it could be safely discarded during data validation check.
Fix #163

Check validity of event timestamp in ValidateFeatureRowDoFn

---

ingestion/src/main/java/feast/store/errors/json/JsonFileErrorsWrite.java

Prevent throwing RuntimeException when invalid proto is received

---

core/src/main/java/feast/core/training/BigQueryDatasetTemplater.java
core/src/main/resources/templates/bq_training.tmpl
core/src/test/java/feast/core/training/BigQueryDatasetTemplaterTest.java
core/src/test/resources/sql/expQuery1.sql
core/src/test/resources/sql/expQuery2.sql

Previous BigQuery query template used by `DatasetService` to retrieve training data has some errors for e.g. it creates query like
```sql
SELECT mygcpproject.mydataset.mycolumn FROM mygcpproject.mydataset.mycolumn LIMIT 5
```
This is a fix to the templates.
**Extra notes**
How to reproduce this error using Feast Python SDK which will call the `DatasetService`:
> Assuming you have ingested feature: myentity.myfeature with event timestamp between 2019-01-01 and 2019-01-02
```python
feature_set = FeatureSet(entity="myentity", 
features=["myentity.myfeature"])
dataset_info = feast_client.create_dataset(feature_set, "2019-01-01", "2019-01-02")
dataset = fs.download_dataset_to_df(dataset_info, staging_location="gs://mybucket")
```

Fix BigQuery query template to retrieve training data

---

serving/src/main/java/feast/serving/service/CoreService.java

Consider `ConnectivityState.IDLE` as a ready state.
Fix #190

Readiness probe

---

.prow/config.yaml

In case the dataset name clashes with previously undeleted dataset.
(Clash is possible because only the first 5 characteres of build id are used)
> Normally during integration test, the dataset created should be deleted during cleanup. But just in case it was not deleted, this update ensures the next integration test will not be affected. Because build id (hence dataset id) created during each run will always be unique.

Use full prow build id as dataset name during test

---

.prow/scripts/install_google_cloud_sdk.sh
.prow/scripts/run_unit_test.sh

Previously, when running unit test for CLI, the return code is the return code of the "tee" command NOT the "test" command. Hence it was always successful and we might miss failing Feast CLI unit tests.

Fix unit test cli in prow script not returning correct exit code

---

Dockerfiles/core/Dockerfile
Dockerfiles/serving/Dockerfile
charts/feast/templates/_helpers.tpl
charts/feast/templates/core-deploy.yaml
charts/feast/templates/serving-deploy.yaml
charts/feast/values.yaml
docs/install.md
integration-tests/feast-helm-values.yaml.template

With latest Feast release `0.1.1`, the previous installation doc is no longer valid.
This pull request updates the Feast installation doc, including step-by-step commands for setting up Feast infrastructure and configuration.
It's a bit verbose, but I think it's easier for people not that familiar with Google Cloud and Kubernetes to get started.
The updated installation quickstart doc can be viewed from this link:
https://github.com/gojek/feast/blob/installation-doc/docs/install.md
> NOTE:
> If you want to test this pull request by following the commands in the 
> the new `install.md` make sure you do:
> `git clone https://github.com/gojek/feast`
> `git checkout installation-doc`
>
> Since this pull request updates some of the chart definition and the install
> guide includes installing …

Update Feast installation doc

---

docs/install.md

- rename the feast service account
- add notes on `--no-address`
- make the important notes not greyed out

update feast installation docs

---

core/src/main/java/feast/core/model/JobInfo.java

When trying to ingest a lot of features in one go, core complains about data integrity, saying that entry is too long for type character varying(4096)
```
{  
"timeMillis":1560409069190,
"thread":"grpc-default-executor-52",
"level":"ERROR",
"loggerName":"feast.core.grpc.JobServiceImpl",
"message":"Error in submitJob: {}",
"thrown":{  
"commonElementCount":0,
"localizedMessage":"Error running ingestion job: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement",
"message":"Error running ingestion job: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could …
```

expand raw column to accomodate more features ingested in one go

---

core/src/main/java/feast/core/config/TrainingConfig.java
core/src/main/java/feast/core/grpc/DatasetServiceImpl.java
core/src/main/java/feast/core/training/BigQueryDatasetTemplater.java
core/src/main/java/feast/core/training/BigQueryTraningDatasetCreator.java
core/src/main/java/feast/core/util/RandomUuidProvider.java
core/src/main/java/feast/core/util/UuidProvider.java
core/src/main/resources/templates/bq_training.tmpl
core/src/test/java/feast/core/grpc/DatasetServiceImplTest.java
core/src/test/java/feast/core/training/BigQueryDatasetTemplaterTest.java
core/src/test/java/feast/core/training/BigQueryTraningDatasetCreatorTest.java
core/src/test/resources/sql/expQueryWithJobIdFilter.sql
core/src/test/resources/sql/expQueryWithNumberAndStringFilter.sql
core/src/test/resources/sql/expQueryWithNumberFilter.sql
core/src/test/resources/sql/expQueryWithStringFilter.sql
protos/feast/core/DatasetService.proto
sdk/python/feast/core/DatasetService_pb2.py
sdk/python/feast/sdk/client.py
sdk/python/tests/sdk/test_client.py

This follows implementation suggested in #214
fix #214

Implement filter for create dataset api

---

sdk/python/feast/sdk/importer.py

To fix: https://github.com/gojek/feast/issues/203
- Replace the custom datetime format pattern with a generic `.isoformat()` function call

[Issue 203]:  fix the datetime column format during the import via python sdk

---

sdk/python/feast/sdk/client.py
sdk/python/feast/sdk/utils/bq_util.py
sdk/python/feast/sdk/utils/gs_utils.py
sdk/python/tests/sdk/utils/test_bq_utils.py

Updates bq_utils and gs_utils for downloading larger datasets. For BigQuery, if you are exporting more than 1 GB of data, you must export your data to multiple files (see https://cloud.google.com/bigquery/docs/exporting-data)
- BQ TableDownloader extracts tables to one or many sharded files in a tempory gcs folder
- helper methods under gs_utils download the contents of the temporary gcs folder and concatenate into a single dataframe
- client.download_dataset() can take a wild-card file pattern destination (including a *), similar to https://cloud.google.com/bigquery/docs/exporting-data#exporting_data_into_one_or_more_files
- a RuntimeError is raised if the user-provided destination does not include a * and multiple shards are required
- the api for client.download_dataset_to_df() has not …

BQ TableDownloader extracts to sharded files to handle larger datasets

---

docs/specs.md

Just a tiny `../` to fix a 404 ☺️

Fix relative link to FeatureRow.proto in specs doc

---

sdk/python/feast/config.py

This PR adds the ability to set the cli config path via an env var:
- `FEAST_CONFIG: 'path/to/dir/with/configfile'`
The path assumes it is being written from the $HOME dir. The default value is `.feast`
Fixes #149

Allow cli config path to be set by env var

---

core/pom.xml
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
ingestion/pom.xml
ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
ingestion/src/test/java/feast/store/FileStoreOptionsTest.java
ingestion/src/test/java/feast/store/TextFileDynamicIOTest.java
ingestion/src/test/resources/logback-test.xml
pom.xml
protos/feast/types/Value.proto
sdk/java/pom.xml
serving/pom.xml
serving/src/main/java/feast/serving/service/CachedSpecService.java
serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java

Hi folks!
There are three main themes here:
1. The pebble that got me rolling, this was giving us a headache while trying to work:
Fix the `core` module dependency on `ingestion` so that Maven resolves it as an inter-project dep, without requiring it to be `install`ed to (local) repository and mucking with the version as you work.
1. Use [`<dependencyManagement>`] in parent POM for common dependencies and families—version drift between modules on things like gRPC and Google Cloud deps will bring more pain in the long run than any short-term convenience of letting them differ between modules I think. This makes it easy to control that consistently.
1. Avoid (re)defining `<properties>` in submodule POMs—similar reasoning  as dependencies: drift leads to suffering. If you build only a subset …

Clean up the Maven build

---

core/pom.xml
ingestion/pom.xml
pom.xml
sdk/java/pom.xml
serving/pom.xml

A goal of #262 was to standardize versions of dependencies used across modules in the project. If everyone is on board with that, then we want to avoid re-declaring versions outside of [`<dependencyManagement>`].
If you're not used to `<dependencyManagement>` it may help to think of it this way: it _defines_ dependencies, while `<dependency>` _references_ in modules "instantiate" them.
Maven's [Enforcer plugin] provides a rule that detects duplicate dependency definitions and fails the build early. This adds a bit of friction nudging developers to understand this way of working. My feeling is this friction is more than worth the sum frustration of dependency hell that it can relieve over time.
I'll have some additions to `CONTRIBUTING.md` coming sooner or later, if you think this warrants …

Set Maven build requirements and some project POM metadata

---

ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java

We are setting up sharded with twemproxy in front of it. However, twemproxy doesn't support transaction (https://github.com/twitter/twemproxy/blob/master/notes/redis.md)
- Remove transaction in RedisCustomIO

Remove redis transaction

---

.prow/scripts/test-serving.sh
CONTRIBUTING.md
core/pom.xml
core/src/test/java/feast/core/job/dataflow/DataflowJobMonitorTest.java
ingestion/pom.xml
pom.xml
serving/pom.xml

Two things here—can extract out the small fix commit to a separate PR if there's any issue with the (hopefully last for awhile) dependency management-related part.
We realized that changing `core`'s dependency on `ingestion` to be inter-module instead of package install-based in #262 left behind a workflow issue. Using something like:
$ mvn -am -pl core spring-boot:run
from the project root directory broke, because it tried to find a main application class in the parent POM project and failed.
The first commit here resolves that, and provides dev docs whether you prefer to run from the IDE or CLI.
A next step for `<dependencyManagement>`. Typically it's recommended that Spring Boot applications inherit the `spring-boot-starter-parent` POM, such that you take on its Maven plugin …

Import Spring Boot's dependency BOM, fix spring-boot:run at parent project level

---

core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
infra/charts/feast/charts/prometheus-statsd-exporter/.helmignore
infra/charts/feast/charts/prometheus-statsd-exporter/Chart.yaml
infra/charts/feast/charts/prometheus-statsd-exporter/README.md
infra/charts/feast/charts/prometheus-statsd-exporter/templates/NOTES.txt
infra/charts/feast/charts/prometheus-statsd-exporter/templates/_helpers.tpl
infra/charts/feast/charts/prometheus-statsd-exporter/templates/config.yaml
infra/charts/feast/charts/prometheus-statsd-exporter/templates/deployment.yaml
infra/charts/feast/charts/prometheus-statsd-exporter/templates/pvc.yaml
infra/charts/feast/charts/prometheus-statsd-exporter/templates/service.yaml
infra/charts/feast/charts/prometheus-statsd-exporter/templates/serviceaccount.yaml
infra/charts/feast/charts/prometheus-statsd-exporter/values.yaml
infra/charts/feast/requirements.lock
infra/charts/feast/requirements.yaml
infra/charts/feast/values.yaml
ingestion/pom.xml
ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteDeadletterRowMetricsDoFn.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteMetricsTransform.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
ingestion/src/test/java/feast/ingestion/ImportJobTest.java
ingestion/src/test/java/feast/test/TestUtil.java

Still need to review metrics and also if infra changes need to be made as well

Replace Prometheus logging in ingestion with StatsD logging

---

sdk/python/feast/client.py
serving/src/main/resources/templates/bq_featureset_query.sql

Originally in PR #288, but moving it out because that might take awhile more to fix.
This PR
- Adds missing argument to `_serving_service_stub.GetFeastServingInfo`
- Fixes lookups to featuresets with different entities not returning anything

Batch ingestion fix

---

core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/util/PackageUtil.java
core/src/main/java/feast/core/util/PipelineUtil.java
core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
ingestion/src/test/java/feast/ingestion/ImportJobTest.java

To resolve error when launching Dataflow jobs from Feast Core:
```
Caused by: java.lang.IllegalArgumentException: Unable to convert url (jar:file:/opt/feast/core/target/feast-core-0.3.0-SNAPSHOT.jar!/BOOT-INF/classes!/) to file.
at org.apache.beam.runners.core.construction.PipelineResources.detectClassPathResourcesToStage(PipelineResources.java:67)
at org.apache.beam.runners.dataflow.DataflowRunner.fromOptions(DataflowRunner.java:285)
... 38 common frames omitted
```
When Feast Core starts from a packaged jar.
Reference:
https://stackoverflow.com/questions/48961440/illegalargumentexception-unable-to-convert-url-jarfile-app-jar-boot-inf-cla
https://stackoverflow.com/questions/48292491/java-dataflow-unable-to-use-classloader-to-detect-classpath-elements

Feast Core: Stage files manually when launching Dataflow jobs

---

.mvn/README.md
.mvn/maven.config
CONTRIBUTING.md
serving/README.md

I realized that Maven has a project-local config file where `--also-make` could be turned on always, and this is especially helpful for IntelliJ users because the IDE picks it up: it ends the breakage where the Build Project button or running tests error out because of not resolving core's dependency on ingestion. I had tried to find a way to tell it to consistently do this, and it turns out an answer lies outside of IntelliJ.
So far I haven't encountered cases where having this always-on causes issue for Maven operations I've run by CLI or IDE, but let me know if you run into any, and let's see how CI goes.
The `CONTRIBUTING.md` still has redundancy that I'm consolidating along with Docker Compose instructions for #272, but I did remove the instructions to `cd` into subdirectories in …

Use Maven's --also-make by default

---

core/src/main/java/feast/core/dao/FeatureSetRepository.java
core/src/main/java/feast/core/model/JobInfo.java

Some minor tweaks: 
1. feature_id was still referring to old schema -> should be changed to feature_set _id
2. ~ is postgresql specific -> changed to LIKE

Database tweaks

---

sdk/python/cli.py

For example running `feast apply -f feature-set.yaml` will throw this error
```
AttributeError: module 'feast.loaders.file' has no attribute 'yaml_loader'
```
Since `yaml_loader()` function has been moved to module `feast.loaders.yaml`

Fix module import error in Feast CLI

---

infra/charts/feast/charts/feast-serving/templates/deployment.yaml
infra/charts/feast/charts/feast-serving/values.yaml
serving/pom.xml
serving/src/main/java/feast/serving/configuration/InstrumentationConfig.java
serving/src/main/java/feast/serving/service/BigQueryServingService.java
serving/src/main/java/feast/serving/service/CachedSpecService.java
serving/src/main/java/feast/serving/service/RedisServingService.java
serving/src/main/java/feast/serving/util/Metrics.java
serving/src/main/resources/application.yml

Exposing metrics for feast serving via prometheus.
Still thinking of what metrics to add for batch retrieval, but currently for online serving, the following metrics are exposed:
- method latencies
- number of rows missing
- number of rows stale
- number of rows requested
Additionally, we track:
- specs cache last updated time
- number of of feature sets served by the serving instance

Add prometheus metrics to serving

---

.prow/scripts/test-end-to-end.sh
core/src/main/java/feast/core/service/SpecService.java
core/src/test/java/feast/core/service/SpecServiceTest.java
ingestion/src/main/java/feast/ingestion/ImportJob.java
ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
ingestion/src/main/java/feast/ingestion/transform/ValidateFeatureRows.java
ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
ingestion/src/main/java/feast/ingestion/transform/fn/KafkaRecordToFeatureRowDoFn.java
ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteDeadletterRowMetricsDoFn.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteMetricsTransform.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
ingestion/src/main/java/feast/ingestion/utils/SpecUtil.java
ingestion/src/main/java/feast/ingestion/values/FailedElement.java
ingestion/src/main/java/feast/ingestion/values/FeatureSetSpec.java
ingestion/src/main/java/feast/store/serving/bigquery/FeatureRowToTableRow.java
ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
pom.xml
serving/src/main/java/feast/serving/service/RedisServingService.java

The current ingestion job graph is built such that each distinct feature set has its own subgraph; branching is done by tagging each incoming feature row.
This has resulted in the following 2 problems:
1. With large amounts of features the graph balloons in size - so much so that the job is unable to be submitted to dataflow. 
2. Inability to update jobs with metrics enabled, since the type for the metrics step is changed between updates
This PR consolidates the steps such that all feature rows follow the same path through the graph.

Consolidate jobs into single steps instead of branching out

---

.prow/scripts/test-end-to-end.sh
ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
ingestion/src/main/java/feast/store/serving/bigquery/GetTableDestination.java
ingestion/src/main/java/feast/store/serving/bigquery/GetTableReference.java

Fixes this error:
```
Caused by: java.lang.IllegalArgumentException: The supplied getTableFunction object can directly set TimePartitioning. There is no need to call BigQueryIO.Write.withTimePartitioning.
at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
```

Set BigQuery table timepartition inside get table function

---

serving/src/main/resources/application.yml
serving/src/test/java/feast/serving/service/RedisServingServiceTest.java

Two things: 
1. Fixed the path in serving config to point to redis store config
2. There was a bug in RedisServingService when checking for equality to default Duration. I was adding the bug fix to my Cassandra serving branch but now I saw that it has already been fixed. However, the unit test was not catching that bug, so I thought we should still have this unit test. Unit test did not catch the bug because it EntityRow and FeatureRow time specified was the same in the test so those features are never stale.

Add unit test in Redis to return values with no max age set

---

serving/src/main/java/feast/serving/service/BigQueryServingService.java
serving/src/main/java/feast/serving/service/RedisServingService.java

Swapping out the prometheus timers because `Timer` records latencies in seconds, which is too large for our use case.

Change latency calculation method to not use Timer

---

ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
ingestion/src/test/java/feast/ingestion/util/StoreUtilTest.java

**BOOL** value type in FeatureSetSpec is registered as **repeated** mode in BigQuery, because of incorrect comparison of the type Enum. It should be a single (non repeated) mode.
The comparison:
https://github.com/gojek/feast/blob/1ef1b712b56c00504f37fa4396ed1ebdce625f6a/ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java#L121
The proto for the enum:
https://github.com/gojek/feast/blob/1ef1b712b56c00504f37fa4396ed1ebdce625f6a/protos/feast/types/Value.proto#L34
This pull request:
1. Add a test to ensure correct BigQuery schema is created.
2. Compare using the enum **name suffix** versus the enum int value. This makes the comparison more explicit.

Fix incorrect BigQuery schema creation from FeatureSetSpec

---

core/src/main/java/feast/core/grpc/CoreServiceImpl.java
core/src/test/java/feast/core/grpc/CoreServiceImplTest.java

When feature sets are applied, jobs are run with all featuresets matching relevant stores' subscriptions, but our jobs are created for store::source pairs. 
Adding in filter to filter out feature sets that do not match the source of the applied feature set.

Filter out feature sets that dont share the same source

---

docs/community.md

I happened to be looking at docs and noticed this [link gone funny](https://github.com/gojek/feast/blob/2abeabde011737e0bcb1d97f79d976f718b90321/docs/community.md), maybe a GitBook editor tried to Markdown-escape something pasted that was already Markdown format.

docs: Fix broken Google Group link on Community page

---

core/pom.xml
core/src/main/java/feast/core/config/MonitoringConfig.java
core/src/main/java/feast/core/dao/FeatureSetRepository.java
core/src/main/java/feast/core/dao/StoreRepository.java
core/src/main/java/feast/core/grpc/CoreServiceImpl.java
core/src/main/java/feast/core/grpc/interceptors/MonitoringInterceptor.java
core/src/main/java/feast/core/metrics/GrpcMetrics.java
core/src/main/java/feast/core/metrics/collector/FeastResourceCollector.java
core/src/main/java/feast/core/metrics/collector/JVMResourceCollector.java
pom.xml

This pull request adds the following Prometheus metrics to Feast Core:
- **feast_core_request_latency_seconds**: duration of each GRPC call (labelled by service name, method name and GRPC status code)
- **feast_core_feature_set_total**: no of registered Feature Set
- **feast_core_store_total**: no of registered Store
- [**feast_core_max_memory_bytes**](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#maxMemory--)
- [**feast_core_total_memory_bytes**](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#totalMemory--)
- [**feast_core_free_memory_bytes**](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#freeMemory--)
- [**feast_core_gc_collection_seconds**](https://docs.oracle.com/javase/8/docs/api/java/lang/management/GarbageCollectorMXBean.html) …

Exports GRPC call metrics and Feast resource metrics in Core

---

.prow/config.yaml
.prow/scripts/test-end-to-end-batch.sh

This set of batch tests tests the following cases with a toy dataset:
- order_by_creation_time
- additional_columns_in_entity_table
- point_in_time_correctness_join
- multiple_featureset_joins
An example of a successful test run can be found [here](http://prow.feast.ai/view/gcs/feast-templocation-kf-feast/pr-logs/pull/gojek_feast/356/test-end-to-end/1204016732633567233)

Batch retrieval tests

---

sdk/java/pom.xml

Java SDK isn't being tested at the moment. This fixes dependencies so that tests run.

Fix Java SDK tests not actually running (missing dependencies)

---

serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
serving/src/main/java/feast/serving/service/BigQueryServingService.java

Catch errors thrown by BQ during entity table loading

---

.prow/scripts/sync-helm-charts.sh

Running `helm dep update` will make sure **requirements.lock** is in sync with **requirements.yaml**, so that `helm dep build` runs successfully. 
This script is used in automated Helm charts release.
Reference: https://github.com/helm/helm/issues/2033

Update sync helm chart script to ensure requirements.lock in in sync with requirements.yaml

---

ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java

Fixes an issue where depending on the upstream, we were not creating deterministic RedisKeys, causing lookups to fail. Also fixed issue where duplicate fields in incoming feature rows would bleed into the redis key.

Make redis key creation more determinisitic

---

infra/charts/feast/charts/feast-serving/values.yaml
infra/charts/feast/values.yaml

Documentation in default values.yaml is missing in Feast chart. This pull request addresses that.
Resolve https://github.com/gojek/feast/issues/350
In the future, there should probably be some automation / script so that the documentation for fields in `values.yaml` originates from a **single source** versus copy pasting it from multiple sources.
For instance, most of the documentation for `feast-core` field in the default `values.yaml` actually comes from the **feast-core** subchart default `values.yaml`:
https://github.com/gojek/feast/blob/7571ba7241c6451f4dd2718b41e4102c058fe1a1/infra/charts/feast/values.yaml#L51
https://github.com/gojek/feast/blob/7571ba7241c6451f4dd2718b41e4102c058fe1a1/infra/charts/feast/charts/feast-core/values.yaml#L102

Add documentation to default values.yaml in Feast chart

---

infra/charts/feast/charts/feast-serving/templates/configmap.yaml

Without option to override the default job options, it would not be possible to provision Redis outside of the helm chart.

Allow user to override job options

---

.prow/config.yaml
sdk/python/feast/client.py
sdk/python/feast/feature_set.py
sdk/python/feast/loaders/abstract_producer.py
sdk/python/feast/loaders/ingest.py
sdk/python/feast/type_map.py
sdk/python/setup.py
sdk/python/tests/test_client.py

- Added support to infer schema of PyArrow table directly (All types supported except bool_list_val)
- Removed schema inference with intermediate pandas DataFrame
- Added confluent-kafka support to improve throughput of FeatureRows being pushed into Kafka
- Added a series of optimizations to reduce memory footprint

Infer schema of PyArrow table directly

---

sdk/python/feast/client.py
sdk/python/feast/job.py
sdk/python/feast/loaders/file.py
tests/e2e/bq-batch-retrieval.py
tests/e2e/conftest.py
tests/e2e/requirements.txt

This PR mirrors [PR #365](https://github.com/gojek/feast/pull/365). The branch was deleted as i did not do a force-push but a delete-push to remote which resulted in PR#365 getting closed.
**Description**
Users should be able to provide large amounts of entity rows when retrieving batch features, but currently they are blocked by memory limits of pandas DataFrames.
Right now, for batch retrieval we already support Avro files as the format for sending entity rows, however this is only available on the Feast Serving API. The Python SDK hides this detail by doing
Entity_rows Pandas DF → .avro (local) → .avro (gcs) → BQ
This pull requests adds the ability for users to provide:
A pandas DataFrame with the "datetime" column
A local Avro file with the "event_timestamp" column
A gcs Avro file
A …

Add support for file paths for providing entity rows during batch retrieval 

---

sdk/python/feast/client.py
sdk/python/feast/loaders/ingest.py

This pull request add these changes:
- Use tmp dir when creating a temporary parquet file with a fixed `row_group_size`.
- Tweak int -> ceil when determining row_group_size when creating temporary parquet file.
- Changed imap_unordered to imap so that results returned by pool workers are ordered.

Minor bug fixes for Python SDK

---

sdk/java/src/main/java/com/gojek/feast/FeastClient.java
sdk/java/src/main/java/com/gojek/feast/RequestUtil.java
sdk/java/src/main/java/com/gojek/feast/Row.java
sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java

The package should be renamed before publishing this to public Maven repository.

Remove alpha v1 from java package name

---

serving/src/main/java/feast/serving/service/BigQueryServingService.java
serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
serving/src/main/java/feast/serving/store/bigquery/SubqueryCallable.java
tests/e2e/bq-batch-retrieval.py

This pull request updates **query configuration in Feast Serving for BigQuery** store such that the query result is always saved explicitly to a **destination table**.  
BigQuery has a default [maximum response size](https://cloud.google.com/bigquery/quotas#queries) of 10 GB compressed when query results are written to a temporary table managed by BigQuery. To overcome this limit, an explicit destination table is provided.
These destination tables are only **intermediate** tables used by Feast Batch Serving to create the final features output, hence Feast set them to expire in 1 day (BigQuery will auto delete them when they expire) by default.

Always set destination table in BigQuery query config in Feast Batch Serving so it can handle large results

---

.prow/scripts/test-end-to-end-batch.sh

Currently `test-e2e-batch` test script assumes the revision to be `0.3.2-SNAPSHOT`regardless of what is set in `pom.xml`. This results in a failed test when revision in `pom.xml` is updated.
This pull request updates test script to use a fixed revision name: 'dev' during testing regardless of the version set in `pom.xml`

Use fixed 'dev' revision for test-e2e-batch

---

infra/charts/feast/charts/feast-core/values.yaml

Since the helm install for feast core overwrites the default application configuration, the application configuration configured by the chart needs to contain the following option:
```
properties.hibernate.event.merge.entity_copy_observer: allow
```

Update feast core default values to include hibernate merge strategy

---

.prow/scripts/test-end-to-end-batch.sh
.prow/scripts/test-end-to-end.sh
Makefile
core/pom.xml
core/src/main/java/feast/core/config/MonitoringConfig.java
core/src/main/java/feast/core/service/SpecService.java
core/src/main/java/feast/core/util/PackageUtil.java
infra/docker/core/Dockerfile
infra/docker/serving/Dockerfile
ingestion/pom.xml
pom.xml
sdk/java/pom.xml
sdk/java/src/main/java/com/gojek/feast/FeastClient.java
serving/pom.xml

I have added Nexus Staging Plugin for deployment to Maven central, and also change the group id to dev.feast, and Java sdk client artifact id to feast-sdk.
This is a work in progress. Have tested snapshot deployment, but have not tested it by importing the sdk into a new Java project.

Use Nexus staging plugin for deployment

---

ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
ingestion/src/main/java/feast/retry/BackOffExecutor.java
ingestion/src/main/java/feast/retry/Retriable.java
ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java
ingestion/src/test/java/feast/store/serving/redis/RedisCustomIOTest.java
protos/feast/core/Store.proto

Currently, the Redis write to the serving store does not handle transient connection failures, which results in data loss. This PR augment the pipeline to retry the connection up to a certain maximum limit. The limit and backoff time are configurable via RedisConfig.

Handle retry for redis io flow

---

ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java

Fixes #401, but also additionally does some preprocessing of the feature row in the ValidateFeatureRowDoFn to (1) filter out extra fields and (2) deduplicate fields
I'm still not 100% sure if we want to commit to this behaviour.
Pros:
- Convenient
- Not failing when extra columns are found makes ingestion jobs more forward-compatible
- Consistent with behaviour of popular serialization methods
Cons:
- Upstream issues will not be flagged to the user
- Order of feature fields lost
That being said deduplication is not being done by field name, but the entire field, so no information should be lost.

Filter out extra fields, deduplicate fields in ingestion

---

serving/src/main/resources/templates/single_featureset_pit_join.sql

There is a loophole in the way the bq batch queries are done that if there are multiple rows with the same event timestamp, created timestamp and entity ids, the query will return duplicate rows.
This patch deduplicates subquery results, preventing that from happening.

Deduplicate rows in subquery

---

infra/docker/core/Dockerfile
infra/docker/serving/Dockerfile

This pull request adds back `-Drevision=$REVISION` argument in the Dockerfiles because without it Docker build will fail because subsequent steps assumes revision property is set.
> **Side note**
>  `${revision}` variable is removed in https://github.com/gojek/feast/pull/394. It is defined explicitly  because during deployment, if revision property is not defined explicitly i.e `${revision}` variable is used, the deployed child pom will have an invalid parent pom version because `${revision}` is not evaluated during deployment.
>
> However, now that we will use maven-flatten-plugin in https://github.com/gojek/feast/pull/406, we can use back `${revision}` variable in `pom.xml`.  `${revision}` gives us more flexibility when running `mvn` install command: …

Define maven revision property when packaging jars in Dockerfile so the images are built successfully

---

tests/e2e/bq-batch-retrieval.py

Some **new** end to end tests that were added to v0.3-branch from master are missing **wait** after running `feast apply`. Feast needs to wait for Beam job to be ready after running `feast apply`, otherwise the ingested data will not be processed by the Beam job.

Fix e2e batch test in v0.3-branch

---

core/src/main/java/feast/core/service/SpecService.java
core/src/main/java/feast/core/util/PackageUtil.java
ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
ingestion/src/main/java/feast/retry/BackOffExecutor.java
ingestion/src/main/java/feast/retry/Retriable.java
ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java
ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
ingestion/src/test/java/feast/store/serving/redis/RedisCustomIOTest.java

Backoff variable has been mistakenly assigned the static modifier. This doesn't affect DirectRunner, but on Dataflow Runner this seems to result in Nullpointer exception.
Edited: FluentBackoff shouldn't have been setup on the constructor, as it is unserializable. Passing the backoff as function argument fixed this. Thanks to @zhilingc for helping me to identify this.

Unserializable FluentBackoff cause null pointer exception in Dataflow Runner

---

.prow/scripts/publish-java-sdk.sh
datatypes/java/README.md

This forward-ports a tiny change from a straggling commit from #407 for v0.3, to include the `datatypes/java` module when publishing `sdk/java` to Sonatype. This was missed when initially creating the datatypes module because Sonatype publishing setup was added concurrently.
I also updated stale TODO note about the publishing.
```release-note
Moved `.proto` definitions and their generated Java class files to a minimal `datatypes-java` artifact, now a dependency of `feast-sdk`.
```

Publish datatypes/java along with sdk/java

---

docs/getting-started/installing-feast.md
infra/charts/feast/values.yaml

**What this PR does / why we need it**: GKE docs and charts are outdated and do not work end-to-end. This PR should do the minimum to fix it. Mostly thanks to @woop who helped me debug the issues and find holes in current docs/charts.
* Makes core, online-serving, batch-serving, kafka, and redis externally accessible using NodePorts in the example `values.yaml`.
* Updates relevant docs in installation guide to reflect nodeport changes.
* Adds instructions in exposing node ports in your gcloud firewall.
The end result is anybody should be able to follow these docs + `values.yaml` to create a feast cluster in GKE and have ingestion, online serving, and batch serving deployed on a publicly accessible IP.
Fixes #427
Fixes #349 
**Does this PR introduce a …

Update GKE installation and chart values to work with 0.4.3

---

core/src/main/resources/log4j2.xml
ingestion/pom.xml
pom.xml
serving/src/main/resources/log4j2.xml

- Allow log level to be set via environmental variable.
- Add ability to set appender type in serving.
- Remove logback-classic from ingestion as it is a library so should not bring its own impl.
- Upgrade log4j to 2.12.1 to support objectMessageAsJsonObject.
- Fix logger config targeting feast package in serving and add same concept for core.
Potentially fixes #277
```release-note
NONE
```

Fix logging

---

.prow/scripts/test-end-to-end-batch.sh
.prow/scripts/test-end-to-end.sh

Allow GCP project/bucket to be set in environment when running end-to-end tests. This is to allow us to run the e2e tests on our CI (Cloud Build) against our own GCP resources.
Additionally, 1/ allow skipping building of jars in e2e steps as we build them in a previous step, 2/ allow suffix to be specified to find jar as we use commit has rather than SNAPSHOT, 3/ print feast logs on test failure to help diagnosis.
This PR also aligns `test-end-to-end.sh` and `test-end-to-end-batch.sh` much more closely.
This does not fix anything. The motivation was to be able replicate the test failures in #431 .
```release-note
NONE
```

Parameterize end-to-end test scripts

---

core/src/main/java/feast/core/grpc/CoreServiceImpl.java
core/src/main/java/feast/core/job/JobUpdateTask.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
core/src/main/java/feast/core/model/FeatureSet.java
core/src/main/java/feast/core/model/Field.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/java/feast/core/service/SpecService.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
core/src/test/java/feast/core/service/SpecServiceTest.java
datatypes/java/src/main/proto/tensorflow_metadata
protos/feast/core/FeatureSet.proto
protos/tensorflow_metadata/proto/v0/path.proto
protos/tensorflow_metadata/proto/v0/schema.proto

This pull request is regarding feature validation in Feast. It updates `EntitySpec` and `FeatureSpec` protos with fields to specify constaints for the values. The constraint specs are adapted from Tensorflow metadata schema: https://github.com/tensorflow/metadata/blob/3b9d4114c6856ce18b7819023acb94f07183d348/tensorflow_metadata/proto/v0/schema.proto.  
Only `presence_constraints`, `shape_type` and `domain_info` are currently added to `EntitySpec` and `FeatureSpec` because it is adequate for the current validation requirement in Feast and to ensure integration with Tensorflow data validation works correctly, before adding more features supported in Tensorflow validation.
Partially addresses  #172 
**Does this PR …

Update protos with Tensorflow data validation schema

---

.prow/scripts/test-end-to-end-batch.sh
serving/src/main/java/feast/serving/FeastProperties.java
serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
serving/src/main/java/feast/serving/service/BigQueryServingService.java
serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
serving/src/main/resources/application.yml

Add two fields to job properties and use them to set retry options in all BigQuery job waitFor calls, as per Google example.
This fixes an issue where job metadata is sometimes used on an object that does not have it set, since the job was not reassigned to the completed job reference that waitFor returns.
Additionally handles errors with best practice and allows some retry options to be configured by the user.
```release-note
NONE
```

Add retry options to BigQuery

---

serving/pom.xml
serving/src/main/java/feast/serving/configuration/JobServiceConfig.java
serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
serving/src/main/java/feast/serving/service/BigQueryServingService.java
serving/src/main/java/feast/serving/service/RedisBackedJobService.java
serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
serving/src/main/resources/application.yml
serving/src/test/java/feast/serving/service/RedisBackedJobServiceTest.java

Current implementation of connection to jobs redis is using a client that upon failure does not refresh its connection to the db - so if anything goes awry batch retrieval is unusable until the instance is restarted to manually establish a new connection with redis.
This PR changes RedisBackedJobService to use a connection pool instead.
N/A
```release-note
NONE
```

Change RedisBackedJobService to use a connection pool

---

serving/src/main/resources/templates/single_featureset_pit_join.sql
tests/e2e/bq-batch-retrieval.py

Keeping batch retrieval consistent with online retrieval. 
Fixes #440 
```release-note
NONE
```

Allow users not to set max age for batch retrieval

---

docs/contributing.md

Seems there're a few breaking changes recently and contributing doc is broken. 
Fixes #436 
NONE
```release-note
Fix broken contributing doc
```

Fix broken contributing doc

---

README.md
infra/charts/feast/README.md
infra/charts/feast/charts/feast-core/templates/deployment.yaml
infra/charts/feast/charts/feast-core/values.yaml
infra/charts/feast/charts/feast-serving/templates/deployment.yaml
infra/charts/feast/charts/feast-serving/values.yaml
infra/charts/feast/requirements.yaml
infra/charts/feast/values.yaml

* It updates the main README.md
* Makes it required for users to provide an `image.tag` for Helm charts. Otherwise we will keep missing the update of versions in these charts and continue to deploy old docker images.

Update README.md and remove versions from Helm Charts

---

sdk/java/src/main/java/com/gojek/feast/Row.java

I want to be able to use AvroCoder with the Java SDK Row type, but since Row fields are defined as `java.util.Map` the AvroCoder is unable to encode objects containing the `Row` object. Since we already always instantiate a HashMap, declaring `fields` to be a HashMap should be fine.
Fixes #
```release-note
NONE
```

Use concrete class in Java SDK Row for AvroCoder compatibility

---

serving/src/main/java/feast/serving/specs/CachedSpecService.java

In release 4.0 we have introduced implicit version retrieval, where latest version of a feature set will be retrieved if no version is explicitly specified.  This feature didn't work as intended, as the feature to feature ref map is incorrectly updated.
Implicit version retrieval should work as intended after this fix, for both batch and online retrieval.

Fix implicit feature set version retrieval

---

.prow/config.yaml
core/pom.xml
core/src/main/java/feast/core/util/PipelineUtil.java
datatypes/java/pom.xml
docs/contributing.md
infra/docker/core/Dockerfile
infra/docker/core/Dockerfile.dev
infra/docker/serving/Dockerfile
infra/docker/serving/Dockerfile.dev
pom.xml

Upgrade Feast to next LTS - Java 11 - since Java 8 is outdated and no longer supported.
Our internal build and testing of Feast has been on Java 11 all along, so it's fair to say there shouldn't be any problems. I'm not able to fully test because 1) slight variation in base-images for building/packaging, 2) we use a different Dockerfile that uses pre-built Jars from another step rather than a 'builder' pattern
NONE
```release-note
Feast now requires a Java 11 runtime. JVM options should be set accordingly.
```

Upgrade to Java 11

---

.prow/config.yaml

Since https://github.com/gojek/feast/pull/451, the master branch is using Java 11 SDK for prow. However, this result in test breaking on branch 4.0, which is not compatible with Java 11.
This PR will add Java 8 prow jobs exclusively for branch 4.0.

Use Java 8 SDK for branch 3.0 / 4.0 and Java 11 for master

---

ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
protos/feast/storage/Redis.proto

Cherrypicking PR #380 into master since it got lost when moving to 0.4.
-
```release-note
NONE
```

Make redis key creation more determinisitic (#380)

---

CHANGELOG.md

This PR is required so that the change log is consistent with the commits on branch v0.4, after we move release tag v0.4.4 from master branch to v0.4 branch.
After this PR, the changeset here will be cherry pick back to v0.4 branch.

Update v0.4.4 changelog to be consistent with the release

---

serving/src/main/java/feast/serving/configuration/SpecServiceConfig.java

This PR reduces the amount of time Feast Serving waits before refreshing its cache of feature specifications from Feast Core. Ideally this would be configurable, but as a quick PR this reduces cache misses.

Reduce refresh rate of specification refresh in Serving to 10 seconds

---

core/src/main/java/feast/core/util/PipelineUtil.java
ingestion/src/test/java/feast/ingestion/ImportJobTest.java
pom.xml
serving/src/main/java/feast/serving/specs/CachedSpecService.java

Moves the `spotless:check` Maven goal to execute after tests compile, but before `test` executes the tests. This way the check will be run on CI, which runs `mvn test`, but it doesn't disrupt development flow by failing before compilation (like the `validate` phase would). This strikes a good compromise on failing fast for code standards without being _too_ nagging.
By default, the spotless plugin binds its check goal to the `verify` phase (late in the lifecycle, after integration tests). Because we currently only run `mvn test` for CI (and `package` with `-DskipTests` for E2E), it doesn't proceed as far as `verify` so changes that don't comply get merged. Then, when someone cleans up at a later date by running `spotless:apply` on their branch, [a …

Fail Spotless formatting check before tests execute

---

.prow/scripts/test-end-to-end-batch.sh
.prow/scripts/test-end-to-end.sh
sdk/python/setup.py

This fixes end to end batch test 
https://github.com/gojek/feast/pull/488#issuecomment-590223880
http://prow.feast.ai/view/gcs/feast-templocation-kf-feast/pr-logs/pull/gojek_feast/488/test-end-to-end-batch/1231860946993942532
```
NONE
```
```release-note
NONE
```
This PR also added debugging info of all Python packages version used during end to end test, when the test fails, to aid debugging failed tests.
**NOTE**   
Probably Feast Python SDK should be updated so it can work with `fastavro` version `0.22.10` and newer rather than fixing it to a specific version of fastavro?

Fix fastavro version used in Feast to avoid Timestamp delta error

---

ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java

Remove transaction from Ingestion

---

serving/src/main/java/feast/serving/service/RedisServingService.java
serving/src/main/java/feast/serving/util/Metrics.java

So that it is consistent with the actual unit of timing being measured.
And recommended metric names in Prometheus https://prometheus.io/docs/practices/naming/#metric-names
NONE
```release-note
NONE
```

Rename metric name for request latency in feast serving

---

core/pom.xml
pom.xml
serving/pom.xml

When starting serving or core (with info level logs) the following warning shows up:
> 2020-02-26 17:38:47,600 restartedMain INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
This PR adds the `log4j-web` jar as requested by this message. I don't believe there are any other implications, it is just to omit the warning.
Given the jar is ~[30K](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-web/2.13.0) I think this is harmless.
n/a
```release-note
NONE
```

Add log4j-web jar to core and serving

---

CHANGELOG.md

Update CHANGELOG for Feast v0.4.5 and v0.4.6
Fixes #
```release-note
```

Update CHANGELOG for v0.4.5 and v0.4.6

---

sdk/python/tests/conftest.py

Python tests involving the stub server currently get stuck on macOS with python version <3.8. This PR configures multiprocessing to use `spawn` for new processes on windows and macOS so that the python tests can run.
```release-note
NONE
```

Add configuration for multiprocessing for python tests

---

core/src/main/java/feast/core/model/Entity.java
core/src/main/java/feast/core/model/Feature.java
core/src/main/java/feast/core/model/FeatureSet.java
core/src/main/java/feast/core/model/Field.java
core/src/main/java/feast/core/model/FieldId.java
core/src/main/java/feast/core/model/Statistics.java
core/src/test/java/feast/core/service/SpecServiceTest.java

Adds the statistics object to the core data model. 
Additionally refactored `Field` to be individual, non `Embeddable` persistent entities, since they are uniquely identifiable. This allows other entities (like `statistics`) to be joined to feast entities and features. 
```release-note
action required: database migration required from previous versions
```

Add statistics to data model; Refactor fields to be individual entities

---

sdk/python/setup.py

- Relax `fastavro` version requirement in Feast Python SDK so we can get the latest `fastavro` updates and do not force users who already have newer versions of `fastavro` to downgrade, in order to install Feast Python SDK.
Recently, we fix to `fastavro==0.22.9` because `fastavro==0.22.10` uses its internal implementation to represent UTC timezone but it is not compatible with Pandas. `fastavro==0.22.11` reverts this to use `pytz` implementation which is compatible with Pandas.
https://github.com/fastavro/fastavro/pull/396
```
NONE
```
```release-note
NONE
```

Relax fastavro version requirement in Feast Python SDK

---

ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java

This PR addresses the stream feature validation milestone 1 https://docs.google.com/document/d/1TPmd7r4mniL9Y-V_glZaWNo5LMXLshEAUpYsohojZ-8/edit#heading=h.3tipf2ghulnf
where users can view historical histograms of the ingested feature values. Currently it is implemented by sending Gauge metrics with min.mean,max and various percentile values. This PR adds additional 25th and 99th percentile values, so **users will have better picture of the distribution of feature values.**
Related previous PR that adds the feature value metrics
https://github.com/gojek/feast/pull/486
NONE
```release-note
NONE
```

Send additional 25th and 99th percentile for feature value metrics in Feast ingestion 

---

datatypes/java/pom.xml
ingestion/pom.xml
pom.xml

Remove unused deps from Ingestion module, for the usual reasons of Good Housekeeping.
My path to this:
- We were notified by vulnerability scanning about [a `hibernate-validator` CVE][CVE] (though it doesn't relate to library functionality Feast has used)
- Turns out that was addressed for master by upgrade in #421, backported to v0.4 in #472 
- I wanted to backport it to v0.3 to quell our vulnerability warning
- Upon inspection, `javax.validation` is no longer used anywhere in Feast, there is no need for its API nor `hibernate-validator` as implementation.
[CVE]: https://nvd.nist.gov/vuln/detail/CVE-2019-10219
None
```release-note
NONE
```

Remove unused ingestion deps

---

infra/docker-compose/docker-compose.yml

Change to docker-compose.yml. 
As described in #484, there is an issue with Postgres not starting up when using the docker-compose.yml file for the first time since `POSTGRES_PASSWORD` is a required environment variable.
From what is written in the contributor guidelines we expect the password to be set to 'password':
```
docker run --name postgres --rm -it -d --net host -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres \
-e POSTGRES_PASSWORD=password postgres:12-alpine
```
For those who ran this docker command before, there might already be an initialized database available and so the current docker-compose file works fine. This change assures that it is also works when running for the first time using docker-compose.
**Which issue(s) this PR …

Fix docker-compose db environment

---

.prow/scripts/test-end-to-end-batch.sh
.prow/scripts/test-end-to-end.sh

Previosly e2e tests check that the system must be running Debian 9 (stretch) before proceeding. But this check may not be necessary as different Debian / Ubuntu versions may still run the e2e tests correctly. Also, the default Debian version used by jdk Docker image may change over time, and this check will prevent newer version of Docker image to pass.
Related to https://github.com/gojek/feast/pull/516
```release-note
NONE
```

Relax OS check when starting e2e test

---

core/src/main/java/feast/core/config/FeatureStreamConfig.java
core/src/main/java/feast/core/dao/FeatureSetRepository.java
core/src/main/java/feast/core/grpc/CoreServiceImpl.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/job/direct/DirectJobRegistry.java
core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
core/src/main/java/feast/core/log/AuditLogger.java
core/src/main/java/feast/core/model/FeatureSet.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/java/feast/core/service/SpecService.java
core/src/main/java/feast/core/util/PackageUtil.java
core/src/main/java/feast/core/util/TypeConversion.java
core/src/test/java/feast/core/service/SpecServiceTest.java
core/src/test/java/feast/core/validators/MatchersTest.java
ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
ingestion/src/test/java/feast/ingestion/ImportJobTest.java
ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
pom.xml
serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java

Backports #487 to `v0.3-branch`—as we are internally developing on this branch for the time being, we're trying to maintain formatting for the sake of easing reviews as intended, and also in hopes that it will ease cherry picks for back- and possible forward-porting since #487 keeps consistency.
I'll send one of these for `v0.4-branch` too, as we are edging closer to catching up to v0.4 🎉 
```release-note
NONE
```

v0.3 backport: Fail Spotless check before tests

---

core/src/main/java/feast/core/service/AccessManagementService.java

Listing projects is a read only operation and therefore should not need the `@Transactional` Hibernate annotation. 
Having `@Transactional` annotation results in excessive locks being used when listing projects because of the `INSERT` and `DELETE` queries generated. As a result, when other operations such as job updates (which is also `Transactional`) is running, users trying to list projects will often encounter GRPC error `TimeoutExceeded` because ListProjects will wait a long for the shared lock to be available.
When there is at least one feature set registered, these are the generated queries when listing projects:
[sql.with.transaction.log](https://github.com/gojek/feast/files/4304481/sql.with.transaction.log) …

Remove transaction when listing projects

---

core/src/main/java/feast/core/model/FeatureSet.java
core/src/main/java/feast/core/model/Field.java
core/src/test/java/feast/core/service/SpecServiceTest.java

FeatureSet should be updated by SpecService in Core when a new Feature/Entity spec with new constraints are applied. However, currently the `equality` comparison in `Field` class does not check for differences in constraints. This PR adds that additional checks.
```
NONE
```
```release-note
NONE
```

Update Field equality check so FeatureSet is updated when new Feature constraints are applied.

---

serving/src/main/java/feast/serving/controller/HealthServiceController.java
serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
serving/src/main/java/feast/serving/interceptors/GrpcMonitoringInterceptor.java
serving/src/main/java/feast/serving/service/BigQueryServingService.java
serving/src/main/java/feast/serving/service/RedisServingService.java
serving/src/main/java/feast/serving/util/Metrics.java

Feast Serving does not expose grpc prometheus metrics.
None
Fixes #
None
```release-note
gRPC calls in feast serving now exposes prometheus metrics.
```

Add Feast Serving gRPC call metrics

---

datatypes/java/pom.xml
ingestion/pom.xml
pom.xml

Backports #520 to `v0.3-branch`—as noted on #520, this is to alleviate a vulnerability warning for the version of `hibernate-validator` in this maintenance branch, though in fact the dependency is unused so can be removed entirely.
```release-note
NONE
```

v0.3 backport: Remove unused ingestion deps

---

ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java

By making the sleep duration for the thread listening for UDP messages shorter than the thread delivering the UDP messages.
This seems to make the test passes more deterministically.
If this value is higher than the one used for sending output (50ms) some messages are sometimes lost leading to failed (flaky) test. 
> I'm not sure why yet
Fixes #
```release-note
```

Fix flaky test WriteFeatureValueMetricsDoFnTest

---

infra/docker/core/Dockerfile
infra/docker/serving/Dockerfile
infra/docker/serving/Dockerfile.dev

- Fix [error](http://prow.feast.ai/view/gcs/feast-templocation-kf-feast/logs/publish-docker-images/1238743096720625664) when building Feast Serving Docker image due to non-existent base Docker image: `openjdk:11-jre-alpine`. Updated to [`openjdk:11-jre-slim`](https://hub.docker.com/layers/openjdk/library/openjdk/11-jre-slim/images/sha256-88d4192a5dab8de64fbeec699bcea3739f097f78f3184cd4e2aea6d7ac238da7?context=explore)
```
Step 7/11 : FROM openjdk:11-jre-alpine as production
manifest for openjdk:11-jre-alpine not found
```
- Add `clean` phase before `package` phase for more deterministic build (in case host directory is dirty)
- Move the downloading of `grpc-health-probe` in Feast Serving to build stage so the production stage does not need extra …

Update base Docker image for building Feast Serving image

---

.prow/scripts/test-end-to-end-batch.sh
.prow/scripts/test-end-to-end.sh
ingestion/pom.xml
ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java
ingestion/src/main/java/feast/store/serving/redis/RedisIngestionClient.java
ingestion/src/main/java/feast/store/serving/redis/RedisStandaloneIngestionClient.java
ingestion/src/test/java/feast/ingestion/ImportJobTest.java
ingestion/src/test/java/feast/store/serving/redis/RedisCustomIOTest.java
serving/pom.xml
serving/src/main/java/feast/serving/configuration/JobServiceConfig.java
serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
serving/src/main/java/feast/serving/configuration/SpecServiceConfig.java
serving/src/main/java/feast/serving/configuration/StoreConfiguration.java
serving/src/main/java/feast/serving/configuration/redis/JobStoreRedisConfig.java
serving/src/main/java/feast/serving/configuration/redis/ServingStoreRedisConfig.java
serving/src/main/java/feast/serving/service/RedisBackedJobService.java
serving/src/main/java/feast/serving/service/RedisServingService.java
serving/src/test/java/feast/serving/service/RedisBackedJobServiceTest.java
serving/src/test/java/feast/serving/service/RedisServingServiceTest.java

Replacing Jedis With Lettuce in ingestion and serving (#485)

---

ingestion/src/main/java/feast/store/serving/redis/RedisStandaloneIngestionClient.java

[Bug] Clear all the futures when sync is called. (#501)

---

sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/config.py
sdk/python/feast/constants.py
sdk/python/tests/test_client.py
sdk/python/tests/test_config.py

The original implementation of configuration loading in the Feast SDK and CLI had a few problems
1. Logic was scattered over client.py, config.py, and cli.py and was overly verbose. 
2. No clear definition of available keys and default options
3. No centralized loader that takes config option precedence into account (initialized, env, file, default)
4. No type casting (int, bool, float)
This PR cleans up the configuration and adds the above functionality.
```release-note
None
```

Refactor Feast CLI/SDK configuration

---

serving/src/main/java/feast/serving/service/RedisServingService.java
serving/src/test/java/feast/serving/service/RedisServingServiceTest.java

#485 introduce a bug, in which Exception is thrown when feature is not found on Redis. This bug is not caught because the corresponding test was not mocked correctly.
Fixes #
This PR is require to prevent Feast serving from throwing exception to the user when key is not found.

Serving should not throw exception when key not found in Redis

---

infra/charts/feast/values.yaml

The image tag values weren't updated since v0.4.5. As a result, if the user does not explicitly overwrite the image tag version in helm values, the old version of Feast is still going to be installed.
Fixes #
```release-note
```

Fix helm chart image tag default value

---

core/src/main/java/feast/core/model/Job.java

With a large amount of feature sets and jobs, any operation on the jobs table takes a ridiculous amount of time - due to the fact that the join table is not indexed, resulting in very long JobCoordinator `poll()` calls. This PR specifies indexes for the two columns in the join table, which should speed up queries.
Tested locally and this should be an automatic upgrade. No migration is required.
```release-note
NONE
```

Add index for join table for jobs-featuresets relation

---

core/src/main/java/feast/core/config/FeastProperties.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/resources/application.yml
infra/scripts/test-end-to-end-batch.sh
infra/scripts/test-end-to-end.sh

Adds config option for JobCoodinator polling interval, and shortens the interval for e2e tests to reduce flakiness of those tests.
Fixes #531
```release-note
Adds new configuration option feast.jobs.updates.pollingIntervalMillis
```

Add pollingInterval config option

---

core/src/main/java/feast/core/job/JobUpdateTask.java
core/src/main/java/feast/core/job/Runner.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/model/Job.java
core/src/test/java/feast/core/job/JobUpdateTaskTest.java
core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java

- Fixes the inconsistency of converting `Runner` to string when assigning to `Job.runner` by converting all to use `Runner.name()`.
- Changes `Runner.toString()` to return a human readable string.
- Changes all uses of `Runner.getName()` for all non `Job.runner` applications (ie logging, config file) to use `Runner.toString()`
- Removes `Runner.getName()`
This is necessary to standardise the use of Runner.name() when
passing to the Job.runner, so that code depending on Job.runner
would know what to expect. 
Fixes #574 
```release-note
NONE
```

Fix runner to string inconsistency

---

core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java

Fixes [Bug](https://github.com/gojek/feast/blob/901e260477d6e2b3ccb1bbbe43cd9553cf7a3ad9/core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java#L194) caused by `toString()` method being used in the conversion lambda used to convert from FeatureSet protos to FeatureSet models instead of the `getName()` method.
Since the conversion lambda duplicates functionality already implemented  by `FeatureSet.fromProto()`, removing the lambda block in favor using the method to do the conversion.
Fixes #577 
```release-note
NONE
```

Fixed bug in featurset proto to model conversion in DataflowJobManager

---

ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java

If an incoming feature row contains entities not defined in the spec, the `FeatureRowToRedisMutationDoFn` throws a null pointer exception:
```
java.lang.NullPointerException
at feast.storage.RedisProto$RedisKey$Builder.addEntities (RedisProto.java:882)
at feast.store.serving.redis.FeatureRowToRedisMutationDoFn.getKey (FeatureRowToRedisMutationDoFn.java:65)
at feast.store.serving.redis.FeatureRowToRedisMutationDoFn.processElement (FeatureRowToRedisMutationDoFn.java:106)
at feast.store.serving.redis.FeatureRowToRedisMutationDoFn$DoFnInvoker.invokeProcessElement ...
```
```release-note
NONE
```

Fix for extra keys throwing an error when converting to RedisMutation

---

datatypes/java/pom.xml
docs/contributing/development-guide.md
ingestion/pom.xml
ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
pom.xml

This is a PoC for the idea in #517 that Ingestion could be easily built for Java 8 while other components continue to target 11.
```
$ mvn clean compile
$ javap -v ingestion/target/classes/feast/ingestion/ImportJob.class | grep major
major version: 52
$ javap -v serving/target/classes/feast/serving/ServingApplication.class | grep major
major version: 55
```
Addresses #517, speculatively and not completely.
```release-note
Feast Ingestion is again built for Java 8, for more certain Beam runner compatibility.
```

Enforce JDK 11 for development, but build Ingestion to target Java 8

---

sdk/python/feast/__init__.py

This fixes a bug (reverts it to a previous state) where it isn't possible to import Feast classes directly like this
```
from feast import Client
```
instead, the user has to do this
```
from feast.client import Client
```
This currently breaks our notebooks.
```release-note
NONE
```

Add __all__ exports to Python SDK

---

core/src/main/java/feast/core/service/SpecService.java
core/src/test/java/feast/core/service/SpecServiceTest.java

Allow create_project to rerun safely #453. Instead of having to run `create_project` before apply, the apply method can create the project if it does not already exist.
Fixes #453 
```release-note
When applying a featureSet to a project that does not yet exist, Feast create the project on apply.
```

Create project if not exists on applyFeatureSet

---

Makefile

Fixes documentation building for docs.feast.dev
None
```release-note
NONE
```

Fix doc building

---

serving/pom.xml
storage/connectors/bigquery/pom.xml

Doesn't exactly solve the issue where the bigquery connector as a whole depends on `beam-sdks-java-io-google-cloud-platform`, which Serving therefore transitively depends on, but removes the offending packages within `beam-sdks-java-io-google-cloud-platform`  it so that the bigquery connector can be imported wholesale by Serving without any dependency clashes.
I've considered removing `beam-sdks-java-io-google-cloud-platform` from the bigquery connector entirely, and implementing a custom write transform, but for it to retain the same level of reliability as the existing `BigQueryIO` would require quite significant dev effort.

Remove exclusions from serving

---

serving/src/main/java/feast/serving/service/OnlineServingService.java
serving/src/main/java/feast/serving/util/Metrics.java
serving/src/main/java/feast/serving/util/RefUtil.java
storage/api/src/main/java/feast/storage/api/retrieval/FeatureSetRequest.java

Additional tweaks to the Storage Refactor PR #567. Addresses @ches 's comments to the PR.

Clean up OnlineServingService code

---

Makefile
infra/docker/ci/Dockerfile

Backports changes to Makefile for docker building and pushing. Also adds version of CI image for jdk8.

Add CI docker image for jdk8, backport changes to Makefile

---

core/src/main/java/feast/core/dao/JobRepository.java
core/src/main/java/feast/core/grpc/CoreServiceImpl.java
core/src/main/java/feast/core/job/JobManager.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
core/src/main/java/feast/core/model/Job.java
core/src/main/java/feast/core/model/JobStatus.java
core/src/main/java/feast/core/service/JobService.java
core/src/test/java/feast/core/service/JobServiceTest.java
protos/feast/core/CoreService.proto
protos/feast/core/FeatureSetReference.proto
protos/feast/core/IngestionJob.proto
sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/feature_set.py
sdk/python/feast/job.py
sdk/python/tests/test_client.py
sdk/python/tests/test_feature_set.py
tests/e2e/basic-ingest-redis-serving.py

Add Ingestion Job management API for Feast Core (#548)

---

sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/feature_set.py
sdk/python/feast/job.py
sdk/python/tests/test_client.py
sdk/python/tests/test_feature_set.py
serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
serving/src/main/java/feast/serving/specs/CachedSpecService.java

Notifies the user with a human readable error when the user attempts to retrieve  
(both online/batch) feature data from feast serving with an feature reference does not match any feature stored in feast.
- currently the error that the user will see is:
```
InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNKNOWN
details = ""
debug_error_string = "{"created":"@1580607090.708289999","description":"Error received from peer ipv4:172.28.0.8:6566","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"","grpc_status":2}"
>
```
- this PR replaces the the error with something more user friendly:
```
grpc.RpcError: Unable to find feature set for feature ref: (project: s, name: s, version: 1, max_age: ) …
```

Make error on retrieval of nonexistent feature humanly readable

---

serving/src/main/java/feast/serving/config/FeastProperties.java

#525 has caused some inconsistencies with e2e tests. I believe it was merged without proper e2e tests running.
This PR attempts fix to inconsistencies.
* Subscriptions configuration isn't loading because the configuration class isn't static.
* JavaDocs are broken (bad links)
```release-note
None
```

Fix subscription config and doctests

---

serving/src/main/java/feast/serving/specs/CachedSpecService.java
serving/src/main/java/feast/serving/specs/CoreSpecService.java
serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java

Fixes Feast Serving not registering its store into Feast Core.
- Adds `registerSource()` to `CoreSpecService` to register source spec in in Feast Core.
- Adds missing `registerSource()` call in `CachedSpecService` to register its store in Feast Core.
- Adds a unit test to ensure that cached spec service registers its store with Feast Core.
Fixes #640 
```release-note
NONE
```

Fix Feast Serving not registering its store in Feast Core

---

serving/src/main/resources/application.yml
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retriever/BigQueryHistoricalRetriever.java

Running feast serving with bigquery as a backend throws the following exception:
```
Failed to instantiate [feast.serving.specs.CachedSpecService]: Factory method 'specService' threw exception; nested exception is com.google.protobuf.InvalidProtocolBufferException: Cannot find field: staging-location in message feast.core.Store.BigQueryConfig
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584)
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:3 …
```

Fix bigquery config for serving store

---

infra/scripts/test-end-to-end-batch.sh
infra/scripts/test-end-to-end.sh

Fixes end to end test scripts to use config introduced by #611

Update end-to-end test config

---

core/src/main/java/feast/core/model/Job.java

Backport the fix for #566, which was already backported earlier.

Backport #647 to v0.4

---

core/src/main/java/feast/core/job/JobUpdateTask.java
core/src/main/java/feast/core/job/Runner.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/model/Job.java
core/src/main/java/feast/core/service/JobService.java
core/src/test/java/feast/core/job/JobUpdateTaskTest.java
core/src/test/java/feast/core/job/RunnerTest.java
core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
core/src/test/java/feast/core/service/JobServiceTest.java

This is refactoring aiming to remove a burden on the programmer to get something right.
#575 sought to clear up inconsistencies between uses of `Runner#name()` (the standard final method of `java.lang.Enum` that returns the value's enum constant name) and the riskily-named `Runner#getName()` defined in Feast for human-readable Beam Runner names.
The latter is used as runner name users can set in config (now as `Runner#toString` since #575). The former is used for values of the runner column of the jobs table in SQL (as it should be). But it relied on careful coding to use the right one when constructing `Job` instances. This is error prone, as #578 demonstrates.
There is a more robust way: use the enum instead of stringly-typed programming. It's one …

core: Use Runner enum type instead of string for Job model

---

ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFailureMetricsTransform.java

Fixes bug as described in #642 . If no metrics output is configured, `WriteFailureMetricsTransform` is a transform with no nodes, which is probably why it throws the error. Added a noop DoFn. Tested this fix locally (with dataflow) and it works.
Fixes #642 
```release-note
NONE
```

Fix Dataflow translator bug

---

core/src/main/java/feast/core/model/JobInfo.java

The indexes added in #566 are an important fix. They weren't backported for v0.3 yet, so this does that in one combined commit of #566 and its bug fix #647. 
The inverse join column name in v0.3 was `feature_set_id`, not `feature_sets_id` (which is a bit weird honestly and it was either a breaking change for v0.4 when projects were added, or backporting it to v0.4 was actually a breaking change mid-v0.4, I'm not sure which yet—see the blame walk below).
I've preserved `feature_set_id` so this is not a breaking change for v0.3.
Walking the blames of `feature_sets_id`:
- https://github.com/gojek/feast/commit/fdd7291e9e81c57f357d59c1efb50beeffad5640
- https://github.com/gojek/feast/pull/393/files#diff-23d202566aa4be59004b3892de68f7d3
- …

Backport #566 & #647 to v0.3

---

.github/workflows/unit-tests.yml

Upgrade github checkout action to v2 from v1, as the v1 api might result in intermittent error as described in https://github.com/actions/checkout/issues/23.

Upgrade github checkout action to v2

---

infra/scripts/test-end-to-end-redis-cluster.sh

Fixes end to end test scripts to use config introduced by #502 
```release-note
NONE
```

Fix redis cluster e2e

---

infra/docker-compose/docker-compose.yml

* ~Change docker compose file to use host based. This avoids having an inconsistency between default configuration and docker compose configuration.~
* Fix bug with application.yml typo
* Fix port configuration bug for postgres
Hopefully fixes all bugs in #652, but more changes are required to close the issue
```release-note
None
```

Docker compose bug fix 

---

core/src/main/java/feast/core/config/FeastProperties.java

Current validation rule for `feast.jobs.metrics.host` will fail when specifying a valid hostname for StatsD Server because it expects a [URL](https://en.wikipedia.org/wiki/URL).
`feast.jobs.metrics.host` is used to connect to a metrics server e.g StatsD Server. 
To support more variety of metrics server (which may work at TCP or UDP layer) `host` value
should probably be just a DNS hostname or IP address, e.g. `10.23.40.1` or `localhost` as opposed to `http://10.23.40.1`. The latter for instance cannot be used as an argument to connect to StatsD UDP server.
> Another option is to include additional field like `protocol` when specifying the target for metrics server.
NA
**Does this PR introduce a user-facing …

Fix config validation for feast.jobs.metrics.host

---

core/src/main/java/feast/core/job/JobUpdateTask.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
core/src/main/java/feast/core/model/Job.java
core/src/main/java/feast/core/model/JobStatus.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/java/feast/core/service/JobService.java
core/src/test/java/feast/core/job/JobUpdateTaskTest.java
core/src/test/java/feast/core/model/JobStatusTest.java
core/src/test/java/feast/core/service/JobServiceTest.java

Cleanup, this is purely refactoring aiming to make code easier to read, understand, and modify.
I've been doing some work—and reviews of work—around this code, and found it a bit hard to follow and work with. This is my attempt at improving that.
This PR is meant to be reviewed commit-by-commit, it should hopefully make sense quickly that way. Tests are untouched until the final commit and should pass at every step.
I have a question or two though that I'll ask inline, so I'm marking this WIP, I may update a bit more based on the answers, especially docstrings where warranted.
No issue
```release-note
NONE
```

JobUpdateTask cleanups

---

.prow/plugins.yaml

Prevents a PR from merging without a `kind/` label. These labels will be used for generating changelogs.
Related to #476

Add label checking to Prow

---

.prow/config.yaml

Just enabled e2e tests by default.

Enable Prow e2e tests by default

---

protos/feast/core/FeatureSet.proto

See #667—the motivation is reserving the lower-numbered fields for optimal encoding. Might be a premature optimization given `FeatureSpec` is not a high-throughput message, but the cost of change is practically nothing.
Fixes #667 
References #536 where the `labels` field number has changed from 19 to 16. Could just keep it at 19, but meh, unless anyone chimes in that they run Feast master in production and started using this since it was merged yesterday 😇 
Since there has been no Feast release with these new fields yet, renumbering is not breaking.
```release-note
NONE
```
**Acknowledgments**
I would like to thank Vim, `27<C-a>` and the `.` operator for assistance …

Move TFDV stats to higher-numbered protobuf fields

---

CHANGELOG.md
infra/scripts/test-end-to-end-batch.sh
infra/scripts/test-end-to-end.sh
pom.xml

Releases v0.3.7. I am not sure how much we need this release, but the point is to test out the release process as a wet run of #476.

Release v0.3.7

---

infra/scripts/test-end-to-end-batch.sh
infra/scripts/test-end-to-end-redis-cluster.sh
infra/scripts/test-end-to-end.sh

Allows us to test non-snapshot releases `x.y.z` instead of `x.y.z-SNAPSHOT`. Scripts will get the build version from the root pom.xml. I see a `JAR_VERSION_SUFFIX` but it doesnt seem to be used. 
```release-note
NONE
```

Update e2e tests to allow non-SNAPSHOT testing

---

protos/feast/core/Store.proto
protos/feast/types/FeatureRow.proto
sdk/python/feast/client.py
sdk/python/feast/loaders/ingest.py
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryFeatureSink.java
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureRowToTableRow.java

This is a split-off off #612 that introduces the model changes made in that PR in a more digestible chunk.
Adds a unique identifier for all discrete batch loads of data into feast for re-referencing the set of data later on.
```release-note
Adds dataset_id field into BQ
```

Add unique ingestion id for all batch ingestions

---

.gitignore
.prow/config.yaml

In https://github.com/gojek/feast/pull/545/files, generated python codes are no longer version controlled. Instead, the code are generated prior to Python unit tests.
However, the publish python sdk script does not include this step. As a result the published artifact does not contain the generated code.
In addition, https://github.com/gojek/feast/blob/master/sdk/python/setup.py#L70 will not be able to find the generated modules, as __init__.py is not auto generated.
Publish Python SDK should work as intended after this fix.
```release-note
```

Ensure that generated python code are considered as module

---

tests/e2e/all_types_parquet/all_types_parquet.yaml

The typo in the e2e test feature set yaml cause the feature set to be registered incorrectly, which is the likely reason as to why the e2e test failed in https://github.com/gojek/feast/pull/676.

Fix typo in all types parquet yml file (e2e test)

---

core/src/main/resources/application.yml
infra/docker-compose/docker-compose.dev.yml
infra/docker/core/Dockerfile.debug

**What this PR does / why we need it**: Simple dev workflow enhancement to allow running core with its dependent services.  In the future, I hope to make this debuggable.
I'm open to changing it the PR as it stands was expecting:
1. make changes (IDE would likely incremental compile)
2. docker-compose up would compile as necessary and run
3. manual testing whatever
4. shut down and repeat
I haven't yet built a whole dev workflow, so there may be an alternative that is better.  One idea from @mrzzy is to keep the code container with just a shell running and use `docker exec` to run `mvn` or other commands.
Eventually I would like a whole debugging setup but this seemed worthwhile as a separate PR.
**Which issue(s) this PR fixes**:  N/A …

Add Docker Compose configuration for development purposes

---

tests/e2e/basic-ingest-redis-serving.py

To make e2e tests more reliable.
Fixes #677 
No

Remove force update flag from e2e test

---

.prow/config.yaml

Fixes bugs introduced by #675 .
- Points prow job for e2e dataflow test to use the correct config files.
- Removes typo that causes docker image creation to fail for prow presubmit job.
```release-note
NONE
```

Dataflow e2e test fixes

---

infra/charts/feast/charts/feast-core/README.md
infra/charts/feast/charts/feast-core/templates/configmap.yaml
infra/charts/feast/charts/feast-core/values.yaml
infra/charts/feast/charts/feast-serving/templates/configmap.yaml
infra/charts/feast/charts/feast-serving/values.yaml

By default, Feast serving is listening on port 8081 for http end points. That includes prometheus metrics. The default helm values for Feast Serving targeted port is 8080, which cause Prometheus to scrape the wrong end point.
This PR makes the generated application.yml file override the default http port based on the provided helm values.
Fixes #
```release-note
```

Include server port config on the generated application.yml

---

.prow/config.yaml
infra/docker/core/Dockerfile

The docker build process for Feast Core is currently broken. Eg. http://prow.feast.ai/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gcs%2Ffeast-templocation-kf-feast%2Flogs%2Fpublish-docker-images%2F1260750880961990656%22%7D&topURL=http%3A//prow.feast.ai/view/gcs/feast-templocation-kf-feast/logs/publish-docker-images/1260750880961990656&lensIndex=1#build-log.txt:3250
The root cause is due to wget not being available in maven slim docker image.
We can either use the non-slim variant, which is the approach taken by Feast Serving, or install wget as part of the build step. For this PR, i chose the former.
There is also another problem where the publish docker image (pre-submit) is …

Fix Feast Core docker image

---

.prow/config.yaml
infra/scripts/test-end-to-end-batch.sh
tests/e2e/bq-batch-retrieval.py

The tests take too long, and timeout frequently because the bq streaming cache refresh doesn't happen within a deterministic amount of time.
The tests can still be run locally if the functionality needs to be tested.
Fixes #
```release-note
```

Extract fs update tests so ci doesn't run it

---

infra/scripts/test-end-to-end-batch-dataflow.sh
infra/scripts/test-end-to-end-batch.sh
tests/e2e/bq-batch-retrieval.py

Also added some time buffer for the batch retrieval file tests so we're not at the mercy of float rounding when converting between df and file.
Fixes #702 
```release-note
```

Ensure that batch retrieval tests clean up after themselves

---

core/src/main/java/feast/core/job/JobUpdateTask.java

Currently, a job is deemed to require update if one or more associated feature set is in pending state. This leads to infinite loop in which the job manager keep updating existing task but the job status never becomes successful:
1. New feature set is created, and status is pending.
2. Job submitted.
3. In the next job polling, requireUpdate is called, and return true because status of the feature set is pending.
4. Dataflow job is updated, eventhough it's not supposed to.
5. Job status update is skipped.
Feature set equality check should have sufficed to determine if a job requires update.
Fixes #
```release-note
```

Remove feature set status check for job update requirement

---

.dockerignore
.github/workflows/unit_tests.yml
Makefile
core/pom.xml
docs/coverage/java/pom.xml
ingestion/pom.xml
pom.xml
sdk/java/pom.xml
serving/pom.xml
storage/connectors/pom.xml

I'm interested in tracking coverage data. I thought you might be too.
This adds [the JaCoCo Maven plugin][2], with a module dedicated to reporting aggregate coverage, which is said to be [the most reliable way to achieve that][1]. It is currently under `docs/coverage/java` as a tidy place to tuck it away, but GitBook might barf on a `pom.xml` being in there, not sure, so I'll move it if you suggest someplace else.
We use Codecov privately, it should slurp up JaCoCo data readily if you're interested in setting it up, and/or I can look into adding a GitHub Action with JaCoCo's stock HTML report kept as an artifact.
I don't have convenient access to a public web host at the moment to drop the static browseable report as an example, so here's a …

Add Java code coverage reporting

---

core/src/main/java/feast/core/job/JobUpdateTask.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
protos/feast/core/FeatureSet.proto

Removal of PENDING status check in #708 causes jobs to be unable to track feature set updates.
This PR adds a new status STATUS_JOB_STARTING to denote that a feature set was updated, but a job has already been initialised, preventing the JobCoordinator from spinning up new jobs in its place.
Fixes #
```release-note
```

Add feature set status JOB_STARTING to denote feature sets waiting for job to get to RUNNING state

---

core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
core/src/main/java/feast/core/model/Project.java
ingestion/src/main/java/feast/ingestion/ImportJob.java
ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
ingestion/src/main/java/feast/ingestion/transform/ProcessAndValidateFeatureRows.java
ingestion/src/main/java/feast/ingestion/transform/fn/ProcessFeatureRowDoFn.java
ingestion/src/test/java/feast/ingestion/ImportJobTest.java
ingestion/src/test/java/feast/ingestion/transform/ProcessAndValidateFeatureRowsTest.java

Extension to #693. Feast Core deploys Feast ingestion jobs with a parameter that sets its default project. This default project is just a string (using “default” for now).
When a FeatureRow is read from Kafka with with a complete feature set reference (`project/feature_set`) then it is processed as normal. However, when a FeatureRow is read in with a feature set reference missing project (just `featureset`), then Feast Ingestion prepends the default project string to this reference.
```release-note
Feature rows can be ingested with just the feature set name. Feast core will apply the default project to those feature rows.
```

Apply default project to rows without project during ingestion

---

sdk/python/feast/cli.py
sdk/python/feast/client.py

Fixes:
1. `feast feature-sets list` properly lists all feature sets
2. `client.apply()` doesn't demand for project to be set. Setting of default is deferred to the server.

Python sdk bug fixes

---

tests/e2e/basic-ingest-redis-serving.py

The Docker Compose tests have been failing sparingly but in a non-deterministic manner, due to timeout errors, [here](https://github.com/feast-dev/feast/runs/684970318?check_suite_focus=true#step:3:469) is an example of the latest of such failure.
NA
```release-note
NONE
```

Increase Docker Compose test timeout

---

.prow/config.yaml
infra/scripts/test-end-to-end-batch-dataflow.sh
infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml

**What this PR does / why we need it**: 
Currently, dataflow tests are broken. They also was meant to create k8s cluster & install all dependencies (kafka, postgres, redis) for each run, which would significantly increase running time. I propose to create cluster once. I also separated rollout of dependencies' containers from feast containers.
**Which issue(s) this PR fixes**: broken tests on dataflow / long running tests
Fixes #
```release-note
```

Rework test-runner for e2e on dataflow w/ reusing existing infrastructure (installed kafka, redis, etc)

---

core/pom.xml
pom.xml
serving/pom.xml

Removes an unused dependency. Just a little housekeeping noticed in the context of something related. Core and Serving were using different versions of Hibernate, which I first wanted to align, then thought to myself, "wait, how does Serving use Hibernate?"
Maybe someone knows the background of what "Hibernate for formatting SQL string" meant, but grepping/`mvn dependency:analyze`/building suggests it is indeed unused.
No issue
```release-note
NONE
```

Remove unused Hibernate dep from Serving

---

core/pom.xml
datatypes/java/pom.xml
ingestion/pom.xml
pom.xml
sdk/java/pom.xml
sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
serving/pom.xml
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisOnlineRetrieverTest.java
storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterCustomIO.java
storage/connectors/rediscluster/src/test/java/feast/storage/connectors/rediscluster/retriever/RedisClusterOnlineRetrieverTest.java

Restores Feast Ingestion compatibility with Java 8 runtimes.
With the addition of the Storage APIs and connector implementations, we did not specify that their build should target Java 8 bytecode. Because Ingestion depends on them and bundles them in an uber jar, we regressed on keeping Ingestion compatible with Java 8 runtimes according to #518.
This could be confirmed prior to this change on master with, for example:
$ mvn -pl ingestion clean compile
$ javap -v storage/connectors/redis/target/classes/feast/storage/connectors/redis/writer/RedisCustomIO.class | grep major
major version: 55
I take this as proof that a blacklist approach with 11 as the default in our root POM is error prone, so this change flips it so that 8 is default and our leaf …

Restore Feast Java SDK and Ingestion compatibility with Java 8 runtimes

---

.dockerignore
.github/workflows/unit-tests.yaml
Makefile
core/pom.xml
docs/coverage/java/pom.xml
ingestion/pom.xml
pom.xml
sdk/java/pom.xml
serving/pom.xml

Backports #686 to `v0.4-branch`, for completeness with #734 doing v0.3.
```release-note
NONE
```

v0.4 backport: Add Java coverage reporting

---

.github/CODEOWNERS
OWNERS

Remove inactive reviewers, so contributors following what the Prow bot instructs them to do are likely to get appropriate attention.
Let me know if there is anything that should be changed. Added myself to reviewers, and ran `:sort` so pardon the diff being a little noisy.
```release-note
NONE
```

Update owners for Prow / GitHub

---

.dockerignore
Makefile
core/pom.xml
docs/coverage/java/pom.xml
infra/docker/core/Dockerfile
infra/docker/serving/Dockerfile
ingestion/pom.xml
pom.xml
sdk/java/pom.xml
serving/pom.xml

Backports #686 to `v0.3-branch`. Also backports #410, which was a final missing piece for v0.3 after #407—this fixes the Prow job for `publish-docker-images` on the branch.
I have possibly a few of these housekeeping-ish things that I want to bring in internally, and as much as possible / whenever valuable for mainline Feast I'm trying to do things as *upstream master => upstream backport => bring backport in-house*. If PR reviews and so forth become a burden though, if you aren't supporting any v0.3 deployments yourselves anymore, I'm happy for us to "formally" take ownership of the maintenance branch in whatever ways make sense.
```release-note
NONE
```

v0.3 backport: Add Java coverage reporting

---

core/pom.xml
datatypes/java/pom.xml
ingestion/pom.xml
pom.xml
sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
serving/pom.xml
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisOnlineRetrieverTest.java
storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterCustomIO.java
storage/connectors/rediscluster/src/test/java/feast/storage/connectors/rediscluster/retriever/RedisClusterOnlineRetrieverTest.java

Backports #722 to v0.5.
```release-note
- Restores Feast Ingestion compatibility with Java 8 runtimes
- Restores Feast Java SDK compatibility with Java 8 runtimes
```

v0.5 backport: Restore SDK and Ingestion compatibility with Java 8 runtimes

---

infra/docker-compose/.env.sample
infra/docker-compose/core/core.yml
infra/docker-compose/serving/batch-serving.yml

Fix Docker Compose Batch Serving setup:
- Fixed Batch Serving gRPC listening on wrong port (6566 instead of 6567)
- Fixed `active-store` typo in `batch-serving.yml` config: should be `historical` instead of `batch`.
- Fixed issue where external Feast Clients (ie not inside docker network) could not access Kafka

Fix Docker Compose Batch Serving

---

serving/src/main/java/feast/serving/service/OnlineServingService.java

Feaute value map is not thread safe. Using parallel stream here can leads to racing condition, which results in incorrect feature value map being computed.
```release-note
Fix the bug where feature value map is generated incorrectly intermittently due to racing condition, when the feature is stale.
```

Remove usage of parallel stream for feature value map generation

---

serving/src/main/java/feast/serving/service/OnlineServingService.java

This is to backport PR-751 to v0.5.

Remove usage of parallel stream for feature value map generation (#751)

---

sdk/go/client.go
sdk/go/types.go
sdk/java/src/main/java/com/gojek/feast/FeastClient.java
sdk/java/src/main/java/com/gojek/feast/Row.java
sdk/python/tests/test_feature.py

This is a split off containing solely the bug fixes of PR #720 
Fixes SDK bugs introduced in PR #693 & #700 
- Go SDK crashes due to trying to add to a `nil` map. (PR #693 ).
- Go SDK obmitted entity values when in values returned from `GetOnlineFeatures()` (PR #693 )
- Java SDK's `Row.set()` rejects `feast.proto.types.ValueProto.Value` as its hardcoded class path to `feast.types.ValueProto.Value`.( PR #700 )
```release-note
Fixed Go SDK error due to trying to add to a nil map.
Fixed Go SDK omitted entity values when get online features.
Fixed Java SDK's Row.set() does not accept feast Value type
```

Fix Go and Java SDK Regressions

---

sdk/python/feast/cli.py

`feast feature-sets describe <name>` cannot be used because it doesn't allow the user to set a project, nor does it default to any value.
Fixes #727 
```release-note
Users can now pass in --project parameter to retrieve information about a feature set using cli.
```

Fix project argument for feature set describe in CLI

---

infra/scripts/setup-common-functions.sh
infra/scripts/test-end-to-end-batch.sh
infra/scripts/test-end-to-end-redis-cluster.sh
infra/scripts/test-end-to-end.sh

Housekeeping of e2e tests. Refactoring to reduce duplication of scripts.
```release-note
NONE
```

Refactor end-to-end tests to reduce duplication

---

core/src/main/java/feast/core/grpc/CoreServiceImpl.java
sdk/python/feast/client.py
tests/e2e/basic-ingest-redis-serving.py

Currently the Python SDK's `version()` method doesn't work because it remains unimplemented in Feast Core. This PR allows versions to be returned to the client.
```release-note
Retrieving the version of Feast Core is now supported and available through the Python SDK
```

Add support for version method in Feast SDK and Core

---

core/src/main/java/feast/core/config/FeastProperties.java
core/src/main/java/feast/core/config/JobConfig.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
core/src/main/java/feast/core/job/direct/DirectRunnerConfig.java
core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
core/src/main/java/feast/core/job/option/RunnerConfig.java
core/src/main/java/feast/core/util/TypeConversion.java
core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
core/src/test/java/feast/core/util/TypeConversionTest.java
protos/feast/core/Runner.proto

Adds option of setting labels for dataflow jobs, and cleans up the job configuration code a bit, also ties the runner configuration classes to the protos. Both runners extend the `RunnerConfig` class which support conversion of the config fields to beam args.

Refactor runner configuration, add labels to dataflow options

---

serving/src/main/java/feast/serving/service/OnlineServingService.java

Helps us to debug performance bottle neck for Online Retrieval.
```release-note
NONE
```

Increase Jaeger Tracing coverage

---

core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
core/src/main/java/feast/core/job/direct/DirectRunnerConfig.java
core/src/main/java/feast/core/job/option/RunnerConfig.java
core/src/test/java/feast/core/job/dataflow/DataflowRunnerConfigTest.java
core/src/test/java/feast/core/job/direct/DirectRunnerConfigTest.java

#718 broke the pipeline options - for `getFields()` to work, fields must be public-access. As a result the `toArgs()` method was returning an empty list.
Added some tests to avoid such careless mistakes from being merged into master again.

Fix pipeline options toArgs() returning empty list

---

serving/src/main/java/feast/serving/service/OnlineServingService.java

Increase Jaeger Tracing coverage (#719)

---

CHANGELOG.md
infra/charts/feast/Chart.yaml
infra/charts/feast/README.md
infra/charts/feast/charts/feast-core/Chart.yaml
infra/charts/feast/charts/feast-core/README.md
infra/charts/feast/charts/feast-serving/Chart.yaml
infra/charts/feast/charts/feast-serving/README.md
infra/charts/feast/requirements.lock
infra/charts/feast/requirements.yaml
pom.xml

The following has been updated in preparation for release 0.5.1:
1. Helm chart version and default image tag
2. Changelog
The changelog will be backported back to master.

Release v0.5.1

---

.prow/config.yaml

The current publish helm chart script modifies the existing charts in the repository before publishing the chart. The original intention is that, should a developer forgot to update the version, the script will automatically correct the mistake.
However, this preprocessing is currently modifying the versions of the non-feast dependencies. As a result the helm chart publication job will fail due to dependency not being met (eg. Prometheus).
This PR remove the preprocessing step. Instead the developer should explicitly update the image/tag version in the release branch.
```release-note
NONE
```

Publish helm chart script should not modify the chart content

---

core/src/test/java/feast/core/service/SpecServiceTest.java

The last assertion was only asserting against the object constructed in the test code and not the object created by production code. This PR fixes it. 
Also removed entities as I don't think they're relevant to this test.
NONE
no 
```release-note
NONE
```

Labels unit tests improvement

---

CHANGELOG.md

Update change log due to release 0.5.1.

Update change log due to release 0.5.1

---

sdk/go/client.go
sdk/python/feast/feature_set.py
sdk/python/tests/test_feature_set.py

This PR allows users to export feature sets to YAML strings. Usage is as follows
```
fs = FeatureSet("my_feature_set")
print(fs.to_yaml())
```
```release-note
Adds the ability to export a feature set to YAML.
```

Add YAML export to Python SDK

---

sdk/python/feast/feature.py
sdk/python/feast/feature_set.py
sdk/python/feast/field.py
sdk/python/tests/test_client.py
sdk/python/tests/test_feature_set.py
tests/e2e/redis/basic-ingest-redis-serving.py

Adding labels to Python sdk with relevant FeatureSet class functions:
```python
set_label(key: str, value: str)
remove_label(key: str)
```
Fixes #663 
```release-note
Users can use the Python SDK to add metadata to feature sets in the form of labels.
```

Add support for labels on feature sets

---

CHANGELOG.md
infra/charts/feast/Chart.yaml
infra/charts/feast/README.md
infra/charts/feast/charts/feast-core/Chart.yaml
infra/charts/feast/charts/feast-serving/Chart.yaml
infra/charts/feast/requirements.lock
infra/charts/feast/requirements.yaml
pom.xml

I wanted to get the switch to using Java 11 for Core and Serving backported as well, to hopefully be able to drop Prow configuration for Java 8 except perhaps one to guard regressions for Ingestion, but there are some issues with Cassandra in Java 11 that we'll have to look into later.
This release is to get the labels support in v0.3 out in published protos.

Release v0.3.8

---

CHANGELOG.md

Brings v0.3.8 changelog to master.
The release process was pretty smooth! 🎉 
~~One thing: Prow publish jobs don't seem to have run for [the release commit](https://github.com/feast-dev/feast/commit/64852e26fd3d4cf342eb8c69b22724ea106cbabe), @davidheryanto maybe you can answer if it needs some extra kick? I've pushed the tag on that commit.~~

Add v0.3.8 changelog

---

infra/charts/feast/charts/feast-core/README.md
infra/charts/feast/charts/feast-core/templates/deployment.yaml
infra/charts/feast/charts/feast-core/values.yaml
infra/charts/feast/charts/feast-serving/README.md
infra/charts/feast/charts/feast-serving/templates/deployment.yaml
infra/charts/feast/charts/feast-serving/values.yaml

Allows pod labels to be included in Kubernetes deployments for easier management and classification of pods.
Fixes #794
```release-note
Added support for Pod labels in Kubernetes.
```

Add Kubernetes Pod labels to Core and Serving.

---

storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/common/TypeUtil.java
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/CompactFeatureRows.java
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
storage/connectors/bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoadsWithResult.java
storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java

Recently we changed BigQuery writes to use BatchLoad method to be able to update table schema in-flight. In order to produce "successful inserts" output for metrics calculation we keep in memory all FeatureRows until BigQuery load job succeed.
To use memory more efficient this PR proposes to compress FeatureRows that awaiting for bq job to finish by converting them from row-orientation into column-orientation and using generic compression on those columns.
Fixes #
```release-note
```

Compression of FeatureRows collection in memory

---

core/src/main/java/feast/core/config/FeastProperties.java
core/src/main/java/feast/core/dao/FeatureSetRepository.java
core/src/main/java/feast/core/job/JobUpdateTask.java
core/src/main/java/feast/core/model/FeatureSetJobStatus.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/java/feast/core/service/SpecService.java
core/src/main/resources/application.yml
core/src/test/java/feast/core/job/JobUpdateTaskTest.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
core/src/test/java/feast/core/service/SpecServiceTest.java
core/src/test/java/feast/core/service/TestObjectFactory.java

To resolve some concerns related to overloading responsibilities in SpecService in my previous PR https://github.com/feast-dev/feast/pull/792 I moved all communications with IngestionJob to JobCoordinatorService
Implemented flow
New FeatureSet:
1. FeatureSet being created through SpecService.applyFeatureSet with status PENDING
2. `JobCoordinator.Poll` allocates this Set to Job(s) by creating FeatureSetJobStatus (see `JobUpdateTask.updateFeatureSets`) with version=0 and deliveryStatus=in-progress
3. `JobCoordinator.notifyJobs` detects that there's pending FeatureSet with allocated job(s) and send FeatureSetSpec to kafka (topic is shared between all jobs)
4. `JobCoordinator.listenAckFromJobs` receives ack from job and update deliveryStatus in …

Move communication with IngestionJob to JobCoordinator

---

Makefile
core/src/main/java/feast/core/service/JobService.java
core/src/test/java/feast/core/service/JobServiceTest.java

Fixes some bugs in the Ingestion Job Management service.
Cleaning house a bit and I had a todo [from here][1] about the `get()` calls that will always fail. These don't actually have much impact since `get()` already throws `NoSuchElementException` which we're doing anyway, but we'd lose the message we try to set.
Actually perhaps more concerning is a bunch of `==` comparisons on strings, those might be a source of more functionally significant bugs for filtering in the list jobs API. I'm surprised that no tests trip something here—a little short on time to look more closely at the existing tests now, apologies.
These issues are all flagged by IntelliJ. The `==` and `this.` receiver for all class member references smell like the author was writing …

Fix Optional#get() and string comparison bugs in JobService

---

infra/charts/feast/charts/feast-core/README.md
infra/charts/feast/charts/feast-core/values.yaml
infra/charts/feast/charts/feast-serving/README.md
infra/charts/feast/charts/feast-serving/values.yaml

**What this PR does / why we need it**: Image tag default is currently dev, which might change very often and might include bugs and breaking changes.
**Which issue(s) this PR fixes**: Fixes #805

Use latest instead of dev as the default image tag in helm charts

---

common/src/main/java/feast/common/models/Feature.java
common/src/test/java/feast/common/models/FeaturesTest.java
sdk/java/src/main/java/com/gojek/feast/FeastClient.java
sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
serving/src/main/java/feast/serving/service/OnlineServingService.java
serving/src/main/java/feast/serving/specs/CachedSpecService.java

Refactor common module's getFeatureStringRef method to not use flag.
```release-note
NONE
```

Refactor common module's feature string reference method

---

common/src/main/java/feast/common/models/Store.java
common/src/test/java/feast/common/models/StoreTest.java
ingestion/src/test/java/feast/ingestion/transform/FeatureRowToStoreAllocatorTest.java
protos/feast/core/Store.proto
serving/src/main/java/feast/serving/specs/CachedSpecService.java

This PR adds a new `exclude` flag to subscriptions to allow blacklisting of projects and featuresets.
```release-note
Users can now include exclude flag to blacklist subscriptions to certain featuresets and projects.
```

Add subscriptions blacklist functionality

---

core/src/main/java/feast/core/job/JobUpdateTask.java
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureSetSpecToTableSchema.java

Currently we create table in BQ only with first batch insert, when first data is arrived.
To speed up e2e tests this PR changes it, so table would be created inside IngestionJob when new FeatureSetSpec is received.
Fixes #
```release-note
```

Create table in BigQuery if doesn't exists when new FeatureSetSpec arrived to IngestionJob

---

core/src/main/java/feast/core/validators/FeatureSetValidator.java
core/src/test/java/feast/core/service/SpecServiceTest.java

This PR prevents applying of Featuresets with Feature names that are reserved.
Fixes #818
```release-note
NONE
```

Prevent reserved fields from being registered

---

serving/src/main/java/feast/serving/service/OnlineServingService.java
serving/src/main/java/feast/serving/util/Metrics.java

[missingKeyCount](https://github.com/feast-dev/feast/blob/master/serving/src/main/java/feast/serving/util/Metrics.java#L41 ) metric used to be available in Prometheus but was removed during refactor to OnlineServingService and RedisOnlineRetriever, from [RedisServingService](https://github.com/feast-dev/feast/blob/cc884b4480c50555d8a9f28e0629d138d0d9bd36/serving/src/main/java/feast/serving/service/RedisServingService.java#L220).
```release-note
NONE
```

Add missing key count metric

---

core/src/main/java/feast/core/config/FeastProperties.java
core/src/main/java/feast/core/config/JobConfig.java
core/src/main/java/feast/core/job/ConsolidatedJobStrategy.java
core/src/main/java/feast/core/job/CreateJobTask.java
core/src/main/java/feast/core/job/JobGroupingStrategy.java
core/src/main/java/feast/core/job/JobPerStoreStrategy.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/resources/application.yml
core/src/test/java/feast/core/job/JobTasksTest.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java

Decision regarding how to group sources and stores into IngestionJobs is extracted from `JobCoordinatorService` to `JobGroupingStrategy`. Thus it's now configurable with `feast.jobs.consolidate-jobs-per-source` whether to create one job per Source (and write to all stores from one job) or one job per pair Source-Store and write only to one store in job. The latter is default.
Fixes #
```release-note
It is possible to enable a job grouping strategy which allows ingestion jobs to be consolidated by source.
```

Allow ingestion job grouping/consolidation to be configurable

---

core/src/main/java/feast/core/model/Job.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java

Previously, when job required upgrade (currently happens when store config changed) - we stopped current running job and then spawn new one sequentially. That may bring downtime in Ingestion, which is unwanted, especially for online storing.
In this PR we spawn clone of the job first. The old one being garbage collected (terminated) on the next run of JobCoordintatorService.Poll when we are sure that replacement is up & running.
Fixes #
```release-note
```

IngestionJob is being gracefully replaced to minimize downtime

---

core/src/main/java/feast/core/config/FeastProperties.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/resources/application.yml

We need option to deploy core without job management
Fixes #
```release-note
Added the option of turning ingestion job management on or off.
```

JobCoordinator may be turned off by configuration

---

ingestion/src/main/java/feast/ingestion/ImportJob.java

Fixes a mistake in #763 where metrics. are written for all validatedRows for every store, without filtering by store.

Write metrics for store allocated rows only

---

Makefile
tests/e2e/bq/bq-batch-retrieval.py
tests/e2e/bq/feature-stats.py
tests/e2e/bq/testutils.py
tests/e2e/pyproject.toml
tests/e2e/redis/basic-ingest-redis-serving.py
tests/e2e/setup.cfg

We currently have Python based formatting and linting for the Python SDK (code and tests), however our end to end test suite also uses Python but isn't covered by linting or formatting. This PR includes the `tests/e2e` folder under the coverage of `make format-python` and `make lint-python`
```release-note
None
```

Enable linting and formatting for e2e tests

---

CHANGELOG.md
sdk/python/feast/job.py
sdk/python/feast/loaders/file.py
sdk/python/feast/staging/staging_strategy.py
sdk/python/feast/staging/storage_client.py
sdk/python/requirements-ci.txt
sdk/python/requirements-dev.txt
sdk/python/setup.py
sdk/python/tests/loaders/test_file.py
sdk/python/tests/test_job.py

Currently Feast client cannot stage data anywhere except GCP storage. The PR adds S3 staging support on client.
**Which issue(s) this PR fixes**: Client can stage files on s3. 
Python Client changes for #706.
Edit: Fixes #562 
```release-note
Added support to Python SDK for staging files on Amazon S3
```

Add support to Python SDK for staging files on Amazon S3

---

core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
core/src/test/java/feast/core/job/dataflow/DataflowRunnerConfigTest.java
protos/feast/core/Runner.proto

After #718, it's not possible to have arbitrary options set for runner configuration. Instead, it has to be one of the options supported by the protos defined in `DataflowRunnerConfigOptions` .
`diskSizeGb` is an important option which wasn't available in the proto. This PR added the configuration.
Fixes #
```release-note
Users will now be able to specify disk size for dataflow workers.
```

Add disk size as Dataflow Job Configuration

---

Makefile
sdk/python/feast/client.py
sdk/python/feast/feature_set.py
sdk/python/feast/field.py
sdk/python/feast/job.py
sdk/python/setup.cfg
sdk/python/tests/test_client.py
sdk/python/tests/test_feature_set.py
tests/e2e/bq/bq-batch-retrieval.py
tests/e2e/bq/feature-stats.py
tests/e2e/bq/testutils.py
tests/e2e/setup.cfg

Enables [isort](https://github.com/timothycrosley/isort) checks for the Python SDK and e2e tests.
Contributors should use `make format` in order to sort their code, and `make lint` in order to validate that their Python code is correctly sorted.
```release-note
NONE
```

Enable isort for Python SDK

---

sdk/python/docs/requirements.txt
sdk/python/requirements-ci.txt
sdk/python/requirements-dev.txt
sdk/python/setup.py
tests/e2e/requirements.txt

**What this PR does / why we need it**: Upgrade pandas to 1.0.x, as it's been released.
```NONE
```

Upgrade pandas to 1.0.x

---

README.md
docs/user-guide/feature-retrieval.md
examples/basic/basic.ipynb
examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
infra/charts/feast/templates/tests/test-feast-batch-serving.yaml
sdk/python/feast/client.py
sdk/python/tests/test_client.py
tests/e2e/bq/bq-batch-retrieval.py

We are slowly starting to rename API methods from `batch` to `historical` for all historical retrieval. This is one step towards deprecating the method `get_batch_features()` for the identical `get_historical_features()`.
```release-note
Users can now use get_historical_features() instead of get_batch_features() on the Python SDK
```

Replace batch with historical for Python SDK retrieval

---

core/src/main/java/feast/core/dao/FeatureSetJobStatusRepository.java
core/src/main/java/feast/core/model/FeatureSetJobStatus.java
core/src/main/java/feast/core/model/Job.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/resources/db/migration/V2.3__Fix_Primary_Keys.sql
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java

After FeatureSet updated with new Source it should be deallocated from its current job and allocated to new one. Deallocation (deletion of FeatureSetJobStatus) doesn't happen which leads to inconsistent state when FeatureSet remains PENDING.
Fixes #
```release-note
```

Deallocate featureSet from job when source changed

---

ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
ingestion/src/test/java/feast/ingestion/transform/ProcessAndValidateFeatureRowsTest.java

Currently we overpopulating deadletter sink (in bq) by sending all FeatureRows that coming in with unknown FeatureSetReference. That could create billions of rows within hours and create long queue in IngestionJob, which disrupt normal processing (OOM, eg). We should just write smth to log instead.
Fixes #
```release-note
```

Don't send unrecognized featureSets to deadletter in IngestionJob

---

core/src/main/java/feast/core/model/Store.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/resources/db/migration/V2.4__Store_Timestamps.sql
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java

TestCase that fails:
1. There's existing consolidated job with state RUNNING
2. Job has attached Store with subscription project_1:*
3. We update Store config (on serving layer) by adding new subscription project_2:*
4. After serving layer sent Store to Core - Job should be replaced with new one that has both subscriptions
Fixes #
```release-note
```

Replace IngestionJob when store was updated

---

core/src/main/java/feast/core/model/FeatureSetJobStatus.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/test/java/feast/core/util/TestUtil.java

Prevent from creating FeatureSetJobStatuses that would violate unique primary key constraint.
Fixes #
```release-note
```

Fix: JobCoordinator tries to create duplicate FeatureSetJobStatuses

---

sdk/python/feast/client.py

The Python SDK doesn't work on macOs because `os.sched_getaffinity(0)` isn't supported. This PR uses `multiprocessing.cpu_count()` which is.
Fixes #
```release-note
```

Fix CPU count selection in Python SDK for non-Unix

---

core/src/main/java/feast/core/model/FeatureSet.java

Currently due to cascade relations from both Job and FeatureSet to FeatureSetJobStatus it's impossible to delete FeatureSetJobStatus. As a solution I propose to delete cascade on FeatureSet side because:
1. We manage FeatureSetJobStatus from Job side
2. Ideally when we completely decouple JobCoordination from Core there will be no foreign key (relationship in general) to FeatureSet in FeatureSetJobStatus (see my other PR #852 )
3. Currently we not planning to physically delete feature sets. Even if we will delete them - only by marking as deleted.
Fixes #
```release-note
```

Fix FeatureSetJobStatus removal

---

core/src/main/java/feast/core/dao/JobRepository.java
core/src/main/java/feast/core/job/ConsolidatedJobStrategy.java
core/src/main/java/feast/core/job/JobPerStoreStrategy.java
core/src/main/java/feast/core/model/Job.java
core/src/main/java/feast/core/model/JobStore.java
core/src/main/java/feast/core/model/Store.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/java/feast/core/service/JobService.java
core/src/main/resources/db/migration/V2.4__Store_Timestamps.sql
core/src/main/resources/db/migration/V2.4__Store_proto.sql
core/src/test/java/feast/core/job/JobTasksTest.java
core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
core/src/test/java/feast/core/service/JobServiceTest.java
sdk/python/feast/client.py

This PR reverts #846 to keep Job and Store more decoupled (and not use StoreRepository from JobCoordinator).
Now Job keeps full copy of related Stores (in proto) in `jobs_stores` table. It allows us to compare deployed stores with new one coming from `SpecService` and upgrade IngestionJob if needed.
Fixes #
```release-note
```

Keep StoreProto inside JobStore to decouple JobCoordination from SpecService internals

---

storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java

Schema can't be inferred when one of the features has only nulls in `FeatureRowBatch` that is used to compress FeatureRows while waiting for BQ job to load.
This PR fixes NPE
Fixes #
```release-note
```

BQ Sink is failing when Feature consists of only null values

---

core/src/main/java/feast/core/model/Feature.java
core/src/main/java/feast/core/model/FeatureSet.java
core/src/test/java/feast/core/service/SpecServiceTest.java

Currently, when we reapply featuresets to add/remove labels from featureset or features, the changes made to labels are not propagated.
Fixes #
```release-note
NONE
```

Bugfix: Re-applying of featuresets does not update label changes

---

storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java

Make sure successful inserts are not duplicated in BigQuerySink. When we joining rows-to-be-inserted with bq-write output it should emit only once.
In addition I made BigQuerySinkTest more stable since it was failing periodically.
Fixes #
```release-note
```

Fix BigQuerySink successful output to produce only once

---

auth/pom.xml
auth/src/main/java/feast/auth/authentication/DefaultJwtAuthenticationProvider.java
auth/src/main/java/feast/auth/authorization/AuthorizationProvider.java
auth/src/main/java/feast/auth/authorization/AuthorizationResult.java
auth/src/main/java/feast/auth/authorization/Keto/KetoAuthorizationProvider.java
auth/src/main/java/feast/auth/config/SecurityConfig.java
auth/src/main/java/feast/auth/config/SecurityProperties.java
common/pom.xml
common/src/main/java/feast/common/validators/OneOfStringValidator.java
common/src/main/java/feast/common/validators/OneOfStrings.java
core/pom.xml
core/src/main/java/feast/core/config/CoreSecurityConfig.java
core/src/main/java/feast/core/config/FeastProperties.java
core/src/main/java/feast/core/service/AccessManagementService.java
core/src/test/java/feast/core/auth/AuthConfigTest.java
core/src/test/java/feast/core/grpc/CoreServiceAuthTest.java
core/src/test/java/feast/core/service/AccessManagementServiceTest.java
pom.xml

Authentication and authorization code is currently part of core, To enable authentication and authorization on Serving, and in other modules on need basis, it is ideal to have it in a separate module. 
Fixes #
Related to #823 
```release-note
None
```

Authentication and Authorization into feast-auth module.

---

core/src/main/java/feast/core/config/CoreSecurityConfig.java
core/src/main/java/feast/core/config/WebSecurityConfig.java

The `/metrics` and `/actuator` endpoints require authentication. Most users do not want auth on these utility endpoints, as they will typically not be exposed. This bug fix ensures that security is not applied to these two HTTP endpoints.
Furthermore, the current Auth test suite needs to be extended to actually catch these regressions. It can be tracked here #860 
```release-note
NONE
```

Bypass authentication for metric endpoints

---

core/src/main/java/feast/core/dao/JobRepository.java
core/src/main/java/feast/core/service/JobService.java
sdk/python/feast/client.py

Python SDK's `list_ingest_jobs()` is currently broken when passing feature_set_ref as the grpc method expects a proto form feature_set_ref. Also, FeatureSet's `getJobStatuses()` does not work as intended.
Fixes #
```release-note
NONE
```

Bugfix: Python SDK listing of ingestion job fails for featureset reference filter

---

infra/scripts/setup-common-functions.sh
infra/scripts/test-end-to-end-redis-cluster.sh
infra/scripts/test-end-to-end.sh
protos/feast/core/Store.proto
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisClusterFeatureSinkTest.java
storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisFeatureSinkTest.java

In redis sink we pack rows into batches before actually flush them to redis. Current implementation use GroupBy null (all rows into one group) which cause a lot of shuffling. It could lead to significant throughput degradation. This PR replaces GroupBy with GroupIntoBatches with FeatureReference used as key. This should improve parallelization of Redis Sink
Fixes #
```release-note
Users can now configure the flush frequency to write to a Redis store.
```

Improve parallelization in Redis Sink

---

storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java

Currently row based metrics (like lag) are calculated incorrectly due to absence of correct timestamp in FeatureRow.
Fixes #
```release-note
```

Add IngestionId & EventTimestamp to FeatureRowBatch to calculate lag metric correctly

---

storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java

Output of BQ batch insert is now sample from all inserted rows.
Currently BQ's `successful inserts` produces all rows that were in batch. In some use-cases like batch ingestion it could produce up to 30k / sec rows (or ~5 M rows in batch for the default flush frequency (3m)). This output is used in metrics where whole batch (with 5M rows) is grouped into single list, which requires it to fit into memory of one machine. This can lead to memory issues.
I suspect that this is overkill since metrics can be easily calculated from sample of inserted data instead of whole batch. This PR changes BQ successful inserts to output only sample of inserted data.
```release-note …
```

BQ sink produces sample of successful inserts

---

.prow/config.yaml
core/pom.xml
infra/scripts/test-end-to-end-batch-dataflow.sh
infra/scripts/test-end-to-end-batch.sh
infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
ingestion/pom.xml
tests/e2e/bq/bq-batch-retrieval.py

Fixes Ingestion Job on dataflow, which currently fails with 
```java.lang.SecurityException: Invalid signature file digest for Manifest main attributes```
Also, to prevent such cases in future I changed dataflow e2e to be mandatory step.
Fixes #
```release-note
```

Exclude dependencies signatures from IngestionJob package

---

auth/src/main/java/feast/auth/authorization/HttpAuthorizationProvider.java
auth/src/main/resources/api.yaml

**What this PR does / why we need it**:  Added Auth token to the header of the request sent to the external Authorization API.
**Does this PR introduce a user-facing change?**: NONE

Add Auth header

---

auth/pom.xml
auth/src/main/java/feast/auth/authorization/HttpAuthorizationProvider.java
auth/src/main/java/feast/auth/config/CacheConfiguration.java
auth/src/main/java/feast/auth/utils/AuthUtils.java
auth/src/test/java/feast/auth/authorization/HttpAuthorizationProviderCachingTest.java
core/src/main/resources/application.yml

Currently all requests are authorized against an external server, as this can cause latency issues in serving, Caching the authorization for a short span of time will avoid external call on subsequent requests. 
related to #823 
**Does this PR introduce a user-facing change?**:No
```release-note
Project level authorization access requests are now cached.
```

Add caching to authorization

---

.github/workflows/load_test.yml
.prow/config.yaml
Makefile
infra/scripts/test-load.sh
infra/scripts/wait-for-docker-images.sh
tests/load/hdr_plot.py
tests/load/ingest.py

Adds a GitHub Action that runs a load tests as part of all PRs and direct pushes. This test runs a range of tests with the following parameters
* Entity count 10 and 50
* RPS 20, 50, 250
* 1 feature set
* 13 features, one of each type
```release-note
NONE
```

Add load test GitHub Action

---

.github/workflows/complete.yml

GitHub Actions won't build and push images based on the PR commit SHA because it creates its own merged commit. This causes dataflow tests to fail because Prow uses the commit SHA from the PR. This PR allows GA to tag and push those images.
```release-note
NONE
```

Fix docker image building for PR commits

---

.github/workflows/complete.yml
.github/workflows/master_only.yml

Currently builds cannot push images to Google GCR because secrets cannot be used on forks. This PR allows self-hosted Kubernetes pods to be used for Github Actions.
```release-note
NONE
```

Allow use of Kubernetes for Github Actions

---

.github/workflows/complete.yml

Github Actions CI `load-test` job currently produces the following [error](https://github.com/feast-dev/feast/pull/908/checks?check_run_id=934351850#step:3:408):
```
Collecting feast
Could not find a version that satisfies the requirement feast (from versions: )
No matching distribution found for feast
```
As there is no `feast` python SDK built for Python 2.7
Adds `install-python` action to `load-test` job to inst
Fixes #
```release-note
NONE
```

Fix Github Actions CI load-test job failing due inability to install Feast Python SDK.

---

core/src/main/java/feast/core/config/FeatureStreamConfig.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java

Adds a delay to Redis spec send acknowledgement in order to prevent a race condition with the send event being commited.
```release-note
Occasionally feature sets might enter a pending state due to a race condition with spec acknowledgement. This race has been resolved.
```

Backport delay in Redis acknowledgement of spec

---

infra/charts/feast/README.md
infra/charts/feast/README.md.gotmpl
infra/charts/feast/values-batch-serving.yaml
infra/docker-compose/serving/batch-serving.yml
protos/feast/core/Store.proto
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryFeatureSink.java

When `write_triggering_frequency_seconds` is not specified in `BigQueryConfig` not very useful exceptions is being thrown
on IngestionJob start.
```
java.lang.IllegalArgumentException: FixedWindows WindowingStrategies must have 0 <= offset < size
```
Instead this PR adds check and throw more informative exception. And also adds default value to helm & docker compose.
Fixes #
```release-note
More informative exception when `BigQueryConfig` is not properly filled.
```

Throw more informative exception when write_triggering_frequency_seconds is missing

---

core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
core/src/main/resources/application.yml
core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
core/src/test/java/feast/core/job/dataflow/DataflowRunnerConfigTest.java
infra/charts/feast/README.md
infra/charts/feast/README.md.gotmpl
infra/charts/feast/values-dataflow-runner.yaml
infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
protos/feast/core/Runner.proto

This PR extends execution parameteres for Dataflow Job according to [official documentation](https://cloud.google.com/dataflow/docs/guides/specifying-exec-params#setting-other-cloud-dataflow-pipeline-options).
Next parameter were added:
* workerDiskType
* enableStreamingEngine
Next parameter were updated:
* zone -> workerZone (due to deprecation)
Fixes #
```release-note
new options introduced in application.yaml
feast:
jobs:
runners:
- name: dataflow
options:
enableStreamingEngine: false
workerDiskType: compute.googleapis.com/projects/asia-east1-a/diskTypes/pd-ssd
workerZone: asia-east1-a  # renamed "zone" due to deprecation
```

Dataflow runner options: disk type & streaming engine

---

.github/workflows/complete.yml
infra/charts/feast/README.md
infra/charts/feast/charts/feast-core/README.md
infra/charts/feast/charts/feast-core/values.yaml
infra/charts/feast/charts/feast-jupyter/README.md
infra/charts/feast/charts/feast-jupyter/values.yaml
infra/charts/feast/charts/feast-serving/README.md
infra/charts/feast/charts/feast-serving/values.yaml
infra/charts/feast/requirements.lock
infra/scripts/validate-version-consistency.sh

Allows for linting of versions based on latest stable tag, bump the requirements lock for our helm charts, and allows for specifying the amount of versions to find in a file.
Fixes #924
```release-note
NONE
```

Fix Helm chart requirements lock and version linting

---

auth/src/main/java/feast/auth/config/SecurityConfig.java
core/src/main/java/feast/core/config/CoreSecurityConfig.java
core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
serving/src/main/java/feast/serving/config/ServingSecurityConfig.java
serving/src/test/java/feast/serving/it/ServingServiceOauthAuthenticationIT.java

Allow unauthenticated requests when only `authentication` is enabled:
- Allows "optional authentication" which is needed when transition users to authentication.
- Forced `authentication` is only enforced when  `authorization` is enabled.
Add exceptions for unauthenticated access to the health probe.
Fixes #
```release-note
Authentication allows unauthenticated requests unless Authorization is also enabled.
Feast now allows unauthenticated access to its health probes.
```

Allow unauthenticated access when Authorization is disabled and to Health Probe

---

core/src/main/java/feast/core/service/StatsService.java

These 2 methods, [this](https://github.com/feast-dev/feast/blob/master/core/src/main/java/feast/core/service/StatsService.java#L254) and [that](https://github.com/feast-dev/feast/blob/master/core/src/main/java/feast/core/service/StatsService.java#L185) will always be returning at least an empty arraylist. So essentially, when being called in [getFeatureStatistics](https://github.com/feast-dev/feast/blob/master/core/src/main/java/feast/core/service/StatsService.java#L92), these conditions, [this](https://github.com/feast-dev/feast/blob/master/core/src/main/java/feast/core/service/StatsService.java#L135) and [that](https://github.com/feast-dev/feast/blob/master/core/src/main/java/feast/core/service/StatsService.java#L151) will never be triggered, …

Fix empty array when retrieving stats data

---

core/src/test/java/feast/core/metrics/CoreMetricsIT.java
serving/src/main/java/feast/serving/config/WebSecurityConfig.java
serving/src/test/java/feast/serving/it/ServingServiceOauthAuthenticationIT.java

Follow up of #862 to extend Authentication Bypass for metrics access to Serving for the `/metrics` and `/actuator` endpoints.
Fixes #
```release-note
NONE
```

  Bypass authentication for metric endpoints on Serving.

---

core/src/main/resources/application.yml
infra/docker/core/Dockerfile.dev
infra/docker/serving/Dockerfile.dev
serving/src/main/resources/application.yml

Grpc security variable names in application.yml are incorrect. Also exec qualifiers are missing from DockerFile.dev
Related #823 
**Does this PR introduce a user-facing change?**:No
```release-note
previous behavior : enabling grpc security and setting valid server.crt and server.key, throws an error. 
Also docker images build using DockerFile.dev will not boot.
With this PR, enabling security shouldn't throw any error if valid server.crt and server.key are set.
Images build using DockerFile.dev will boot without any errors.
```

Fix grpc security variables name and missing exec qualifier in docker.dev

---

core/src/main/java/feast/core/grpc/CoreServiceImpl.java
core/src/main/java/feast/core/service/SpecService.java
core/src/test/java/feast/core/auth/CoreServiceAuthTest.java
core/src/test/java/feast/core/service/SpecServiceTest.java

if `project` is not set in the `featureSet`, which is in the request for `applyFeatureSet` method, an empty project will be passed for authorization. Instead it should authorize against `default` project. 
Related to #793 
**Does this PR introduce a user-facing change?**:no
```release-note
In 'applyFeatureSet' api, project name imputation happens before invoking authorization service. 
Previous behavior, only 'admin' user could create feature sets in 'default' project, 
and authorization was failing for users who have access to 'default' project, 
since authorization was being invoked with empty 'projectId'. 
```

Impute default project if empty before authorization is called

---

storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureSetSpecToTableSchema.java
storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java

After BQ table was edited outside of ingestion job we might fail on generating schema from `FeatureSetSpec`:
```
org.apache.beam.sdk.util.UserCodeException: java.lang.IllegalArgumentException: Multiple entries with same key: s2id_13=6 and s2id_13=0
```
since we expect TableFields to be completely equal (including description).
This PR fix that with overwriting existing fields by using Map (that keeps inserting order) instead of merging two Lists.
Fixes #
```release-note
```

Prevent field duplications on schema merge in BigQuery sink

---

.github/workflows/complete.yml
Makefile
datatypes/java/README.md
docs/contributing/development-guide.md
infra/charts/feast/Chart.yaml
infra/charts/feast/README.md
infra/charts/feast/charts/feast-core/Chart.yaml
infra/charts/feast/charts/feast-core/README.md
infra/charts/feast/charts/feast-jupyter/Chart.yaml
infra/charts/feast/charts/feast-jupyter/README.md
infra/charts/feast/charts/feast-serving/Chart.yaml
infra/charts/feast/charts/feast-serving/README.md
infra/charts/feast/requirements.yaml
pom.xml

Fixes docker image building in `v0.6-branch` pushing to `latest` instead of expected Git commit SHA.
- fixes [this](https://github.com/feast-dev/feast/runs/952897101?check_suite_focus=true#step:10:1) failure of `master only` build and push docker images step
- fixes by backporting `master` Makefile.
Changes Versions to `0.6.3-SNAPSHOT` post release `0.6.2`
Fixes #
```release-note
```

Fix CI Building Images as latest instead of Github SHA and Change versions to v0.6.3-SNAPSHOT

---

core/src/main/java/feast/core/config/FeastProperties.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/main/resources/application.yml
core/src/test/java/feast/core/service/JobCoordinatorIT.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml

This PR adds ability to configure via application properties which FeatureSets and Stores will be available in (and managed by) current instance of JobManager.
This should be useful when you have several deployments of JobManager and each will be responsible for only subset of FeatureSets.
Fixes #
```release-note
feast:
jobs:
coordinator:
featureSetSelector:
- project: "*"
name: "*"
whitelisted-stores: [online, online_cluster, historical]
```

JobCoordinator can be configured to use only subset of FeatureSets or Stores

---

core/src/main/java/feast/core/job/ConsolidatedJobStrategy.java
core/src/main/java/feast/core/job/JobGroupingStrategy.java
core/src/main/java/feast/core/job/JobPerStoreStrategy.java
core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
core/src/main/java/feast/core/model/Job.java
core/src/main/java/feast/core/service/JobCoordinatorService.java
core/src/test/java/feast/core/service/JobCoordinatorIT.java
core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java

1. Each Job can have individual labels that are being merged with common labels (see `feast.jobs.runners.options.labels`) before job created. Job labels are being generated & managed by `JobCoordinator`. Currently labels consists of `feast.job.coordinator.jobSelector` and feast version. Job labels overwrite common labels for the same keys.
2. Added label `feast_version` that keeps version of feast code attached to the job. As soon as new version is being released - JobCoordinator automatically restarts jobs with older version in this label.
Fixes #
```release-note
```

Restart Ingestion Job on code version update

---

infra/docker-compose/.env.sample
infra/docker-compose/core/core.yml
infra/docker-compose/docker-compose.yml
infra/docker-compose/jobcontroller/jobcontroller.yml

This reverts commit 5b72335ca08dad361895fc928918615cd63b2158.
To fix load tests we need to have docker compose config sync with master (latest dev) structure.
Fixes #
```release-note
```

Get job controller deployment for docker compose back

---

docs/reference/limitations.md
infra/scripts/test-end-to-end-batch-dataflow.sh
infra/scripts/test-end-to-end-batch.sh
infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
ingestion/pom.xml
ingestion/src/test/java/feast/ingestion/ImportJobTest.java
ingestion/src/test/java/feast/ingestion/transform/specs/FeatureSetSpecReadAndWriteTest.java
ingestion/src/test/java/feast/test/TestUtil.java
sdk/python/feast/loaders/ingest.py
sdk/python/tests/test_client.py
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retriever/BigQueryHistoricalRetriever.java
storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureRowToTableRow.java
tests/e2e/bq/bq-batch-retrieval.py

Some refactoring / bug fixes to make tests more stable:
1. Use testcontainers in ingestion unit-tests
2. Better isolation for e2e tests
3. Fix rounding error in timestamp for batch tests
4. Fix Segmentation Fault occurring in Python SDK
5. Dynamic port allocation in python SDK unit tests
Fixes #
```release-note
```

Fix flaky tests

---

ingestion/src/main/java/feast/ingestion/ImportJob.java
ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
job-controller/src/main/java/feast/jobcontroller/runner/dataflow/DataflowRunnerConfig.java
job-controller/src/main/resources/application.yml
job-controller/src/test/java/feast/jobcontroller/runner/dataflow/DataflowRunnerConfigTest.java
protos/feast/core/Runner.proto

Kafka consumer that pulls FeatureRows from source should be configurable (via `jobcontroller` application properties) to be able to tune it for better performance.
Fixes #
```release-note
application.yml in jobcontroller
feast:
jobs:
runners:
- name: dataflow
options:
kafkaConsumerProperties:
"max.poll.records": "50000"
"receive.buffer.bytes": "33554432"
```

Configurable kafka consumer in IngestionJob

---

sdk/python/requirements-ci.txt
sdk/python/requirements-dev.txt

Linting is failing for github actions because we are not pegging black's version, and this is caused by black's latest release of 20.8b1.
Fixes #
```release-note
```

Peg black version

---

job-controller/src/main/java/feast/jobcontroller/model/Job.java
job-controller/src/main/java/feast/jobcontroller/runner/dataflow/DataflowJobManager.java
job-controller/src/main/resources/application.yml
job-controller/src/test/java/feast/jobcontroller/runner/dataflow/DataflowJobManagerTest.java

When JobController starts - it pulls existing jobs from dataflow. However, created datetime was missing. This PR fix that.
Fixes #
```release-note
```

Fetch Job's Created Datetime from Dataflow

---

job-controller/src/main/java/feast/jobcontroller/runner/dataflow/DataflowJobManager.java
job-controller/src/test/java/feast/jobcontroller/runner/dataflow/DataflowJobManagerTest.java

Job's labels are missing in JobRepository after JobController restarted.
Fixes #
```release-note
```

Fetch Job's labels from dataflow

---

storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retriever/FeatureSetQueryInfo.java

When project name or feature-set name contains "-" invalid query will be built on historical retrieval.
```
{
"code" : 400,
"errors" : [ {
"domain" : "global",
"location" : "q",
"locationType" : "parameter",
"message" : "Syntax error: Expected \")\" but got \"-\" at [16:13]",
"reason" : "invalidQuery"
} ],
"message" : "Syntax error: Expected \")\" but got \"-\" at [16:13]",
"status" : "INVALID_ARGUMENT"
}
```
And since there's no mechanism to propagate this error to the user
```
client.get_historical_features(...).to_dataframe()
```
will hang.
Fixes #
```release-note
```

Prevent historical retrieval from failing on dash in project / featureSet name

---

.github/workflows/complete.yml

Fixes Github Actions failures due to possible rate limiting:
- Fixes `build-push-docker-images` failing to connect to docker issue by limit no. of parallel builds to 3.
- Reduces test failures due to failing to connect to github.com/maven repo by reducing the no. of parallel test jobs
- Reduces test jobs running by introducing a dependency of unit test on lint, integration test on unit test. 
- Dependent  test jobs will wait for the depended job to complete before running.
Fixes #
```release-note
NONE
```

Fix Github Actions failures due to possible rate limiting.

---

job-controller/src/main/java/feast/jobcontroller/config/FeastProperties.java
job-controller/src/main/java/feast/jobcontroller/config/JobControllerConfig.java
job-controller/src/main/java/feast/jobcontroller/runner/ConsolidatedJobStrategy.java
job-controller/src/main/java/feast/jobcontroller/runner/JobPerStoreStrategy.java
job-controller/src/main/resources/application.yml
job-controller/src/test/java/feast/jobcontroller/service/JobControllerIT.java
job-controller/src/test/java/feast/jobcontroller/service/JobControllerServiceTest.java

To allow multiple deployments with jobs running in parallel, we should separate their Kafka consumer groups which is based on the JobId. This would prevent overwriting each other's offsets.
Fixes #
```release-note
NONE
```

Add configurable prefix to Consumer Group in IngestionJob's Kafka reader

---

core/src/main/java/feast/core/service/SpecService.java
core/src/main/java/feast/core/validators/FeatureSetValidator.java
core/src/main/java/feast/core/validators/Matchers.java
core/src/test/java/feast/core/service/SpecServiceIT.java
core/src/test/java/feast/core/validators/MatchersTest.java

Currently - in names is being replaced to _. This is hacky solution that need to be implemented in many places. It also creates potential bug since project-1 and project_1 (feature-set and feature_set) will be using the same bq table.
It's better to validate this (and not allow such characters) on feature set creation. This PR addresses the above issue for project, featureset, features and entities.
Fixes #
```release-note
Users will no longer be allowed to include dashes in project, featureset, entity and feature name.
```

Fix invalid characters for project, featureset, entity and features creation

---

.github/workflows/complete.yml
.github/workflows/master_only.yml
infra/docker-compose/jobcontroller/jobcontroller.yml
infra/scripts/test-docker-compose.sh

`tests-docker-compose` test that triggers when PRs are merged to master branch currently runs tests on a specific version (eg. 0.6.2) image. This causes test failures since Dockerfiles may have changed since a specific version tag.
Fixes #956 
```release-note
NONE
```

Fix docker-compose test

---

sdk/python/feast/client.py
tests/e2e/redis/basic-ingest-redis-serving.py

Online retrieval with python native types was introduced in 0.6 and a bug was introduced. Specifically, retrieving features with more than 1 entity would fail since only 1 entity is converted during the online retrieval call.
Fixes #
```release-note
```

Fix Python native types multiple entities online retrieval

---

infra/docker-compose/jobcontroller/jobcontroller.yml
tests/e2e/redis/basic-ingest-redis-serving.py

Polling interval is too high for configuration that's used to run docker-compose-tests, resulting in redis pytest failures. Failure also stems for e2e tests when featureset update is not yet propagated.
Example failures:
1. https://github.com/feast-dev/feast/pull/975/checks?check_run_id=1065997200
2. http://prow.feast.ai/view/gcs/feast-templocation-kf-feast/pr-logs/pull/feast-dev_feast/980/test-end-to-end/1301743039177297923 
3. http://prow.feast.ai/view/gcs/feast-templocation-kf-feast/pr-logs/pull/feast-dev_feast/980/test-end-to-end-auth/1301743039177297921
Fixes #
```release-note
NONE
```

Reduce polling interval for docker-compose test and fix flaky e2e test

---

sdk/python/setup.py

Added custom regex to parse versions to `setuptools_scm` used by the Python SDK to parse SemVer versions:
- Required to prevent setuptools_scm from crashing due to 'sdk/go/*' tags when running `setup.py`.
- These are tags need to be introduced to support golang SDK retrieval by version. #824 
Fixes #824 once new go `sdk/go/*` tags are introduced.
```release-note
```

Fix Python SDK setuptools not supporting tags required for Go SDK to be versioned.

---

protos/feast/core/Store.proto
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetriever.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeyPrefixSerializer.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeyProtoSerializer.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeySerializer.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetrieverTest.java
storage/connectors/redis/src/test/java/feast/storage/connectors/redis/serializer/RedisKeyPrefixSerializerTest.java

There are scenarios where multiple Feast deployment are sharing the same Redis cluster, but key collision between the different deployment should be avoided. Since Redis cluster doesn't support database, attaching prefix to keys is a good workaround to achive namespacing.
To facilitate migration of redis keys from one prefix to another, fallback mechanism has also been introduced. If enabled, when a key is not found in the database, a fallback prefix can be used instead. However, this will results in more calls to Redis, and additional latency.
Fixes #
```release-note
Additional optional configuration for Redis cluster, where user can specified a prefix to be …
```

Add redis key prefix as an option to Redis cluster

---

sdk/go/client.go
sdk/java/src/main/java/com/gojek/feast/FeastClient.java
sdk/java/src/main/java/com/gojek/feast/SecurityConfig.java

Follow up of #971:
- implements missing TLS support for Java SDK.
- Fixes Go SDK issue where it does not use system certificates if TLS enabled but no certificate path is specified.
- Rename Go and Java SDK secure client creation methods to include "secure" instead of "authenticated"
- Go SDK: `NewAuthGrpcClient()` -> `NewSecureGrpcClient()`  
- Java SDK: `createdAuthenticated()` -> `createSecure()`
Continuation of #504
Fixes #
```release-note
implements TLS support for Java SDK.
Rename Go and Java SDK secure client creation methods to include "secure" instead of "authenticated"
- Go SDK: `NewAuthGrpcClient()` -> `NewSecureGrpcClient()`  
- Java SDK: …
```

Fix Java & Go SDK TLS support

---

core/src/main/java/feast/core/service/SpecService.java
infra/docker-compose/jobcontroller/jobcontroller.yml
serving/src/main/java/feast/serving/config/FeastProperties.java

This PR fixes the issue where updates to subscriptions exclude flag does not propagate to the stores. The caveat in this PR is that all blacklisted subscriptions will apply to both online and historical stores.
Fixes #
```release-note
NONE
```

Bugfix: Blacklisted subscriptions are currently not updated in store

---

infra/charts/feast/charts/feast-core/templates/deployment.yaml
infra/charts/feast/charts/feast-jobcontroller/templates/deployment.yaml
infra/charts/feast/charts/feast-serving/templates/deployment.yaml

Currently it's not possible to use more complicated expressions (than string or int) as environment variable in kubernetes `Deployment` object via helm charts. `Map` structure could be useful to provide kube metadata as parameter to feast services.
```
env:
- name: MY_POD_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
```
Now this can be achieved with
`--set envOverrides.MY_POD_NAMESPACE.fieldRef.fieldPath=metadata.namespace`
Fixes #
```release-note
```

Allow maps in environment variables in helm charts

---

common/pom.xml
common/src/main/java/feast/common/logging/AuditLogger.java
common/src/main/java/feast/common/logging/config/LoggingProperties.java
common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
core/src/main/resources/application.yml
core/src/test/java/feast/core/logging/CoreLoggingIT.java
job-controller/src/main/resources/application.yml
serving/src/main/resources/application.yml

This PR introduces the option to enable request/response logging to an external fluentd service. This is an addition to the existing Audit logging capabilities which logs to the console.
N/A
```release-note
Users can now enable forwarding of logs to an external fluentd service that's been setup.
```

Add request response logging via fluentd

---

common/src/main/java/feast/common/logging/AuditLogger.java

This typo was introduced in #961 . It should've been `release_name` instead of `release_tag`.
Fixes #
```release-note
NONE
```

Fix typo for fluentd request response map key

---

docs/reference/api.md
docs/reference/api/README.md

including reference to community-provided Node.js SDK
1. Adds a `Community Contributions` section in the reference > api docs
2. Adds a link to the community provided [Node.js SDK](https://github.com/MichaelHirn/feast-client)
cc @woop 
Does not fix an issue
```release-note
NONE
```
**Notes**
- CLA signed
- ❓I'm not sure if only (`docs/reference/api/README.md`) or also (`docs/reference/api.md`) need to be edited. I got the feeling that `docs/reference/api.md` might be stale, but edited it anyway

Add community SDK section to API docs

---

.github/workflows/master_only.yml

- Fix master only workflow regex for semver to allow for prerelease suffix ie `v0.7.0-rc.1`, `v0.7.0-alpha`.
Fixes #
```release-note
```

Fix Github Actions versioned image push

---

docs/reference/api.md
docs/reference/api/README.md

including reference to community-provided Node.js SDK
"Backports" the original PR #992 into the v0.7-branch so changes get published in the docs.
cc @woop 
Does not fix an issue
```release-note
NONE
```

Add community SDK section to API docs [Backporting v0.7-branch]

---

.github/workflows/master_only.yml
datatypes/java/README.md
docs/contributing/development-guide.md
infra/charts/feast/charts/feast-core/README.md
infra/charts/feast/charts/feast-core/values.yaml
infra/charts/feast/charts/feast-jobcontroller/README.md
infra/charts/feast/charts/feast-jobcontroller/values.yaml
infra/charts/feast/charts/feast-jupyter/README.md
infra/charts/feast/charts/feast-jupyter/values.yaml
infra/charts/feast/charts/feast-serving/README.md
infra/charts/feast/charts/feast-serving/values.yaml
infra/charts/feast/requirements.lock
infra/docker-compose/.env.sample
infra/scripts/validate-version-consistency.sh
serving/README.md

**Why we need it**:
Currently the Feast deployments (helm, docker-compose) reference runs the last release version in the current master's infra.
- This can break if infra and release version are not completely compatible #957  
Currently version lint will fail on master when a new release candidate in tagged in a vX.Y-branch release branch
**What this PR does**:
Updates version lint script to become  branch aware:
- Version lint script now lints for 3 kinds of versions:
- Maven version:  Feast version set in maven.
- Docker version: Docker image version tag to use in deployments.
- uses `develop` on master, versioned tag on vX.Y-branch release branches.
- Release version: Stable release version without release candidates.
- uses repo wide latest stable version on master.
- uses last …

Add Branch and RC Awareness to Version Lint & Fix Semver Regex

---

infra/scripts/validate-version-consistency.sh

Fixes lint-version not pulling tags before linting versions.
- Required as Github Actions uses a [no tag fetch](https://github.com/feast-dev/feast/runs/1100675375#step:3:31) running in github actions.
Fixes #
```release-note
```

Fix lint version not pulling tags.

---

sdk/go/auth.go
sdk/go/auth_test.go

Fixes Go SDK outputting a extra `:` in `Authorization` grpc metadata header used for authentication:
- `Bearer: TOKEN` instead of `Bearer TOKEN`, the latter which is correct.
- Bug causes Go SDK authentication with Feast to fail.
Fixes #
```release-note
```

Fix Go SDK extra colon in metadata header for Authentication

---

storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetriever.java
storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetrieverTest.java

Currently there's no check if `indexMissingValue` is empty before making second (fallback) request to redis. That cause exception
```
io.lettuce.core.RedisCommandExecutionException: ERR wrong number of arguments for 'mget' command
```
Fixes #
```release-note
```

In redis retrieval call fallback only when there's missing keys

---

infra/scripts/test-end-to-end-batch-dataflow.sh
tests/e2e/bq/bq-batch-retrieval.py

Due to some internals of dataflow implementation - it takes some time before FeatureSetSpec is propagated to all workers. It means that even when FeatureSet is in READY status, job can still drop FeatureRows for a while.
In this PR we explicitly wait until FeatureSet is READY to apply some timeout before ingestion.
Fixes #
```release-note
```

In e2e tests wait for FeatureSet ready to make a pause before ingestion

---

core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
core/src/test/java/feast/core/auth/CoreServiceAuthorizationIT.java

Current hardcoding port to 45124 causes port conflict.
Fixes #901 
```release-note
NONE
```

Probe for available port to prevent race condition

---

job-controller/src/main/java/feast/jobcontroller/runner/dataflow/DataflowRunnerConfig.java

When selecting a region that Dataflow is not supported in, user is not receiving a descriptive exception.
Fixes #812 
```release-note
NONE
```

Add validation for dataflow region

---

sdk/python/feast/job.py

Current implementation attempts to append to a Dict instead of List, which throws `AttributeError`. Also, last chunk of data which is less than max_chunk_size is not returned.
Fixes #944, #948 
```release-note
NONE
```

Fix py SDK historical retrieval job to chunked dataframe conversion

---

common/src/main/java/feast/common/logging/AuditLogger.java
docs/administration/audit-logging.md

Adds `identity` field to Fluentd Message Audit Logs to output user identity.  
Fixes #
```release-note
Fluentd Message Audit Logs now output user identity in the 'identity' field..
```

Add User Identity in Fluentd Message Audit Logs

---

.github/workflows/master_only.yml
infra/scripts/setup-common-functions.sh
infra/scripts/validate-version-consistency.sh

Forward ports lint version script fixes:
- Fixes issue where lint-version sorts prerelease versions higher than stable versions. (ie `v0.7.0-rc.3` was higher sorted than `v0.7.0`)
- Refactor out version parsing from tags into `get_tag_release()` common function.
- Use `get_tag_release` in master docker push workflow to determine highest merged versioned tag.
Fixes #
```release-note
```

Forward port Lint Version script fixes

---

ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
ingestion/src/test/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFnTest.java

Every time job is being restarted metrics labels produced by ingestion job are changed. Thus it can be treated as completely different metric (in prometheus terms).
This PR changes jobName label in row metrics to produce stable metrics between restarts.
Fixes #
```release-note
```

Provide stable jobName in RowMetrics labels

---

ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java
ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
ingestion/src/test/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFnTest.java

Backporting "Stable job name in metrics" from master
Fixes #
```release-note
```

[v0.7-branch] Provide stable jobName in RowMetrics labels (#1028)

---

spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala

Support SSL option for redis connections (aka "encryption in-transit" in AWS ElastiCache) in the Spark job. SSL is already supported by lettuce/springboot out of the box, so this brings Spark to feature parity.
```release-note
NONE
```

add redis SSL support to the offline-to-online ingestion job

---

.prow/config.yaml
infra/scripts/test-end-to-end-redis-cluster.sh

New e2e test will involve the need for google cloud sdk auth inorder to access BQ table.
Fixes #
```release-note
NONE
```

Add svc account volume mount to prow jobs

---

core/src/main/java/feast/core/validators/Matchers.java
infra/scripts/test-docker-compose.sh
sdk/python/feast/feature.py
sdk/python/feast/feature_table.py
tests/e2e/test-register.py

Fixes the following:
1. docker-compose test are currently failing due to missing GCP credentials
2. Usage of polling instead of sleep for e2e tests
3. Using BQ source should allow dataset to contain underscore
4. Flaky e2e test due to ordering of entities and features (which are returned as a set)
Fixes #
```release-note
NONE
```

Cleanup e2e and docker-compose tests

---

infra/terraform/aws/README.md
infra/terraform/aws/eks.tf
infra/terraform/aws/emr.tf
infra/terraform/aws/helm.tf
infra/terraform/aws/iam.tf
infra/terraform/aws/online_store.tf
infra/terraform/aws/rds.tf
infra/terraform/aws/s3.tf
infra/terraform/aws/variables.tf

This contains an example tf config for setting up Feast on AWS. This includes: 
* VPC and subnets
* EKS cluster
* Redis (via Elasticache)
* Configuring and applying Helm charts via terraform helm provider
* Postgres DB (via serverless Aurora)
* Optional persistent EMR Spark cluster
* S3 bucket to store logs jars and temporary data
Does not (yet) include:
* Kafka
```release-note
NONE
```

terraform config for aws

---

sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/pyspark/aws/jobs.py

This code runs the spark job on EMR. It also add a CLI command to kick off the job for debugging, but I expect this code will primarily be run by the upcoming job service (mainly because it requires a non-trivial amount of configuration).

Run offline-to-online ingestion job on EMR

---

spark/ingestion/pom.xml
spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/registry/proto/LocalProtoRegistry.scala
spark/ingestion/src/main/scala/feast/ingestion/registry/proto/ProtoRegistry.scala
spark/ingestion/src/main/scala/feast/ingestion/registry/proto/ProtoRegistryFactory.scala
spark/ingestion/src/main/scala/feast/ingestion/registry/proto/StencilProtoRegistry.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/DefaultSource.scala
spark/ingestion/src/main/scala/feast/ingestion/utils/ProtoReflection.scala
spark/ingestion/src/main/scala/feast/ingestion/utils/TypeConversion.scala
spark/ingestion/src/main/scala/feast/ingestion/validation/TypeCheck.scala
spark/ingestion/src/test/proto/com/example/source.proto
spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
spark/ingestion/src/test/scala/feast/ingestion/SparkSpec.scala
spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
spark/ingestion/src/test/scala/feast/ingestion/UnitSpec.scala
spark/ingestion/src/test/scala/feast/ingestion/helpers/DataHelper.scala
spark/ingestion/src/test/scala/feast/ingestion/helpers/RedisStorageHelper.scala
spark/ingestion/src/test/scala/feast/ingestion/registry/StencilSpec.scala

This PR replaces current (beam) Ingestion Job with spark version. However, several changes are introduced:
1. Input to streaming pipeline is arbitrary* protobuf. Message class must be provided through `FeatureTable` configuration.
2. Ingestion job stores only to redis and writes deadletters as parquet files.
Currently there are two ways to make protobuf class available for job in runtime:
1. Compile proto & pack it into jar and add jar to list of files on Spark-submit.
This option has a limitation that compiled class must be linked to shadowed protobuf library `com.google.protobuf.vendor`
since in our job we had to shadow protobuf due to conflicts with spark dependencies.
2. Use proto registry (external service) as source of proto descriptors. As …

Streaming Ingestion Pipeline with Spark

---

sdk/python/feast/cli.py
sdk/python/feast/pyspark/aws/jobs.py

Add SDK glue code and the corresponding CLI command to kick off the streaming ingestion on EMR, check if it is already running, stop it and list running jobs.
```release-note
Added CLI commands `start-stream-to-online` and `stop-stream-to-online` to kick off stream ingestion jobs 
```

CLI command to start/stop/list streaming ingestion job on emr

---

common-test/src/main/java/feast/common/it/DataGenerator.java
core/src/main/java/feast/core/model/DataSource.java
core/src/main/resources/db/migration/V2.9__Data_Source_Created_Timestamp_Column.sql
go.mod
go.sum
protos/feast/core/DataSource.proto
sdk/python/feast/client.py
sdk/python/feast/data_source.py
sdk/python/feast/loaders/file.py
sdk/python/feast/pyspark/aws/jobs.py
sdk/python/feast/staging/storage_client.py
sdk/python/tests/test_client.py
sdk/python/tests/test_feature_table.py
spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/sources/bq/BigQueryReader.scala
spark/ingestion/src/main/scala/feast/ingestion/sources/file/FileReader.scala
spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
tests/e2e/test-register.py

`created_timestamp_column` in DataSource will help with deduplicating values for the same entity on historical retrieval.
`timestamp_column` renames to `event_timestamp_column` to avoid confusion
Fixes #
```release-note
```

Add created_timestamp_column to DataSource. Rename timestamp_column -> event_timestamp_column

---

sdk/python/feast/client.py
sdk/python/feast/constants.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/feast/staging/storage_client.py
tests/e2e/conftest.py
tests/e2e/test_online_features.py

This PR aim to glue together various backend implementations of job submission and Feast SDK by introducing some cleaner structure with `SparkJob`, `SparkJobParameters` interfaces and separate `launch` modules.
Also `offline_to_online_ingestion` is added to `JobLauncher` interface. Implementations for standalone & dataproc launchers provided as well.
Fixes #
```release-note
```

"Start Offline-to-online ingestion" method in Python SDK

---

sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/staging/storage_client.py

Currently, the dataproc launcher is using it's own implementation of staging client rather than reusing existing staging client in feast.staging.storage_client. This PR consolidate the implementation.
This would also help https://github.com/feast-dev/feast/pull/1061 to use the existing staging client as well.
Fixes #
```release-note
NONE
```

Use existing staging client for dataproc staging

---

sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/constants.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/historical_feature_retrieval_job.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/__init__.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/local.py

This adds a EMR launcher in line with the new launcher interface. It does historical retrieval and offline-to-online retrieval. I'll do stream ingestion next, figured this is large enough.
A few notable bits (aside from just moving things around):
* this adds redis configuration to the SDK client, which exists solely to be passed to the spark job. We might want to make it optional
* I've converted a lot of the existing EMR code to aws/emr_utils.py, but left the old code in for now -- will clean it up in a separate PR
* added a convenience method to upload a pandas DF to s3 (currently only supported by EMR launcher). It is not strictly necessary but comes in handy for testing/cli
Fixes #
**Does this PR introduce a …

EMR launcher

---

sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/__init__.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/local.py

Add streaming ingestion job support to the EMR launcher and the launcher interface
```release-note
NONE
```

Add EMR streaming job launcher

---

.github/workflows/complete.yml
.github/workflows/master_only.yml
Makefile
infra/docker/jupyter/Dockerfile
infra/scripts/test-docker-compose.sh
infra/scripts/test-end-to-end-redis-cluster.sh
sdk/python/feast/client.py
sdk/python/feast/config.py
sdk/python/feast/constants.py
sdk/python/feast/staging/storage_client.py
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/HashTypePersistence.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/Persistence.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
spark/ingestion/src/test/scala/feast/ingestion/helpers/RedisStorageHelper.scala
tests/e2e/conftest.py
tests/e2e/test_online_features.py

Refactor Redis Sink in Ingestion Job to produce format readable by serving:
1. Keys are generated with RedisKeyV2 proto
2. Java (`com.google.common.hash`) implementation of MurMur hash is used, since its version is better compatible with other implementations.
Fixes #
```release-note
```

Use RedisKeyV2 as key serializer and java murmur implementation in Redis Sink

---

sdk/python/feast/client.py
sdk/python/feast/constants.py
sdk/python/feast/pyspark/launcher.py

Currently, historical feature retrieval accepts only Datasource as input. This PR enables the user to supply a Panda dataframe instead, which will then be uploaded to a staging location.
Staging location configuration for the different spark clusters are also merged into a single key in this PR.
Fixes #
```release-note
Added support for supplying Pandas DataFrames when running historical retrieval
```

Accept Pandas dataframe as input for historical feature retrieval

---

.github/workflows/master_only.yml
core/src/main/java/feast/core/validators/DataSourceValidator.java
infra/charts/feast/values.yaml
sdk/python/feast/constants.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/historical_feature_retrieval_job.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/requirements-ci.txt
sdk/python/requirements-dev.txt
sdk/python/tests/test_as_of_join.py
spark/ingestion/pom.xml
spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
tests/e2e/requirements.txt
tests/e2e/test_online_features.py

Add avro parser to Streaming Ingestion Job if `AvroFormat` was set in `Source`. Relies on `jsonSchema` passed with `AvroFormat` to generate `DataFrame` structure.
Fixes #
```release-note
```

Streaming Ingestion Job supports AVRO format as input

---

sdk/python/feast/cli.py
sdk/python/setup.py

- Puts emr-related cli commands under `jobs` group, where we'll be adding future support for dataproc as well.
- Removes kafka dependencies.
Fixes #
```release-note
sync_offline_to_online, start_stream_to_online, stop_stream_to_online and list_jobs commands in cli will now be found under `jobs` group
```

Cleanup CLI and Python dependencies

---

infra/terraform/aws/eks.tf
infra/terraform/aws/emr.tf
infra/terraform/aws/helm.tf
infra/terraform/aws/msk.tf
infra/terraform/aws/online_store.tf
infra/terraform/aws/rds.tf
infra/terraform/aws/s3.tf
infra/terraform/aws/variables.tf

Apply `terraform fmt`, add tags to every resource, flip the default for persistent_emr_cluster param
```release-note
NONE
```

terraform cleanup: tags, formatting, better defaults

---

infra/charts/feast/charts/feast-jupyter/README.md
infra/charts/feast/charts/feast-jupyter/templates/deployment.yaml
infra/terraform/aws/helm.tf

Automatically provide all the necessary settings on AWS to the jupyter pod via terraform. 
Fixes #
```release-note
NONE
```

Configure jupyter env on AWS via terraform

---

core/src/main/java/feast/core/validators/Matchers.java
core/src/test/java/feast/core/validators/MatchersTest.java

Fixes #
```release-note
NONE
```

Fix java class name validation

---

.github/workflows/complete.yml

The load test github action is still using Feast 0.7 ingestion retrieval flow, and is broken when job controller is removed from the docker compose setup. This PR will remove the load test from github action. It should be restored when we adapt the load test to fit Feast 0.8 workflow.
Fixes #
```release-note
```

Remove load test from github action

---

sdk/python/feast/client.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/feast/staging/storage_client.py
sdk/python/tests/test_historical_feature_retrieval.py

There is currently no unit test for cases where the input to the historical feature retrieval output is a panda dataframe. This PR add the test.
Fixes #
```release-note
```

Add unit test for historical retrieval with panda dataframe

---

spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala

It causes mysterious NoClassDefFound errors on EMR so disabling it for now by default
Fixes #
```release-note
NONE
```

disable statsd by default for spark

---

examples/minimal/Feast 101.ipynb
infra/docker-compose/docker-compose.yml

Currently, the demo notebook assumes that the user has access to a GCS bucket, which may or may not be the case. The example has been adapted to use local file system instead, but also provides code snippets that allows the user to easily switch to using GCS to store their feature tables.
Add more instructions as well to make the demo clearer.
Fixes #
```release-note
```

Add more explanations to the demo notebook, use local file system instead of GCS by default

---

infra/terraform/aws/helm.tf
protos/feast/core/Store.proto
sdk/python/requirements-ci.txt
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClient.java

Support connecting to redis with ssl in feast-serving
```release-note
NONE
```

support redis ssl in feast-serving

---

infra/docker/jobservice/Dockerfile
infra/docker/jupyter/Dockerfile
sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/aws/emr_utils.py

* Fix object path math in client staging uploader
* Add random suffix to the historical retrieval output location
* EMR job now actually checks for status
* add boto3 dep
Fixes #
```release-note
NONE
```

Multiple tiny AWS related fixes

---

sdk/go/client.go

This PR adds support for custom grpc dial options in Go SDK. Currently there is now way for the clients to specify custom grpc.DialOption
Fixes #1042 
```release-note
Adding support for custom grpc dial options in Go SDK
```

Adding support for custom grpc dial options in Go SDK

---

sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/local.py

Job Service will need those to implement its API calls. 
Fixes #
```release-note
NONE
```

Add get_by_id and list_jobs interface to the launcher interface and implement it for EMR

---

.prow/config.yaml
infra/scripts/test-end-to-end-gcp.sh
infra/scripts/test-end-to-end.sh

E2E flow in prow is working

---

serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
serving/src/main/java/feast/serving/specs/CachedSpecService.java
serving/src/test/java/feast/serving/it/ServingServiceIT.java

In the past, we didn't allow changes to feature types so this validation was not necessary. As we think about implementing deletion of feature tables, we'll need to consider how old values stored in redis will be retrieved. This PR is the first step to handling older values that are based of older types.
Fixes #
```release-note
NONE
```

Add validation when feature type is changed

---

core/src/main/java/feast/core/model/FeatureTable.java
core/src/main/java/feast/core/model/FeatureV2.java
core/src/main/java/feast/core/service/SpecService.java
core/src/test/java/feast/core/service/SpecServiceIT.java

As we're moving towards supporting deletion of feature tables, this is a step towards it by allowing changes to:
- the entities in a feature table
- the features and their types in a feature table
Fixes #
```release-note
Users can now update their entities and features in a feature table.
```

Allow entities and features to be updated

---

docs/user-guide/feature-retrieval.md
sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/data_source.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/historical_feature_retrieval_job.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/tests/test_historical_feature_retrieval.py
tests/e2e/test_historical_features.py
tests/e2e/test_online_features.py

Currently, created timestamp columns are mandatory arguments for Datasource. While this is true for Feature Table datasource, it should be optional for Entity datasource. This PR will make created timestamp column optional for DataSource, BigQuerySource and FileSource.
Fixes #
```release-note
```

Make created timestamp column optional

---

.prow/config.yaml
infra/scripts/test-integration.sh
tests/integration/conftest.py

This PR add integration tests stage to prow. Once this is merged to master, we will be able to start adding integration test and run it via CI.
Fixes #
```release-note
```

Scaffolding for integration tests

---

protos/feast/core/JobService.proto
sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/constants.py
sdk/python/feast/job_service.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/feast/remote_job.py
sdk/python/tests/test_remote_job.py

This implements end-to-end flow for historical retrieval via job service. Tested only manually for now, until we include job service setup in e2e tests.
Fixes #
```release-note
NONE
```

Add historical retrieval via job service

---

examples/minimal/minimal_ride_hailing.ipynb
infra/docker/jupyter/Dockerfile

The current minimal Jupyter notebook doesn't work because it requires `confluent_kafka` to be installed.
```release-note
None
```

Add confluent kafka installation to minimal notebook

---

spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala

Instead of just map columns with different name - this PR allows to use expressions (spark style) to enable simple transformations of features during ingestion.
Example
```
fieldMapping = {
"feature1": "cos(feature1)",
"feature2": "feature2 / feature1"
}
```
Available functions: https://spark.apache.org/docs/2.3.1/api/sql/index.html
Fixes #
```release-note
```

Allow spark expressions in field mapping during Ingestion

---

serving/src/main/java/feast/serving/config/FeastProperties.java
serving/src/main/java/feast/serving/config/SpecServiceConfig.java
serving/src/main/resources/application.yml
serving/src/test/java/feast/serving/it/ServingServiceIT.java

Following this [PR](https://github.com/feast-dev/feast/pull/1105), this PR adds an integration test that checks for `NOT FOUND` values in online retrieval when feature types are changed.
Fixes #
```release-note
NONE
```

Add serving integration test for updated feature type

---

sdk/python/feast/loaders/ingest.py

Fixes flaky e2e tests which involves ingesting data into BQ.
Fixes #
```release-note
NONE
```

Ensure job is completed when ingesting to BQ

---

common-test/src/main/java/feast/common/it/SimpleCoreClient.java
core/src/main/java/feast/core/grpc/CoreServiceImpl.java
core/src/main/java/feast/core/model/FeatureTable.java
core/src/main/java/feast/core/service/SpecService.java
core/src/main/resources/db/migration/V3.0__Feature_Table_Deletion.sql
core/src/test/java/feast/core/service/SpecServiceIT.java
protos/feast/core/CoreService.proto
protos/feast/core/FeatureTable.proto
sdk/python/feast/client.py

This PR enables feature table deletion. The following has been implemented:
- `is_deleted` flag to check if a table is deleted or not
- Updated feature table metadata to include hash to determine if job needs to be restarted
- Added `delete_feature_table` method to Python SDK
Fixes #
```release-note
Users can now delete feature tables.
```

Add feature table deletion

---

infra/scripts/test-integration.sh
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
tests/integration/conftest.py
tests/integration/fixtures/job_parameters.py
tests/integration/fixtures/launchers.py
tests/integration/test_launchers.py
tests/integration/test_simple.py

get_by_id and list_jobs methods were added to the launcher interface on https://github.com/feast-dev/feast/pull/1095, but was not implemented for Dataproc launcher. This PR provides the implementation.
Fixes #
```release-note
```

Implement list job and get job methods for Dataproc launcher

---

tests/e2e/conftest.py
tests/e2e/fixtures/client.py

Ability to run e2e tests in non-default project

---

tests/integration/test_launchers.py

Currently the python sdk integration test is flaky, as the cancel job API may fail due to the job not being in Ready state when the api is called. This PR add a check for job status before cancelling the job.
Fixes #
```release-note
```

Wait for job to be ready before cancelling

---

infra/charts/feast/README.md
infra/charts/feast/charts/feast-core/README.md
infra/charts/feast/charts/feast-core/templates/deployment.yaml
infra/charts/feast/charts/feast-core/values.yaml
infra/charts/feast/charts/feast-jobservice/Chart.yaml
infra/charts/feast/charts/feast-jobservice/README.md
infra/charts/feast/charts/feast-serving/README.md
infra/charts/feast/charts/feast-serving/templates/deployment.yaml
infra/charts/feast/charts/feast-serving/values.yaml

…
Currently, users has no way to mount existing Kubernetes secrets to Feast services. One of the consequences of this is that Feast Core and Feast Serving would not be able to use GCP authentication, since there is no way to set up Google Application Credential.
This PR adds a new helm values called `secrets`, which the user can provide the list of kubernetes secrets to be mounted. They can then use envoverride variable to setup the credentials.
Fixes #
```release-note
```

Allow user to specify custom secrets to be mounted on Feast Serving and Feast Core pods

---

.prow/config.yaml
infra/docker/ci/Dockerfile

Signed-off-by: Oleg Avdeev <oleg.v.avdeev@gmail.com>
Trigger AWS cicd from prow. It won't succeed yet since that would require the other AWS CICD PR to land, but will allow me to test the other PR.
```release-note
NONE
```

Add Prow to AWS codebuild trigger

---

.github/workflows/complete.yml
Makefile
docs/coverage/java/pom.xml
infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
infra/docker-compose/docker-compose.yml
infra/docker/jobservice/Dockerfile
infra/scripts/test-docker-compose.sh
infra/scripts/test-end-to-end-gcp.sh
pom.xml
sdk/python/feast/client.py
sdk/python/feast/constants.py
sdk/python/feast/job_service.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
tests/e2e/conftest.py
tests/e2e/fixtures/client.py
tests/e2e/fixtures/external_services.py
tests/e2e/fixtures/feast_services.py

1. SDK / JobService should be able to configure `statsd`, `deadletterPath` and `stencilURL` optional parameters of IngestionJobs.
2. Non-default project passed to Job via SDK / JobService
Fixes #
```release-note
```

Optional IngestionJob parameters passed by Spark Launcher

---

infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml

Fixes 
```
Traceback (most recent call last):
File "/opt/conda/bin/feast", line 33, in <module>
sys.exit(load_entry_point('feast', 'console_scripts', 'feast')())
File "/opt/conda/bin/feast", line 25, in importlib_load_entry_point
return next(matches).load()
File "/opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
module = import_module(match.group('module'))
File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in …
```

JobService is in crashloop after installing helm chart

---

infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml

Core Service name can be overridden on helm installation, so `FEAST_CORE_URL` should not be hardcoded in helm chart
Fixes #
```release-note
```

Drop hardcoded FEAST_CORE_URL env from JobService helm chart

---

sdk/python/feast/client.py

Previously it was mandatory to specify project in `get_historical_features` and `client.project` was not used, which is a bug.
This PR proposes to sync signatures of `get_historical_features` & `start_offline_to_online_ingestion` and use project from client context only.
Fixes #
```release-note
```

In Historical Retrieval (SDK) use project from client context

---

serving/src/main/java/feast/serving/util/Metrics.java

https://github.com/feast-dev/feast/issues/1036
the request latency is sometimes larger than 50 ms. so, we need more buckets which are larger than 50 ms.
there are some options. one option is to use the default buckets, which are up to 10 seconds instead of 50 ms.
in this pr, buckets of feast_serving_request_latency_seconds are updated to {.005, .01, .025, .05, .075, .1, .25, .5, .75, 1, 2.5, 5, 7.5, 10} (which are same as feast_core_request_latency_seconds) instead of {0.001, 0.002, 0.004, 0.006, 0.008, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.05}
Fixes #
https://github.com/feast-dev/feast/issues/1036
```release-note
Buckets of feast_serving_request_latency_seconds …
```

use default buckets in latency histogram

---

infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
infra/scripts/codebuild_runner.py
infra/scripts/setup-e2e-env-aws.sh
infra/scripts/test-end-to-end-aws.sh
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
spark/ingestion/pom.xml
tests/e2e/conftest.py
tests/e2e/fixtures/client.py
tests/e2e/test_historical_features.py
tests/e2e/test_online_features.py

Add CI/CD pipeline for AWS.
Notable changes: 
* shade kafka in the ingestion jar
* add boto3 to the feast-ci image
* tweak some timeouts in the e2e test suite
Fixes #
```release-note
NONE
```

e2e test fixes to make them work on AWS

---

.prow/config.yaml

CICD pipeline doesn't currently support more than one concurrent run
```release-note
NONE
```

Limit concurrency on e2e test runs to 1

---

sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
spark/ingestion/pom.xml
spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
spark/ingestion/src/test/scala/feast/ingestion/SparkSpec.scala
spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala

This PR makes deadletter path unique per feature table & job run (using spark app id)
Fixes #
```release-note
```

Add feature table name & job id to deadletter destination

---

spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
tests/e2e/test_online_features.py

[E2E] In Streaming Test filter kafka consumers by group id prefix

---

sdk/python/feast/data_source.py
sdk/python/tests/test_client.py
sdk/python/tests/test_feature_table.py
spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
tests/e2e/test_online_features.py
tests/e2e/test_register.py

To keep SDK API consistent (currently created timestamp is optional for File & BQ sources) this PR make optional `created_timestamp_column` in KafkaSource as well
Fixes #
```release-note
```

Make created_timestamp property optional in KafkaSource

---

spark/ingestion/src/main/scala/feast/ingestion/registry/proto/StencilProtoRegistry.scala

Fixes #
```
Caused by: java.io.NotSerializableException: com.gojek.de.stencil.cache.DescriptorCacheLoader
Serialization stack:
- object not serializable (class: com.gojek.de.stencil.cache.DescriptorCacheLoader, value: com.gojek.de.stencil.cache.DescriptorCacheLoader@5fb7af07)
- field (class: com.gojek.de.stencil.client.URLStencilClient, name: cacheLoader, type: class com.gojek.de.stencil.cache.DescriptorCacheLoader)
- object (class com.gojek.de.stencil.client.URLStencilClient, com.gojek.de.stencil.client.URLStencilClient@70c56f9d)
- field (class: feast.ingestion.registry.proto.StencilProtoRegistry, name: stencilClient, type: interface …
```

Fix stencil client serialization issue

---

.github/workflows/release.yml

The current github release action is broken because the repository is not checkout before running the subsequent scripts.
Fixes #
```release-note
```

Add checkout action before proceeding with get version tasks

---

.github/workflows/release.yml

Currently, the release process failed because the github action runner is not authenticated to retrieve resources from GCP.
Fixes #
```release-note
```

Enable service account on gcloud action

---

.github/workflows/master_only.yml
.github/workflows/release.yml

Makefile no longer contains jobcontroller build and push steps. It should be updated to jobservice.
Fixes #
```release-note
NONE
```

Update jobcontroller to jobservice

---

infra/scripts/sync-helm-charts.sh

The publish helm chart release step is failing due to failure to build the chart, caused by missing repository.
Fixes #
```release-note
```

Add bitnami repository before building helm chart

---

.github/workflows/complete.yml
.github/workflows/master_only.yml
Makefile
infra/docker/ci/Dockerfile
infra/docker/jobservice/Dockerfile
infra/docker/jupyter/Dockerfile

Currently, images are built with `dev` default value for REVISION arg when building images eg. [Dockerfile](https://github.com/feast-dev/feast/blob/master/infra/docker/core/Dockerfile#L32). 
This results in the following when calling version API.
```
{'serving': {'url': 'example.feast:6566', 'version': 'dev'},
'core': {'url': 'example.feast:6565', 'version': 'dev'}}
```
Fixes #
```release-note
NONE.
```

Fix revision arg when building image

---

.github/workflows/release.yml
infra/scripts/sync-helm-charts.sh

- `helm repo add` command has additional parameter when being called in sync-helm-charts.sh bash script
- context is not provided when running build-push to dockerhub
Fixes #
```release-note
NONE
```

Fix helm repo addition and dockerhub path context

---

Makefile
infra/scripts/setup-e2e-env-aws.sh
infra/scripts/test-end-to-end-aws.sh
tests/e2e/fixtures/base.py

feast_version was not set in AWS e2e pipeline
```release-note
NONE
```

make aws e2e tests use correct feast_version

---

.github/workflows/master_only.yml

Github actions will be deprecating `set-env` as described in this [blog post](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). Thus, we need to update it before it causes issues to our ci/cd.
Fixes #
```release-note
NONE
```

Fix github workflow deprecating env variable

---

.github/workflows/complete.yml
infra/scripts/test-docker-compose.sh
protos/feast/core/JobService.proto
sdk/python/feast/client.py
sdk/python/feast/constants.py
sdk/python/feast/job_service.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/__init__.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/feast/remote_job.py
sdk/python/tests/feast_core_server.py
sdk/python/tests/test_streaming_control_loop.py

See #1140 for start of the discussion. Compared to that PR, this addresses some comments and adds tests for the control loop logic.
```release-note
NONE
```

Jobservice control loop (based on #1140)

---

.github/workflows/complete.yml

Fixes connection resets for Maven on `publish-ingestion-jar`
See https://github.com/actions/virtual-environments/issues/1499#issuecomment-718396233
```release-note
NONE
```

Fix connection resets in CI for Maven

---

sdk/python/feast/client.py

Currently, in `ingest` method of python SDK client, if `feature_table` parameter is a str, the `name` variable will not be instantiated correctly. This PR addresses that.
Fixes #
```release-note
NONE
```

Fix missing name variable instantiation

---

.github/workflows/complete.yml
.github/workflows/master_only.yml
infra/docker-compose/.env.sample
infra/docker-compose/docker-compose.yml
infra/scripts/test-end-to-end-gcp.sh
infra/scripts/test-end-to-end.sh
tests/e2e/fixtures/feast_services.py

This PR addresses 
1. Issue with pytest parametrized fixtures dependencies: currently resolving doesn't work, thus I turned off auth parametrization
2. mvn cache issue in e2e tests
3. ingestion jar building fails. It was moved from "self-hosted" runner and now jar is being shared via flow artifactis
Fixes #
```release-note
```

Stabilize flaky e2e tests

---

.github/workflows/mirror.yml

Current mirror workflow uses `webfactory/ssh-agent@v0.4.0` which has been updated to v0.4.1 in light of recent github actions `set-env` deprecation. 
Fixes #
```release-note
NONE
```

Bump ssh-agent version

---

sdk/python/docs/index.rst
sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/config.py
sdk/python/feast/constants.py
sdk/python/feast/grpc/auth.py
sdk/python/feast/job_service.py
sdk/python/feast/loaders/ingest.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/wait.py
sdk/python/tests/grpc/test_auth.py

Currently, constants used for `Config` class are declared separately from default values and the term is used interchangeably with config options, making it difficult to maintain as the number of configurable options increase.
This PR addresses the following:
- Address constants which have different parameter name to be the same
eg. ```CONFIG_SPARK_HISTORICAL_FEATURE_OUTPUT_FORMAT = "historical_feature_output_format"``` to
```CONFIG_HISTORICAL_FEATURE_OUTPUT_FORMAT = "historical_feature_output_format"```
- Add documentation for configurable options.
Fixes #
```release-note
NONE
```

Refactor configurable options and add sphinx docs

---

.github/workflows/complete.yml
.github/workflows/master_only.yml
.github/workflows/release.yml
Makefile
infra/docker/core/Dockerfile
infra/docker/jobservice/Dockerfile
infra/docker/jupyter/Dockerfile
infra/docker/serving/Dockerfile
infra/scripts/test-docker-compose.sh

This PR ensures the following consistency:
- Use of SHA for master branch builds
- Use of version for release branch builds to GCR
- Shift GCR version branch builds to release workflow
Fixes #
```release-note
NONE
```

Ensure consistency of github workflow

---

common-test/src/main/java/feast/common/it/SimpleCoreClient.java
core/src/main/java/feast/core/controller/CoreServiceRestController.java
core/src/main/java/feast/core/model/FeatureTable.java
core/src/main/java/feast/core/model/FeatureV2.java
core/src/main/java/feast/core/service/SpecService.java
core/src/test/java/feast/core/controller/CoreServiceRestIT.java
core/src/test/java/feast/core/service/SpecServiceIT.java
protos/feast/core/CoreService.proto
sdk/python/feast/client.py
sdk/python/feast/feature.py
sdk/python/tests/test_client.py

Currently, `listFeatures` method is not updated to return features from feature tables, but rather feature sets.
This PR includes:
- Updated `ListFeaturesResponse` proto
- Updated `SpecService` to retrieve features from feature tables
- Updated REST (GET) endpoint for listing features
Fixes #
```release-note
Users can now retrieve features registered in feature tables.
```

Update Feast Core list features method

---

spark/ingestion/pom.xml
spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/HashTypePersistence.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/Persistence.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/SparkRedisConfig.scala
spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
spark/ingestion/src/test/scala/feast/ingestion/helpers/RedisStorageHelper.scala

Since the release of Feast 0.8, the Redis ingestion is performed via Spark ingestion module rather than the existing Redis storage module. Hence, #955 is not applicable to Feast 0.8. 
For the current implementation, instead of a global value of ttl which would be applicable to all Redis key, the ttl will be computed based on the max ages of all the feature tables associated with the Redis Key. For example, if two feature table are associated with the Redis key, the ttl will be computed as follows:
```
ttl = max(event_timestamp_feature_table_1 + max_age_feature_table_1, event_timestamp_feature_table_2 + max_age_feature_table_2) - current time
```
In the event where any of the feature table associated …

Expires Redis Keys based on Feature Table Max Age

---

spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/metrics/StatsdReporterWithTags.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
spark/ingestion/src/main/scala/org/apache/spark/metrics/source/RedisSinkMetricSource.scala
spark/ingestion/src/test/scala/feast/ingestion/metrics/StatsReporterSpec.scala

`RedisSinkMetricSource` cannot be initialized with `MetricsSystem` in executor, since `SparkEnv` is not yet available at the moment of `MetricsSystem.start`. To resolve it I moved `RedisSinkMetricSource` registering inside `RedisSinkRelation`.
I also replaced `Librato-style` statsd format with `DogStatsD` extension, since it seems to be more stable (and it was previously used in ingestion job with Beam).
Fixes #
```release-note
```

Lazy metrics initialization (to correct pick up in executor)

---

sdk/python/feast/constants.py
sdk/python/feast/pyspark/historical_feature_retrieval_job.py
sdk/python/feast/pyspark/launcher.py
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
spark/ingestion/src/main/scala/feast/ingestion/sources/bq/BigQueryReader.scala

When using BQ view as source for historical retrieval and batch ingestion there could be an issue with permissions. Since spark-bq connector first needs to materialize view before read it - it requires "create table" access, which could be problematic when view is located in different / uncontrolled project.
This PR introduces two configuration options
```
SPARK_BQ_MATERIALIZATION_PROJECT
SPARK_BQ_MATERIALIZATION_DATASET
```
that will be passed to both ingestion & historical retrieval jobs. This will make possible to use project / dataset where feast project has permissions to create table.
Fixes # …

Configurable materialization destination for view in BigQuerySource

---

.github/workflows/release.yml

Currently, the release workflow tag step indicates the source and target images in the wrong order resulting in the built image to be not found.
Fixes #
```release-note
NONE
```

Fix tag order for release workflow

---

spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala

To help distinguish (ingestion) metrics from different projects this PR adds project name as one of metrics dimensions.
Fixes #
```release-note
project label is added to ingestion job metrics
```

Add project name to metrics labels in Ingestion Job

---

spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala

Kafka produces too many debug logs (with info level) that quickly fill disk. This PR turn off those logs.
Fixes #
```release-note
```

Suppress kafka logs in Ingestion Job

---

core/src/main/java/feast/core/model/FeatureTable.java
core/src/test/java/feast/core/service/SpecServiceIT.java

Fixes #
Bug in `FeatureTale.equals` method that should check whether FeatureTable was changed. If only max age was updated - FeatureTable is not saved.
```release-note
```

Feature Table is not being update when only max_age was changed

---

spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/SparkRedisConfig.scala
spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala

Fixes #
With big values of max age (like 1 month) stored as Integer (2628000) converting to milliseconds that happens during writing to redis fails with overflow `2628000 * 1000 = -1666967296`. Thus all rows are being stored with negative expiry time and being deleted right away.
This PR suggests use Long instead of Int for max age. Alternative would be to do `maxAge.toLong` before converting to milliseconds, but it's very easy to miss that part.
```release-note
NONE
```

Features are not being ingested due to max age overflow

---

infra/scripts/setup-e2e-env-aws.sh

New pip resolver seems to either go into infinite loop, or take way too long with our requirements-dev.txt. Roll back to the older version for now.
Fixes #
```release-note
NONE
```

pin pip to 20.2 in aws tests for now

---

sdk/python/feast/client.py
sdk/python/feast/staging/entities.py
tests/e2e/test_historical_features.py

Using timestamps with micro or nano seconds in entity dataset leads to exception, when pandas dataframe is being converted to parquet:
```
ArrowInvalid: Casting from timestamp[ns] to timestamp[ms] would lose data: 1606826389820565000
```
This PR fix this by truncating timestamps provided by users up to milliseconds before calling `pandas.to_parquet`.
Fixes #
```release-note
Timestamps in entity dataset for historical retrieval are being truncated to ms
```

When staging entities dataset timestamps are being truncated to ms

---

.github/workflows/complete.yml
go.mod
go.sum
sdk/go/client.go
sdk/go/client_test.go
sdk/go/go.mod
sdk/go/go.sum
serving/pom.xml
serving/src/main/java/feast/serving/config/InstrumentationConfig.java
serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
serving/src/main/java/feast/serving/service/OnlineServingService.java

Adding grpc interceptors to serving and go client instead of manual tracing. That would allow cross-service tracing.
Fixes #
```release-note
`NewTraceableGrpcClient` constructor was added to go sdk. It allows to pass Tracer on client creation phase
```

Tracing GRPC interceptor in serving & go sdk

---

sdk/python/feast/constants.py
sdk/python/feast/loaders/file.py
sdk/python/feast/loaders/ingest.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/staging/entities.py
sdk/python/feast/staging/storage_client.py
sdk/python/tests/loaders/test_file.py

It makes EMR launcher use the standard uploader from `feast.staging`. Since EMR launcher relied on some functionality that didn't exist in the staging uploader, I had to update the staging uploader to support it.
Fixes #
```release-note
NONE
```

Refactor staging client uploader and use it in EMR launcher

---

spark/ingestion/src/main/scala/org/apache/spark/metrics/source/RedisSinkMetricSource.scala

Currently, for `ingested_row` counter metric, we would end up having multiple time series even for ingestion into the same feature table, due to different `job_id`. This PR removes `job_id` for counter metrics.
Fixes #
```release-note
Ingested row count metric will no longer have job_id label.
```

Remove job id from ingested row counter metric

---

sdk/python/feast/cli.py
sdk/python/feast/client.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/standalone/local.py

It was only implemented for EMR anyway. Also now that all upload paths are using the staging client, we can implement this once without having launcher-specific implementations.
```release-note
NONE
```

remove stage_dataframe from the launcher interface

---

.github/workflows/complete.yml
infra/docker/jobservice/Dockerfile
infra/docker/jupyter/Dockerfile
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/requirements-ci.txt
sdk/python/requirements-dev.txt
sdk/python/setup.py
spark/ingestion/pom.xml
spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/test/scala/feast/ingestion/SparkSpec.scala

Bump spark & bigquery-connector versions.
Base images for jobservice & notebook were also upgraded. As well as some python dependencies.
Fixes #1167
```release-note
If user has custom Spark installation - it should be upgraded to version 3.0.1.
```

Upgrading spark to 3.0.1

---

sdk/python/feast/constants.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/historical_feature_retrieval_job.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/k8s/__init__.py
sdk/python/feast/pyspark/launchers/k8s/k8s.py
sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/feast/staging/storage_client.py
sdk/python/requirements-dev.txt
sdk/python/setup.py

This allows Feast to run Spark jobs using spark-k8s-operator. 
To enable it:
1.  set `spark_launcher="k8s"`
2. set `spark_k8s_use_incluster_config` to `True` or `False`, depending on whether spark is running in the same k8s cluster or not. Make sure that feast serviceaccount has permissions to create `SparkApplication` resources. Provide KUBECONFIG if running Feast outside of the cluster.
3. Typically you need `spark_staging_location` and `historical_feature_output_location` to be set and use `s3a://` URL scheme if using S3.
4. Lastly, set `spark_k8s_job_template_path` to point to YAML template containing spark application configuration. Feast comes with one out of the box, but in production you'll likely want to provide a custom one.
**Additional …

Add spark k8s operator launcher

---

.github/workflows/complete.yml
infra/docker/ci/Dockerfile
infra/scripts/codebuild_runner.py
sdk/python/feast/cli.py

To guarantee compatibility with python 3.6 (as declared in our `setup.py`) this PR downgrades python version to 3.6 in CI docker image.
Fixes #
```release-note
NONE
```

CI should work on python 3.6

---

infra/scripts/codebuild_runner.py
infra/scripts/setup-e2e-env-sparkop.sh
infra/scripts/test-end-to-end-sparkop.sh
sdk/python/feast/constants.py
sdk/python/feast/pyspark/launchers/k8s/k8s.py
sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
tests/e2e/conftest.py
tests/e2e/fixtures/client.py
tests/e2e/test_historical_features.py

Added integration test for k8s spark operator support + a few bugfixes to make it actually succeed.
Fixes #
```release-note
NONE
```

Integration test for k8s spark operator support

---

serving/pom.xml
serving/src/main/java/feast/serving/config/InstrumentationConfig.java
serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java

This is a back port of https://github.com/feast-dev/feast/pull/1212, excluding client side change. Implementation of grpc tracing interceptor on golang and java client will be on a separate PR.
Fixes #
```release-note
Two new tags have been added to Jaeger Tracing spans, for online serving: number of entities and features in request.
```

Apply grpc tracing interceptor on online serving

---

serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
serving/src/main/java/feast/serving/util/Metrics.java

This PR adds histogram metrics for Feast serving, which would allow us to determine:
- amount of entity rows per request (buckets)
- amount of features per request (buckets)
- amount of feature tables per request (buckets)
Fixes #
```release-note
Users can gather entity row, features and feature table requested metrics in Feast Serving.
```

Add Feast Serving histogram metrics

---

.github/workflows/complete.yml
infra/docker/ci/Dockerfile
infra/scripts/azure-runner.sh
infra/scripts/runner-helper.sh

**What this PR does / why we need it**: Runs e2e tests on Azure using the new spark operator and Azure blob storage support. Note it therefore requires #1218 
Fixes #1181
```release-note
NONE
```

azure e2e test

---

sdk/python/feast/constants.py
sdk/python/feast/loaders/file.py
sdk/python/feast/staging/storage_client.py

**What this PR does / why we need it**: Supports Azure Blob Storage as an object store and batch data source as part of #1181 
Fixes #
```release-note
Users can now use Azure blob storage as a staging location and as a batch data source. To configure it, they will need to set the environment variables FEAST_AZURE_BLOB_ACCOUNT_NAME and FEAST_AZURE_BLOB_ACCOUNT_ACCESS_KEY 
```

implement abstractstagingclient for azure blob storage

---

sdk/go/client.go
sdk/go/client_test.go
sdk/go/go.mod
sdk/go/go.sum
sdk/java/pom.xml
sdk/java/src/main/java/com/gojek/feast/FeastClient.java
sdk/python/feast/client.py
sdk/python/setup.py

This would enable out of the box Tracing support on Golang, Python and Java SDK. If user has registered a GlobalTracer, Feast client will automatically construct a grpc tracing interceptor using the registered tracer. Otherwise, a NoopTracer is used instead.
Fixes #
```release-note
gRPC tracing will now be enabled automatically on Feast clients if a global tracer instance is registered.
```

Apply grpc tracing interceptor on Feast SDK

---

infra/scripts/build-ingestion-py-dependencies.sh

Fix build-ingestion-py-dependencies script

---

sdk/python/feast/pyspark/launchers/gcloud/dataproc.py

With migrating to latest dataproc image version (2.0.0-RC21-debian10) we now can use more recent python version as default one.
Fixes #
```release-note
NONE
```

Update python version requirements to 3.7 for Dataproc launcher

---

sdk/python/feast/pyspark/historical_feature_retrieval_job.py
sdk/python/tests/test_as_of_join.py

Since `created_timestamp_column` is required sometimes user wants to reuse the same column from datasource for both `event_timestamp` & `created_timestamp`.
Fixes #
```release-note
Same column is allowed in `created_timestamp_column` & `event_timestamp_column` in DataSource.
```

Allow use the same timestamp column for both created & even timestamp in Historical Retrieval

---

sdk/python/feast/pyspark/launchers/k8s/k8s.py
sdk/python/feast/staging/storage_client.py
sdk/python/requirements-ci.txt
tests/e2e/test_historical_features.py

**What this PR does / why we need it**: fixes the historical test to support azure blob storage
Fixes #
```release-note
NONE
```

fix historical test for azure

---

spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
spark/ingestion/src/main/scala/feast/ingestion/utils/JsonUtils.scala

All keys in fieldMapping dictionary passed to IngestionJob are being camelized, which is unwanted behaviour, they should stay untouched.
Fixes #
```release-note
NONE
```

Prevent ingestion job config parser from unwanted fieldMapping transformation

---

infra/docker-compose/docker-compose.yml
infra/scripts/test-docker-compose.sh
sdk/python/feast/contrib/validation/ge.py
sdk/python/feast/feature_table.py
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/main/scala/org/apache/spark/api/python/DynamicPythonFunction.scala
tests/e2e/conftest.py
tests/e2e/fixtures/client.py
tests/e2e/fixtures/external_services.py
tests/e2e/fixtures/services.py
tests/e2e/fixtures/statsd_stub.py
tests/e2e/test_validation.py

In this PR previously added Python UDF for feature validation reports amount of unexpected rows (that didn't pass validation) as statsd counter. That will allow to monitor percentage of invalid data and create alert when it reach some threshold.
Fixes #
```release-note
NONE
```

Reporting metrics from validation UDF

---

protos/feast/core/Store.proto
serving/src/main/java/feast/serving/config/ServingServiceConfigV2.java
serving/src/main/resources/application.yml
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClient.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterClient.java

Prior to this PR Feast Serving only read from master nodes in redis cluster. Here I make it configurable via `application.yaml`.
Fixes #
```release-note
new configuration option
RedisClusterConfig:
read_from: MASTER | MASTER_PREFERRED | REPLICA | REPLICA_PREFERRED
```

Make nodes priority (for redis cluster) configurable in Serving

---

protos/feast/core/JobService.proto
sdk/python/feast/client.py
sdk/python/feast/job_service.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/k8s/k8s.py
sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/feast/remote_job.py
sdk/python/tests/test_remote_job.py
tests/e2e/test_historical_features.py
tests/e2e/test_online_features.py
tests/integration/test_launchers.py

As part of an effort to create an UI for Feast, the JobService API needs to return more information, in particular, job start time and the feature table associated with the ingestion jobs.
Fixes #
```release-note
gRPC responses for submitting spark jobs via job service now have additional fields: start time for all types of jobs, and feature table for ingestion jobs. These fields have also been added to the corresponding Job object returned by list_jobs and get_job API.
```

Enhance job api to return associated feature table and start time

---

sdk/python/feast/pyspark/launchers/gcloud/dataproc.py

`get_log_uri` is currently returning the GCS uri of the Spark driver logs. This is changed to the dataproc console uri instead.
Fixes #
```release-note
DataprocClusterLauncher jobs will now return the dataproc console url referring to the job, rather than the GCS uri that points to the Spark driver logs.
```

Use dataproc console url instead of gcs for log uri

---

sdk/python/feast/contrib/validation/ge.py
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
tests/e2e/test_validation.py

Along with feature table name this PR adds project name into `feast_feature_validation_check_failed` metric.
Fixes #
```release-note
NONE
```

Add project name to feature validation metric

---

spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
spark/ingestion/src/main/scala/feast/ingestion/metrics/IngestionPipelineMetrics.scala
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala

1. Avoid expensive partition materialization in metrics calculation
2. Checkpoint data in case of repartitioning (trigger materialization)
Fixes #
```release-note
NONE
```

Optimize memory footprint for Spark Ingestion Job

---

tests/e2e/conftest.py
tests/e2e/test_online_features.py
tests/e2e/test_validation.py

If flag passed to e2e tests - they won't manually trigger streaming jobs.
Fixes #
```release-note
NONE
```

E2E tests support for jobservice's control loop

---

tests/e2e/test_online_features.py
tests/e2e/test_validation.py

Fixes #
```release-note
NONE
```

Increase kafka consumer waiting time in e2e tests

---

tests/e2e/test_historical_features.py

**What this PR does / why we need it**: small bugfix to fix flaky historical test
Fixes #
```release-note
NONE
```

fix historical test flakiness

---

sdk/python/feast/pyspark/launchers/aws/emr_utils.py

Instead of hard `TERMINATE_PROCESS` use softer `SEND_INTERRUPT` to stop EMR jobs. The problem with `TERMINATE_PROCESS` is that sometimes this causes the job to be cancelled from EMR point of view, but it still shows up as RUNNING in Yarn, so the next job scheduled doesn't get the resources it needs.
```release-note
NONE
```

use SEND_INTERRUPT to cancel EMR jobs

---

sdk/python/feast/pyspark/launchers/aws/emr_utils.py
sdk/python/feast/pyspark/launchers/k8s/k8s.py

**What this PR does / why we need it**: previously if the spark ingestion jar was a https url (which is the default), ingestion would fail because Feast would try to read and upload the jar as if the url were a local path
Fixes #
```release-note
NONE
```

allow https url for spark ingestion jar

---

serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
serving/src/main/java/feast/serving/util/Metrics.java

Feast request counter metric (based on feature name) was removed in https://github.com/feast-dev/feast/pull/1240. This PR adds back the missing metric.
Fixes #
```release-note
Users can now track metrics no. of request counts for each feature.
```

Add request feature counter metric

---

sdk/python/feast/pyspark/launcher.py

**What this PR does / why we need it**: bugfix - `config.get()` errors when the variable is not set
Fixes #
```release-note
NONE
```

don't error when azure vars not set

---

infra/scripts/test-docker-compose.sh
sdk/python/feast/pyspark/launchers/standalone/local.py
spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala

For streaming pipeline we don't need to create excessive amount of partitions.
Fixes #
```release-note
NONE
```

Keep same amount of partitions after repartitioning in IngestionJob

---

sdk/python/feast/contrib/validation/ge.py

Instead of using counter we report observed value during feature validation as raw value (gauge).
Fixes #
```release-note
NONE
```

Report observed values in feature validation as Gauge

---

sdk/python/feast/pyspark/launchers/aws/emr_utils.py

EMR jar uploader shouldn't upload the jar if it is already uploaded somewhere
Fixes #1275
```release-note
Fix jar url handling in EMR launcher
```

make EMR jar uploader work the same as k8s one

---

infra/charts/feast/charts/feast-jobservice/templates/configmap.yaml
infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
infra/charts/feast/charts/feast-jobservice/values.yaml
sdk/python/requirements-ci.txt

Currently, there's no way for users to mount the spark job template on the jobservice pod. This PR enables the user to mount custom job template as configmap.
Fixes #
```release-note
New options for Jobservice helm chart: users are now able to mount custom spark job template as configmap.
```

Enable user to provide spark job template as input for jobservice deployment

---

infra/scripts/codebuild-entrypoint.sh
infra/scripts/k8s-common-functions.sh

Add aws codebuild entrypoint script
```release-note
NONE
```

Add EMR CI/CD entrypoint script

---

docs/SUMMARY.md
docs/getting-started/install-feast/README.md
docs/getting-started/install-feast/kubernetes-azure-aks-with-terraform.md

**What this PR does / why we need it**: adds a docs page for Azure setup
Fixes #
```release-note
NONE
```

Add docs page for Azure setup

---

common-test/src/main/java/feast/common/it/DataGenerator.java
core/src/test/java/feast/core/service/SpecServiceIT.java
infra/charts/feast/charts/feast-serving/templates/deployment.yaml
infra/charts/feast/charts/feast-serving/values.yaml
infra/docker/serving/Dockerfile
serving/pom.xml
serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
serving/src/main/java/feast/serving/specs/CachedSpecService.java
serving/src/main/java/feast/serving/specs/CoreSpecService.java
serving/src/test/java/feast/serving/it/ServingServiceOauthAuthorizationIT.java
serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
storage/api/src/main/java/feast/storage/api/retriever/OnlineRetrieverV2.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/common/RedisHashDecoder.java
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/OnlineRetriever.java

Some performance concerns about `OnlineServingServiceV2` were addressed in this PR:
1. Move `specs` retrieving out of nested for loops - prepare required data in advance.
2. Less data copying / Less hash tables
3. Rewritten CacheLoader for specs to minimise missing cache exceptions
4. Simplify `OnlineRetrieverV2` interface - get rid of `Optional`
5. Add Ability to tune java options through helm chart values
Fixes #
```release-note
NONE
```

Online serving optimizations

---

protos/feast/core/JobService.proto
sdk/python/feast/client.py
sdk/python/feast/job_service.py
sdk/python/feast/pyspark/abc.py
sdk/python/feast/pyspark/launcher.py
sdk/python/feast/pyspark/launchers/aws/emr.py
sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
sdk/python/feast/pyspark/launchers/k8s/k8s.py
sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
sdk/python/feast/pyspark/launchers/standalone/local.py
sdk/python/requirements-ci.txt
tests/e2e/test_online_features.py
tests/e2e/test_validation.py
tests/e2e/utils/common.py
tests/e2e/utils/kafka.py

This PR adds feature table name filter to `ListJobs` api. This would allow us to perform filtering on server side.
Fixes #
```release-note
Users can list jobs based on feature table name.
```

Add feature table name filter to jobs list api

---

spark/ingestion/src/main/scala/feast/ingestion/sources/file/FileReader.scala
spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala

With additional filtering by partitioning column (when it's specified) IngestionJob won't need to read the whole data lake, but only required partitions.
Fixes #
```release-note
NONE
```

Use date partitioning column in FileSource

---

.prow/config.yaml
Makefile
docs/SUMMARY.md
docs/advanced/telemetry.md
infra/scripts/setup-e2e-env-aws.sh
infra/scripts/setup-e2e-env-sparkop.sh
infra/scripts/test-end-to-end-aws.sh
infra/scripts/test-end-to-end-gcp.sh
infra/scripts/test-end-to-end-sparkop.sh
infra/scripts/test-end-to-end.sh
infra/scripts/test-integration.sh
infra/scripts/test-telemetry.sh
sdk/python/feast/client.py
sdk/python/feast/constants.py
sdk/python/feast/telemetry.py
sdk/python/telemetry_tests/test_telemetry.py

**What this PR does / why we need it**: adds basic telemetry
Fixes #
```release-note
Starting in v0.9, Feast will begin to collect anonymized usage statistics. To opt out or learn more see https://docs.feast.dev/v/master/advanced/telemetry
```

Add telemetry to Python SDK

---

infra/scripts/test-docker-compose.sh
sdk/python/feast/job_service.py

**What this PR does / why we need it**: disables telemetry in the docker-compose test
Fixes #
```release-note
NONE
```

disable telemetry in docker-compose test and job_service

---

tests/e2e/fixtures/services.py

**What this PR does / why we need it**: fixes kafka download url to fix e2e tests
Fixes #
```release-note
NONE
```

fix kafka download url

---

sdk/python/requirements-dev.txt
sdk/python/setup.py

Latest numpy release (1.20.0) cause issue in pandas -> pyarrow conversion
```
/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py:588: in dataframe_to_arrays
for c, f in zip(columns_to_convert, convert_fields)]/usr/local/lib/python3.7/site-packages/_pytest/compat.py:340: PytestDeprecationWarning: The TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.
See https://docs.pytest.org/en/stable/deprecations.html#terminalreporter-writer for more information.
return getattr(object, name, default)
/usr/local/lib/python3.7/site-packages/pyarrow/pandas_compat.py:588: in <listcomp>
for c, f in zip(columns_to_convert, convert_fields)] …
```

Freeze numpy version

---

infra/scripts/build-ingestion-py-dependencies.sh

Fixes #
```release-note
NONE
```

Freeze numpy version in ingestion python dependencies

---

infra/scripts/test-telemetry.sh
sdk/python/feast/entity.py
sdk/python/feast/pyspark/launcher.py
sdk/python/requirements-ci.txt
sdk/python/requirements-dev.txt
sdk/python/tests/test_client.py

Fixes  #1238. `Entity.value_type` now consistently is a `feast.ValueType`
```release-note
more consistent value_type handling in Entity class
```

more consistent value_type handling in Entity

---

docs/getting-started/install-feast/kubernetes-with-helm.md

improves docs.
Use label select instead of grep.
grep was returning multiple pods and crashing for me.

Fix in install instructions

---

infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
infra/charts/feast/requirements.yaml

Currently, job service is not restarted when the configmap changes. As a result, the config map changes won't take effect. This PR enables the job service to restart automatically.
Fixes #
```release-note
Jobservice will now be restarted when the associated configmap is changed.
```

Autoreload jobservice when configmap changed

---

.github/workflows/master_only.yml
protos/feast/core/Entity.proto
protos/feast/core/FeatureTable.proto
protos/feast/core/Registry.proto
sdk/python/feast/client.py
sdk/python/feast/constants.py
sdk/python/feast/registry.py
sdk/python/tests/conftest.py
sdk/python/tests/test_client.py

**What this PR does / why we need it**: Add support for an object store registry to the SDK. However, note that this should not be used until serving also supports this registry.
Fixes #
```release-note
```

WIP Add option to use object store metadata registry

---

protos/feast/core/Store.proto
serving/pom.xml
serving/src/main/resources/application.yml
storage/connectors/redis/pom.xml
storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterClient.java

Default configuration options for redis client are far from ideal. This PR adds basic timeouts / keep-alive / topology refresh options.
Fixes #
```release-note
Redis Client timeout is configurable through application.yml
```

Add configurable timeout to redis cluster connection

---

sdk/python/feast/big_query_source.py
sdk/python/feast/feature_store.py
sdk/python/feast/feature_store_config.py
sdk/python/feast/feature_view.py

**What this PR does / why we need it**: Scaffold classes for updated SDK; FeatureStore will replace the Client class but these are currently just mostly-empty classes.
Fixes #
```release-note
NONE
```

FeatureStore, FeatureView, Config, and BIgQuerySource classes for updated SDK

---

.github/workflows/privileged.yml
.github/workflows/unprivileged.yml

Adds support for using secrets when receiving PRs from external contributors. Also fixes the naming of workflows so its clear that one is privileged (contains secrets) while the other doesn't.
```release-note
None
```

Add support for privileged tests

---

docs/reference/feast-and-spark.md
sdk/python/feast/constants.py

Documents the `SPARK_K8S_JOB_TEMPLATE_PATH` constant with example and reference to the spec.

Improve documentation for k8s-spark resource template

---

docs/specs/online_store_format.md

Signed-off-by: Oleg Avdeev <oleg.v.avdeev@gmail.com>
Fixes #
```release-note
NONE
```

Fix hashing algorithm in the firestore spec

---

Makefile

I got "/bin/sh: /Users/tedchang/bin/protoc: cannot execute binary file" error while  running "make protos" on Mac.
NONE
```release-note
```

Support make protos on Mac

---

sdk/python/feast/big_query_source.py
sdk/python/feast/feature_store.py
sdk/python/feast/feature_view.py
sdk/python/feast/offline_store.py
sdk/python/feast/repo_config.py
sdk/python/requirements-dev.txt
sdk/python/setup.py

**What this PR does / why we need it**: Implements downloading a BQ table to an in-memory pyarrow table, which will be part of the python-based ingestion flow
Fixes #
```release-note
NONE
```

Download BigQuery table to pyarrow table for python-based ingestion flow

---

sdk/python/feast/client.py
sdk/python/feast/grpc/auth.py

Fix bug in client.archive_project. It should use the core_service method instead of raw core_service_stub. Also fix lint in grpc/auth.py.
NONE
```release-note
Fix bug in client.archive_project and fix lint in grpc auth
```

Fix a bug in client archive_project method and fix lint in grpc auth

---

docs/reference/feast-and-spark.md

**What this PR does / why we need it**: Fills in some missing parts of the spark-on-k8s-operator documentation
Fixes #
```release-note
NONE
```

Improve spark-on-k8s-operator documentation

---

sdk/python/docs/index.rst
sdk/python/feast/infra/provider.py
sdk/python/feast/repo_config.py
sdk/python/setup.py
sdk/python/tests/cli/test_datastore.py
sdk/python/tests/test_repo_config.py

This adds nicer error messages for the config reader. This PR also adds an additional dep on `jsonschema` package. This is already a popular dep (for example, for `jupyter` and `great-expectations`) so that is arguably not too bad.
```release-note
NONE
```

Add nicer validation for repo config

---

sdk/python/feast/infra/local_sqlite.py
sdk/python/tests/cli/test_cli_local.py
sdk/python/tests/cli/test_datastore.py

Make sure you can run apply twice and not get an error the second time.
```release-note
NONE
```

Make CLI apply in local mode idempotent

---

.github/workflows/integration_tests.yml
.github/workflows/pr_integration_tests.yml
.github/workflows/release.yml

Upgrading to https://github.com/google-github-actions/setup-gcloud because GoogleCloudPlatform/github-actions/setup-gcloud has been deprecated
```release-note
None
```

Upgrade Gcloud setup dependency

---

Makefile
sdk/python/feast/feature_store.py
sdk/python/feast/infra/gcp.py
sdk/python/feast/infra/local_sqlite.py
sdk/python/feast/infra/provider.py
sdk/python/tests/cli/example_feature_repo_1.py
sdk/python/tests/cli/online_read_write_test.py
sdk/python/tests/cli/test_cli_local.py
sdk/python/tests/cli/test_datastore.py
sdk/python/tests/cli/test_online_retrieval.py
sdk/python/tests/cli/utils.py
sdk/python/tests/test_bigquery_ingestion.py

Added python-online read API to the FeatureStore class. It closely mimicks the existing API on feast client.
```release-note
NONE
```

Add online read API to FeatureStore class

---

sdk/python/feast/data_source.py
sdk/python/feast/feature_store.py
sdk/python/feast/offline_store.py
sdk/python/tests/test_bigquery_ingestion.py
sdk/python/tests/test_materialize_from_bigquery_to_datastore.py

**What this PR does / why we need it**: Add support to materialize a specified BigQuery query into the online store
Fixes #
```release-note
Adds support to materialize a specified BigQuery query into the online store
```

Support pulling query from BigQuery

---

sdk/python/feast/infra/gcp.py

Previously we'd continue retrying the writes even if there was no exception, so we'd write all data 3x over.. not ideal.
```release-note
NONE
```

Fix retry handling for GCP datastore

---

sdk/python/feast/__init__.py
sdk/python/feast/infra/provider.py
sdk/python/tests/test_client.py

Allows importing of FeatureStore and RepoConfig classes as top level classes
Fixes #
```release-note
Users can now import the FeatureStore and RepoConfig classes directly without submodules
```

Allow importing of new Python classes

---

sdk/python/feast/grpc/auth.py
sdk/python/tests/grpc/test_auth.py

Currently python SDK requires `gcloud` cli to be installed in order to extract `id_token` from ServiceAccount. This is very inconvenient. This PR uses `google.oauth2` instead.
Fixes #
```release-note
NONE
```

[Python SDK][Auth] Refresh token id w/o gcloud cli

---

sdk/python/feast/feature_store.py
sdk/python/feast/registry.py
sdk/python/tests/test_client.py
sdk/python/tests/test_feature_store.py

**What this PR does / why we need it**: Adds missing entity and feature view methods on FeatureStore class and also moves object registry tests to new FeatureStore API
Fixes #
```release-note
Add get_entity, list_entities, get_feature_view, list_feature_views, and delete_feature_view to FeatureStore class
```

Add missing FeatureStore methods

---

sdk/python/feast/data_source.py
sdk/python/feast/entity.py
sdk/python/feast/offline_store.py
sdk/python/tests/online_write_benchmark.py
sdk/python/tests/test_entity.py
sdk/python/tests/test_historical_retrieval.py

**What this PR does / why we need it**: Makes entity description optional and fixes bug with empty table_ref
Fixes #
```release-note
Entity description is now optional
```

Make entity description optional and fix empty table_ref

---

docs/getting-started/install-feast/google-cloud-gke-with-terraform.md
infra/terraform/gcp/feast.tf

This PR only fixes small issues with Terraform reference configuration for GCP so the Quickstart guide actually works.
Fixes #1419 
```release-note
NONE
```

Fix broken Terraform installation files

---

CONTRIBUTING.md
README.md

- Moves Development Guide docs for Main Feast Repo components out of central Development Guide on Gitbook into individual CONTRIBIUTING.md in repositories.
- Updates Development Guide docs for new repository structure [(Preview)](https://github.com/mrzzy/feast/blob/chore/add-dev-guide/CONTRIBUTING.md).
- Add Links to relevant docs ie CONTRIBUTING.md on the README.
WIP: Yet to be done:
- Add docs on how the development workflow for working with the Feast Terraform Deployment.
Partly implement feast-dev/feast#1353 for the Feast components in the Main Feast Repository.
```release-note
NONE
```

Add Development Guide for Main Feast Repo Feast Components

---

sdk/python/feast/feature_store.py
sdk/python/feast/repo_config.py
sdk/python/feast/repo_operations.py
sdk/python/tests/cli_utils.py
sdk/python/tests/online_write_benchmark.py
sdk/python/tests/test_cli_gcp.py
sdk/python/tests/test_cli_local.py
sdk/python/tests/test_feature_store.py
sdk/python/tests/test_historical_retrieval.py
sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
sdk/python/tests/test_online_retrieval.py
sdk/python/tests/test_repo_config.py

Simply a naming change from `metadata_store` to `registry`.
```release-note
NONE
```

Rename Metadata Store to Registry

---

sdk/python/feast/feature_store.py
sdk/python/tests/test_e2e_local.py
sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
sdk/python/tests/test_online_retrieval.py

**What this PR does / why we need it**: get_online_features returns colons in feature names, while get_historical_features uses double underscores. Here, we solve the name consistency by moving online API to also use double underscores.
Fixes #
```release-note
NONE
```

Fix feature name consistency between online & historical apis

---

sdk/python/feast/feature_view.py

**What this PR does / why we need it**: This fixes a bug, where we initialize materialization_intervals in FeatureView as a class-level parameter. So basically every instance of FeatureView have the same materialization_intervals, appending on top of each other.
Fixes #
```release-note
```

Fix materialization_intervals initialization in FeatureView

---

sdk/python/feast/feature_store.py
sdk/python/feast/infra/local_sqlite.py
sdk/python/tests/example_feature_repo_1.py
sdk/python/tests/test_online_retrieval.py

In the new online retriever interface, when multiple entities are required for a lookup, the online retriever wont return any results. This PR fixes a bug in the key building.
```release-note
NONE
```

Fix multi-entity online retrieval

---

sdk/python/feast/infra/local_sqlite.py

**What this PR does / why we need it**: Fixes a bug in local mode when the event timestamp column in the source and the entity dataframe are both named event_timestamp
Fixes #
```release-note
NONE
```

Fix bug in event timestamp removal in local mode

---

sdk/python/feast/cli.py

**What this PR does / why we need it**: We have fs.materialize_incremental functionality in the FeatureStore, but don't have the equivalent function in the CLI. This PR adds that command.
Fixes #
```release-note
Add `feast materialize-incremental` command to the CLI
```

Add materialize-incremental cli command

---

sdk/python/tests/test_e2e_local.py

**What this PR does / why we need it**: We add a unit test for `feast materialize-incremental` cli command to make sure it doesn't silently break in future.
Fixes #
```release-note
NONE
```

Add materialize-incremental cli test

---

sdk/python/feast/grpc/auth.py
sdk/python/tests/grpc/test_auth.py

Currently, auth id_token will expire after an hour. When auth is switched on, JobService which connects to Core Client will face authentication issues because of expired id_token. This PR validates if tokens are expired when requests hit Core and refreshes if they are.
Fixes #
```release-note
NONE
```

Use timestamp check for token refresh

---

sdk/python/feast/data_source.py

Stops a noisy warning when the user provides a `path` argument to a `FileSource` (which is correct), but the warning mistakes this for `file_url`.
```release-note
NONE
```

Fix noisy path warning

---

sdk/python/feast/client.py
sdk/python/feast/feature_store.py
sdk/python/feast/telemetry.py
sdk/python/feast/version.py
sdk/python/setup.py
sdk/python/telemetry_tests/test_telemetry.py

**What this PR does / why we need it**: Ports opt-out telemetry to the new FeatureStore API
Fixes #
```release-note
Opt-out telemetry (usage logging) is now enabled on the FeatureStore API. To disable it, see https://docs.feast.dev/v/master/feast-on-kubernetes/advanced-1/telemetry
```

Port telemetry to FeatureStore API

---

protos/feast/core/Entity.proto
protos/feast/types/EntityKey.proto
sdk/python/feast/entity.py
sdk/python/feast/feature_store.py
sdk/python/feast/infra/gcp.py
sdk/python/feast/infra/key_encoding_utils.py
sdk/python/feast/infra/local_sqlite.py
sdk/python/feast/infra/provider.py
sdk/python/feast/registry.py
sdk/python/tests/online_read_write_test.py
sdk/python/tests/online_write_benchmark.py
sdk/python/tests/test_entity.py
sdk/python/tests/test_materialize.py
sdk/python/tests/test_online_retrieval.py

**What this PR does / why we need it**: Add entity join key and fix FeatureStore methods to use join keys instead of input entity names
Fixes #
```release-note
Add optional join_key parameter to Entity that defaults to the entity name. Previously, the entity name was both the name of the entity and the name of the column it referred to; now one can set join_key to the column name and set name to a more human-readable string.
```

Add entity join key and fix entity references

---

sdk/python/feast/infra/gcp.py
sdk/python/feast/infra/local.py
sdk/python/feast/infra/offline_stores/bigquery.py
sdk/python/feast/infra/offline_stores/file.py
sdk/python/feast/infra/offline_stores/helpers.py
sdk/python/feast/infra/offline_stores/offline_store.py
sdk/python/feast/infra/provider.py
sdk/python/tests/test_historical_retrieval.py

The Provider model delegates control over which sources/stores can be used to individual provider implementations. #1437 moved the store logic into each provider. This PR separates out the offline store (sources) into their own class, allowing providers to opt into specific storage implementations (FileSource, BigQuerySource), while still granting control to providers to choose which providers they allow/disallow. More tangibly, we now allow a LocalProvider to use a BigQueryOfflineStore. We also allow a BigQueryProvider to use a FileOfflineStore.
```release-note
Added support for providers to be able to opt into any sources (offline stores) 
```

Add multi-source support to local and GCP provider

---

sdk/python/feast/feature_store.py
sdk/python/feast/feature_view.py
sdk/python/feast/infra/gcp.py
sdk/python/feast/infra/local.py
sdk/python/feast/infra/offline_stores/bigquery.py
sdk/python/feast/infra/offline_stores/file.py
sdk/python/feast/infra/offline_stores/offline_store.py
sdk/python/feast/infra/provider.py
sdk/python/feast/registry.py
sdk/python/tests/test_historical_retrieval.py

**What this PR does / why we need it**: Use join keys from the registry in historical feature retrieval rather than using the entity name strings in the input.
Fixes #
```release-note
NONE
```

Support join keys in historical feature retrieval

---

sdk/python/feast/online_response.py
sdk/python/tests/test_online_retrieval.py

**What this PR does / why we need it**: Include all requested features in the return schema of get_online_features even when no keys are found in the online store
Fixes #
```release-note
`feature_store.get_online_features(...).to_dict()` returns a dictionary that now always contains all requested features; previously, features with no values for any of the requested keys had not been included.
```

Fix get_online_features return schema

---

sdk/python/feast/infra/gcp.py
sdk/python/feast/infra/local.py
sdk/python/tests/online_read_write_test.py
sdk/python/tests/online_write_benchmark.py

**What this PR does / why we need it**: We used to have less than 100 QPS on writing data to the online store in Gcp Firestore. This was due to using non-batch requests (get & put) instead of batch variants (get_multi & put_multi). Moreover, we completely removed the read part of the functionality and directly write the new data without comparing timestamps. So, it's up to the user now to make sure they're not overwriting old data over the new data. In future we'll add a flag that if enabled by the user, will do this check on every write, but the performance hit is too much to leave it on by default.
The new functionality benchmarks at ~1.95K writes per second.
Fixes #
```release-note
Improve Firestore …
```

Optimize write rate in Gcp Firestore

---

sdk/python/feast/feature_store.py

**What this PR does / why we need it**: Validate start_date and end_date in materialize are in the correct order
Fixes #
```release-note
NONE
```

Validate datetimes in materialize in correct order

---

sdk/python/feast/feature_store.py
sdk/python/tests/test_feature_store.py

**What this PR does / why we need it**: Allows apply to take in a single Entity or FeatureView
Fixes #
```release-note
`feature_store.apply()` now can accept a single Entity or FeatureView. Previously, it only accepted a list of Entities or FeatureViews.
```

Allow apply to take a single Entity or FeatureView

---

sdk/python/feast/cli.py
sdk/python/feast/repo_operations.py
sdk/python/tests/cli_utils.py
sdk/python/tests/test_cli_gcp.py
sdk/python/tests/test_cli_local.py
sdk/python/tests/test_e2e_local.py

* Remove repo_path argument from commands: apply, registry-dump, teardown, materialize, materialize-incremental
* Remove commands: config, feature-tables, projects
* Misc
* Add help text to `init` command
* Provide only SDK version in `version` command
* Add help text including links to doc & Feast Slack to `feast` command
* Add feature views to `registry-dump` command
Fixes #
```release-note
Fix & clean up Feast CLI commands
```

Fix & clean up Feast CLI commands

---

sdk/python/feast/infra/offline_stores/bigquery.py
sdk/python/feast/infra/offline_stores/file.py

**What this PR does / why we need it**: Validates that a correctly named timestamp column is present in the entity dataframe passed to get_historical_features
Fixes #
```release-note
NONE
```

Validate timestamp column present in entity dataframe

---

sdk/python/feast/feature_store.py

Adds logs to the Materialize and Materialize Incremental commands
```release-note
Improved logging for materialization commands
```

Add logging to materialize

---

sdk/python/feast/infra/offline_stores/file.py
sdk/python/feast/infra/provider.py

**What this PR does / why we need it**: Fixes some small bugs with created_timestamp
Fixes #
```release-note
NONE
```

Small fixes for created_timestamp

---

sdk/python/feast/infra/offline_stores/bigquery.py
sdk/python/feast/infra/offline_stores/file.py
sdk/python/tests/test_materialize.py
sdk/python/tests/test_offline_online_store_consistency.py

**What this PR does / why we need it**: Discovered 2 different bugs in get_historical_features. 1) if the entity_df contains tz-naive timestamps, point-in-time merging doesn't work in local mode. 2) field_mapping is not being used in offline mode (it's used in online mode). Meaning that if you define field_mapping, get_historical_features simply fails in both local and gcp modes.
Fixes #
```release-note
Fix tz-naive issue with offline store and apply field_mapping during historical feature retrieval
```

Fix offline store (tz-naive & field_mapping issues)

---

sdk/python/feast/infra/offline_stores/file.py

**What this PR does / why we need it**: Looks like x.tz exists only for pandas Timestamp type (which extends Python's native datetime object), but it that fields doesn't exist in the original datetime object. Given that tz is just an alias for tzinfo, x.tzinfo exists both in pandas Timestamp & in Python's native datetime objects, so I'm changing it to that.
Fixes #
```release-note
NONE
```

Fix time zone access with native python datetimes

---

sdk/python/feast/templates/gcp/driver_repo.py
sdk/python/feast/templates/gcp/test.py

**What this PR does / why we need it**: Running through the quickstart should now also work with `feast init -t gcp`
Fixes #
```release-note
NONE
```

Change GCP template names to match local template

---

sdk/python/feast/cli.py
sdk/python/feast/errors.py
sdk/python/feast/registry.py
sdk/python/tests/test_cli_local.py

**What this PR does / why we need it**: Existing CLI entities command is trying to use feast core. Instead, it should be using new FeastStore abstraction. Also, the CLI didn't have a way of accessing feature views, and I'm adding that as well. Here are the 4 new commands:
```
feast entities list
feast entities describe <entity-name>
feast feature-views list
feast feature-views describe <feature-view-name>
```
I also noticed that in bunch of places where we want to throw errors, we use `Exception` class, which has some disadvantages. For example, when you want to catch this error you have to use `except Exception as e`, which can catch all different kinds of exceptions. In this PR I started a new `errors.py` class where I introduces some new …

Fix CLI entities command & add feature-views command

---

infra/docker/ci/Dockerfile

Remove unused environment variable. The `MAVEN_CONFIG` variable is used by the maven Docker image (which we're not using) and is not used by Maven itself in any way. It is colliding with Maven Wrapper configuration (which also uses this variable) and is causing feast-dev/feast-java#26 to fail

Remove unnecessary MAVEN_CONFIG

---

sdk/python/feast/driver_test_data.py
sdk/python/feast/infra/offline_stores/file.py
sdk/python/tests/test_historical_retrieval.py

**What this PR does / why we need it**: There was an issue with FeatureStore.get_historical_features when you pass records with timestamp with non-UTC time zones (pandas merge_asof was throwing an exception). This PR fixes that issue by converting all timestamps in the entity to UTC. If timestamp is tz-naive, we assume it's UTC. If it's tz-aware, we localize to UTC.
I also made significant changes to the tests. First, when generating entities we now generate timestamps in all kinds of different formats. Second, `test_historical_retrieval.py:get_expected_training_df` function used a very similar logic to the local offline store (based on pandas merge_asof). Meaning that if there are bugs in the local offline store, we replicate them in the …

Fix time zone issue with get_historical_features

---

sdk/python/feast/infra/offline_stores/bigquery.py
sdk/python/tests/test_historical_retrieval.py

**What this PR does / why we need it**: Fix errors in historical retrieval when created_timestamp_column is not set on a BigQuery data source
Fixes #
```release-note
NONE
```

Fix created timestamp related errors for BigQuery source

---

sdk/python/feast/cli.py
sdk/python/feast/errors.py
sdk/python/feast/feature_store.py
sdk/python/feast/infra/gcp.py
sdk/python/feast/infra/local.py
sdk/python/feast/infra/offline_stores/bigquery.py
sdk/python/feast/infra/provider.py
sdk/python/feast/registry.py
sdk/python/feast/repo_operations.py
sdk/python/tests/test_cli_local.py
sdk/python/tests/test_feature_store.py
sdk/python/tests/test_online_retrieval.py

* Add better logging to the Apply CLI method
* Add error message when missing authentication for GCP provider  
* Add proper error message for missing feature views in historical retrieval
* Add proper error message for credential error for BigQuery client
* Add proper GCP project missing error for BigQuery client
* Ensure all apply commands initialize a feature repository
* Ensure FeatureStore object can be run from outside a repository 
```release-note
* Add clearer logging to the Apply CLI method
* Add error message when missing authentication for GCP provider  
* Add proper error message for missing feature views in historical retrieval
* Add proper error message for credential error for BigQuery …
```

Improve exception handling, logging, and validation

---

sdk/python/feast/registry.py

We introduced a bug with #1477. We allow initialization of the registry during `apply`, even with empty repositories. However, support was only added for the local registry, not the GCS registry.
```release-note
Fix bug in allowing empty repositories to be applied to a GCS registry
```

Fix bug in allowing empty repositories to be applied to a GCS registry

---

sdk/python/docs/index.rst
sdk/python/feast/feature.py
sdk/python/feast/feature_store.py
sdk/python/feast/repo_config.py
sdk/python/tests/test_online_retrieval.py

**What this PR does / why we need it**: Updates and fixes formatting issues in the python SDK reference documentation
Fixes #
```release-note
NONE
```

Python docs formatting fixes

---

sdk/python/feast/feature_store.py
sdk/python/feast/infra/gcp.py
sdk/python/feast/infra/local.py
sdk/python/feast/infra/provider.py
sdk/python/feast/repo_operations.py
sdk/python/tests/online_write_benchmark.py

Some Providers would need the information about the entities to keep and to delete.
Therefore this PR aims to pass this information to the Provider object.
Fixes #
Not really as even if a user created a custom Provider, they could not use it (yet) because of the hard coded logic happening at the `get_provider` function [see reference](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/provider.py#L127-L137))
```release-note
We now pass the information about the entities to the Provider object
```

Pass entities information to Provider

---

sdk/python/feast/errors.py
sdk/python/feast/infra/provider.py
sdk/python/tests/cli_utils.py
sdk/python/tests/foo_provider.py
sdk/python/tests/test_cli_local.py

**What this PR does / why we need it**: Currently there's no way to plug in custom providers in Feast CLI. With this PR, you can modify `provider` field in the `feature_store.yaml` to a Python class path. For example, if you define your provider `MyCustomProvider` under `my_package.providers`, you can specify `provider: my_package.providers.MyCustomProvider` and then normally run `feast apply` or any other CLI command.
Fixes #
```release-note
Add support for third party providers
```

Add support for third party providers

---

sdk/python/setup.py

**What this PR does / why we need it**: Currently, setup.py incorrectly supports Python 3.6. Bumping the version to 3.7.
Fixes #1502
```release-note
NONE
```

Bump supported Python version to 3.7

---

docs/concepts/apply.md
docs/feast-on-kubernetes/concepts/entities.md

**What this PR does / why we need it**: It fixes a documentation formatting inconsistency.
```release-note
It changes a documentation subheading weight to be consistent with previous subheadings.
```

Fix documentation inconsistency

---

CONTRIBUTING.md

Update broken urls in contributing.md
