feast-dev/feast

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
Add `to_remote_storage ` method to `SparkRetrivalJob` to write to remote storage. Both a local file-based and s3-based option have been implemented.
This is facilitated by 2 new config parameters for the `SparkOfflineStore`:
`staging_location`: should either start with `file://` or `s3://` to specify uri accordingly
`region`: aws region if applicable
Spark Universal tests pass. This is untested with an S3-based `staging_location`.
This PR is required in preparation for implementing a `SparkBatchMaterializationEngine` in a later PR.
**Which issue(s) this PR fixes**: None
First step towards solving https://github.com/feast-dev/feast/issues/3167
=> feat: Add `to_remote_storage` functionality to `SparkOfflineStore`

sdk/python/feast/feature_view.py, sdk/python/feast/type_map.py
=> fix: Fix Shopify timestamp bug and add warnings to help with debugging entity registration

docs/how-to-guides/customizing-feast/adding-support-for-a-new-online-store.md, sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py, sdk/python/feast/infra/online_stores/snowflake.py
=> chore: Clean up entity key serialization

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
When running materialization and have Spark offline store configured to use cluster (`spark.master` pointing to actual Spark master node) `self.to_spark_df().write.parquet(temp_dir, mode="overwrite")` will create parquet file in worker node but `return pq.read_table(temp_dir)` is executed on driver node and it can't read from worker. Proposed fix makes materialization work when run on Spark cluster.
Fixes #
=> fix: Fix materialization when running on Spark cluster.

CODEOWNERS
This is pending all the people mentioned in this are members of the Feast community and have write access
Fixes #
=> chore: Add CODEOWNERS file to automate more code reviews

sdk/python/feast/infra/offline_stores/snowflake.py
Removes faulty retrieval method that doesnt incorporate on-demand feature views
Fixes #
=> fix: Remove bad snowflake offline store method

docs/reference/online-stores/snowflake.md, sdk/python/feast/infra/materialization/snowflake_engine.py, sdk/python/feast/infra/online_stores/snowflake.py, sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
=> feat: Add tag kwarg to set Snowflake online store table path

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
Signed-off-by: niklasvm <niklasvm@gmail.com>
* `os.path.abspath` does not resolve correctly if `staging_location` starts with `file://`
* Fix bug related to the temporary directory created during integration tests
* Fix incorrect import of `aws_utils` (tests were failing)
None
=> fix: Local staging location provision

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev, sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
Signed-off-by: 11425176+ptran32@users.noreply.github.com <11425176+ptran32@users.noreply.github.com>
Author: 11425176+ptran32@users.noreply.github.com <11425176+ptran32@users.noreply.github.com>
This PR is need to fix feast-feature-server (using helm chart) that can't connect to mysql as registry. (see issue below for more details)
* Add mysqlclient in order to use mysql as registry
* Add it to requirements.txt and also moved pip install feast in it
Which issue(s) this PR fixes:
Fixes [#3218](https://github.com/feast-dev/feast/issues/3218)
=> fix: Feature-server image is missing mysql dependency for mysql registry

sdk/python/feast/infra/offline_stores/file_source.py
Remove opening file object when validating S3 parquet source.
Let instead PyArrow handle opening the path using the filesystem.
Fixes issue #3216 when trying to `feast apply` a `parquet dataset` to the feature registry.
Fixes #3216
=> fix: Remove opening file object when validating S3 parquet source

go/internal/feast/onlineserving/serving.go
According to the FeatureView docstring, 'A ttl of 0 indicates that this group of features lives forever.' However, the Go feature server doesn't currently respect this, returning OUTSIDE_MAX_AGE for FeatureViews that have a TTL of 0. This fixes that issue by always returning false for checkOutsideTtl if the TTL is 0.
=> fix: Fix handling of TTL in Go server

sdk/python/feast/infra/registry/s3.py, sdk/python/feast/repo_config.py
Give the ability to add extra arguments to the boto3 put_object method when using the S3 registry.
We use this feature to enable `ServerSideEncryption=AES256` if required by our buckets.
For example: `feature_store.yaml`:
```
...
registry:
path: s3://my-bucket/registry.db
boto_extra_args:
ServerSideEncryption: AES256
...
```
N/A
=> feat: Add ability to give boto extra args for registry config

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev, sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
**What this PR does / why we need it**: #3223 introduced this `requirements.txt`. However, `docker build` copies files from the root directory, so the correct command would be `RUN pip install -r sdk/python/feast/infra/feature_servers/multicloud/requirements.txt` instead of `RUN pip install -r requirements.txt`. Instead of running this command, I decided to just remove the `requirements.txt` file and install the dependencies directly.
This bug is the reason why the Docker images were not built correctly during the latest 0.25.0 release.
Fixes #
=> fix: Build dockerfile correctly

sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_queries.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
**What this PR does / why we need it**: Adds more authentication properties to users of Trino
Fixes #
=> fix: Add `X-Trino-Extra-Credential` header and remove user override

.github/workflows/build_wheels.yml, docs/project/release-process.md, java/infra/docker/feature-server/Dockerfile
=> chore: Build docker images in `build_wheels.yml`

sdk/python/feast/infra/registry/base_registry.py
Signed-off-by: hao-affirm <104030690+hao-affirm@users.noreply.github.com>
fix the issue that feast UI doesn't show stream feature view
Fixes #
=> fix: Stream feature view not shown in the UI

ui/src/pages/features/FeatureOverviewTab.tsx
Signed-off-by: Benjamin Tan <benjamintanweihao@gmail.com>
We have added descriptions via tags in Fields. While the Feast UI shows descriptions for Feature Views, this is not so for Fields.
=> feat: Add tag description in Field in the Feast UI

sdk/python/feast/feature_store.py, sdk/python/feast/repo_config.py
Signed-off-by: ammarar <ammar.alrashed@gmail.com>
**What this PR does / why we need it**: Currently, for `get_historical_features` coerces `entity_df` datetime columns to have timezone if the columns don't have timezone. The problem this coercion causes for Trino offline specifically is that if the `entity_df` passed does not have timezone, the Trino provider converts it to `timestamp(3) with time zone`.  However, it should be `timestamp(3)` instead.
So this fix is basically to give option to the user to use this functionality or not.
Fixes #
=> fix: Configuration to stop coercion of tz for entity_df

docs/reference/online-stores/snowflake.md, sdk/python/feast/errors.py, sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py, sdk/python/tests/integration/e2e/test_python_feature_server.py
Signed-off-by: Rob Howley <rhowley@seatgeek.com>
* added a new exception for push source not found
* in the feature store, raise the `PushSourceNotFoundException` when a push source name is provided that doesn't exist
* in feature server /push endpoint, return 422 in the case of a push source not found
Fixes #3210
=> fix: Return 422 on bad push source name

sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
Signed-off-by: ammarar <ammar.alrashed@gmail.com>
**What this PR does / why we need it**: To use the configured user specified in env var. The current way is incorrect since it shadows whatever the user provides.
Fixes #
=> fix: Use configured user in env var instead of "user" for Trino

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
This enables a SQL registry (postgres based) when using the helm charts for the python feature server
Fixes #
=> fix: Add postgres to the feature server Dockerfile to fix helm chart flow

sdk/python/feast/infra/offline_stores/bigquery.py
Signed-off-by: “Varun <varun.mallya@tech.jago.com>
One is able to add big query billing project, this can enable to run Bigquery job in a separate project which is not the project which has the BQ feature datasets. Useful in cases when certain projects have reservations (slots) for Bigquery jobs to run.
=> feat: Adding billing_project_id in BigQueryOfflineStoreConfig

sdk/python/feast/infra/registry/base_registry.py, sdk/python/feast/stream_feature_view.py
Signed-off-by: hao-affirm <104030690+hao-affirm@users.noreply.github.com>
Fixes #
=> fix: Udf in stream feature view UI shows pickled data

.github/workflows/publish.yml, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
=> fix: Fix docker image for feature-server

setup.py
The install script for version 0.22 creates conflicts with other packages over the version of numpy. It looks like the version specification is wrong as it is unusual to see redundant constraints like what is there now (i.e: <1.22 _and_ also <2). 
Fixes #
=> fix: Fix numpy version specification

sdk/python/feast/infra/offline_stores/file.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/utils/e2e_test_validation.py
Signed-off-by: Max Zwiessele <ibinbei@gmail.com>
When loading data in parquet dataset format it can happen that the dataset only has one partition in the `event_timestamp` column. If that is the case, dask will fail to process the dataset, erroring with a `ZeroDividionError` similar to 
https://github.com/feast-dev/feast/blob/769c31869eb8d9bb693f8a2876cc68b8cdd16521/sdk/python/feast/infra/offline_stores/file.py#L327
This PR adds a `try-catch` block to gracefully circumvent the error and process the data in only one partition.
N/A
=> fix: Dask zero division error if parquet dataset has only one partition

sdk/python/feast/infra/offline_stores/snowflake_source.py
This is because the default numeric type in Snowflake has up to 38 digits (surpassing the limits of INT64)
Fixes #
=> fix: Ensure that Snowflake accounts for number columns that overspecify precision

README.md
When you run 'feast init my_feature_repo', it makes a 'my_feature_repo' directory. However the 'feature_store.yaml' file is within another directory called 'feature_repo'. So the feast apply command gives an error if you are simply in the 'my_feature_store' directory.
Which issue(s) this PR fixes:
This fixes a minor issue in the README with the install instructions
Fixes #
Fixes #
=> docs: Install instructions fix directory issue

sdk/python/feast/infra/offline_stores/file_source.py
Correction in spelling mistake in file_source.py line number 59
Spelling Mistake in FileSource #3353
Fixes #
original docstring
timestamp_field (optional): Event timestamp foe;d used for point in time joins of feature values.
fixed docstring
timestamp_field (optional): Event timestamp field used for point in time joins of feature values.
=> docs: Correction in spelling mistake in file_source.py line number 59

sdk/python/feast/errors.py, sdk/python/feast/infra/offline_stores/snowflake.py
1. Added feature to offline_store-> snowflake.py to return results of snowflake query as pyspark data frame.This helps spark-based users to distribute data, which often doesn't fit in driver nodes through pandas output.
2. Also added relevant error class, to notify user on missing spark session , particular to this usecase.
Signed-off-by: amithadiraju1694 <amith.adiraju@gmail.com>
This adds feature to `SnowflakeRetrievalJob` to return result of snowflake query execution as a pyspark data frame. 
Fixes #2504
=> feat: Get Snowflake Query Output As Pyspark Dataframe (#2504)

setup.py
_Motivation_: Being able to use feast in an application with more recent versions of dask in a Python 3.8+ environment without having to work around conflicts due to versions specified in package.
This PR removes the upper bound on dask requirement added in #2342 This upper bound was added because newer versions of dask dropped support for Python 3.7. 
However, **the upper bound isn't necesesary for Python 3.7 compatibility (unless a version of dask was released that had the wrong `python_requires` specified.)**
- pip install dask (or "dask>=2021.*") in a Python 3.7 environment installs dask==2022.2.0 which was the last version that specfied comaptitibility with Python 3.7 (with `python_requires` in the pacakge config)
_Additional context_
It seems …
=> chore: Remove upper bound on dask dependency

docs/reference/online-stores/cassandra.md, sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/README.md, sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py, sdk/python/feast/templates/cassandra/bootstrap.py, sdk/python/feast/templates/cassandra/feature_repo/feature_store.yaml
This changes the retrieval of features from the Cassandra online store by leveraging the
Cassandra driver's native concurrency capabilities.
When there are several entities to be retrieved, instead of a sequential read one-by-one, entity after entity,
the reads are executed concurrently, with the driver ensuring the results are kept in the correct order and the call
returns when all results are available.
This, as measured in realistic environments, implies a speedup of 2-3x for retrieval of 20 to 100 entities at once.
Using the Cassandra driver's `execute_concurrent_with_args` function requires a new parameter controlling the maximum amount of concurrency to use (somewhat bounded by the number of vCPUs at hand): for transparency, this is exposed in the feature store configuration yaml as …
=> feat: Cassandra online store, concurrent fetching for multiple entities

docs/reference/online-stores/cassandra.md, sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/README.md, sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py, sdk/python/feast/templates/cassandra/bootstrap.py, sdk/python/feast/templates/cassandra/feature_repo/feature_store.yaml
This implements the counterpart of #3356 but for writing. Using the native concurrency offered by Cassandra drivers allows for much faster write operations to the online store, which is crucial especially in the Materialize phase.
On a realistic setup (EC2 instance running the materialization on a DB in the same region), speedups of a factor about 12x are achieved.
Similarly to the read-optimization mentioned above, a new `write_concurrency` parameter is introduced (with defaults and full backward-compatibility) to control the level of concurrency should it ever be needed (the defaults should be fine in all cases, anyway).
In order to preserve the behaviour of the callbacks to `progress` during writes to the online store, which makes the progress bar behave correctly, in the function …
=> feat: Cassandra online store, concurrency in bulk write operations

sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py, setup.py
This PR addresses an issue with Bytewax materialization, updates to a more recent version of Bytewax, and removes the creation of services in k8s when running a batch materialization job.
=> fix: Update bytewax materialization

.github/fork_workflows/fork_pr_integration_tests_gcp.yml, .github/workflows/java_master_only.yml, .github/workflows/java_pr.yml, .github/workflows/master_only.yml, .github/workflows/nightly-ci.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/publish.yml, docs/project/maintainers.md
=> ci: Fix workflows to use new gcloud auth step

sdk/python/feast/infra/offline_stores/redshift_source.py
Signed-off-by: Alexandre Brehelin <alexandre.brehelin@needelp.com>
As described in issues, with current get_table_column_names_and_types method in Redshift source we can't register data with more than 500 columns.  
Push method raise an error because input DataFrame doesn't fit condition (`set(input_columns) != set(source_columns)`) return by get_table_column_names_and_types. 
By default, describe table method return only 500 first columns from table. To get all columns we have to iterate through page results. 
Fixes #3282
=> fix: Get all columns with describe table method from RedshiftData-api

docs/getting-started/concepts/registry.md, docs/tutorials/using-scalable-registry.md, sdk/python/feast/infra/registry/proto_registry_utils.py, sdk/python/feast/infra/registry/registry.py, sdk/python/feast/infra/registry/sql.py
This refactors logic from the regular file based registry, and also uses an in memory proto cache for the registry, when using the SQL Registry. Caches primarily are relevant in the read path
Note: this builds on https://github.com/feast-dev/feast/pull/3394
Fixes #3328
=> fix: Enable registry caching in SQL Registry

sdk/python/feast/infra/offline_stores/snowflake.py
* Moves the pyspark import inside of the relevant method so that the Snowflake offline store does not have a necessary dependency on pyspark
* Uses typing.TYPE_CHECKING to do the imports while type checking, but not in runtime
**Resulting behavior**
* The Snowflake Offline Store can be used without `pyspark` installed
* However, when running an environment without `pyspark`, then calling `to_spark_df` raises a `FeastExtrasDependencyImportError`
Fixes [this issue](https://github.com/feast-dev/feast/issues/3383)
=> fix: Update import logic to remove `pyspark` dependency from Snowflake Offline Store

sdk/python/feast/infra/offline_stores/bigquery.py
google-api-core==2.11.0 change the default value for polling the exception as per ->
https://github.com/googleapis/python-api-core/issues/479
`block_until_done` funciton would failt because of a TypeError
This is a quick patch to support google-api-core 2.11.0
=> fix: Specifies timeout in exception polling

sdk/python/feast/type_map.py
When materializing a feature defined as a float type, if int is 0, materialization fails.
Fixes #3400
=> fix: Assertion condition when value is 0

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/bigquery_source.py
**What this PR does / why we need it**: Avoid making extra cost on a non-billing project id when applying feature views
Fixes #3416
=> fix: Apply billing project when infer schema

protos/feast/core/Feature.proto, protos/feast/types/Field.proto, sdk/python/feast/feature.py, sdk/python/feast/field.py, sdk/python/feast/templates/local/feature_repo/example_repo.py, sdk/python/tests/unit/test_feature.py, ui/src/pages/features/FeatureOverviewTab.tsx
Signed-off-by: Amom Mendes <amommendes@hotmail.com>
Adds description attribute for features/fields
Fixes #3277
=> feat: Adds description attribute for features/fields

sdk/python/feast/cli.py, sdk/python/feast/feature_store.py, sdk/python/feast/ui_server.py
Signed-off-by: Hai Nguyen <quanghai.ng1512@gmail.com>
**What this PR does / why we need it**: To support feast UI can run behind reverse proxy
Fixes #3011
=> feat: Make UI accessible behind proxy

sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py
Removes parentheses that lead to SQL syntax error when calling `get_table_column_names_and_types`
No corresponding issue created.
=> fix: Buggy SQL for postgres source

sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/registration/test_universal_types.py
**What this PR does / why we need it**: #3403 is currently blocked on being able to run an entity inference test without overwriting the `fv.schema` attribute. This PR unblocks #3403.
Fixes #
=> chore: Force entity inference without modifying `fv.schema`

sdk/python/feast/feature_view.py, sdk/python/tests/unit/infra/test_inference_unit_tests.py
Signed-off-by: gbmarc1 <marcantoine.belanger@shopify.com>
This PR replaces the `schema` attribute in the `FeatureView` object by a property. The `schema` and `entity_columns` + `features` would duplicate the source of truth internally. 
This PR exposes the `schema` as a property that is built from the `entity_columns` and `features` attributes.
Furthermore, there was a problem in the `from_proto` method were the `schema` attribute would not be assigned. This PR also avoid that gymnastic.
=> chore: Feature view as property instead to remove duplicate source of truth

sdk/python/feast/type_map.py
Signed-off-by: Ryan Beauchamp <ryan.beauchamp@ezcater.com>
The current implementation throws an exception when `sample == False` as it enters this conditional:
```python
if sample == 0 or sample == 0.0:
assert type(sample) in [np.int64, int, np.float64, float]
```
This PR adds an additional check to bypass this condition when dealing with `bool`. 
Fixes https://github.com/feast-dev/feast/issues/3451
=> fix: Add check for bool type in addition to sample

sdk/python/feast/feature_view.py, sdk/python/feast/field.py
=> fix: Ensure no duplicates in `fv.schema`

sdk/python/feast/feature_store.py
Signed-off-by: hao-affirm <104030690+hao-affirm@users.noreply.github.com>
StreamFeatureView is subclass of FeatureView, so when update a StreamFeatureView, it will be deleted twice as it is in `views_to_delete` and `sfv_to_delete`
Fixes #
=> fix: Fix delete sfv twice issue

sdk/python/feast/field.py, sdk/python/tests/unit/test_feature.py
Signed-off-by: gbmarc1 <marcantoine.belanger@shopify.com>
description field was not added to the from_proto method. We add it here.
None registered
=> fix: Add description attribute to the Field.from_proto method

sdk/python/feast/infra/offline_stores/bigquery.py
Signed-off-by: Hai Nguyen <quanghai.ng1512@gmail.com>
**What this PR does / why we need it**: point-in-time joining in BQ offline store can be more scalable
Fixes #3426
=> fix: Improve BQ point-in-time joining scalability

examples/quickstart/quickstart.ipynb
it fixies `quickstart.ipynb` notebook
Hi.
When running `quickstart.ipynb` notebook, there is a problem with the hierarchy of the directories.
After `!feast init feature_repo` we can see two nested `feature_repo` directories on the hierarchy on the left:
and then when runninng `!pygmentize feature_store.yaml` we got an error
`Error: no such file or directory`
Fix: make `%cd feature_repo/feature_repo`
Tested in colab: "Run all cells without errors".
=> fix: Fixed path inside quickstart notebook

docs/SUMMARY.md, docs/reference/online-stores/README.md, docs/reference/online-stores/rockset.md, sdk/python/docs/source/feast.infra.online_stores.contrib.rockset_online_store.rst, sdk/python/docs/source/feast.infra.online_stores.contrib.rst, sdk/python/feast/infra/online_stores/contrib/rockset_online_store/rockset.py, sdk/python/feast/repo_config.py, sdk/python/feast/templates/rockset/README.md, sdk/python/feast/templates/rockset/bootstrap.py, sdk/python/feast/templates/rockset/feature_repo/feature_store.yaml, sdk/python/feast/ui_server.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/tests/integration/feature_repos/repo_configuration.py, setup.py
This commit adds Rockset as a contributed online store. It implements the Update, Teardown, Read and Write apis using the Rockset python client.
Signed-off-by: Daniel Lin <dan@rockset.com>
This PR adds Rockset as an implemented OnlineFeatureStore
Fixes #
N/A
=> feat: Add Rockset as an OnlineStore

sdk/python/feast/feature_store.py, sdk/python/feast/infra/registry/proto_registry_utils.py, sdk/python/feast/infra/registry/registry.py, sdk/python/feast/infra/registry/sql.py, sdk/python/feast/repo_operations.py, sdk/python/tests/integration/registration/test_registry.py, sdk/python/tests/unit/infra/test_local_registry.py, sdk/python/tests/unit/test_sql_registry.py
There were issues reading from the SQL registry cache because the self.proto() method didn't populate the project in each of the object protos.
This also adds a test for reading from the SQL cache
Fixes #3457 #3430
=> fix: Fix SQL Registry cache miss

sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
These dependencies were added before any extras existed in setup.py. Feast users would generally expect that using AWS or Azure does not require Google Cloud apis.
Fixex #3458
Signed-off-by: Chris Burroughs <chris.burroughs@gmail.com>
=> chore: Move google-api dependencies to GCP extras

sdk/python/feast/infra/offline_stores/bigquery_source.py, setup.py
protobuf in python sdk should be lower bound to 3.20 because they introduced the `builder` in 3.20.
```
feast/protos/feast/types/Value_pb2.py:5
1 # -*- coding: utf-8 -*-
2 # Generated by the protocol buffer compiler.  DO NOT EDIT!
3 # source: feast/types/Value.proto
4 """Generated protocol buffer code."""
----> 5 from google.protobuf.internal import builder as _builder
6 from google.protobuf import descriptor as _descriptor
7 from google.protobuf import descriptor_pool as _descriptor_pool
ImportError: cannot import name 'builder' from 'google.protobuf.internal' /lib/python3.9/site-packages/google/protobuf/internal/__init__.py)
```
Fixes #3287
=> fix: Protobuf lower bound to 3.20 to alert that Feast is incompatible with tensorflow

sdk/python/feast/infra/contrib/spark_kafka_processor.py
Signed-off-by: shaurya.rawat <shaurya.rawat@new-work.se>
Minor fix for the sorting in `sdk/python/feast/infra/contrib/spark_kafka_processor.py` to make sure latest values are picked up for each entity.
=> fix: Spark kafka processor sorting

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py, sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssql.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, sdk/python/tests/unit/infra/offline_stores/test_bigquery.py, sdk/python/tests/unit/infra/offline_stores/test_offline_store.py, setup.py
- Introduces a `timeout` argument for `RetrievalJob` class `to_df` and `to_arrow` methods. In the bigquery implementation, the timeout was hardcoded to 1800s using those 2 functions. We want to make it configurable.
- Also, adds some base unit tests for all retrieval classes.
=> feat: Adding query timeout to `to_df` and `to_arrow` retrieval methods

sdk/python/feast/type_map.py, sdk/python/tests/unit/test_type_map.py
- We need test to avoid regressions
- Also, add support for int in `_python_value_to_proto_value` for bool values. 
@adchia Make sure that it indeed make sense to add the int support! Not sure about this one.
=> chore: Add tests to bool test type

sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
**What this PR does / why we need it**: bump great expectation dependencies
Fixes #3500
=> chore: Bump great expectation version

docs/reference/batch-materialization/bytewax.md, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
This PR adds configuration options to the Bytewax materialization engine so that it can be configured to run on at-scale Kubernetes clusters.
The Bytewax materialization engine now supports the following options:
* `image_pull_secrets` so that you can pull your engine container from a secured repository
* `service_account_name` so that the job can run under a service account
* `annotations` for attaching metadata to the job descriptor. Useful for tying the job container to an AWS role when running on EKS
* `resources` for fine-tuning the memory and CPU requirements of the materialization engine
Example of full configuration is included in the updated documentation:
```yaml
batch_engine:
type: bytewax
namespace: bytewax
image: …
```
=> feat: adds k8s config options to Bytewax materialization engine

sdk/python/feast/feature_view.py
fix: Converts `feature_view_proto.spec.entities` from `google.protobuf.internal.containers.RepeatedScalarFieldContainer` to `list`
`google.protobuf.internal.containers.RepeatedScalarFieldContainer` is not serializable and still a proto not a list.
=> fix: Feature view `entities` from_proto type

sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
Pyarrow==7.0.0 and 8.0.0 + homebrew python@3.10 do not like each [other](https://github.com/Homebrew/homebrew-core/issues/125329) on MacOS ventura.
Unbounding pyarrow to greater than 8 solves the issue.
=> build: Looser upper bound on pyarrow dependency

sdk/python/feast/ui_server.py, ui/src/FeastUISansProviders.tsx, ui/src/components/FeaturesInServiceDisplay.tsx, ui/src/components/FeaturesListDisplay.tsx, ui/src/components/ObjectsCountStats.tsx, ui/src/components/ProjectSelector.tsx, ui/src/index.tsx, ui/src/pages/RootProjectSelectionPage.tsx, ui/src/pages/Sidebar.tsx, ui/src/pages/data-sources/DataSourcesListingTable.tsx, ui/src/pages/entities/EntitiesListingTable.tsx, ui/src/pages/entities/FeatureViewEdgesList.tsx, ui/src/pages/feature-services/FeatureServiceListingTable.tsx, ui/src/pages/feature-services/FeatureServiceOverviewTab.tsx, ui/src/pages/feature-views/ConsumingFeatureServicesList.tsx, ui/src/pages/feature-views/FeatureViewListingTable.tsx, ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx, ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx, ui/src/pages/feature-views/components/FeatureViewProjectionDisplayPanel.tsx, ui/src/pages/feature-views/components/RequestDataDisplayPanel.tsx, ui/src/pages/features/FeatureOverviewTab.tsx, ui/src/pages/saved-data-sets/DatasetsListingTable.tsx
**What this PR does / why we need it**: resolve base URL in react code
Fixes #3481
=> fix: UI working behind base url

setup.py
Newest typeguard release has breaking changes. This pins typeguard to newest compatible release.
Fixes #
=> fix: Pin typeguard to 2.13.3 which is what we are currently using.

sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py, setup.py
This PR changes the Bytewax materialization config to use a list of dictionaries instead of a list of strings to correctly generate the materialization job container.
Fixes #3546
=> fix: Bytewax image pull secret config

docs/reference/online-stores/README.md, docs/reference/online-stores/rockset.md, sdk/python/feast/cli.py, sdk/python/feast/repo_config.py, sdk/python/feast/templates/rockset/bootstrap.py
Has some minor fixes and general clean up for Rockset connector.
N/A
Fixes #
=> fix: Clean up Rockset Online Store for use

.github/workflows/build_wheels.yml, setup.cfg
Since we've deleting all the go code, we do not need platform specific builds anymore. We should exploit this fact by building universal images. Anyway, cibuildwheel barfs when trying to build platform specific builds anyway.
Fixes #
=> ci: Use build --wheel instead of cibuildwheel

sdk/python/feast/infra/materialization/snowflake_engine.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/infra/online_stores/snowflake.py, sdk/python/feast/infra/registry/snowflake.py, sdk/python/feast/infra/utils/snowflake/snowflake_utils.py, sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
=> feat: Added SnowflakeConnection caching

docs/tutorials/validating-historical-features.md
The great expectactions tutorial is not working properly, I managed to run it with some small changes in the code and I thought it would be good to update it.
The complete great expectations tutorial can now be run by copying and pasting the code from the documentation.
Fixes #
=> docs: Fix the documentation to run the tutorial Validating historical features with Great Expectations

sdk/python/feast/infra/registry/sql.py, sdk/python/feast/repo_config.py
Fixes bug with using Sql Registry as described in #3544 
Fixes #3544
=> fix: Fix bug with no SqlRegistryConfig class

docs/reference/batch-materialization/bytewax.md, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
This PR adds a configuration option that signals whether or not to include Kubernetes security context capabilities in the job & pod specification.
Metadata labels also added to assist with cleaning up resources after materialization jobs have completed.
Fixes #3572
=> fix: Bytewax materializer security context

sdk/python/feast/infra/registry/registry.py
I noticed that the stream feature views were not being included in the check for conflicting feature views.
=> fix: Add Stream Feature Views to helper that collect Feature View names

sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, setup.py
boto3 1.20.23 was released in late 2021. There have been many releases since that downstream projects would reasonably want to use.
s3fs is a particularly thorny dependency because each version of s3fs depends on a very narrow range of aiobotocore versions.  s3fs (as opposed to pyarrow._s3fs) does not appear to be used directly for AWS related code.  If users want to avail themself of pandas<-->s3 integration with s3fs they can still install it directly.
=> feat: Relax aws extras requirements

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py, sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssql.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
**What this PR does / why we need it**: to support declaring timeout when persisting historical retrieval job
Fixes #
=> fix: Support param timeout when persisting

protos/feast/core/DataSource.proto, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py, sdk/python/tests/unit/test_data_sources.py
Signed-off-by: miles.adkins <miles.adkins@snowflake.com>
Fixes #2981
=> fix: Remove snowflake source warehouse tech debt

docs/reference/offline-stores/overview.md, docs/reference/offline-stores/snowflake.md, sdk/python/feast/infra/offline_stores/snowflake.py
make offline store materialization options for snowflake "better"
Fixes #3447 #3084 #3364
=> feat: Update snowflake offline store job output formats -- added arrow

docs/reference/offline-stores/overview.md, docs/reference/offline-stores/snowflake.md, sdk/python/feast/errors.py, sdk/python/feast/infra/offline_stores/snowflake.py
=> fix: Clean up snowflake to_spark_df()

docs/project/development-guide.md
Fix one minor typo in development-guide.md. The right pypi package name of pip-tools is "pip-tools" instead of "piptools". Refer: https://pypi.org/project/pip-tools/
Fixes #
=> docs: Fix minor typo.

sdk/python/feast/infra/registry/registry.py, sdk/python/feast/infra/registry/snowflake.py, sdk/python/feast/infra/registry/sql.py
=> chore: Adding logging to the feature server when the registry is refreshed

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/feast/type_map.py
When calling the Push API with the BigQuery Offline Store, if the timestamp field exists, the pyarrow timestamp unit in the code defaults to us (microsecond).
However, when bigquery load_table is executed, the timestamp column operates in ns (nano second), so the unit is inconsistent.
Because there is a time difference of 1000 times, bigquery actually inputs 1/1000 times the time, so if you put the current time, the old time of the 1970s is entered.
Fixes #3613
=> fix: Fix timestamp consistency in push api

sdk/python/feast/infra/offline_stores/bigquery_source.py
For bigquery schema inference, query the table (or query) data with LIMIT 1 and obtain a schema object.
LIMIT 1 actually returns one record, but the entire table is full scanned and costs are incurred.
For simple schema inference, it makes sense to get the schema with LIMIT 0 without scan bytes and billing.
Fixes #3433
=> fix: Fix scan datasize to 0 for inference schema

sdk/python/feast/infra/online_stores/contrib/postgres.py, sdk/python/feast/infra/utils/postgres/connection_utils.py, sdk/python/feast/infra/utils/postgres/postgres_config.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/online_store/test_universal_online.py
When using a postgres online store, there's a chance the single connection times-out due to inactivity, so we get: 
InterfaceError
connection already closed 
The mainstream solution for that is implementing a connection pool with psycopg in order to guanratee the connections to the database are managed correctly.
https://github.com/feast-dev/feast/issues/3611
Fixes #
=> fix: Implements connection pool for postgres online store

sdk/python/feast/cli.py, sdk/python/feast/repo_operations.py
This PR creates generic functionality to create a Feature store for the CLI command to have the same functionality across commands.
Currently only serve uses ENV variable-based config loader using the same functionality across commands.
=> fix: Added generic Feature store Creation for CLI

sdk/python/feast/cli.py, sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
Required for better performance of serve api application.
Using only one uvicorn process per pod in a typical kubernetes environment is inefficient.
gunicorn is recommended to manage stable multi-process in fastapi. Therefore, add the function to use processes as many as the number of workers received as arguments. 
In addition, when using LoadBalancer, options related to keep alive, which must be handled with care, are added to the gunicorn argument.
Fixes #
=> feat: Add gunicorn for serve with multiprocess

sdk/python/feast/type_map.py
For column types that exist in bigquery but don't currently exist in Feast's typemap (e.g. DATE), most of them can be used as strings.
Currently, attempting schema inference will result in an error saying that there is no type.
In order to use schema inference more actively, it seems reasonable to infer these columns as string type.
Fixes #
=> feat: Use string as a substitute for unregistered types during schema inference

ui/src/index.tsx
I think the previous coder intended for the OR operator to take precedence over the string concatenation operator but in fact, with NodeJS, string concatenation takes precedence over OR. You can confirm it by running the following commands in shell:
```sh
$ export PUBLIC_URL=/feast
$ node -e 'console.log(process.env.PUBLIC_URL || "" + "/projects-list.json")'
/feast (wrong)
$ node -e 'console.log((process.env.PUBLIC_URL || "") + "/projects-list.json")'
/feast/projects-list.json (correct)
```
This PR fixes that.
=> fix: Broken non-root path with projects-list.json

sdk/python/feast/infra/registry/sql.py
Extend the limit of the data_source_name field from 50 to 255.
Fixes #3629
=> fix: For SQL registry, increase max data_source_name length to 255

sdk/python/feast/inference.py
using python SDK when try to execute `feature_store.plan(...)` using feature_views with and without entities, feast breaks looking for __dummy keys.
There is no open issue for this bug.
=> fix: Entityless fv breaks with `KeyError: __dummy` applying feature_store.plan() on python

sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/tests/unit/infra/offline_stores/test_redshift.py, sdk/python/tests/unit/test_data_sources.py
When Feast writes to a Redshift offline store, this PR ensures that it takes the fully qualified table name into consideration so that it does not write to the wrong place in the database.
Fixes #3651
=> fix: Redshift push ignores schema

java/serving/pom.xml
To use S3 based registry, Java server needs access to S3 bucket and objects. Currently, the default S3 client uses default chain to acquire credentials. At present, S3 client acquire the role associated with EKS Node, instead of IRSA role. 
This change is to include `aws-java-sdk-sts` dependency so that default credential chain uses web identity and assume IRSA Role.
Fixes https://github.com/feast-dev/feast/issues/3648
Reference: 
https://github.com/aws/aws-sdk-java/issues/2136
=> fix: Add aws-sts dependency in java sdk so that S3 client acquires IRSA role

.github/fork_workflows/fork_pr_integration_tests_aws.yml, .github/fork_workflows/fork_pr_integration_tests_gcp.yml, .github/fork_workflows/fork_pr_integration_tests_snowflake.yml, .github/workflows/build_wheels.yml, .github/workflows/java_master_only.yml, .github/workflows/java_pr.yml, .github/workflows/linter.yml, .github/workflows/master_only.yml, .github/workflows/nightly-ci.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/pr_local_integration_tests.yml, .github/workflows/publish.yml, .github/workflows/unit_tests.yml
=> ci: Upgrade `setup-python` Github Action

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
This PR adds a possibility to use saved_dataset as a table for different spark session.  The existing solution saves the dataset’s name in registry, but the data exists only within the scope of the spark session. 
Fixes #3644
=> feat: Add possibility to save dataset as table, when spark config has remote warehouse info

sdk/python/feast/repo_operations.py
This line of code:
registry_diff, infra_diff, new_infra = store.plan(repo)
is always executed while we run "feast apply". It will call the validate() method by default which makes the option "-skip-source-validation" invalid.
Based on the original code logic, I change it to run it only when it is required. The requirement comes from:
`if store._should_use_plan():`
In the implementation of ` _should_use_plan()`:
```
def _should_use_plan(self):   
"""Returns True if plan and _apply_diffs should be used, False otherwise."""   
"""# Currently only the local provider with sqlite online store supports plan and _apply_diffs. """  
return self.config.provider == "local" and ( self.config.online_store and self.config.online_store.type == "sqlite" )`  
```
the …
=> fix: Run store.plan() only when need it.

sdk/python/tests/unit/test_sql_registry.py
See #3731
Fixes #3731
Have confirmed locally that python unit tests all now pass with `make test-python`
=> fix: Fix python unit tests

sdk/python/feast/type_map.py
Right now when trying to read a postgres table, if there are any unknown types *even if you're using a query on top of the table with only valid types* it will throw an exception. Technically you can avoid this by creating a view on top of your table but this can be a hassle when the custom query is serving this purpose anyways imo
With this fix, the only change is to surface unknown types as "unknown", which your code handles as-is with a warning and ignoring the column, allowing for usage of these tables without needing to support the arbitrary types themselves.
=> fix: Handle unknown postgres source types gracefully

README.md, docs/reference/online-stores/dragonfly.md, docs/roadmap.md
Adds Dragonfly (drop in Redis replacement as an online-store option)
Fixes #
=> docs: Add Dragonfly as an online-store option to Feast Readme and docs

sdk/python/feast/infra/offline_stores/bigquery.py
=> fix: Remove unwanted excessive splitting of gcs path, so expected gcs parquet paths are returned from BigQueryRetrievalJob.to_remote_storage()

sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, setup.py
**What this PR does / why we need it**: This PR widen Redis requirement to make it easier to install alongside other requirements, as well as to make it possible to fix some vulnerabilities.
**Which issue(s) this PR fixes**: https://github.com/feast-dev/feast/issues/3753
Fixes #3753
=> chore: Widen redis requirement to make it easier to install alongside other requirements

sdk/python/feast/infra/registry/proto_registry_utils.py
This PR fixes an issue where creating a saved dataset breaks the CLI `feast registry-dump` command. A `SavedDatasetProto` object was being incorrectly accessed in the `list_saved_datasets()` utility function, leading to a `AttributeError` when running the CLI `feast registry-dump` command.
(Sorry for the double PR, I misunderstood the DCO requirement on the first go)
Fixes #3715
=> fix: Saved datasets no longer break CLI registry-dump command

docs/reference/offline-stores/trino.md, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/data_source.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_queries.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
Right now, the Trino Offline Store implementation lacks support for authentication. Taking a look at the code it seems like it is supported via the `TRINO_AUTH` environment variable; however, environment variables can only hold string values. The issue here is that `TRINO_AUTH` is passed to [`trino.dbapi.connect`](https://github.com/trinodb/trino-python-client/blob/master/trino/dbapi.py#L119) as is (i.e. a string), but it must be a `trino.Authentication` instance. So in practice, there's no way to make authentication work.
Aside from that, the current implementation supports customizing Trino connections via `feature_store.yaml` file, or via environment variables as hinted above. Particularly, the set of supported parameters on both sides is as …
=> feat: Enhance customization of Trino connections when using Trino-based Offline Stores

sdk/python/feast/infra/utils/postgres/postgres_config.py
I think you shouldn't pass 'keepalives_idle=0' by default.
Fixes #3750
=> fix: Set keepalives_idle None by default

sdk/python/feast/infra/registry/proto_registry_utils.py
If you use File Registry, the registry file becomes heavy because materialize records are accumulated while a long period.
Even if the registry cache is enabled, performance degraded because each online feature lookup traverses the registry object and searches the meta.
As long as the registry_proto object does not change, you must avoid multiple lookups through the function-level cache.
Fixes #3649 #3597
=> feat: Apply cache to load proto registry for performance

sdk/python/feast/feature_server.py
=> feat: Add materialize and materialize-incremental rest endpoints

sdk/python/feast/infra/offline_stores/bigquery.py
This introduces an optional parameter to bigquery offline store - `table_create_disposition` which is used as part of the bigquery job client. This would benefit anyone who doesn't want to be forced to give the `bigquery.tables.create` permission to the service account that will be used to write data into their offline store. I have tested locally behaviour of a create_disposition="CREATE_NEVER" and it does not need the permission to create tables when writing to an existing table, whereas the default behaviour does.
Fixes #3763
=> feat: Add support for `table_create_disposition` in bigquery job for offline store

sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py, setup.py
This PR adds 2 new features to bytewax materialization.  
The first is to support loading kubernetes config from in_cluster config, so that materialization can easily be run as a kubernetes job. 
The second is to support adding additional labels to kubernetes objects created by bytewax so they can better be tracked.
It also addresses missing dependencies that were causing failures in the bytewax worker image by adding s3fs and pyOpenSSL dependencies
Fixes #3746
Fixes #3745
=> feat: Add support for in_cluster config and additional labels for bytewax materialization

sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
=> feat: Make bytewax job write as mini-batches

sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py
**What this PR does / why we need it**: This PR resolves hotspot issue when materializing records to HBase online store.
Previously, row keys are generated with simple serialization, which led to unbalanced row keys distribution across HBase regions. So I resolve this by applying the similar mechanism being used in BigTable online store because BigTable and HBase work the same way under the hood.
Fixes #
=> fix: Resolve hbase hotspot issue when materializing

sdk/python/feast/infra/offline_stores/bigquery.py, setup.py
We need to encapsulate the table path as the "tmp" table path can contain symbols that BigQuery can't process without encapsulation.
=> fix: Make generated temp table name escaped

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py, sdk/python/feast/infra/utils/hbase_utils.py
**What this PR does / why we need it**: Adopt connection pooling for HBase online store to keep the feature server stable and avoid broken pipe error with socket connection
Fixes #
=> fix: Adopt connection pooling for HBase

sdk/python/feast/infra/materialization/contrib/bytewax/Dockerfile, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_job.py, sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py
This PR fixes 2 issues encountered while attempting to run very large materializations (Several billion rows as part of an initial run of online materialization).
1.  Every pod created materializes every file in the dataset.  This is redundant and costs a lot of time and money.  To fix this, I updated the dataflow code to select only the single file corresponding to the running pod's JOB_COMPLETION_INDEX as input.
2. The last materialized date used for incremental materialization was being updated before materialization had even run.  This meant that if materialization had failed for some reason, many updates could be ignored, because the next run would continue from beyond the end date of the failed run.  I solved this by implementing a synchronous …
=> fix: Redundant feature materialization and premature incremental materialization timestamp updates

protos/feast/serving/GrpcServer.proto, protos/feast/serving/ServingService.proto, sdk/python/feast/cli.py, sdk/python/feast/infra/contrib/grpc_server.py, sdk/python/feast/type_map.py
**What this PR does / why we need it**: Add get online feature rpc to gprc server
Fixes #3813
=> feat: Add get online feature rpc to gprc server

sdk/python/feast/cli.py, sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py
**What this PR does / why we need it**: Regarding  #3597 and according to the current implementation of http feature server, after each interval of `cached_ttl_seconds` the main thread tries to refresh the cached registry and blocks every incoming requests.
So we need an async refresh mechanism in another thread to make the feature server stable
Fixes #
=> fix: Add async refresh to prevent synchronous refresh in main thread

sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
**What this PR does / why we need it**: Instead of reading the content of config yaml file to create configmap for bytewax job, we parse directly from repo_config object
Fixes #
=> fix: Bytewax engine create configmap from object

sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py, sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_job.py, sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py
**What this PR does / why we need it**: To optimize bytewax pods resource usage, for the case in #3825, each pods only consume 300MB of memory.
Fixes #3825
=> feat: Optimize bytewax pod resource with zero-copy

docs/reference/online-stores/redis.md, sdk/python/feast/infra/online_stores/redis.py
Redis Sentinel is a standard strategy for autonomous high availability.
[Redis Docs for Sentinel](https://redis.io/docs/management/sentinel/)
I did not create an issue. Also, docs updated too.
=> feat: Adding redis sentinel support

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/utils/aws_utils.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
Update the Pyarrow to the latest version v14.0.1 which has the fix for https://github.com/advisories/GHSA-5wvp-7f3h-6wmm
Fixes # 3832
1. Before this PR, the Pyarrow version is v10.0.1 for Feast. It's default parquet format version is v2.4 for the function "[pyarrow.parquet.write_table()](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html#pyarrow.parquet.write_table)".  Check the "version" argument.
2. With parquet format v2.4, this function will change the timestamps's resolution (check the doc of argument "coerce_timestamps": 
"By default, for version='1.0' (the default) and version='2.4', nanoseconds are cast to microseconds (‘us’),"
3. After upgraded the Feast with "pyarrow==14.0.1", …
=> fix: Upgrade the pyarrow to latest v14.0.1 for CVE-2023-47248.

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/utils/aws_utils.py
If timestamp_fields is entered in Microseconds, a 500 error occurs.
Allow truncation of numbers when coercing nano seconds in pyarrow write_table.
Fixes #3860
=> fix: Allow trancated timestamps when converting

sdk/python/feast/feature_view.py, sdk/python/feast/stream_feature_view.py, sdk/python/tests/unit/test_feature_views.py
There is a logic error while checking the StreamFeatureView's proto_class.  In function "_check_conflicting_feature_view_names()" of "feast/infra/registry/registry.py", the code will check all FeatureView's proto_class. With the current implementation (v0.34.1), the StreamFeatureView is a subclass of FeatureView class, and it does not have its own overload of "proto_class()" function. As a result, the proto_class() will always return "FeatureViewProto" instead of "StreamFeatureViewProto".
The developer @romqn1999 mentioned this error and solution in the created issue [#3805](https://github.com/feast-dev/feast/issues/3805)
Fixes #3805 #3836
=> fix: Correct the returning class proto type of StreamFeatureView to StreamFeatureViewProto instead of FeatureViewProto.

sdk/python/feast/infra/registry/snowflake.py, sdk/python/feast/infra/utils/snowflake/registry/snowflake_registry_table.py, sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
For snowflake users who only have "USAGE" and "SELECT" privileges, we want to allow them able to run the "feast apply" command and do READ-only access existing Registry tables in snowflake cloud.
Please be aware that the Feast Registry is designed to allow every user can modify the records of registry tables under their own "project" name. This PR didn't change the original design. It only changes the previous implementation logic of snowflake.py which always calls "CREATE" sql command while initializing the SnowflakeRegistry(), which will be called while run statement:
store = FeatureStore()
This PR is tested with snowflake cloud privilege for a Role with setting as below:
for feast Registry database : SELECT - FUTURE TABLE, SELECT - FUTURE VIEW, USAGE …
=> fix: Verify the existence of Registry tables in snowflake before calling CREATE sql command. Allow read-only user to call feast apply.

sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/offline_stores/snowflake_source.py, sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_creation.sql, sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_udfs.py, sdk/python/feast/type_map.py, sdk/python/tests/data/data_creator.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py, sdk/python/tests/integration/materialization/test_snowflake.py
Snowflake doesn't support type-checked arrays but this adds support for arrays where developers have to guarantee the type consistency themselves through the external data pipelines.
This implementation adds support for these data types when stored as an array column in Snowflake:
- Array(String)
- Array(Bytes)
- Array(Int32)
- Array(Int64)
- Array(UnixTimestamp)
- Array(Float64)
- Array(Float32)
- Array(Bool)
This *does not work* with Feast's Feature Inference or the push/spark online store. The schema for these columns has to be defined in Feast because Snowflake itself isn't storing the data type of these variant columns for us to know how to translate them.
Which issue(s) this PR fixes:
Fixes https://github.com/feast-dev/feast/issues/2280
=> feat: Add support for arrays in snowflake

sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/tests/unit/infra/offline_stores/test_snowflake.py
- We need to run Feast in AWS govcloud regions 
- We also use Snowflake as our offline datastore
- bytewax is online materializer
- DynamoDB is online store
This stack works really well in commercial AWS regions.
However, it is a different story when it comes to AWS govcloud. 
It turned out that you have to use special snowflake schema `s3gov` when data exported by Snowflake with `COPY INTO location` during Feast materialization into online store.  
`blob_export_location` is set to 's3gov://bucket/path` to get a temp data dump to s3. Export part works just fine.
But, following data upload into online data store fails, because pyarrow doesn't recognize `s3gov` schema of temp data dump. Here is actual error
```
[2024-01-10, 19:45:52 UTC] …
```
=> feat: Support s3gov schema by snowflake offline store during materialization

sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py
The primary rationale behind these changes is to prevent duplicate key errors that occur when attempting to create an index that already exists. By checking for the existence of an index before creating it, the PR ensures calling `feast apply` more than once won't cause an error.
**Which issue(s) this PR fixes**
This PR addresses a potential issue where the MySQL online store could encounter duplicated key errors when the Feast SDK tries to create an index that already exists. 
Fixes https://github.com/feast-dev/feast/issues/3906
=> fix: Create index only if not exists during MySQL online store update

sdk/python/feast/infra/materialization/contrib/bytewax/Dockerfile, sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py
**What this PR does / why we need it:**
PR ensures that the Bytewax materialization engine works.
**Which issue(s) this PR fixes**
yaml.safe_load() raises an error while trying to reconstruct the object below:
pathlib.PosixPath
The error occurs while running materialization using Bytewax at the point where the feature_store.yaml is loaded. The code where this happens is in [sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py](https://github.com/feast-dev/feast/blob/ac6529c380bc623a15054350c9936b69617b4bee/sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py#L14). 
Fixes https://github.com/feast-dev/feast/issues/3893
=> fix: Bytewax materialization engine fails when loading feature_store.yaml

sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
Since bytewax spawns many pods to run, it's easy to reach daily limitation pulls from dockerhub, which blocks the engine from execution.
A minor change to adjust image pull policy from `Always` to `IfNotPresent`
Fixes #
=> fix: Prevent spamming pull busybox from dockerhub

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/tests/unit/test_sql_registry.py, setup.py
feast mysql extra declares dependency on `mysqlclient`, but that's actually incorrect because `mysqlclient` is only used in sql registry tests, mysql online store implementation uses `pymysql`. this PR changes the relevant tests to use pymysql as well and removes `mysqlclient` from the project.
P.S. This might break someone's build if they relied on a transitive dependency provided by feast, but I don't think that's enough of a reason to keep an unnecessary extra dependency.
Fixes #3916
=> fix: Remove unnecessary dependency on mysqlclient

.github/workflows/pr_integration_tests.yml, .github/workflows/pr_local_integration_tests.yml, .github/workflows/unit_tests.yml
Following up with [NEP](https://numpy.org/neps/nep-0029-deprecation_policy.html) and many libraries are dropping py38 support
We need to migrate our CI integration tests to py39+ version
**Additional information:**
Related to #3928, if we want to run integration tests with pandas v2, we must run on py3.9+,
So that we need to extend our integration tests workflow matrix to run on py310 additionally
Fixes #
=> ci: Extend python base version for test cases

sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
**What this PR does / why we need it:**
When Feast with OfflineStore as Trino with basic Authentication, password is converted with `SecretStr` in Pydantic type.
Then error occurred with 401('Access Denied: Invalid credentials').
It can be solved when I replace `SecretStr` into `StrictStr` where `.feast.infra.offline_stores.contrib.trino_offline_store.trino.py` line 43.
* Before
*  After 
And `feature_store.yaml` format is like below
```yaml
project: deepfm_repo
registry: data/registry.db
provider: local
offline_store:
type: trino
host: localhost
port: 443
catalog: lakehouse
connector:
type: hive
file_format: parquet
user: aidt-devops
source: feast-trino-offline-store
http-scheme: https
ssl-verify: true
auth:
type: basic
config:
username: aidt-devops
password: devops123@ …
```
=> fix: Trino as an OfflineStore Access Denied when BasicAuthenticaion

ui/README.md
The PR addresses a specific typo within the Feast UI README file. The correction involves updating the reference to the `projects-list.json` file, ensuring that it accurately reflects the intended file name. This change is important for maintaining the clarity and utility of the documentation, thereby preventing potential confusion among users attempting to configure the customized Feast UI.
This PR resolves the issue highlighted in [Feast Issue #3332](https://github.com/feast-dev/feast/issues/3332)
Fixes #3332
=> fix: Typo Correction in Feast UI Readme

docs/SUMMARY.md, docs/reference/online-stores/README.md, docs/reference/online-stores/scylladb.md
Add documentation about ScyllaDB and ScyllaDB Cloud as online store alternatives. ScyllaDB can use the already existing Cassandra connector.
=> docs: Add ScyllaDB as online store alternative (fixed DCO)

sdk/python/feast/infra/online_stores/contrib/postgres.py
This PR ensures that the materialization step in the PostgreSQLOnlineStore succeeds and thus the data is pushed to the online store. It does so by running `conn.commit()` after the insert SQL statement has ran.
Fixes #3903
=> fix: Add conn.commit() to Postgresonline_write_batch.online_write_batch

sdk/python/feast/infra/transformation_servers/Dockerfile
Transformation Server docker image does editable pip install and the resulting installation lacks python files generated from protobuf. The image is currently failing on startup.
Fixes #3627
=> fix: Transformation server doesn't generate files from proto

sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, sdk/python/tests/unit/test_feature_views.py, setup.py
Pinning typeguard to 2.X.X causes quite a few incompatibilities with other dependencies. The [original reason](https://github.com/feast-dev/feast/issues/3538) why this pinning happened has been fixed with [this commit](https://github.com/agronholm/typeguard/commit/216a7b982a8444b72e28392c7dcae13bcc5120e2)
which is in typeguard==3.0.1
=> fix: Update typeguard version to >=4.0.0

docs/how-to-guides/structuring-repos.md, sdk/python/feast/cli.py
The code in cli.py (line 75) doest not configure shortcut:
@click.option( "--feature-store-yaml", help="Override the directory where the CLI should look for the feature_store.yaml file.", )
Refer to an closed obsolete PR: https://github.com/feast-dev/feast/pull/3783
Fixes #3771
=> fix: Fix typo as the cli does not support shortcut-f option.

Makefile, sdk/python/feast/infra/contrib/spark_kafka_processor.py, sdk/python/feast/infra/contrib/stream_processor.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/data_source.py, sdk/python/feast/infra/offline_stores/snowflake.py
revert mypy scoped config
Changes:
+ Lint fixes
Fixes #
=> fix: Revert mypy config

docs/reference/data-sources/overview.md, docs/reference/data-sources/snowflake.md, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/tests/unit/infra/offline_stores/test_snowflake.py
A bug appears when the following happens.
1. Fetch from a Snowflake-backed FeatureView.
2. The FeatureView has an array-type column.
3. One of the fetched entities does not have a record in the Snowflake table.
This add a null check and includes the documentation around Snowflake now supporting array types. I forgot to add it in my previous PR.
Fixes # 3963
=> fix: Bugfix for grabbing historical data from Snowflake with array type features.

protos/feast/core/OnDemandFeatureView.proto, protos/feast/registry/RegistryServer.proto, sdk/python/feast/infra/registry/base_registry.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/on_demand_pandas_transformation.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/unit/test_on_demand_feature_view.py
This PR decouples transformation logic and default engine from on demand feature views. It's a first step to eventually resolve - #3945. It introduces a new class `OnDemandPandasTransformation` and refactors pandas-related code from `OnDemandFeatureView`. This is to be followed by other types of transformations like `OnDemandSqlTransformation` and `OnDemandSubstraitTransformation`.
PR technically breaks `OnDemandFeatureView` "public" api, as the following code will no longer work:
```
OnDemandFeatureView(
name="my-on-demand-feature-view",
sources=sources,
schema=[
Field(name="output1", dtype=Float32),
Field(name="output2", dtype=Float32),
],
udf=udf1,
udf_string="udf1 source code",
)
```
Instead now you would do:
```
OnDemandFeatureView( …
```
=> feat: Decouple transformation types from ODFVs

sdk/python/feast/stream_feature_view.py, sdk/python/tests/unit/test_feature_views.py
This PR fixes `__copy__` method of `StreamFeatureView` which is used here https://github.com/feast-dev/feast/blob/4e450ad3b1b6d2f66fd87e07805bb57772390142/sdk/python/feast/feature_store.py#L2191.
I believe this issue prevents the possibility to get features defined in `StreamFeatureView` using `FeatureService`s.
=> fix: Fix copy method for StreamFeatureView

examples/quickstart/quickstart.ipynb
Removed unnecessary comma in notebook
Fixes #3975
=> fix: Quickstart notebook example

sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, setup.py
=> chore: Bump CI requirement cryptography to v42

.github/workflows/java_pr.yml, .github/workflows/lint_pr.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/pr_local_integration_tests.yml
Restore or add conditional label check to any action jobs utilizing `pull_request_target` to ensure manual screening of included changes occurs prior to PR hook checkout/execution of fork branch payloads.
Fixes #3684
=> fix: Restore label check for all actions using pull_request_target

sdk/python/feast/infra/online_stores/redis.py
Even if the feature view is no longer used, the data is not deleted until there are no feature views left in the join key.
Memory in redis is a very expensive resource.
When deleting feature_view, a function is added so that the corresponding key can be found and deleted in the redis hash.
Fixes #3856
=> feat: Added delete_table to redis online store

Makefile, sdk/python/feast/infra/offline_stores/contrib/duckdb_offline_store/duckdb.py, sdk/python/feast/infra/offline_stores/contrib/duckdb_repo_configuration.py, sdk/python/feast/infra/offline_stores/contrib/ibis_offline_store/ibis.py, sdk/python/feast/repo_config.py, setup.py
This PR adds duckdb as a contrib offline store to feast. Introduces another extra named `duckdb` which is not part of a `ci` extra as we don't run ci tests for contrib components. The changes can be tested by running `test-python-universal-duckdb` command from Makefile. The primary reason why this need to be a contrib component as of now is that it's only targeting Python 3.9+. While possible to backport it to Python 3.8 as well, `ibis` on which the codebase depends on has dropped 3.8 support a long time ago and I thought it wasn't worth wasting time on 3.8 compatibility when we are slated to drop the support pretty soon anyway.
This PR supersedes #3822 and is a first step to eventually address - #3979. While this PR targets duckdb as an offline …
=> feat: Add duckdb offline store

sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/data_source.py, sdk/python/tests/integration/feature_repos/universal/online_store/redis.py, sdk/python/tests/unit/test_sql_registry.py
Testing container hosts are hardcoded to either localhost, which makes the life for people who develop inside containers hard. This PR instead gets host from testcontainer's `get_container_host_ip`. This also doesn't always get it right, but at least lets the developer override the values with some env vars. For example in my case (vscode running inside Docker for Windows WSL container with docker socket mounted) this config seems to get tests working:
```
volumes:
- //var/run/docker.sock:/var/run/docker.sock
environment:
TC_HOST: host.docker.internal
DOCKER_HOST: unix:///var/run/docker.sock
```
=> fix: Get container host addresses from testcontainers

.github/workflows/lint_pr.yml
After recently adding security label checks to all `pull_request_target` actions that were missing it, I noticed title validation checkjs started being [skipped](https://github.com/feast-dev/feast/actions/runs/8162568306/job/22313824999?pr=3986) due to the conditional paired with this trigger type. This PR takes the check logic back to the simple repo verify, but adds explicit read-only permissions matching the [recommended](https://github.com/amannn/action-semantic-pull-request#installation) install configuration.
=> fix: Swap security label check on the PR title validation job to explicit permissions instead

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
**What this PR does / why we need it**: For handling bigdata, using sparkofflinestore, it is not efficient to create entity df in pandas dataframe type then pass to get_historical_features function, this pr will add ability to input a Spark DataFrame entitydf 
Fixes #
=> feat: Add Entity df in format of a Spark Dataframe instead of just pd.DataFrame or string for SparkOfflineStore

java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh, setup.py
PR #3687 added a spiffy feature to ingest streaming features, but this came along with a large batch of depdencies.  Notable this induces a core dependency on `protobuf>=4.21.6` while Feast itself is on `protobuf<4.23.4,>3.20`.  This is a fiddly narrow range and excludes all 3.x uses.
=> fix: Move gRPC dependencies to an extra

.github/workflows/lint_pr.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/pr_local_integration_tests.yml, .github/workflows/unit_tests.yml, docs/reference/alpha-web-ui.md, docs/reference/offline-stores/spark.md, java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh, sdk/python/feast/errors.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/data_source.py, sdk/python/feast/infra/registry/base_registry.py, sdk/python/feast/infra/registry/registry.py, sdk/python/feast/infra/registry/remote.py, sdk/python/feast/repo_config.py, sdk/python/feast/types.py, sdk/python/tests/integration/feature_repos/universal/online_store/redis.py, sdk/python/tests/unit/infra/registry/test_remote.py, sdk/python/tests/unit/test_sql_registry.py, setup.py, ui/README.md, ui/yarn.lock
=> merge master

docs/getting-started/concepts/registry.md, docs/tutorials/using-scalable-registry.md, sdk/python/feast/infra/registry/sql.py, sdk/python/feast/repo_config.py, sdk/python/tests/unit/test_sql_registry.py
The PR introduces an optional `sqlalchemy_config_kwargs` key to the [SQL Registry](https://docs.feast.dev/getting-started/concepts/registry#sql-registry) config. The new key allows passing in custom `**kwargs` to [sqlalchemy.create_engine](https://github.com/feast-dev/feast/blob/fa8492dfe7f38ab493a8d35a412ec9334a0ff6b9/sdk/python/feast/infra/registry/sql.py#L202).
One such kwarg is [pool_pre_ping: true](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine) which in turn helps avoid errors due to closed or timed out connections. Such errors happen in particular when running the Python Feature Server as an API.
Example errors this prevents:
```python
psycopg2.OperationalError: connection to server at "<SERVER_DNS>" …
```
=> fix: Extend SQL registry config with a sqlalchemy_config_kwargs key

sdk/python/feast/infra/registry/caching_registry.py, sdk/python/feast/infra/registry/sql.py
Adds another abstract class `CachingRegistry` that extends `BaseRegistry`. It replaces `BaseRegistry` methods like `get_entity` with it's own abstract `_get_entity` and injects caching logic. Caching logic came from `SqlRegistry`, which was also refactored to use `CachingRegistry` as part of this PR.
P.S. I chose not to touch snowflake registry yet, because it isn't tested in CI.
Fixes #3940
=> feat: Refactor registry caching logic into a separate class

sdk/python/feast/driver_test_data.py, sdk/python/feast/infra/offline_stores/file.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/on_demand_pandas_transformation.py, sdk/python/feast/utils.py, sdk/python/tests/unit/infra/offline_stores/test_redshift.py, sdk/python/tests/unit/infra/offline_stores/test_snowflake.py, sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py, sdk/python/tests/unit/test_on_demand_feature_view.py, sdk/python/tests/unit/test_sql_registry.py, sdk/python/tests/utils/test_wrappers.py
Fixes a bunch of annoying warnings thrown by `make test-python`. There are some notable exceptions still left like dask and sqla deprecation warnings and a single warning in `ibis-substrait` that needs to be fixed in the source.
=> fix: CI unittest warnings

sdk/python/feast/feature_store.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.8-ci-requirements.txt, sdk/python/requirements/py3.8-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
This PR fix the segmentation fault error while upgrading the "protobuf" version to above 4.24.0.
Based on my debug, the root cause is this line of code under the "plan()" function of "FeatureStore" class. (around line 748 of https://github.com/feast-dev/feast/blob/master/sdk/python/feast/feature_store.py )
`current_infra_proto = self._registry.proto().infra.__deepcopy__()`
The above "self._registry.proto().infra" could return an Empty object and will create a segmentation fault. 
My current solution is to create an empty object first and use the "CopyFrom()"  method from protobuf.
My test env:
python 3.8
protobuf 4.25.3
Fixes #3921
=> fix: Use CopyFrom() instead of __deepycopy__() for creating a copy of protobuf object.

docs/reference/online-stores/hazelcast.md
docs change to fix the formatting for the Hazelcast connector code sample
https://docs.feast.dev/v/master/reference/online-stores/hazelcast#examples
Added ```endcode``` tag for code sample
=> docs: Updated hazelcast for missing code tag

Makefile, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
- removed unused dependency on `avro`
- removed unused dependency on `proto-plus` (it's still pulled in through transitive dependency on gcp libraries)
- moved `httpx` to `ci` extra as it's only used by `fastapi` testing utilities
- `docs` and `dev` extras are same as `ci`, there are no longer any reasons at this point for them to be different, problematic mysql dependency was fixed a while ago
Also fixes #4000
=> chore: Clean up dependencies in setup.py

sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
[pull_latest_from_table_or_query](https://github.com/feast-dev/feast/blob/9df2224283e04760116b61bed3c8bfa7f17cbf7e/sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py#L60) attempts to pull the latest data using the outputted string from [get_table_query_string](https://github.com/feast-dev/feast/blob/9df2224283e04760116b61bed3c8bfa7f17cbf7e/sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py#L119). However on line [97](https://github.com/feast-dev/feast/blob/9df2224283e04760116b61bed3c8bfa7f17cbf7e/sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py#L97) of postgres.py the query includes open and close parens assuming an inner query. These params should be …
=> fix: Remove parentheses in pull_latest_from_table_or_query

protos/feast/core/OnDemandFeatureView.proto, protos/feast/core/StreamFeatureView.proto, protos/feast/core/Transformation.proto, sdk/python/feast/diff/registry_diff.py, sdk/python/feast/infra/registry/base_registry.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/on_demand_pandas_transformation.py, sdk/python/feast/on_demand_substrait_transformation.py, sdk/python/feast/stream_feature_view.py, sdk/python/tests/unit/diff/test_registry_diff.py, sdk/python/tests/unit/test_feature_views.py, sdk/python/tests/unit/test_on_demand_feature_view.py, sdk/python/tests/unit/test_sql_registry.py, sdk/python/tests/unit/test_stream_feature_view.py, ui/src/pages/feature-views/OnDemandFeatureViewOverviewTab.tsx
This PR updates the `OnDemandFeatureView` and `StreamingFeatureView` protobuf objectss into separate `FeatureTransformation` protobuf objects explicitly. This is a much cleaner way for machine learning engineers to understand the transformations. 
This PR will do the following:
1. Create the new `FeatureTransformation.proto` file and object
2. Deprecate `UserDefinedFunction` in the `OnDemandFeatureView.proto` and `StreamFeatureView.proto` files
3. Store the new `FeatureTransformationProto` in the `OnDemandFeatureViewSpec` and `StreamFeatureViewSpecProto` objects so that when writes are executed the new protos are stored alongside the old protos
4. Read from both the old `UserDefinedFunction` proto and the new `FeatureTransformation` proto and handle …
=> feat: Updating protos to separate transformation

sdk/python/feast/base_feature_view.py, sdk/python/feast/infra/registry/base_registry.py, sdk/python/feast/infra/registry/registry.py
#4004 removed `proto-plus` from required dependencies but missed some dangling imports that were still part of the codebase.
=> fix: Remove proto-plus imports

java/CONTRIBUTING.md, java/pom.xml, java/serving/.gitignore, java/serving/pom.xml, java/serving/src/main/java/feast/serving/registry/AzureRegistryFile.java, java/serving/src/main/java/feast/serving/service/config/ApplicationProperties.java, java/serving/src/main/java/feast/serving/service/config/RegistryConfigModule.java, java/serving/src/test/java/feast/serving/it/ServingRedisAzureRegistryIT.java, java/serving/src/test/java/feast/serving/it/ServingRedisGSRegistryIT.java, java/serving/src/test/java/feast/serving/it/ServingRedisS3RegistryIT.java
This PR is implementing the feature requested in issue: Azure blob storage support in Java feature server #2319
Changes:
- Add azure blob storage support in java feature server
- Fix S3 integration test to work without a real AWS account (to make sure it works before opening the PR)
- Add GCS mock to integration tests to be able to run them without a real google cloud account (to make sure it works before opening the PR)
- Adding dependency management in maven for libraries with older incompatible versions as transitive dependencies (0.35.0 is actually broken because of transitive dependency version conflicts)
Fixes #2319 
**How it was tested**
- All  integration tests are green
- A docker image has been built from …
=> fix: Azure blob storage support in Java feature server (#2319)

sdk/python/feast/constants.py, sdk/python/feast/feature_server.py, setup.py
#3636 introduced `gunicorn` to run `uvicorn` workers to improve feature server performance. Unfortunately `gunicorn` import happens at the module level and breaks feast on windows which is not supported by `gunicorn`. This PR checks which platform is being used and falls back on pure `uvicorn` server on windows. 
Fixes #3770
=> fix: Run feature server w/o gunicorn on windows

sdk/python/feast/infra/registry/sql.py, setup.py
Upgrade the SqlAlchemy to 2.x Regarding the PVE-2022-51668  mentioned in issue: [#4062 ](https://github.com/feast-dev/feast/issues/4062)
Implemented following the instruction: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html
Fixes #4062
=> fix: Upgrade sqlalchemy from 1.x to 2.x regarding PVE-2022-51668.

sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/transformation/pandas_transformation.py, sdk/python/feast/transformation/python_transformation.py, sdk/python/feast/transformation/substrait_transformation.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py
Refactors schema inference logic for ODFVs and delegates it to respective transformations. Also refactors creation of substrait transformations in the decorator to make it similar to pandas and python flow.
=> feat: Refactor ODFV schema inference

sdk/python/feast/infra/materialization/kubernetes/Dockerfile, sdk/python/feast/infra/materialization/kubernetes/k8s_materialization_engine.py, sdk/python/feast/infra/materialization/kubernetes/k8s_materialization_job.py, sdk/python/feast/infra/materialization/kubernetes/k8s_materialization_task.py, sdk/python/feast/infra/materialization/kubernetes/main.py, sdk/python/feast/repo_config.py, sdk/python/tests/integration/materialization/kubernetes/README.md, sdk/python/tests/integration/materialization/kubernetes/eks-config.yaml, sdk/python/tests/integration/materialization/kubernetes/test_k8s.py, setup.py
As our efforts to prune bytewax dependencies to support python 3.11, in this PR I've rewritten bytewax engine as a new one called kubernetes engine.
Most of the code is unchanged, genuinely modify image entrypoint to process paths from remote storage
Relates to #4046 
Docs will be provided in a separate PR and also bytewax removal
=> feat: Kubernetes materialization engine written based on bytewax

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
Importing pyspark lazily.
This change will fix the issue - https://github.com/feast-dev/feast/issues/3872
Picked up changes from the PR - https://github.com/feast-dev/feast/pull/3873
=> fix: Trying to import pyspark lazily to avoid the dependency on the library

sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/transformation/pandas_transformation.py, sdk/python/feast/transformation/python_transformation.py, sdk/python/feast/transformation/substrait_transformation.py, sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
ODFV execution in offline flow revolves around pandas as both `pandas` and `substrait` transformations take pandas dataframes as an input. `substrait` has an unnecessary performance penalty as a consequence because it has to then convert pandas to arrow before execution. This PR flips the order around and makes arrow the primary interchange for execution, therefore `substrait` transformation can work without ever touching pandas.
P.S. This PR only touches offline flow for now just to make the scope smaller. I'll make necessary changes to the online side later in a separate PR and get rid of some of the dead code that will be left unused.
=> feat: Make arrow primary interchange for offline ODFV execution

sdk/python/feast/infra/contrib/spark_kafka_processor.py
making the query_timeout variable as optional int because upstream timeout is also optional. This is expected to fix the issue - https://github.com/feast-dev/feast/issues/3799
=> fix: Making the query_timeout variable as optional int because upstream is considered to be optional

docs/reference/usage.md, sdk/python/feast/constants.py, sdk/python/feast/usage.py
The "usage.feast.dev" is no long available.  Let's disable it by default.
=> fix: Disable the Feast Usage feature by default.

sdk/python/feast/cli.py
Removes top-level grpc import in cli.
=> fix: Remove top-level grpc import in cli

sdk/python/feast/infra/online_stores/dynamodb.py
Add the option to configure and set tags on the AWS DynamoDB table resource created for an online store. Many organizations use tags to manage their resources which makes it convenient to directly add tags in the configuration file of Feast so that they are added upon creation of the tables.
=> feat: Add tags to dynamodb config

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
=> revert: Reverts "fix: Using version args to install the correct feast version"

protos/feast/core/Transformation.proto, sdk/python/feast/infra/offline_stores/ibis.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/transformation/pandas_transformation.py, sdk/python/feast/transformation/python_transformation.py, sdk/python/feast/transformation/substrait_transformation.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/unit/test_substrait_transformation.py
This PR changes the offline flow for ODFV execution in ibis-based offline stores (currently only duckdb). Instead of collecting raw offline store output into a pyarrow table and applying a substrait transformation with acero, ibis-based offline stores now get ibis functions and directly extend ibis logical plan, meaning ODFVs will be executed by the offline store engine itself.
The feature necessitated a couple of underlying changes in `substrait` ODFVs:
1. `substrait` ODVS now also store ibis python functions in protos to directly apply these functions in `transform_ibis`. This can probably be avoided in the future if there's a good substrait to ibis compiler in place, but currently is the simplest solution. Note: there are other problems here as well, substrait plans need to know …
=> feat: Incorporate substrait ODFVs into ibis-based offline store queries

sdk/python/feast/feature_view_projection.py
=> fix: Get rid of empty string `name_alias` during feature view projection deserialization 

sdk/python/feast/__init__.py, sdk/python/feast/cli.py, sdk/python/feast/proto_json.py, sdk/python/feast/ui_server.py, sdk/python/feast/version.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
Explicit dependency on non-standard importlib libraries (`importlib-resources` and `importlib_metadata`) is no longer required after dropping 3.8. This PR switches to use alternatives from standard library.
=> chore: Drop dependency on non-standard importlib libraries

protos/feast/core/DataFormat.proto, sdk/python/feast/data_format.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/ibis.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, setup.py
This PR adds delta format to `FileSource` (only parquet was supported before), also implements logic for handling delta sources in ibis offline store. It also adds integration tests for duckdb offline store with delta sources, dukdb tests are effectively run twice, once for parquet and then for delta.
=> feat: Add delta format to `FileSource`, add support for it in ibis/duckdb

java/serving/src/test/java/feast/serving/it/ServingEnvironment.java, java/serving/src/test/java/feast/serving/it/ServingRedisAzureRegistryIT.java, java/serving/src/test/java/feast/serving/it/ServingRedisGSRegistryIT.java, java/serving/src/test/java/feast/serving/it/ServingRedisS3RegistryIT.java
This PR makes similar changes to java integration tests as #3946 did to python ones. Changes are necessary for the tests to be runnable from inside a container.
- Resolves container address by calling `getHost()` instead of hardcoding `localhost`. The user will usually have to also set `TESTCONTAINERS_HOST_OVERRIDE` env variable to `host.docker.internal`
- `DockerComposeContainer` by default works by first running another container with `docker-compose` inside and mounting build context and running `docker-compose up` from there. This doesn't really work if you're already inside a container as volume mounts and `docker-in-docker` don't really get along well. This PR introduces an environment variable `FEAST_TESTCONTAINERS_LOCAL_COMPOSE` which if set changes the default behavior to running …
=> fix: Get container host addresses from testcontainers (java)

docs/getting-started/quickstart.md
Updating the instructions for quick start guide as per new instructions or output and also fixes the issue [4104](https://github.com/feast-dev/feast/issues/4104)
[4104](https://github.com/feast-dev/feast/issues/4104)
=> fix: Updating the instructions for quickstart guide.

.devcontainer/devcontainer.json, .github/fork_workflows/fork_pr_integration_tests_aws.yml, .github/fork_workflows/fork_pr_integration_tests_gcp.yml, .github/fork_workflows/fork_pr_integration_tests_snowflake.yml, .github/workflows/build_wheels.yml, .github/workflows/nightly-ci.yml, .github/workflows/unit_tests.yml, java/serving/src/test/java/feast/serving/it/ServingEnvironment.java, java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml, java/serving/src/test/resources/docker-compose/feast10/Dockerfile, java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh, java/serving/src/test/resources/docker-compose/feast10/requirements.txt
In a docker-compose setup used in java integration tests, `pip install .` is part of an entrypoint.sh file, which effectively means that it's run once for each test (there are 6 tests as of now). This PR changes compose setup and moves feast pip install to a docker build step. This should noticeably speed up java integration tests.
=> chore: Move feast install to docker build in java it tests

.devcontainer/devcontainer.json, .github/fork_workflows/fork_pr_integration_tests_aws.yml, .github/fork_workflows/fork_pr_integration_tests_gcp.yml, .github/fork_workflows/fork_pr_integration_tests_snowflake.yml, .github/workflows/build_wheels.yml, .github/workflows/nightly-ci.yml, .github/workflows/unit_tests.yml, CHANGELOG.md, infra/charts/feast-feature-server/Chart.yaml, infra/charts/feast-feature-server/README.md, infra/charts/feast-feature-server/values.yaml, infra/charts/feast/Chart.yaml, infra/charts/feast/README.md, infra/charts/feast/charts/feature-server/Chart.yaml, infra/charts/feast/charts/feature-server/README.md, infra/charts/feast/charts/feature-server/values.yaml, infra/charts/feast/charts/transformation-service/Chart.yaml, infra/charts/feast/charts/transformation-service/README.md, infra/charts/feast/charts/transformation-service/values.yaml, infra/charts/feast/requirements.yaml, java/pom.xml, java/serving/src/test/java/feast/serving/it/ServingEnvironment.java, java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml, java/serving/src/test/resources/docker-compose/feast10/Dockerfile, java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh, java/serving/src/test/resources/docker-compose/feast10/requirements.txt, sdk/python/feast/ui/package.json, sdk/python/feast/ui/yarn.lock, ui/package.json
* Pgvector patch ([#4108](https://github.com/feast-dev/feast/issues/4108)) ([1a1f0b1](https://github.com/feast-dev/feast/commit/1a1f0b1c56aa2ac00b1e1aa1e21cc200ea659334))
* Reverts "fix: Using version args to install the correct feast version" ([#4112](https://github.com/feast-dev/feast/issues/4112)) ([d5ded69](https://github.com/feast-dev/feast/commit/d5ded69dea9af3a363feaa948cd3d2dcf10fb80c)), closes [#3953](https://github.com/feast-dev/feast/issues/3953)
=> chore: Incorporate release 0.37.1 to master

.github/workflows/linter.yml, .github/workflows/master_only.yml, .github/workflows/nightly-ci.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/pr_local_integration_tests.yml, .github/workflows/unit_tests.yml, Makefile
- Upgrades setup-python action to latest
- Disables caching, caches are bound to branches and unit tests run on different PR source branches cannot reuse each other's cache. Only multiple runs on the same PR can.
- Installs python dependencies with [uv](https://github.com/astral-sh/uv)
=> chore: Install python dependencies with uv in workflows

sdk/python/feast/feature_store.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/online_response.py, sdk/python/feast/transformation/python_transformation.py, sdk/python/feast/transformation/substrait_transformation.py, sdk/python/feast/transformation_server.py, sdk/python/tests/unit/test_on_demand_feature_view.py
This PR is an online counterpart of #4083. online response object no longer needs to be converted to pandas for substrait transformations to be executed. Also cleans up some leftover unused code from `on_demand_feature_view.py`.
=> feat: Make arrow primary interchange for online ODFV execution

README.md, docs/SUMMARY.md, docs/reference/online-stores/README.md, docs/reference/online-stores/ikv.md, docs/reference/online-stores/overview.md, docs/roadmap.md
Followup on https://github.com/feast-dev/feast/pull/4068, adding documentation for IKV online store.
=> feat: Feast/IKV online store documentation

docs/how-to-guides/running-feast-in-production.md
Removed documentation of Redis connection string supporting default values when using environment variables as it isn't supported
Fixes #3669
=> fix: Default value is not set in Redis connection string using environment variable

sdk/python/feast/infra/offline_stores/snowflake_source.py
If I pass `schema="my_schema"` and `table="my_table"` when creating a `SnowflakeSource`, I would expect that `SnowflakeSource.get_table_query_string` outputs `'"my_schema"."my_table"'`. However, currently, `SnowflakeSource.get_table_query_string` outputs `"my_table"`.
This PR fixes that by extending the `get_table_query_string` method with an additional branch for when both `schema` and `table` are specified on the `SnowflakeSource` class.
https://github.com/feast-dev/feast/issues/4130
=> fix: Make sure schema is used when calling `get_table_query_string` method for Snowflake datasource

.github/workflows/master_only.yml
Fixes newly broken action in automation by updating back to correct checkout action version
=> fix: Change checkout action back to v3 from v5 which isn't released yet

.github/fork_workflows/fork_pr_integration_tests_aws.yml, .github/fork_workflows/fork_pr_integration_tests_gcp.yml, .github/fork_workflows/fork_pr_integration_tests_snowflake.yml, .github/workflows/build_wheels.yml, .github/workflows/java_master_only.yml, .github/workflows/java_pr.yml, .github/workflows/linter.yml, .github/workflows/master_only.yml, .github/workflows/nightly-ci.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/pr_local_integration_tests.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/unit_tests.yml
After recently fixing a typo issue, we noticed the checkout action is ready for a version bump, so applying across the board.
=> chore: Update checkout action from v3 to v4 in all workflows

.github/fork_workflows/fork_pr_integration_tests_aws.yml, .github/fork_workflows/fork_pr_integration_tests_gcp.yml, .github/fork_workflows/fork_pr_integration_tests_snowflake.yml, .github/workflows/build_wheels.yml, .github/workflows/nightly-ci.yml, .github/workflows/unit_tests.yml
macos runners are obviously slower than linux ones in the ci. We are using `macos-12` which is (3CPU/14RAM) while `linux-latest` is (4CPU/16RAM). This PR bumps macos runner version to 13, which should be a similar image with [4 cores](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
=> chore: Bump macOS runners to macos-13

docs/reference/online-stores/ikv.md
Minor changes to the documentation.
=> feat: Feast/IKV documenation language changes

examples/python-helm-demo/README.md, infra/charts/feast-feature-server/templates/service.yaml
Changes metadata.name in service.yaml template to use `"feast-feature-server.fullname"`, like the deployment template already does. This ensures the service name for each helm install will be unique to the namespace.
Of note, the service template in the [java helm chart](/feast-dev/feast/tree/master/infra/charts/feast/charts/feature-server) is already configured this way -
https://github.com/feast-dev/feast/blob/2b493e0457cea19a9b3faa163f099d6b32fde30d/infra/charts/feast/charts/feature-server/templates/service.yaml#L4
An example of the fix working -
```bash
$ helm install example1 infra/charts/feast-feature-server --set feature_store_yaml_base64=$(base64 feature_store.yaml)
NAME: example1
LAST DEPLOYED: Mon Apr 29 14:16:09 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: …
```
=> fix: Helm chart `feast-feature-server`, improve Service template name

.github/workflows/pr_integration_tests.yml
Even with recent workflow improvements, the recent change to increase scope of integration tests from only python v3.9 to v's 3.9-3.11 has caused us to begin hitting rate limiting errors with google cloud resources due to 3 simultaneous executions per action trigger. This PR reduces integration tests back to a single version scope using v3.11 so that actions won't require constant monitoring and re-triggers.
=> chore: Limit integration runs back to a single python version due to rate limiting errors

sdk/python/feast/feature_server.py
Feature server invokes `get_online_features` a little differently from sdk. It converts native python values to proto values with a simple proto `Parse` and as a result doesn't take into account the exact data types of the entities involved. This PR removes this preprocessing step from feature server, which now passes native python values to `get_online_features` that already has a logic in place to better handle type conversion.
Fixes #4110
=> fix: Pass native input values to `get_online_features` from feature server

docs/reference/online-stores/postgres.md, sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/contrib/postgres.py, sdk/python/feast/infra/online_stores/online_store.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/tests/foo_provider.py, sdk/python/tests/integration/online_store/test_universal_online.py
- Adds 3 other distance metrics configurable by the `get_online_documents` call based on [PGVector's documentation](https://github.com/pgvector/pgvector?tab=readme-ov-file#querying)
- Also updated docs to outlines more explicit steps on how to get started
=> feat: Enable other distance metrics for Vector DB and Update docs

.github/workflows/master_only.yml
Update bucket name due to global resource name collisions with old AWS acct. in order to fix master-only test runs failing as seen [here](https://github.com/feast-dev/feast/actions/runs/8989121663/job/24693009473#step:17:29).
=> fix: Update master-only benchmark bucket name due to credential update

protos/feast/core/DatastoreTable.proto, sdk/python/feast/infra/online_stores/datastore.py, sdk/python/tests/unit/diff/test_infra_diff.py
When introducing Firestore in Datastore mode in place of Datastore, Google added a possibility to create multiple databases other than (default) (in Datastore there was only one database called (default)). This PR adds 'database' argument to DatastoreOnlineStore. 
Fixes https://github.com/feast-dev/feast/issues/4113
=> feat: Adding DatastoreOnlineStore 'database' argument.

README.md, sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/online_store.py, sdk/python/feast/infra/online_stores/redis.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/feast/online_response.py, sdk/python/tests/foo_provider.py, sdk/python/tests/unit/infra/online_store/test_redis.py
=> feat: Adding get_online_features_async to feature store sdk

docs/project/development-guide.md
This shows users how to run tests locally with podman, instead of docker, on fedora and rhel machines.
The docs will point to https://github.com/feast-dev/feast/issues/4190 so we'll need someone to add the `keep-open` & 
`kind/process` labels to that issue. This is identical to https://github.com/feast-dev/feast/issues/2105, which is already similarly used.
=> docs: Add docs for using `podman` on RHEL or Fedora machines

sdk/python/feast/feature_server.py
Change fastapi's deprecated lifespan code to async context manager.
``` text 
[FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  @app.on_event("shutdown") …
```
=> refactor: Replace deprecated lifespan event

sdk/python/feast/infra/online_stores/contrib/ikv_online_store/ikv.py, setup.py
1) Updates ikvpy (client) version to resolve protobuf dependency conflicts
2) Invoking startup() methods as required
Ran full benchmark suite - feast apply, materialize, serve.
=> feat: Feast/IKV upgrade client version

sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/transformation/pandas_transformation.py, sdk/python/feast/transformation/python_transformation.py, sdk/python/feast/transformation/substrait_transformation.py, sdk/python/tests/unit/infra/test_inference_unit_tests.py, sdk/python/tests/unit/online_store/test_online_writes.py, sdk/python/tests/unit/test_on_demand_feature_view.py, sdk/python/tests/unit/test_on_demand_python_transformation.py
The SonarCloud (company which provides SonarCube) suggests several improvements about the code quality. 
Also, this PR is about to improve the code quality and the first step of improving running efficiency of "on-demand feature view" feature.
=> fix: Improve the code related to on-demand-featureview.

sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/feast/repo_operations.py, sdk/python/tests/foo_provider.py
During `feast apply` data source validation is invoked from `OfflineStore`'s `validate_data_source` method instead of `validate` method in `DataSource`. The default implementation of `validate_data_source` still calls `validate` on the data source to keep everything backwards-compatible.
Fixes #4186
=> feat: Move data source validation entrypoint to offline store

sdk/python/feast/infra/offline_stores/duckdb.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/ibis.py, sdk/python/pytest.ini, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/integration/materialization/contrib/spark/test_spark.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/registration/test_registry.py
- Adds tests and some missed functionality to access delta tables stored in s3 with duckdb offline store.
- Adds ability to export the output of duckdb retrieval job to s3.
=> feat: Add s3 remote storage export for duckdb

Makefile, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Temporarily skips failing `test_historical_features_main` test (had to change the name to correctly apply a pytest expression) for snowflake.
=> chore: Skip test_historical_features_main for Snowflake

sdk/python/feast/infra/materialization/snowflake_engine.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/online_stores/snowflake.py, sdk/python/feast/infra/registry/snowflake.py
Adding optional params `private_key` and `private_key_passphrase` to the Snowflake config classes so that they can be used in `feature_store.yaml` file directly.
Fixes https://github.com/feast-dev/feast/issues/4204
=> feat: Add optional private key params to Snowflake config

sdk/python/tests/integration/online_store/test_universal_online.py
Follow up on https://github.com/feast-dev/feast/pull/4172 After checking integration tests, I understand this one is relevant to the async method. Let me know if you understand more integration tests are needed.
=> fix: Integration tests for async sdk method

sdk/python/feast/infra/online_stores/contrib/ikv_online_store/ikv.py
Some date-time inputs had decoding errors while running benchmark (<1%)
make format-python && make lint-python
=> feat: Feast/IKV datetime edgecase errors

sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/materialization/contrib/spark/test_spark.py, sdk/python/tests/integration/materialization/test_snowflake.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/integration/registration/test_universal_cli.py, sdk/python/tests/integration/registration/test_universal_types.py, sdk/python/tests/unit/infra/offline_stores/test_offline_store.py, sdk/python/tests/utils/e2e_test_validation.py
This PR refactors bunch of code around environment setup for integration tests. 
- Decouples `IntegrationTestRepoConfig` and `Environment` classes from one another. (Need to investigate if we can get rid of one of them entirely)
- Introduces a new `setup` method in `DataSourceCreator` that takes registry config as an input. This is necessary for remote DataSourceCreator as server-side feature store and client-side need to use the same registry in tests.
=> chore: Refactor test environment setup

infra/feast-operator/README.md
Fixes the operator readme docs.
Fixes an issue when operator docs are followed on a linux machine. This change improves cross-platform documentation.
=> docs: Operator readme fix

infra/scripts/release/bump_file_versions.py
This is changing the validation to ignore patch version changes. So the CI should trigger correctly for increments from `0.37.1` -> `0.38.0`.
```bash
python infra/scripts/release/bump_file_versions.py 0.37.0 0.38.0
Updated 16 files with new version 0.38.0
```
Previously this failed as `0.37.1` wasn't recognized as a tag.
=> chore: Adjusting the file version validation for minor releases

java/serving-client/src/main/java/dev/feast/FeastClient.java, java/serving-client/src/test/java/dev/feast/FeastClientTest.java
Added configurable deadlines for the Feast Java gRPC client. We need it because clients could otherwise [get stuck forever](https://grpc.io/docs/guides/deadlines/) waiting for the feature server to respond, and we should make it simpler for users of this library to implement retries and timeouts; especially when it's already supported in gRPC by default.
N/A
N/A
=> feat: Added deadline to gRPC Java client

sdk/python/feast/infra/online_stores/redis.py
In this link (https://github.com/feast-dev/feast/pull/3857), I added function to perform a full-scan and delete data to save Redis memory. However, full-scan in Redis does not work beautifully, takes too long at production scale, and often fails in CI that performs feast-apply. So, I think it would be a good idea to add the 'full_scan_for_deletion' option in redis so that the user can select and delete it.
=> feat: Set optional full-scan for deletion

protos/feast/core/Transformation.proto, protos/feast/registry/RegistryServer.proto, sdk/python/feast/infra/registry/base_registry.py, sdk/python/feast/infra/registry/remote.py, sdk/python/feast/registry_server.py, sdk/python/tests/integration/registration/test_universal_registry.py, sdk/python/tests/unit/infra/registry/test_remote.py, sdk/python/tests/unit/test_registry_server.py
- This PR adds apply/delete endpoints to the grpc registry server, also makes necessary changes in `remote` registry that call those endpoints.
Fixes #4216
=> feat: Make RegistryServer writable

java/serving-client/src/main/java/dev/feast/FeastClient.java, java/serving-client/src/test/java/dev/feast/FeastClientTest.java
In my previous [PR](https://github.com/feast-dev/feast/pull/4217) I added deadlines to the gRPC stub used in Java `FeastClient`, however deadlines in gRPC don't behave like timeouts and in that PR are only set once when the client is constructed, causing requests after construction to fail with deadline exceeded even though the time they took was was within the deadline the used thought they had set up; here's an example of the issue:
```java
// Create the client, deadline starts counting from the moment client is instantiated
FeastClient client = new FeastClient(channel, Optional.empty(), Optional.of(Deadline.after(200, TimeUnit.MILLISECONDS)));
Thread.sleep(200);
client.getOnlineFeatures(...); // throws a StatusRuntimeException: DEADLINE_EXCEEDED
```
The `getOnlineFeatures(...)` call …
=> fix: Make Java gRPC client use timeouts as expected

sdk/python/feast/ui_server.py
Starting the UI fails when using the builtin `importlib.resources.files` function; it works with the one from the library `importlib-resources`. 
> TypeError: 'feast.ui_server' is not a package
Using the reference to the module's parent (its package) through __spec__ ([docs](https://docs.python.org/3/library/importlib.html#importlib.machinery.ModuleSpec.parent)). We're using `__spec__.parent` as opposed to `__package__` because `__package__` does not seem to be the way according [to this](https://docs.python.org/3/reference/import.html#package__).
According to the python-docs, the function should work with both modules and packages, but that does not seem to be the case ([link to docs](https://docs.python.org/3.11/library/importlib.resources.html#importlib.resources.files)).
Fixes …
=> fix: Feast UI importlib change

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
The python Feature UI Server image should run in an OpenShift cluster without issue.
This change allows the following code to function in a "random uid" container -
https://github.com/feast-dev/feast/blob/0b81ba00c48ab2163f91bb8a348dfb3b784ceb5f/sdk/python/feast/ui_server.py#L54-L57
Fixes #4247
=> fix: Feature UI Server image won't start in an OpenShift cluster

go/types/typeconversion.go, go/types/typeconversion_test.go, sdk/python/feast/type_map.py, sdk/python/tests/unit/test_type_map.py
Null values are materialized to online store as &types.Value{} instead of nil. Fixing the issue in Go Feature Server code to handle NULL values during retrieval. Without this fix, Go Feature server retrieval fails. 
- Go Feature server retrieval for NULL values in online store.
- Formatting in type_map.py and Log error when NULL values in INT are upcasted to FLOAT64. Logging helps to easily find the issue otherwise it's hard to debug the issue. Dataset has INT values when the TypeError is raised all the values are logged as FLOAT64 in _type_err() function. 
We need to fix NULL values in the array during the retrieval process. Below are my observations:
Null values inside arrays are not supported by either Materialization or Feature Retrieval in GO
- INT32, INT64 columns are upcasted to …
=> fix: Handles null values in data during GO Feature retrieval

docs/SUMMARY.md, docs/reference/online-stores/README.md, docs/reference/online-stores/remote.md, sdk/python/feast/infra/online_stores/remote.py, sdk/python/feast/repo_config.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/online_store/test_remote_online_store.py
Adds the new online store of type "remote" which will interact with remote feature server. Able to read and write the features only at the moment. 
https://github.com/feast-dev/feast/issues/4121
=> feat: Feature/adding remote online store

sdk/python/feast/feature_server.py
Remove deprecation from write.
The endpoints should behave as follows:
- push: async write
- write: sync write
- materialize: async batch write
This is the architecture I recommend:
=> chore: Removing warning from feature server

sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/contrib/grpc_server.py, sdk/python/feast/utils.py, sdk/python/tests/unit/test_feature_validation.py, sdk/python/tests/unit/test_unit_feature_store.py
- Changes `get_online_features` signature to also accept entity_rows in columnar format. This allows `get_online_features` to be used from python feature server (previously it was calling `_get_online_features`).
- Refactors most of online retrieval functions from `feature_store.py` to `utils.py`. This is a first step for #4270, functions in utils no longer depend on `FeatureStore` object state.
=> feat: Change get_online_features signature, move online retrieval functions to utils

docs/reference/feast-cli-commands.md, protos/feast/registry/RegistryServer.proto, sdk/python/feast/cli.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/registry/base_registry.py, sdk/python/feast/infra/registry/caching_registry.py, sdk/python/feast/infra/registry/proto_registry_utils.py, sdk/python/feast/infra/registry/registry.py, sdk/python/feast/infra/registry/remote.py, sdk/python/feast/infra/registry/snowflake.py, sdk/python/feast/infra/registry/sql.py, sdk/python/feast/registry_server.py, sdk/python/feast/utils.py, sdk/python/tests/example_repos/example_feature_repo_1.py, sdk/python/tests/example_repos/example_feature_repo_with_feature_service_2.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/online_store/test_universal_online.py, sdk/python/tests/integration/registration/test_universal_registry.py, sdk/python/tests/unit/local_feast_tests/test_feature_service.py, sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py, sdk/python/tests/unit/online_store/test_online_retrieval.py
In the feast registry & cli, add the ability to list objects by `tags`... same as the UI already supports.
Here are the object types with this new `--tags` capability -
- data-sources (`DataSource`)
- entities (`Entity`)
- feature-services (`FeatureService`)
- feature-views (`FeatureView`)
- on-demand-feature-views (`OnDemandFeatureView`)
- `StreamFeatureView`
Fixes: https://github.com/feast-dev/feast/issues/4245
e.g. 
```bash
$ feast feature-views list --help
Usage: feast feature-views list [OPTIONS]
List all feature views
Options:
--tags TEXT  Filter by tags (e.g. --tags 'key:value' --tags 'key:value,
key:value, ...'). Items return when ALL tags match.
--help       Show this message and exit.
```
```bash
$ feast feature-views list --tags team:driver_performance              
NAME …
```
=> feat: Add the ability to list objects by `tags`

sdk/python/feast/infra/key_encoding_utils.py, sdk/python/feast/infra/online_stores/contrib/postgres.py, sdk/python/feast/repo_config.py, sdk/python/tests/unit/infra/test_key_encoding_utils.py
* Create new version 3 of entity key serialization
* Create entity key deserialization
To avoid breaking changes the default version of serialization is still set to `2`.
Deserialization function is supported by adding the entity key length in the serialization output:
```
for k in sorted_keys:
output.append(struct.pack("<I", ValueType.STRING))
if entity_key_serialization_version > 2:
output.append(struct.pack("<I", len(k)))
```
https://github.com/feast-dev/feast/issues/4283
=> feat: Entity key deserialization

sdk/python/feast/infra/registry/snowflake.py, sdk/python/feast/infra/registry/sql.py
Change from
```
>>> dt_now = datetime.utcnow()
>>> dt_ts = datetime.utcfromtimestamp(1571595618.0)
```
to
```
>>> from datetime import timezone
>>> dt_now = datetime.now(tz=timezone.utc)
>>> dt_ts = datetime.fromtimestamp(1571595618.0, tz=timezone.utc)
```
Reference: https://blog.ganssle.io/articles/2019/11/utcnow.html
=> fix: Deprecated the datetime.utcfromtimestamp().

Makefile, docs/SUMMARY.md, docs/reference/online-stores/README.md, docs/reference/online-stores/singlestore.md, sdk/python/docs/source/feast.infra.online_stores.contrib.rst, sdk/python/docs/source/feast.infra.registry.contrib.postgres.rst, sdk/python/docs/source/feast.infra.registry.contrib.rst, sdk/python/feast/infra/online_stores/contrib/singlestore_online_store/singlestore.py, sdk/python/feast/infra/online_stores/contrib/singlestore_repo_configuration.py, sdk/python/feast/repo_config.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.11-ci-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/tests/integration/feature_repos/universal/online_store/singlestore.py, setup.py
This commit adds SingleStore as a contributed online store. It contains all the changes needed (as described in https://docs.feast.dev/how-to-guides/customizing-feast/adding-support-for-a-new-online-store)
Signed-off-by: Olha Kramarenko <okramarenko-ua@singlestore.com>
=> feat: Add SingleStore as an OnlineStore

go/internal/feast/server/http_server.go, go/internal/feast/transformation/transformation.go
Releases the memory used by [CGOArrowAllocator](https://github.com/apache/arrow/blob/go/v8.0.0/go/arrow/memory/cgo_allocator.go). Not releasing the memory causing the memory leaks. Pods restart after all the memory allocated by container is filled up.
NA
- Memory leak in GO feature server which is causing the pod restarts after allocated memory filled up
- Sets the response content type to application/json (Before its application/text type)
- Added health check endpoint for GO HTTP feature server
=> fix: CGO Memory leak issue in GO Feature server

sdk/python/feast/infra/online_stores/sqlite.py
Adds try/except block to importing `sqlite_vec`
https://github.com/feast-dev/feast/issues/4293
https://github.com/feast-dev/feast/issues/4293
=> fix: Fix SQLite import issue

sdk/python/feast/infra/online_stores/contrib/postgres.py
Since the materialization engine already batches the data and calls the `online_write_batch` method of the online store for each batch, we can get rid of the additional batching in the `PostgreSQLOnlineStore.online_write_batch` method, which will speed up materialization logic for Postgres. 
While there, fix the progress bar by updating it with the number of entities in the batch, instead of the number of entity * feature pairs.
https://github.com/feast-dev/feast/issues/4309
=> fix: Remove redundant batching in PostgreSQLOnlineStore.online_write_batch and fix progress bar

sdk/python/feast/transformation/pandas_transformation.py, sdk/python/feast/transformation/python_transformation.py, sdk/python/feast/transformation/substrait_transformation.py, sdk/python/feast/type_map.py, sdk/python/tests/unit/test_on_demand_pandas_transformation.py, sdk/python/tests/unit/test_on_demand_python_transformation.py
`OnDemandFeatureView.feature_transformation.infer_features` should be able to infer features from python types for all supported feast data types, for all transformation backends. This PR passes values to `python_type_to_feast_value_type` so that list types can be inferred correctly.
- Unit tests passing in CI for all Python versions on my fork.
- Tested against a local project by patching `PandasTransformation.infer_features`, _e.g._
```Python
from feast.transformation.pandas_transformation import PandasTransformation
def __patched_infer_features(
self, random_input: dict[str, list[Any]]
) -> list[Field]:
df = pd.DataFrame.from_dict(random_input)
output_df: pd.DataFrame = self.transform(df)
return [
Field(
name=f,
dtype=from_value_type(
python_type_to_feast_value_type(
f, …
```
=> fix: OnDemandFeatureView type inference for array types

sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/offline_utils.py
=> fix: Avoid XSS attack from Jinjin2's Environment().

sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/offline_utils.py
=> revert: Revert "fix: Avoid XSS attack from Jinjin2's Environment()."

infra/feast-operator/Makefile, infra/feast-operator/config/manager/kustomization.yaml
the feast-operator version fell behind, likely because it merged after the `0.37.1` release. because of this, 
matches operator version with the other files in `infra/scripts/release/files_to_bump.txt`. allows future scripted version increments to complete successfully, e.g. 
```shell
python ./infra/scripts/release/bump_file_versions.py 0.39.1 0.39.2
```
=> fix: Increment operator to v0.39.1

infra/feast-operator/Makefile, infra/feast-operator/config/manager/kustomization.yaml
the feast-operator version fell behind, likely because it merged after the `0.37.1` release. because of this, 
matches operator version with the other files in `infra/scripts/release/files_to_bump.txt`. allows future scripted version increments to complete successfully, e.g. 
```shell
python ./infra/scripts/release/bump_file_versions.py 0.39.0 0.39.1
```
=> fix: Increment operator to v0.39.0

.releaserc.js, infra/feast-operator/Makefile, infra/feast-operator/config/manager/kustomization.yaml
This fixes the issue where past releases are not properly versioning the feast-operator.
=> fix: Add feast-operator files to semantic-release script (v0.40-branch)

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, java/serving/pom.xml, java/serving/src/test/java/feast/serving/it/ServingEnvironment.java
`ubuntu-latest` runner image updated docker compose plugin to v2 which broke java integration tests that rely on `docker-compose` being in PATH instead of `docker compose`. This PR temporarily updates java testcontainers to use Compose V2.
=> fix: Update java testcontainers to use Compose V2

.releaserc.js, infra/feast-operator/Makefile, infra/feast-operator/config/manager/kustomization.yaml
This fixes the issue where past releases are not properly versioning the feast-operator.
=> fix: Add feast-operator files to semantic-release script

docs/README.md, docs/SUMMARY.md, docs/getting-started/architecture-and-components/README.md, docs/getting-started/architecture-and-components/push-vs-pull-model.md
This PR adds documentation about why Feast uses a Push Model.
In another PR, I'll outline different write patterns when pushing / writing features to Feast.
=> docs: Adding some content about the push vs pull model

sdk/python/feast/on_demand_feature_view.py, sdk/python/tests/unit/infra/scaffolding/test_repo_operations.py
signature function to get the return annotation, can sometimes return it as a string if the annotation itself was defined using forward references. We imported `from __future__ import annotations` in our definitions file. That will return OnDemandFeatureView UDF return type as **'pd.DataFrame'** instead of **pd.DataFrame**. 
Added test cases to prove that.  
get_type_hints will resolve the forward references by giving you the actual type objects instead of strings.
=> fix: Using get_type_hints instead of inspect signature for udf return annotation 

sdk/python/feast/infra/utils/postgres/connection_utils.py, sdk/python/tests/integration/feature_repos/universal/online_store/postgres.py
Update the helper function that creates the connection string to use key-value pairs. This makes sure that the special characters in the password are escaped.
Fixes #4393
I updated the setup for the postgres online store to use a password with special characters to verify this keeps working in the future.
=> fix: Escape special characters in the Postgres password

sdk/python/feast/infra/utils/postgres/connection_utils.py, sdk/python/tests/integration/feature_repos/universal/online_store/postgres.py
This PR cherry-picks a fix commit to properly parse special characters in Postgres passwords.
More information can be found in the [original PR](https://github.com/feast-dev/feast/pull/4394).
=> fix: Escape special characters in the Postgres password (#4394)

sdk/python/feast/infra/materialization/snowflake_engine.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/online_stores/snowflake.py, sdk/python/feast/infra/registry/snowflake.py, sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
Allows the user to pass private_key as a byte string for Snowflake key-pair authentication rather than only limiting the ability to refer to the file path where the private key is stored. 
Gives the ability to pass in `private_key` from a Secret Manager service (i.e: Google Cloud Secret Manager)
=> feat: Allow feast snowflake to read in byte string for private-key authentication

sdk/python/feast/repo_operations.py, sdk/python/feast/transformation/pandas_transformation.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
* Allows the use of `--feature-store-yaml` when running `teardown` (`feast --feature-store-yaml <some-other-file> teardown`) as this currently does not work as the `.yaml` file is resolved differently to `plan` and `apply`.
* Fixes some issues with linting and formatting that prevent committing & pushing.
tbd
=> fix: Using repo_config parameter in teardown to allow for feature-store-yaml overrides

sdk/python/feast/driver_test_data.py, sdk/python/feast/embedded_go/type_map.py, sdk/python/feast/feature_logging.py, sdk/python/feast/infra/materialization/snowflake_engine.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/connectors/upload.py, sdk/python/feast/infra/offline_stores/dask.py, sdk/python/feast/infra/offline_stores/ibis.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/infra/online_stores/contrib/elasticsearch.py, sdk/python/feast/infra/online_stores/contrib/hazelcast_online_store/hazelcast_online_store.py, sdk/python/feast/infra/online_stores/contrib/ikv_online_store/ikv.py, sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py, sdk/python/feast/infra/online_stores/contrib/postgres.py, sdk/python/feast/infra/online_stores/contrib/singlestore_online_store/singlestore.py, sdk/python/feast/infra/online_stores/redis.py, sdk/python/feast/registry_server.py, sdk/python/feast/templates/aws/feature_repo/test_workflow.py, sdk/python/feast/templates/snowflake/test_workflow.py, sdk/python/feast/utils.py, sdk/python/tests/data/data_creator.py, sdk/python/tests/integration/materialization/test_snowflake.py, sdk/python/tests/integration/registration/test_universal_registry.py, sdk/python/tests/utils/e2e_test_validation.py, sdk/python/tests/utils/feature_records.py, sdk/python/tests/utils/test_log_creator.py
The Python library `pytz` is not recommended after Python3.9. 
This PR updated most code with "timezone.utc" instead of the **dask.py** file. 
It seems for Pandas's dataframe (after call the Dask.Dateframe.compute()) still have timezone info equals to pytz.UTC. 
It requires further work to investigation and retire the pytz in **dask.py**
Fix: #4239
=> fix: Retire pytz library

sdk/python/feast/on_demand_feature_view.py
Used pandas mode as default for the ODFV objects that are already present in database. Without this it complaints that mode is missing to convert from Proto to ODFV.
=> fix: Default to pandas mode if not specified in ODFV proto in database

.github/pull_request_template.md, docs/project/development-guide.md, infra/templates/README.md.jinja2
The table of contents in the [Developer Guide](https://docs.feast.dev/project/development-guide#development-guide-main-feast-repository) had two links that became broken when viewed in HTML (when viewed on the webpage). When viewed in markdown, the links worked fine. 
This PR makes them consistent, which makes it so the links work on the webpage. 
To verify the issue, go to https://docs.feast.dev/project/development-guide#development-guide-main-feast-repository and click on the link [Feast Python SDK / CLI](https://docs.feast.dev/project/development-guide#feast-python-sdk--cli) in the table of contents. Nothing happens! However it should take you to the indicated section. This is also the case with the link [Code Style & Linting](https://docs.feast.dev/project/development-guide#code-style- …
=> docs: Updated README template and fixed links to be consistent for HTML

.releaserc.js
This fixes the issue where past releases are not properly versioning the feast-operator.
=> fix: Add feast-operator Makefile to semantic-release script

pyproject.toml
This PR enforces the protobuf version in the build system so that it is compatible with the runtime dependency
Fixes #4437
The runtime version of protobuf is determined at:
https://github.com/feast-dev/feast/blob/0a48f7bb436febb0171c78a559a577eedeff421f/setup.py#L46
I have manually tested this PR with the following command
```
pip install git+https://github.com/Atry/feast.git@build-system-protobuf-version && python -m feast.protos.feast.types.Value_pb2
```
=> build: Set a proper build-system protobuf version

README.md, docs/getting-started/components/authz_manager.md, sdk/python/feast/permissions/auth/oidc_token_parser.py, sdk/python/feast/permissions/auth_model.py, sdk/python/feast/permissions/client/oidc_authentication_client_manager.py, sdk/python/feast/permissions/oidc_service.py, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/unit/infra/scaffolding/test_repo_config.py, sdk/python/tests/unit/permissions/auth/conftest.py, sdk/python/tests/unit/permissions/auth/server/mock_utils.py, sdk/python/tests/unit/permissions/auth/test_token_parser.py
refactoring the permissions side server side code to get the OIDC end points from the discovery URL. Also removing the auth_server_url config from OIDC auth config.
(https://github.com/feast-dev/feast/issues/4428)
=> feat: Refactoring code to get oidc end points from discovery URL.

Makefile, sdk/python/tests/conftest.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
- Adds a workaround to mark tests with xdist markers using new static method on `DataSourceCreator`
- Increases the number of workers for integration tests back to 8
=> chore: Mark tests using keycloak with xdist_group

sdk/python/feast/permissions/enforcer.py, sdk/python/feast/permissions/security_manager.py, sdk/python/feast/registry_server.py, sdk/python/tests/unit/permissions/conftest.py, sdk/python/tests/unit/permissions/test_security_manager.py
Fixes #4444 
Will update the code using the new `get_any_feature_view` method once #4435 is merged
=> fix: Validating permission to update an existing request on both the new and the old instance

sdk/python/feast/infra/materialization/snowflake_engine.py
When running `feast apply` using the snowflake materialization engine, feast only checks if the stage in snowflake exists and assumes the functions have been created.  This allows a case where if anything goes wrong during function creation, such as permission issues, a stage can be created while the functions are not. Following attempts to `feast apply` see the created stage and tell the user that the functions exist without creating them. This leads to materialization on snowflake to fail down the line due to missing functions.
This PR aims to change the apply logic to instead check for snowflake functions before deciding if action is required.
A current workaround for this is to delete the stage in Snowflake before running the next `feast apply`.
=> fix: Check for snowflake functions when setting up materialization engine

.github/workflows/build_wheels.yml, Makefile, environment-setup.md, pyproject.toml, setup.py
Right now if one downloads `feast-0.40.1-py2.py3-none-any.whl` from PyPi it contains:
```
$ grep 'Protobuf Python Version' feast/protos/feast/registry/RegistryServer_pb2.py
```
Which is outside
```
$ grep 'protobuf<' feast-0.40.1.dist-info/METADATA
Requires-Dist: protobuf<5.0.0,>=4.24.0
```
Leading to runtime errors (#4437).  This was mitigated by #4438.  This change tightens this up further by:
* Deleting the Makefile command that was trying to do this unsuccessfully.
* Aligns the setup/build requirements
* Sets the version of protobuf to match the *minimum* of the range. There is no guarantee that protos generated by `4.X` will work with `4.(X-1)`.
=> build: Explicit protobuf build version; consistent build/setup deps

sdk/python/feast/errors.py, sdk/python/feast/feature_server.py, sdk/python/feast/infra/online_stores/remote.py, sdk/python/feast/rest_error_handler.py, sdk/python/tests/integration/online_store/test_python_feature_server.py, sdk/python/tests/unit/test_rest_error_decorator.py
Added a decorator for rest calls to remote online server failures and adds an additional message to the response with the failure status and details.
The proxy client then rebuilds the original error from the status data.
Fixes https://github.com/feast-dev/feast/issues/4481
=> fix: Added Online Store REST client errors handler

README.md, sdk/python/feast/data_source.py
https://github.com/feast-dev/feast/issues/4493
=> fix: Hao xu request source timestamp_field

sdk/python/tests/integration/conftest.py, sdk/python/tests/integration/registration/test_universal_registry.py
- Splits up registry fixtures in `test_universal_registry` into session-scoped container fixtures and function-scoped registry fixtures that depend on container fixtures. This way container startup times are avoided per function.
- Each test function is now run in a separate database (mysql, postgres) or bucket (minio). Tests can no longer spill side-effects to one another even when session-scoped.
=> chore: Scope fixtures to session in test_universal_registry

sdk/python/feast/feature_server.py
- When using the serve command in cli,
--registry_ttl_sec is defined not to update the registry if it is 0.
However, the active_timer actually runs and updates the registry regardless of the value of registry_ttl_sec.
This PR fixes the above issue and does not run the timer thread if registry_ttl_sec is 0.
=> fix: Disable active_timer When registry_ttl_sec is 0

sdk/python/feast/ui_server.py
Fix #4462 
If "mypy>=1.11", it will show the following error:
`feast/ui_server.py:54: error: Argument 1 to "files" has incompatible type "str | None"; expected "str | Module"  [arg-type]`
=> fix: Ignore the type check as both functions calls are not belonging to Feast code.

docs/getting-started/components/authz_manager.md, docs/reference/feast-cli-commands.md
Adding the missed documentation for - 
* OIDC Token requirement or assumptions
* Added `feast permissions check` cli command documentation.
=> docs: Adding the missed documentation for the RBAC

sdk/python/feast/arrow_error_handler.py, sdk/python/feast/infra/offline_stores/remote.py, sdk/python/feast/offline_server.py, sdk/python/feast/permissions/client/arrow_flight_auth_interceptor.py, sdk/python/feast/permissions/server/arrow.py, sdk/python/tests/unit/test_arrow_error_decorator.py, sdk/python/tests/unit/test_offline_server.py
Added a decorator for arrow calls to remote offline server failures and adds an additional message to the response with the failure status and details.
The proxy client then rebuilds the original error from the status data.
Fixes https://github.com/feast-dev/feast/issues/4523
=> fix: Added Offline Store Arrow client errors handler

Makefile, pyproject.toml, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.11-ci-requirements.txt, sdk/python/requirements/py3.11-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
1. Resolves the error when generating sdist. Current error is `pkg_resources.ContextualVersionConflict: (protobuf 4.24.0 (/feast/.eggs/protobuf-4.24.0-py3.8-macosx-14.4-arm64.egg), Requirement.parse('protobuf<6.0dev,>=5.26.1'), {'grpcio-tools'})`
2. Moved grpcio-tools as DEV dependency
=> fix: Removed protobuf as a required dependency

sdk/python/feast/infra/registry/sql.py
1. Indexes help to optimize the query execution when the tables are growing. Based my local test, I see an improvement of 40-60% in query execution time.
=> perf: Added indexes to sql tables to optimize query execution

docs/getting-started/concepts/README.md, docs/getting-started/concepts/tags.md
Added documentation with examples of how to use the tags in the cli, in the definition file and in the code with feature views.
Fixes https://github.com/feast-dev/feast/issues/4534
=> docs: Add docs example of how to use tags with feature views

pyproject.toml, sdk/python/feast/infra/registry/caching_registry.py, sdk/python/feast/infra/registry/sql.py, sdk/python/tests/integration/registration/test_universal_registry.py
Fixes issues with SQL Registry Initialization
Fixes #4543
=> fix: Fix for SQL registry initialization fails #4543

sdk/python/feast/utils.py
Currently during `get_online_features` call, feast lists all feature views in the registry, stores them in a dict and then does lookups. This PR changes the flow to directly retrieving only the required feature views.
=> refactor: Use get_any_feature_view in online flow instead of listing them

sdk/python/feast/infra/offline_stores/bigquery.py
Fixes a regression in BigQuery offline store due to newer pydantic version
Fixes https://github.com/feast-dev/feast/issues/4280
=> fix: Fixes validator field access for 'project_id' in BigQuery offline Store

sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
- Adding unit test to test feature view dummy entity serialization after apply()
- Discovered that this was untested in an integration test and it should be surfaced earlier (https://github.com/feast-dev/feast/pull/4530)
https://github.com/feast-dev/feast/issues/4552
@tokoko
=> chore: Adding unit test to test feature view dummy entity serialization after apply()

ui/package.json, ui/tsconfig.build-lib.json
Makes Feast UI TypeScript declarations available in TypeScript projects that use Feast UI as a module.
Fixes #4539.
I tested this by running `yarn build:lib-dev` in this repository (after installing [`yalc`](https://www.npmjs.com/package/yalc)), then linking it in my test app with `yalc add @feast-dev/feast-ui`.
No type declarations available:
Only "import FeastUI" shown on hover:
Type declarations available and shown on hover:
You can also easily navigate to the type declaration file:
=> feat: Publish TypeScript types in Feast UI package

ui/package.json, ui/yarn.lock
As noted in #3794, Feast UI is not compatible with the latest react-router-dom versions, more precisely [from 6.4.0 onwards](https://stackoverflow.com/a/74252839/305436). Limit react-router-dom version to a compatible range to avoid the runtime errors mentioned in the issue when installing app dependencies without specifying exact versions.
After setting the restricted versions in `package.json`, running `yarn install` updated `react-router-dom` to the latest compatible version 6.3.0. It should be a minor upgrade (https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v630), and I didn't notice anything not working in the UI after it.
#3794 has already been closed since there was another way to resolve it, but otherwise this should have fixed it too.
I've noticed that regardless …
=> fix: Update react-router-dom to 6.3.0 and restrict its version in Feast UI

docs/reference/alpha-web-ui.md, ui/README.md
I initially created a `project-list.json` file following the web site docs, then found out it should be `projects-list.json`. Then spotted another tiny typo, so fixed it too.
=> docs: Fix small typos in Feast UI projects list documentation

sdk/python/feast/protos/feast/core/FeatureViewProjection_pb2.py, sdk/python/feast/protos/feast/core/FeatureViewProjection_pb2.pyi, sdk/python/feast/protos/feast/core/OnDemandFeatureView_pb2.py, sdk/python/feast/protos/feast/core/OnDemandFeatureView_pb2.pyi
Fixing the master branch build failure.
You can see the below PR is failing without any code changes on the master branch after rebase.
https://github.com/feast-dev/feast/actions/runs/11006822654/job/30561720252?pr=4562
=> fix: Fixing the master branch build failure.

sdk/python/feast/feature_store.py
feat: Adding registry cache support for get_on_demand_feature_view
N/A
This should have already been there and I saw it along the way.
=> feat: Adding registry cache support for get_on_demand_feature_view

docs/reference/alpha-web-ui.md, ui/README.md, ui/package.json
npm [peer dependencies](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependencies) in a consumed package are used for dependencies that should be installed by the consuming package/app and usually shared between the two. Most of Feast UI's current peer dependencies can be removed because installing them is not necessarily required in the consuming app when `@feast-dev/feast-ui` is used as a module.  The less we have peer dependencies, the easier it is to take Feast UI into use as a module.
Fixes #3785.
Rationale for the new set of peer dependencies is given in https://github.com/feast-dev/feast/issues/3785#issuecomment-2373098965 and in the commit message)
=> fix: Remove unnecessary peer dependencies from Feast UI

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
the previous base image (Python:3.11) for feature-server has vulnerabilities issue. 
It is changed to Debian:11-slim and manually install python, python-pip that have default python version 3.9.
Fix #4506
=> fix: Update the base image for feature-server.

sdk/python/tests/unit/online_store/test_online_retrieval.py
Remove sqlite Vec version assertion
=> chore: Remove sqlite_vec assertion in test_online_retrieval.py

sdk/python/feast/infra/online_stores/contrib/postgres.py, sdk/python/feast/infra/online_stores/contrib/singlestore_online_store/singlestore.py, sdk/python/feast/infra/online_stores/helpers.py
=> fix: Fix online pg import

sdk/python/feast/infra/materialization/kubernetes/Dockerfile
the current base image (python:3.11-slim-bullseye) in sdk/python/feast/infra/materialization/kubernetes/Dockerfile  has vulnerabilities.
Update it to 'debian:11-slim"
Fix #4506
=> fix: Update the base image of materilization engine.

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
When using `SparkOfflineStore` without S3, the following error is raised:
```shell
❯ python -c "from feast.infra.offline_stores.contrib.spark_offline_store.spark import SparkOfflineStore"
Traceback (most recent call last):
File "[REDACTED]/python3.10/site-packages/feast/infra/utils/aws_utils.py", line 28, in <module>
import boto3
ModuleNotFoundError: No module named 'boto3'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "[REDACTED]/python3.10/site-packages/feast/infra/offline_stores/contrib/spark_offline_store/spark.py", line 34, in <module>
from feast.infra.utils import aws_utils
File "[REDACTED]/python3.10/site-packages/feast/infra/utils/aws_utils.py", line 34, in <module>
raise …
```
=> fix: FeastExtrasDependencyImportError when using SparkOfflineStore without S3

sdk/python/tests/integration/materialization/test_snowflake.py
Updated snowflake test to be more explicit about post apply entity_columns return value
N/A
=> chore: Updated snowflake test to be more explicit about post apply entity_columns return value

ui/.eslintignore
We see lots of ESLint warnings from the generated protos.js file when running `yarn start` in the `ui` directory. No need to lint generated files, so add that file to ESLint's ignore list.
At the end of `yarn start` output, you currently see these warnings:
```sh
WARNING in src/protos.js
Line 2:1:        'use strict' is unnecessary inside of modules                                                 strict
Line 779:44:     Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations  no-mixed-operators
Line 779:91:     Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations  no-mixed-operators
Line 835:21:     Nested block is redundant                                                                     no-lone-blocks
Line …
```
=> chore: Ignore generated protos.js file in ESLint (Feast UI)

sdk/python/feast/infra/online_stores/dynamodb.py
Hi Team,
This PR enables feast to create aws client from either current session or using default boto3.client. This will enable feast to use dynamodb in a cross account setup i.e if feast is running in account A and want to use dynamodb in account B, right now it dosen't offers that and creates a default client which is limits the usage of feast.
https://github.com/feast-dev/feast/issues/4605
=> feat: Add boto3 session based auth for dynamodb online store for cross account access

ui/src/pages/saved-data-sets/DatasetExpectationsTab.tsx
Gets rid of this when running `yarn start`:
```sh
WARNING in src/pages/saved-data-sets/DatasetExpectationsTab.tsx
Line 22:7:  'expectationsData' is defined but never used  @typescript-eslint/no-unused-vars
webpack 5.94.0 compiled with 1 warning in 20434 ms
```
I don't know how this has now come up, I saw no linter warnings in #4599 after my changes. 🤷 In any case, it's a clear case.
=> chore: Remove unused `expectationsData` in Feast UI

sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/feast/infra/online_stores/online_store.py
Improve the use of async batch calls to dynamo db for `get_online_features_async`
* tested on a feature service w 3 feature views and 11 features
* compared to the sync method, the async method was
* 50% faster w 5 entities retrieved
* 75% faster w 80 entities retrieved
=> perf: Parallelize read calls by table and batch

sdk/python/feast/repo_config.py, sdk/python/tests/unit/sdk/python/feast/test_repo_operations_validate_feast_project_name.py
Addressing the issue - https://github.com/feast-dev/feast/issues/4626
=> fix: Updating the documentation and adding tests for project length

sdk/python/feast/feature_store.py, sdk/python/feast/inference.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/remote.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/feast/infra/registry/remote.py, sdk/python/feast/offline_server.py, sdk/python/feast/permissions/client/grpc_client_auth_interceptor.py, sdk/python/tests/foo_provider.py, sdk/python/tests/unit/infra/test_inference_unit_tests.py
Moves methods used to run `feast apply` in the Offline Server.
E.g. `DataSource.get_column_names_and_types`
Fixes https://github.com/feast-dev/feast/issues/4529 and https://github.com/feast-dev/feast/issues/4542
=> fix: Remote apply using offline store

sdk/python/feast/type_map.py
Currently, `_python_value_to_proto_value` does not properly handle lists. It will always return a list of values of length one, regardless of the number of input values.
This PR aims to fix this bug, and also adds a check to ensure that the number of returned proto values is the same as the inputted values.
=> fix: Correctly handle list values in _python_value_to_proto_value

docs/getting-started/components/authz_manager.md, examples/rbac-remote/server/k8s/server_resources.yaml, sdk/python/feast/permissions/auth/kubernetes_token_parser.py, sdk/python/tests/unit/permissions/auth/conftest.py, sdk/python/tests/unit/permissions/auth/server/mock_utils.py, sdk/python/tests/unit/permissions/auth/test_token_parser.py
Avoid assigning cluster-wide privileges to Feast services to handle RBAC enforcement.
Foxes #4623 
Tested on cluster with existing "rbac_remote" example (which IMO needs some review)
=> fix: Replaced ClusterRoles with local RoleBindings

sdk/python/tests/unit/test_on_demand_python_transformation.py
This PR updates `get_historical_features` to return the requested set of features when ODFVs are called as `get_online_features`. 
As outlined in https://github.com/feast-dev/feast/issues/4479, `get_historical_features` returns more features than what is requested when an ODFV is requested. 
This PR updates:
1. The tests to verify that `get_historical_features` when calling an ODFV returns only the fields requested
2. The tests to verify that an ODFV will result in an error when `get_historical_features` is called with an entity that does not have data to calculate an ODFV
3. The code to properly return only the requested features in `get_historical_features`
https://github.com/feast-dev/feast/issues/4479
N/A
=> chore: Updated tests to confirm behavior of inconsistent offline/online return values

docs/getting-started/concepts/permission.md, docs/reference/feast-cli-commands.md, protos/feast/core/Permission.proto, sdk/python/feast/cli.py, sdk/python/feast/cli_utils.py, sdk/python/feast/permissions/matcher.py, sdk/python/feast/permissions/permission.py, sdk/python/feast/protos/feast/core/Permission_pb2.py, sdk/python/feast/protos/feast/core/Permission_pb2.pyi, sdk/python/tests/integration/registration/test_universal_registry.py, sdk/python/tests/unit/permissions/conftest.py, sdk/python/tests/unit/permissions/test_permission.py
Allowing Permissions to match multiple instance by different name patterns
Fixes #4510 
@franciscojavierarceo
=> fix: Added support for multiple name patterns to Permissions

ui/package.json, ui/yarn.lock
[d3](https://www.npmjs.com/package/d3) is no longer used by Feast UI nor by any of its dependencies, so we can remove it. I could find that it was [initially used](https://github.com/feast-dev/feast/pull/2352/files#diff-32cdbb4974d568b6d232dfb306798aa4d4c9f1bdd61231891c0d9cc53f2a9923) in a component called SparklineHistogram but that no longer exists.
This removes 4 vulnerabilities reported by `yarn audit`. I actually initially started upgrading `d3` and its dependencies to get rid of the vulnerabilities, which did work, but when I wanted to check if d3 related code still worked, I realised it's not used.
```sh
% yarn audit --summary
yarn audit v1.22.22
70 vulnerabilities found - Packages audited: 1797
Severity: 2 Low | 26 Moderate | 39 High | 3 Critical
Done in 3.26s.
```
```sh
% yarn …
```
=> chore: Remove unused d3 dependency from Feast UI

docs/README.md
=> chore: Update 'What is Feast' documentation

sdk/python/feast/transformation/python_transformation.py, sdk/python/tests/unit/test_on_demand_python_transformation.py
This PR adds support for `mode="python"` for On Demand Feature Views (ODFVs) when calling `get_historical_features` by ensuring   that when `*.to_df()` is called, pyarrow executes the function.
https://github.com/feast-dev/feast/issues/4490
@job-almekinders
=> feat: Adding mode='python' for get_historical_features on ODFVs

ui/package.json, ui/src/pages/data-sources/BatchSourcePropertiesView.tsx, ui/yarn.lock
This is the only clear runtime app dependency (at least to me 😄) that had vulnerabilities listed in `yarn audit` output. Upgrading it to the latest version removes 4 high and 5 moderate level vulnerabilities.
Relates to a small part of #4451.
We only use `react-code-blocks` in one place, and only one component of it, `CopyBlock`, but I wasn't able to make it show when running Feast UI locally with `yarn start` to verify that it works and looks OK. But the needed changes were so small and clear that I feel quite confident about the upgrade.
=> chore: Upgrade react-code-blocks to 0.1.6 in Feast UI

ui/package.json, ui/yarn.lock
Bump several dependencies to reduce the number of vulnerabilities reported by `yarn audit` from 57 to 3.
Before:
```sh
% yarn audit --summary
yarn audit v1.22.22
57 vulnerabilities found - Packages audited: 1713
Severity: 2 Low | 21 Moderate | 31 High | 3 Critical
Done in 2.16s.
```
After:
```sh
% yarn audit
yarn audit v1.22.22
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ cookie accepts cookie name, path, and domain with out of     │
│               │ bounds characters                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ cookie                                                       │
├───────────────┼──────────────────────────────────────────────── …
```
=> chore: Bump dependencies to reduce vulnerabilities in /ui

setup.py
pyarrow.substrait is only available starting pyarrow 9.0.0. Similarly protobuf version <4.24.0 doesn't work.
=> fix: Update min versions for pyarrow and protobuf

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/utils/auth_permissions_util.py
* Updates `get_historical_features` to not create a BigQuery dataset when `create_table_disposition` is set to `CREATE_NEVER`.
* Cleans up or ignores some linting issues preventing pushing due to pre-commit checks.
Fixes #4648 
This PR brings BigQuery dataset creation in line with table creation - this will hopefully be useful to orgs (such as mine!) that have stricter requirements over what can/cannot make infrastructure/warehouse changes in production environments. In our case `get_historical_features` is expected to be read only operation.
=> fix: Bigquery dataset create table disposition

ui/package.json
Newest Node.js versions include a tool called [Corepack](https://nodejs.org/docs/latest-v20.x/api/corepack.html), and if you enable it and run `yarn install`, the `packageManager` field gets automatically added to `package.json` with this message:
> ! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e.
> ! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
Corepack is an experimental feature but can be quite useful, and having this field doesn't affect people who don't use it, so I propose to add it permanently. From the Corepack …
=> chore: Add packageManager to ui/package.json

sdk/python/feast/feature_server.py, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.10-requirements.txt, sdk/python/requirements/py3.11-ci-requirements.txt, sdk/python/requirements/py3.11-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, sdk/python/requirements/py3.9-requirements.txt, setup.py
Removes the deprecation warning: for `uvicorn.workers`.
The `uvicorn.workers` module is deprecated, they refer using `uvicorn-worker` package instead.
Fixes https://github.com/feast-dev/feast/issues/4638
=> chore: Added uvicorn-worker dependency

sdk/python/feast/utils.py, sdk/python/tests/unit/test_on_demand_python_transformation.py
This PR fixes failure of proto type adjustment during ODFV transformations for missing entities
https://github.com/feast-dev/feast/issues/4473
=> fix: Fixing failure of protos during ODFV transformations for missing entities

sdk/python/tests/integration/online_store/test_universal_online.py
=> chore: Address flakey online retrieval test

infra/feast-operator/dist/install.yaml, infra/scripts/release/files_to_bump.txt
Updates the release version in a pertinent Operator file and adds said file to scripting. A followup PR will add additional release-specific CI for the operator so this doesn't happen again.
Operator CI is failing because of the recent 0.41.x release
=> fix: Update release version in a pertinent Operator file

sdk/python/feast/offline_server.py
Fixing the issue [4639](https://github.com/feast-dev/feast/issues/4639).
Here is the output currently printing for `feast serve_offline` command.
```
(feast) lokeshrangineni@Lokeshs-MacBook-Pro feature_repo % feast serve_offline
10/21/2024 04:09:08 PM feast.offline_server INFO: Offline store server serving at: grpc+tcp://127.0.0.1:8815
10/21/2024 04:09:08 PM feast.offline_server INFO: offline server starting with pid: [37351]
^C10/21/2024 04:09:11 PM feast.offline_server INFO: KeyboardInterrupt received, stopping the offline server.
10/21/2024 04:09:11 PM feast.offline_server INFO: Sending a shutdown signal to the offline server running with pid:: [37351]
10/21/2024 04:09:11 PM feast.offline_server INFO: offline server stopped.
```
=> feat: Printing more verbose logs when we start the offline server 

sdk/python/feast/data_source.py, sdk/python/feast/infra/offline_stores/bigquery_source.py, sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssqlserver_source.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/feast/infra/offline_stores/redshift_source.py, sdk/python/feast/infra/offline_stores/snowflake_source.py
This is a natural continuation of the work done in this PR: [[PR](fix: Fixed SparkSource docstrings so it wouldn't used inhereted class docstrings)](https://github.com/feast-dev/feast/pull/4722).
There were other DataSource subclasses that had the same issue--using the abstract class docstring (and `__init__` docstring, which did not accurately describe the parameters and functionality of the specialized subclasses.
I have added class docstrings and class `__init__` docstrings where they were missing for subclasses of the `DataSource` class.
=> fix: Issue of DataSource subclasses using parent abstract class docstrings

sdk/python/feast/feature_server.py
* FastApi by default creates an openapi docs page which lists out endpoints
* the python feature server doesn't use pydantic models for request bodies, so the sample inputs for the endpoints aren't populated and schema unknown
* remove json request body parsing and replace it w pydantic models
* this mr does _not_ define a robust response schema for `/get-online-features`
* simply specifies it as dict[str, any]
* should come up w something better but as a follow up
```
feast serve --port 8080
```
generates the following at [http://localhost:8080/docs](http://localhost:8080/docs)
Fixes #4720
=> feat: Add api contract to fastapi docs

sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
This PR adds a docstring to the `SparkSource` class and its `__init__` method.
The current behavior is that `SparkSource` inherits the docstrings from the `DataSource` class. This is wrong, as the `DataSource` class has different functionality and parameters than does `SparkSource`. 
When calling `help(SparkSource)` or `inspect.getdoc(SparkSource)`, the `DataSource` docstring is (wrongfully) returned. Also, when calling `SparkSource.__doc__` or `SparkSource.__init__.__doc__` directly, no docstring is returned.
```
In [1]: from feast.infra.offline_stores.contrib.spark_offline_store.spark_source import SparkSource
In [2]: import inspect
In [3]: print(inspect.getdoc(SparkSource))
DataSource that can be used to source features.
Args:
name: Name of data source, which should be unique within a …
```
=> fix: Fixed SparkSource docstrings so it wouldn't used inhereted class docstrings

docs/getting-started/quickstart.md, examples/quickstart/quickstart.ipynb
In the [quickstart documentation](https://docs.feast.dev/getting-started/quickstart#step-6-ingest-batch-features-into-your-online-store), step 6 mistakenly provides both start and end date parameters to the `feast materialize-incremental` command (which only takes an end date). This was probably just confused with the parameters for the `feast materialize` command. Running the command as is results in an error.
In addition, the docs explain that `materialize-incremental` "serializes all new features since the last materialize call", but this is confusing since no `materialize` call has been run in the quickstart.
In this PR, I fixed the parameter input, and improved the documentation to include a mention of when the ttl is used.
To reproduce the issue:
1. Initialize the quickstart repo: …
=> fix: Fixed example materialize-incremental and improved explanation

protos/feast/core/OnDemandFeatureView.proto, sdk/python/feast/feature_store.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/protos/feast/core/OnDemandFeatureView_pb2.py, sdk/python/feast/protos/feast/core/OnDemandFeatureView_pb2.pyi, sdk/python/feast/transformation/pandas_transformation.py, sdk/python/feast/transformation/python_transformation.py, sdk/python/feast/transformation/substrait_transformation.py, sdk/python/feast/utils.py, sdk/python/tests/unit/test_on_demand_python_transformation.py
This PR adds support for native Python transformations on a dictionary of a singleton (i.e., what most Data Scientists would call a single row).
As an example, Data Scientists can now transform features using an On Demand Transform like so:
```python
@on_demand_feature_view(
sources=[driver_stats_fv[["conv_rate", "acc_rate"]]],
schema=[
Field(name="conv_rate_plus_acc_python_singleton", dtype=Float64)
],
mode="python",
singleton=True,
)
def python_singleton_view(inputs: dict[str, Any]) -> dict[str, Any]:
output: dict[str, Any] = dict(conv_rate_plus_acc_python=float("-inf"))
output["conv_rate_plus_acc_python_singleton"] = (
inputs["conv_rate"] + inputs["acc_rate"]
)
return output
``` 
Compare this to the previous logic to do the transformation which looks like:
```python …
```
=> feat: Adding support for native Python transformations on a single dictionary 

docs/reference/starting-feast-servers-tls-mode.md, sdk/python/feast/cli.py, sdk/python/feast/feature_store.py, sdk/python/feast/ui_server.py
* Adding SSL support for the React UI server and feast UI command. 
* Adding the separate documentation for all the feast servers to start in TLS mode except the offline server. 
* We will update the documentation for offline server once the SSL support is added to offline server.
=> feat: Adding SSL support for the React UI server and feast UI command.

sdk/python/feast/feature_store.py
This PR removes the `version` function from `feature_store.py`, which is a method to the `FeatureStore` class. The `version` method was unused, un-needed, and confusing. See issue #4747 for more details.
I categorized this as a "fix" because I see an unused/un-needed function as a bug, but I understand that this could merit a different categorization.
#4747
=> fix: Removed version func from feature_store.py

docs/SUMMARY.md, docs/how-to-guides/starting-feast-servers-tls-mode.md, sdk/python/feast/cli.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/remote.py, sdk/python/feast/offline_server.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py, sdk/python/tests/utils/generate_self_signed_certifcate_util.py
* Adding TLS support for offline server.
* Added test cases for the TLS offline server by creating RemoteOfflineTlsStoreDataSourceCreator
=> feat: Adding TLS support for offline server.

docs/reference/denormalized.md
=> docs: Update Streaming feature computation with Denormalized entry

.github/workflows/operator-e2e-integration-tests.yml, infra/feast-operator/test/utils/utils.go
* Adding github action to do the operator end-to-end testing. This action will create a kind cluster and runs the tests on it.
=> feat: Adding github action to run the operator end-to-end tests.

infra/feast-operator/config/rbac/role.yaml, infra/feast-operator/dist/install.yaml, infra/feast-operator/internal/controller/featurestore_controller.go, infra/feast-operator/internal/controller/featurestore_controller_test.go, infra/feast-operator/internal/controller/services/services.go
For each feast service the operator deploys, a new service account will be created and used. This will ensure we're not using the default SA which can sometimes have been modified by the user or have elevated perms, etc.
Fixes https://github.com/feast-dev/feast/issues/4766
=> feat: Operator will create k8s serviceaccount for each feast service

examples/quickstart/quickstart.ipynb
This PR removes the command `pip install Pygments -q` (and a supporting comment) from the `quickstart.ipynb` notebook. This install command is not needed because `Pygments` is a `feast` dependency that is installed with `feast`.  Removing the extra install line simplifies the notebook and makes it easier to get started quickly, as it makes the cell run faster.
To test that the notebook still works you can:
1. Create a new venv and install jupyter (you need this to run the notebook):
```#bash
cd examples/quickstart
python -m venv temp-venv
pip install jupyter
```
2. Run the `quickstart.ipynb` from this PR (with the Pygments import statement removed). It should run successfully.
```#bash
jupyter execute quickstart.ipynb
```
Note that the notebook itself installs `feast` latest. You can …
=> chore: Removed unneeded install line

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Improve the Dockerfile to remove unnecessary packages and do some cleanup. This will reduce the current image size by over 300mb.
```shell
$ podman images
REPOSITORY                         TAG         IMAGE ID      CREATED        SIZE
quay.io/tchughesiv/feature-server  0.41.3      84dc7acaad64  2 minutes ago  1.04 GB
docker.io/feastdev/feature-server  0.41.3      1bbf34c192d9  3 weeks ago    1.37 GB
```
This is done by switching to the official python3 debian 11 slim image (`python:3.11-slim-bullseye`) which handles some of cleanup around python installation. We also tell pip install not to use cache and remove the `build-essential` package. Finally, we do some additional cleanup around apt.
Additionally, this PR fixes `Dockerfile.dev` so that it builds local dev changes into a …
=> fix: Reduce feast-server container image size & fix dev image build

.devcontainer/devcontainer.json, .github/fork_workflows/fork_pr_integration_tests_aws.yml, .github/fork_workflows/fork_pr_integration_tests_gcp.yml, .github/fork_workflows/fork_pr_integration_tests_snowflake.yml, .github/workflows/java_master_only.yml, .github/workflows/java_pr.yml, .github/workflows/linter.yml, .github/workflows/master_only.yml, .github/workflows/nightly-ci.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/pr_local_integration_tests.yml, .github/workflows/smoke_tests.yml, .github/workflows/unit_tests.yml, .gitpod.yml, Makefile, docs/how-to-guides/customizing-feast/adding-a-new-offline-store.md, docs/project/development-guide.md
The current guide for setting up a development environment is unclear and the existing makefile includes multiple tasks that do very similar things, are un-used, or are confusingly named. This PR seeks to clear up confusion around how one should configure their python environment for developing feast.
This PR
- cleans up makefile tasks related to python dependencies to make it more clean which should be used when
- Updates the environment setup docs to make it clear UV should be used for dependency management
=> chore: Clean up makefile

infra/feast-operator/api/v1alpha1/featurestore_types.go, infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml, infra/feast-operator/config/samples/v1alpha1_featurestore_db_persistence.yaml, infra/feast-operator/dist/install.yaml, infra/feast-operator/internal/controller/featurestore_controller_db_store_test.go, infra/feast-operator/test/api/featurestore_types_test.go
This PR contains the changes and leftovers from [4771](https://github.com/feast-dev/feast/pull/4771)
Fixes https://github.com/feast-dev/feast/issues/4793
Fixes https://github.com/feast-dev/feast/issues/4783
=> feat: Updated feast Go operator db stores

infra/feast-operator/config/samples/v1alpha1_featurestore_db_persistence.yaml
This PR contains the changes and leftovers from [4771](https://github.com/feast-dev/feast/pull/4771) - following review 
Fixes https://github.com/feast-dev/feast/issues/4793
Fixes https://github.com/feast-dev/feast/issues/4783
=> feat: Updated sample secret following review

infra/feast-operator/Makefile, infra/feast-operator/README.md, infra/feast-operator/test/e2e/e2e_test.go, infra/feast-operator/test/e2e/test_util.go, infra/feast-operator/test/testdata/feast_integration_test_crs/v1alpha1_default_featurestore.yaml
Adding first basic feast operator e2e test.
Planing to address following scenarios as part of the test in this PR:
1. Kubernetes FeatureStore CR should spin up all the necessary services required  in our case it will be registry, online and offline services.
2. Assert `FeatureStore` CR status should be in ready state.
3. Assert registry, online and offline service Deployments are in Running and available state.
4. Assert feast client ConfigMap is existing.
5. Assert registry, online and offline services are having associated Kubernetes service objects defined.
6. Assert registry, online and offline services are having associated Kubernetes service account objects defined.
Issue we are fixing: [4792](https://github.com/feast-dev/feast/issues/4792)
=> feat: Adding first feast operator e2e test.

.github/workflows/operator-e2e-integration-tests.yml, infra/feast-operator/Makefile, infra/feast-operator/test/e2e/e2e_test.go, infra/feast-operator/test/e2e/test_util.go, infra/feast-operator/test/testdata/feast_integration_test_crs/v1alpha1_remote_registry_featurestore.yaml
We have added the operator E2E test to cover following scenario. 
* Deploy the feature store custom resource in one of of the kubernetes namespace.
* Deploy the another feature store custom resource in another namespace but should point to the registry using remote setting which should refer to the registry service created in the previous step.
* Increase the `go test` timeout so that github ci will succeed without time out issue. Also added the kind cluster logs when there is a failure of operator e2e test github action so it will help in troubleshooting the issue.
Issue related to [4823](https://github.com/feast-dev/feast/issues/4823)
=> feat: Operator E2E test to validate FeatureStore custom resource using remote registry

infra/feast-operator/test/e2e/e2e_test.go, infra/feast-operator/test/e2e/test_util.go
Parsing the output to go lang structs rather than a Map to simplify the parsing logic.
=> feat: Go Operator - Parsing the output to go structs

infra/feast-operator/api/v1alpha1/featurestore_types.go, infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml, infra/feast-operator/dist/install.yaml, infra/feast-operator/internal/controller/featurestore_controller_db_store_test.go, infra/feast-operator/internal/controller/services/repo_config.go, infra/feast-operator/internal/controller/services/repo_config_test.go, infra/feast-operator/test/api/featurestore_types_test.go
* FeatureStore CR goes into an error state if the user includes the `type` or `registry_type` field in their persistence config Secret.
The fix is to throw an error only if these fields are set and do not match the CR configured persistence type for that service.
* There are some missing online/offline store types validations in the CR.
The fix is to add CR validation for missing types
=> fix: Made fixes to Go Operator DB persistence

sdk/python/feast/entity.py, sdk/python/tests/unit/test_entity.py
Make value_type for Entity issue a warning if not set. Next release we'll make it mandatory.
https://github.com/feast-dev/feast/issues/4670
=> chore: Issue warning announcing entity's value_type as mandatory 

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
duckdb is used in our feast-aws-credit-scoring-tutorial example, so it should be available here by default. this would allow us to use that same demo with the operator
=> feat: Add duckdb extra to multicloud release image

sdk/python/tests/data/data_creator.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/integration/offline_store/test_feature_logging.py
This pull request introduces several enhancements and updates to the `feast` repository. The changes are focused on adding new features and improving existing functionalities in the Python SDK. Below are the detailed changes:
- Added new fields to the `create_document_dataset` function:
- `string_feature`: A list of strings `["a", "b", "c"]`.
- `float_feature`: A list of floats `[1.0, 2.0, 3.0]`.
- Updated imports to include `String` from `feast.types`.
- Enhanced the `create_item_embeddings_feature_view` function:
- Added `vector_index` and `vector_search_metric="L2"` attributes to `embedding_double` and `embedding_float` fields.
- Added new fields `string_feature` of type `String` and `float_feature` of type `Float32`.
- Modified the `retrieve` function to handle timezone-aware datetime …
=> chore: Update document test to add other feature data types and fix feature logging

sdk/python/feast/infra/offline_stores/snowflake.py
The query template for the Snowflake Offline Store is updated to use the recently added ASOF JOIN (https://www.snowflake.com/en/blog/time-series-analytics-asof-join-generally-available/). We have seen a very substantial improvement in feature queries using the new template. Especially, for large feature tables that have many historical entries for certain entity values the performance is even better than using the `ttl` parameter in the current query template.
Fixes #4732
@bimtauer and @miianiemela have shown interest in the feature, are you able to take a look and test it in your setup?
=> feat: Use ASOF JOIN in Snowflake offline store query

infra/feast-operator/internal/controller/services/repo_config.go, infra/feast-operator/internal/controller/services/repo_config_test.go, infra/feast-operator/internal/controller/services/util.go
- Change order of status.applied update to avoid conflicts & ensure all defaults are properly set
- Add offline PVC unit test to ensure ephemeral registry & online paths are updated accordingly
- Minor code improvements
Relates to https://github.com/feast-dev/feast/issues/4866
=> fix: Improve status.applied updates & add offline pvc unit test

.gitignore, Makefile, sdk/python/requirements/protoc-requirements.txt, setup.py
This PR fixes or updates some of the go-related targets, specifically addresses the following:
- incorrectly defined dependency targets
- protobuf/GRPC go tools installed globally, thus potentially messing up existing installations
- pip used instead of uv pip
- .PHONY targets not declared
- moved inline python/grpc requirements to separate file
N/A
target `build-go` builds a binary in the root directory, it should be moved under `dist/`  (follow-up PR)
=> chore: Update go targets in Makefile

Makefile, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/online_store/test_universal_online.py
Fixing testing in Milvus, Makefile, and repo_configuration
N/A
N/A
=> chore: Fixing testing in Milvus, Makefile, and repo_configuration

infra/feast-operator/api/v1alpha1/featurestore_types.go, infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml, infra/feast-operator/dist/install.yaml, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
Once https://github.com/feast-dev/feast/pull/4751 merges, we'll want to support Milvus out of the box in the Operator. This PR would allow for that.
Relates to https://github.com/feast-dev/feast/issues/4364
=> feat: Add milvus package to release image & option to Operator

docs/README.md
Minor language improvements to make the docs easier to read
None
Hope you find my contributions helpful.
=> chore: Minor language improvements 

go/internal/feast/errors.go, go/internal/feast/featurestore.go, go/internal/feast/featurestore_test.go, go/internal/test/feature_repo/example.py
Prevents the Go feature server from panicking when `transformation_service_endpoint` configuration is not defined in feature_store.yaml. 
N/A
=> fix: Make transformation_service_endpoint configuration optional

.github/workflows/pr_integration_tests.yml
Add Milvus to pr_integration_tests.yml
N/A
Tested the Milvus container in this repo: https://github.com/franciscojavierarceo/testing-github-action-sandbox/blob/main/.github/workflows/milvus.yml
Screen shot for reference of successful build:
=> chore: Add Milvus to pr_integration_tests.yml

.github/workflows/operator-e2e-integration-tests.yml, .github/workflows/pr_remote_rbac_integration_tests.yml, Makefile, sdk/python/pytest.ini, sdk/python/tests/conftest.py, sdk/python/tests/integration/conftest.py, sdk/python/tests/integration/feature_repos/universal/data_source_creator.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py, sdk/python/tests/integration/online_store/test_remote_online_store.py, sdk/python/tests/integration/registration/test_universal_registry.py
* Separating the tests related to remote and rbac functionality.
* Added a new test marker to separate the tests related to rbac and remote functionality.
* Added a new github action to perform tests related to rbac and remote functionality.
* Filtered the rbac integration tests in the current github job. and added new make target to run the new tests.
* Added shared state so that same keycloak instance can be reused.
[4904](https://github.com/feast-dev/feast/issues/4904)
=> feat: Separating the RBAC and Remote related integration tests.

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py, sdk/python/tests/integration/feature_repos/universal/online_store/milvus.py, sdk/python/tests/integration/online_store/test_universal_online.py
This PR moves the Milvus Online Store implementation to the PyMilvus Client instead of using Connections, in addition to some other minor changes. 
More specifically:
1. `sdk/python/feast/feature_store.py`:
- Changed the default value of the `distance_metric` parameter in the `retrieve_online_documents` method to "L2".
2. `sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py`:
- Replaced the usage of `pymilvus.orm.connections` with `MilvusClient` for managing Milvus connections.
- Added support for `username` and `password` configurations in `MilvusOnlineStoreConfig`.
- Updated the `MilvusOnlineStore` class to use `MilvusClient` for creating and managing collections, including:
- Creating collections with a composite key.
- Preparing and creating indexes for vector fields.
- …
=> chore: Moving Milvus client to PyMilvus

docs/getting-started/concepts/permission.md
The current example for setting up a `Permission` object with the `READ` action, which serves as a composition of multiple read actions (`READ_OFFLINE` and `READ_ONLINE`), makes Feast crash when running `feast apply`.
It is documented like this at the moment:
```py
from feast.permissions.action import AuthzedAction, READ
Permission(
name="feature-reader",
types=[FeatureView, FeatureService],
policy=RoleBasedPolicy(roles=["super-reader"]),
actions=[AuthzedAction.DESCRIBE, READ],
)
```
So `actions` ultimately ends up resolving `READ` and looking like this:
```py
from feast.permissions.action import AuthzedAction, READ
Permission(
name="feature-reader",
types=[FeatureView, FeatureService],
policy=RoleBasedPolicy(roles=["super-reader"]),
actions=[AuthzedAction.DESCRIBE, …
```
=> docs: Add missing unpacking operator in Permission objects docs

sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py, sdk/python/tests/example_repos/example_rag_feature_repo.py, sdk/python/tests/unit/online_store/test_online_retrieval.py, sdk/python/tests/utils/cli_repo_creator.py
Updating tests to allow for the CLIRunner to use Milvus, also have to handle special case of not running apply and teardown
https://github.com/feast-dev/feast/issues/4364
=> chore: Updating tests to allow for the CLIRunner to use Milvus, also have to handle special case of not running apply and teardown

Makefile, infra/feast-operator/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Move towards UBI base images for feast related containers. Also, removing `libarrow-dev` libraries from feature-server image.
Fixes https://github.com/feast-dev/feast/issues/4920
Removes unused `libarrow-dev` installation, which also reduces the size of the resulting image. This library hasn't been needed for close to 2 years since all Go feature server references were removed from the feast python code.
https://github.com/feast-dev/feast/pull/3554
For reference ... from the stale Feast docs on this removed component - 
_You must also install the Apache Arrow C++ libraries. This is because the Go feature server uses the cgo memory allocator from the Apache Arrow C++ library for interoperability between Go and Python, to prevent memory from being accidentally garbage collected when …
=> chore: Change feature-server and operator base images to ubi9

sdk/python/feast/type_map.py
Add date support when converting from python to feast types. This is a follow up to https://github.com/feast-dev/feast/pull/4913
None
=> feat: Add date support when converting from python to feast types

.github/workflows/java_master_only.yml, .github/workflows/java_pr.yml, .github/workflows/master_only.yml
The gcr.io image registry is being decommissioned and we can no longer add new repos to it. Because of this, we have a failing GH workflow.
=> fix: Move pre-release image builds to quay.io, retire gcr.io pushes

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/offline_utils.py
This PR addresses a syntax error that occurs when querying a feature view with a column name starting with a number, specifically when using the BigQuery data source. To resolve this issue, the PR wraps all BigQuery feature view column names in backticks (`).
Fixes #4688
This issue was closed by the PR https://github.com/feast-dev/feast/pull/4713, however the bug was not resolved with 4713. 
The current PR fixes bugs mentioned in #4688
=> fix: Resolving syntax error while querying a feature view with column name starting with a number and BigQuery as data source

infra/feast-operator/Makefile, infra/feast-operator/bundle/manifests/feast-operator.clusterserviceversion.yaml, infra/feast-operator/config/default/kustomization.yaml, infra/feast-operator/config/default/related_image_fs_patch.tmpl, infra/feast-operator/config/default/related_image_fs_patch.yaml, infra/feast-operator/config/default/related_image_grpc_patch.yaml, infra/feast-operator/internal/controller/services/services_types.go, infra/feast-operator/internal/controller/services/util.go, infra/feast-operator/test/e2e/e2e_test.go, infra/scripts/release/files_to_bump.txt
Related to https://github.com/feast-dev/feast/pull/4928
This allows a user to set the `FS_IMG` env variable during Operator manifest generation. The result will be a modified `RELATED_IMAGE_FEATURE_SERVER` env var in the Operator deployment object.
e.g.
```bash
$ make build-installer bundle FS_IMG=localhost/feastdev/feature-server:dev
```
```bash
$ make deploy FS_IMG=localhost/feastdev/feature-server:dev
```
=> chore: Add ability to change default feature-server image during Operator deploy

.github/workflows/build_wheels.yml, .github/workflows/publish_images.yml
=> chore: Fix publish, versions issue

infra/feast-operator/test/e2e/test_util.go
Adding periodic check to fix the sporadic failures of the operator e2e tests. 
Fixes - [4953](https://github.com/feast-dev/feast/issues/4953)
=> fix: Adding periodic check to fix the sporadic failures of the operator e2e tests. 

.github/workflows/build_wheels.yml
=> chore: Build wheels fix

.github/workflows/publish_python_sdk.yml
=> fix: Updating pypi upload to use legacy repo url

sdk/python/feast/infra/key_encoding_utils.py, sdk/python/tests/unit/infra/test_key_encoding_utils.py
Updating entity key v3 serialization. Fails for multiple entities during vector retrieval.
N/A
N/A
=> chore: Updating entity key serialization for multiple entities

ui/src/pages/Sidebar.tsx
Fixes showing the currently active/selected navigation item in the sidebar.
No related issues as far as I know, just something I happened to notice.
Our [`useMatchSubpath`](https://github.com/feast-dev/feast/blob/dc2c1dc67c8e191c29155ced3334244351f312c7/ui/src/hooks/useMatchSubpath.ts#L3) hook uses these two react-router-dom hooks:
1. [`useResolvedPath`](https://reactrouter.com/6.28.2/hooks/use-resolved-path)
2. [`useMatch`](https://reactrouter.com/6.28.2/hooks/use-match)
After some investigation, I found that `useMatch` [doesn't work with relative or partial paths](https://github.com/remix-run/react-router/issues/8684#issuecomment-1050521422). Furthermore, in our Sidebar `useResolvedPath` doesn't include any parts of the current page pathname in the result, resulting in just e.g. …
=> fix: Fix showing selected navigation item in UI sidebar

ui/src/FeastUISansProviders.test.tsx, ui/src/pages/Sidebar.tsx
Render navigation item links as links instead of buttons: Using link is semantically correct and improves accessibility, allows opening the linked pages in another tab etc.
Couldn't find any issues, just noticed this myself.
Use react-router-dom [Links](https://reactrouter.com/6.28.2/components/link) instead of plain anchors to prevent full page reloads when navigating.
=> fix: Render UI navigation items as links instead of buttons

infra/feast-operator/config/default/kustomization.yaml, infra/feast-operator/config/default/related_image_grpc_patch.yaml, infra/feast-operator/config/manager/manager.yaml, infra/feast-operator/dist/install.yaml, infra/feast-operator/go.mod, infra/feast-operator/internal/controller/featurestore_controller_test.go, infra/feast-operator/internal/controller/services/services.go, infra/feast-operator/internal/controller/services/services_types.go, infra/feast-operator/internal/controller/services/util.go
Removing this grpcurl image dependency as it's unnecessary and, if possible, we should avoid third party deps.
=> fix: Remove grpcurl dependency from Operator

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py, sdk/python/feast/infra/online_stores/online_store.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/feast/utils.py, sdk/python/tests/example_repos/example_rag_feature_repo.py, sdk/python/tests/foo_provider.py, sdk/python/tests/unit/online_store/test_online_retrieval.py
This PR adds support for returning multiple fields when doing  vector similarity search with Milvus.
The behavior is now as simple as:
```python
document_embeddings = FeatureView(
name="embedded_documents",
entities=[item, author],
schema=[
Field(
name="vector",
dtype=Array(Float32),
vector_index=True,
vector_search_metric="COSINE",
),
Field(name="item_id", dtype=Int64),
Field(name="author_id", dtype=String),
Field(name="sentence_chunks", dtype=String),
Field(name="created_timestamp", dtype=UnixTimestamp),
Field(name="event_timestamp", dtype=UnixTimestamp),
],
source=rag_documents_source,
ttl=timedelta(hours=24),
)
result = store.retrieve_online_documents_v2(
features=[
"embedded_documents:vector",
"embedded_documents:item_id",
"embedded_documents:author_id", …
```
=> feat: Adding support to return additional features from vector retrieval for Milvus db

ui/config/jest/cssTransform.js, ui/jest.config.js, ui/package.json, ui/yarn.lock
Upgrade Jest related packages to their latest versions. This is preparatory work to upgrade [msw](https://github.com/mswjs) (whose old version causes security alerts due to vulnerable dependencies), which proved out to be impossible to do with older versions of Jest (at least for me). (I also tried switching from Jest to Vitest but had some mysterious failures with it too, may revisit it later.)
None.
This was a long and winding road filled with desperation at times, so I should explain some changes:
- The syntax for Jest transformers has changed, updated `cssTransform.js` accordingly
- By default, we don't transform files in `node_modules`, but we now need to transform a couple dependencies, so we need to un-ignore them in `transformIgnorePatterns` in the Jest config:
- `@elastic/eui` …
=> chore: Upgrade Jest packages to latest versions in /ui

infra/feast-operator/test/e2e/e2e_test.go
Added conditional run of BeforeAll in e2e tests, after the change it will not run in an OpeshiftCI environment since the OpeshiftCI infrastructure is responsible for the operations performed in BeforeAll
This change is need to enable e2e tests to be run with OpenshiftCI
=> fix: Changed Env Vars for e2e tests

sdk/python/feast/infra/offline_stores/snowflake_source.py
For Snowflake data sources, there it is checked if all columns in a table have data types that are supported. If not an exception is thrown with limited information. 
These changes add more information about which column and datatype are affected. This information will help in fixing the underlying table schema.
=> feat: Improve exception message for unsupported Snowflake data types

infra/feast-operator/Makefile, infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml, infra/feast-operator/dist/install.yaml
We're experiencing some CRD bloat due to large field descriptions. Going forward, we'll want to point users to our API reference doc instead.
https://github.com/feast-dev/feast/blob/v0.43-branch/infra/feast-operator/docs/api/markdown/ref.md
Fixes https://github.com/feast-dev/feast/issues/4984
https://developers.redhat.com/articles/2022/12/23/configuring-kubernetes-operands-through-custom-resources
=> fix: Resolve Operator CRD bloat due to long field descriptions

infra/feast-operator/Dockerfile, infra/feast-operator/Makefile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
switch base images to ubi8
cherry-pick of https://github.com/feast-dev/feast/pull/4987
=> chore: Switch base builder images to ubi8 (v0.43-branch)

OWNERS
Added OWNERS file for OpenshiftCI
Used by openshiftCI infrastructure
=> feat: Added OWNERS file for OpenshiftCI

sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Our feature-server dev image builds aren't using the latest UI code. This PR resolves that.
Relates to https://github.com/feast-dev/feast/issues/4981
=> fix: Use locally built feast-ui package in dev feature-server image

docs/SUMMARY.md, docs/reference/online-stores/milvus.md, examples/rag/README.md, examples/rag/milvus-quickstart.ipynb, sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py, sdk/python/feast/type_map.py, sdk/python/feast/types.py, sdk/python/tests/example_repos/example_feature_repo_1.py, sdk/python/tests/unit/online_store/test_online_retrieval.py
This pull request includes several updates and improvements to the Feast project, focusing on the integration and enhancement of the Milvus online store. Below is a detailed summary of the changes made:
1. **Examples Update**
- **README.md**: Modified the materialization steps for features into the online store by switching to Python code snippets.
- **milvus-quickstart.ipynb**: Format change.
2. **Milvus Online Store Enhancements**
- **milvus.py**:
- Removed unused imports.
- Added `VALUE_TYPE_TO_PROTO_VALUE_MAP` for mapping value types.
- Introduced a new method `_get_composite_key_name` to generate composite key names.
- Updated methods to utilize `_get_composite_key_name` for consistency.
- Implemented the `online_read` method to handle reading from the Milvus online store.
- Improved …
=> feat: Implementing online_read for MilvusOnlineStore

sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
When there are field mappings on an entity's join keys, `get_historical_features()` fails because it does not use the original column name in the data source.
This is needed when the source data cannot be modified, and a field mapping is used to map the source data's column to the join key.
Example:
```python
from feast import Entity, Field, FeatureStore, FeatureView
from feast.types import Float32, String
from feast.infra.offline_stores.contrib.spark_offline_store.spark_source import SparkSource
store = FeatureStore(...)
driver = Entity(name="driver", join_keys=["driver_id"])
driver_stats_src = SparkSource(
name="driver_stats",
field_mapping={"id": "driver_id"},
path=...,
file_format=...,
)
driver_stats_fv = FeatureView(
name="driver_stats",
source= driver_stats_src,
entities=[driver], …
```
=> fix: Invalid column names in get_historical_features when there are field mappings on join keys

.releaserc.js
The `bin/` dir for feast-operator is not needed.
=> chore: Ignore `infra/feast-operator/bin` during release

.github/workflows/release.yml, .github/workflows/update_stable_branch.yml
Moving the job to seperate action so that we can test it easily
=> feat: Moving the job to seperate action so that we can test it easily.

community/maintainers.md, docs/project/release-process.md
=> chore: Update release docs

infra/feast-operator/api/v1alpha1/featurestore_types.go, infra/feast-operator/internal/controller/featurestore_controller.go, infra/feast-operator/internal/controller/featurestore_controller_db_store_test.go, infra/feast-operator/internal/controller/featurestore_controller_ephemeral_test.go, infra/feast-operator/internal/controller/featurestore_controller_kubernetes_auth_test.go, infra/feast-operator/internal/controller/featurestore_controller_loglevel_test.go, infra/feast-operator/internal/controller/featurestore_controller_objectstore_test.go, infra/feast-operator/internal/controller/featurestore_controller_oidc_auth_test.go, infra/feast-operator/internal/controller/featurestore_controller_pvc_test.go, infra/feast-operator/internal/controller/featurestore_controller_test.go, infra/feast-operator/internal/controller/featurestore_controller_tls_test.go, infra/feast-operator/internal/controller/services/services.go
Changed feast Operator to update FeatureStore CR's status.conditions by checking resulting Deployment's status
Now the status of the feast CR is more accurate
=> fix: Changed feast operator to set status of featurestore cr to ready based on deployment.status = available

docs/getting-started/components/feature-server.md
Adding docs and retrieve online documents endpoint to Feature Server documentation
=> docs: Adding docs and retrieve online documents endpoint to Feature Server documentation

community/maintainers.md
Add Tornike and Zhiling back as maintainers since they have not explicitly volunteered to be moved to emeritus.
N/A
=> chore: Add Tornike and Zhiling back as maintainers

infra/feast-operator/config/component_metadata.yaml, infra/scripts/release/files_to_bump.txt
added component_metadata file to show feast latest release in ODH operator
same PR moving to stable branch #5021
=> chore: Added component_metadata file to show Feast latest release in ODH operator [stable]

sdk/python/feast/utils.py, sdk/python/tests/unit/online_store/test_online_retrieval.py, sdk/python/tests/unit/test_unit_feature_store.py
This PR addresses the issue of unexpected crashes when using feature_store.get_online_features with incorrect or missing join keys. 
Specifically, it introduces validation logic in the `_get_unique_entities` function to ensure that all expected join keys are present and non-empty before proceeding. 
**If any required join keys are missing** or have empty values, a KeyError is raised with a descriptive error message. Additionally, new unit tests have been added to cover various edge cases, ensuring that the function behaves as expected under different scenarios.
Changes:
- `sdk/python/feast/utils.py`:
- Added validation for missing and empty join keys in `_get_unique_entities`.
- Updated the logic to convert column-oriented `table_entity_values` into row-wise data and handle edge cases.
- …
=> fix: Validate entities when running get_online_features

docs/how-to-guides/running-feast-in-production.md, infra/feast-helm-operator/README.md
Updated  Helm Operator to point out that the operator is deprecated and the new feast go operator should be used instead.
The feast go operator is more powerful and allows a flexible deployment
=> docs: Deprecate Helm Operator - docs

.github/workflows/operator_pr.yml, .github/workflows/pr_local_integration_tests.yml, infra/feast-operator/.golangci.yml, infra/feast-operator/Makefile, infra/feast-operator/api/v1alpha1/featurestore_types.go, infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml, infra/feast-operator/dist/install.yaml, infra/feast-operator/docs/api/markdown/ref.md, infra/feast-operator/test/api/featurestore_types_test.go, infra/feast-operator/test/data-source-types/data-source-types.py, infra/feast-operator/test/data-source-types/data_source_types_test.go
The operator needs to remain in sync with the feast data source python class types. This PR ensures that's the case long-term.
=> chore: Operator / Feast should have matching Data Source types

sdk/python/feast/infra/online_stores/postgres_online_store/postgres.py
We are using `psycopg3` in case we use Postgres for the online store. If you create connections with `psycopg3` using a context manager (i.e. a `with ...` block), it will automatically commit the transaction once you exit the context. However, in `feast` we are manually creating (and in the case of connection pools, putting) connections, so we need to ensure that we also explicitly call `commit` after firing queries to the database. 
The `commit` statements were missing for (async) read methods of the `PostgresOnlineStore` and the `teardown` method. For the read statements, this wasn't an issue as we just do a `SELECT`. However, it does add warning statements and quite a bit of latency as transactions needed to be rolled back. 
Hence, for those read methods, I introduced an optional …
=> fix: Ensure Postgres queries are committed or autocommit is used

docs/reference/feast-cli-commands.md, sdk/python/feast/cli.py, sdk/python/tests/unit/cli/test_cli.py
This PR introduces a new CLI command, feast configuration, to dump the actual configuration being used by Feast. This includes both user-provided configurations and default configurations applied by Feast. This feature is particularly useful for debugging and ensuring transparency in how configurations are interpreted, especially when defaults are applied.
For example, if a user provides a partial configuration, Feast will automatically apply default values for missing fields. The new CLI command will expose the complete configuration, including these defaults, in a human-readable format.
Example usage:
```bash
feast configuration
```
Example output: 
```yaml
project: foo
registry: data/registry.db
provider: local
online_store:
type: sqlite
path: data/online_store.db
offline_store: 
type: …
```
=> feat: Adding Click command to display configuration details

infra/feast-operator/Makefile, infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml, infra/feast-operator/dist/install.yaml
With the last release, we were experiencing k8s errors related to CRD bloat. Because of this we took the extreme measure of removing all descriptions from the CRD to reduce its size. However, keeping some level of field descrips is very important for a user's experience, both with the Operator and with Feast. In this PR, we'll continue to limit the line length of the descrips, but increase that length from `0` to `120`.
Relates to https://github.com/feast-dev/feast/pull/5001
=> chore: Operator - increase maxDescLen to include some CRD descriptions

infra/feast-operator/internal/controller/authz/authz.go
Fixing a bug which causes an operator created RoleBinding to infinitely grow in size... and the operator's controller to get stuck in a loop.
Fixes https://github.com/feast-dev/feast/issues/5055
=> fix: Operator - resolve infinite reconciler loop when authz configured

.github/workflows/release.yml
Fixing the release workflow to refresh the stable branch when the release is not running in the dry run mode.
Fixes: [5058](https://github.com/feast-dev/feast/issues/5058)
=> fix: Fixing the release workflow to refresh the stable branch when the release is not running in the dry run mode.

docs/reference/alpha-vector-database.md, sdk/python/feast/infra/online_stores/sqlite.py, sdk/python/tests/integration/registration/test_universal_registry.py, sdk/python/tests/unit/online_store/test_online_retrieval.py
Add  `retrieve_online_documents_v2` to sqlite-vec
- **docs/reference/alpha-vector-database.md**
- Added a new column `Online Read` in the vector database support table.
- Marked SQLite as supporting `retrieve_online_documents_v2`.
- Noted that both Milvus and SQLite implement the `retrieve_online_documents_v2` method.
- **sdk/python/feast/infra/online_stores/sqlite.py**
- Added new attributes to the `SqliteOnlineStoreConfig` class for vector search.
- Modified `_get_conn` method to conditionally enable SQLite vector extension.
- Refactored `retrieve_online_documents` to use `vec_table`.
- Added a new method `retrieve_online_documents_v2` for vector similarity search.
- Updated `_initialize_conn` method to handle the vector extension initialization.
- …
=> feat: Add SQLite retrieve_online_documents_v2

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/online_store.py, sdk/python/feast/utils.py, sdk/python/tests/unit/test_unit_feature_store.py
Is some use cases, for example in recommender systems, we need to retrieve features for hundreds and thousands of entities. As stated in the issue https://github.com/feast-dev/feast/issues/3596, current implementation has a significant overhead.
I ran a benchmark test for 1000 entities with profiling and noticed, that `_populate_response_from_feature_data` and `_convert_rows_to_protobuf` functions are quite heavy.
A have several proposals for improvement:
- `_populate_response_from_feature_data` has 3 calls of `apply_list_mapping` where we calculate `output_len = sum(len(item) for item in mapping_indexes)` which is time consuming. We could calculate `output_len` only once, when we deduplicate entities. And we could combine all 3 vectors into response in one loop
- We get feature_data from …
=> refactor: Rework `get_online_features` helper functions

README.md
ScyllaDB is already supported as online stores and even have separate [docs](https://docs.feast.dev/reference/online-stores/scylladb)
List Scylladb in online stores lists in repos README.md
=> fix: Add scylladb to online stores list in docs

docs/roadmap.md, pyproject.toml
Move setup.py configs to pyproject.toml
Fixes #5066
=> fix: Move Feast to pyproject.toml instead of setup.py

sdk/python/feast/infra/registry/caching_registry.py, sdk/python/tests/unit/infra/registry/test_registry.py
This is the fix to prevent deadlocks on registry cache refresh.
- Used `self._refresh_lock.acquire(blocking=False)` to avoid infinite waiting and avoids releasing an unlocked lock.
- Fixed recursive calls by checking `self._refresh_lock.locked()` flag to prevent `self.refresh()` from calling itself indirectly.
- Handled exceptions by wrapping logic inside try to catch errors and always release locks.
#4898 
Tests:
```
sdk/python/tests/unit/infra/registry/test_registry.py::test_cache_expiry_triggers_refresh 02/20/2025 03:36:21 PM feast.infra.registry.caching_registry INFO: Registry cache expired, so refreshing
02/20/2025 03:36:21 PM feast.infra.registry.caching_registry INFO: Skipping refresh if already in progress
02/20/2025 03:36:21 PM feast.infra.registry.caching_registry INFO: Registry …
```
=> fix: Skip refresh if already in progress or if lock is already held

sdk/python/feast/infra/offline_stores/dask.py, sdk/python/feast/infra/offline_stores/duckdb.py, sdk/python/feast/infra/offline_stores/file_source.py, sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
This is the fix to correctly identify the file path as relative or absolute or remote path using urllib urlparse, which checks both scheme and netloc, ensuring it's a remote URI. 
This seems the regression introduced in https://github.com/feast-dev/feast/pull/4624
Input cases :
Input URI ->  Recognized As -> Behavior
- s3://bucket/data.parquet -> Remote -> Uses as-is
- /absolute/path/file.parquet -> Local -> Resolves normally
- relative/path/file.parquet -> Local -> Resolves against `config.repo_path`
- C:/path/to/file.parquet (Windows) -> Local -> Resolves correctly
Fixes #4873 #4753 #4993
=> fix: Identify s3/remote uri path correctly

sdk/python/feast/entity.py
In the last release a deprecation warning was added to `Entity` if the `value_type` is `None`. Currently, the `from_proto` method creates an `Entity` object first without `value_type` and sets it afterwards. Therefore, for each creation a Warning log is issued.
This change moves the `value_type` into the creator of `Entity` in the `from_proto` method.
=> feat: Set value_type of entity directly in from_proto

README.md, sdk/python/feast/on_demand_feature_view.py, sdk/python/tests/unit/test_on_demand_feature_view.py
This PR allows the user to define an ODFV function with a name override so we don't have to use the function name if we don't want to. This is also meant to provide feature parody with other ways of defining an ODFV.
N/A
N/A
=> feat: Override the udf name when provided as input to an on demand transformation

.github/workflows/operator-e2e-integration-tests.yml
=> fix: Adding extra space on the VM to kind cluster to see if this solves the issue with memory not available with operator e2e tests.

sdk/python/feast/feature_view.py
Meant to clean up the following log message:
`
DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity '__dummy'.
DUMMY_ENTITY = Entity(
`
Related to #4833 and #5092 
The choice of using `ValueType.UNKNOWN` was simply to pick something as the default.
=> chore: Assign the dummy entity a value type

Makefile, docs/getting-started/architecture/push-vs-pull-model.md, docs/getting-started/architecture/write-patterns.md, infra/feast-operator/Makefile, pyproject.toml, sdk/python/requirements/py3.10-ci-requirements.txt, sdk/python/requirements/py3.11-ci-requirements.txt, sdk/python/requirements/py3.9-ci-requirements.txt, setup.py
Adds docling and torch as add on to feast.
Integrating Docling would allow users to efficiently chunk text data within Online Feature Views (ODFVs) during the write process and torch will allow conversion of feature vectors into pytorch tensors.
#5037 #4890
=> feat: Added docling and pytorch as add on

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py, sdk/python/feast/infra/online_stores/online_store.py, sdk/python/feast/infra/online_stores/sqlite.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/tests/foo_provider.py, sdk/python/tests/unit/online_store/test_online_retrieval.py
chore: Making embedding optional in retrieve_online_documents
=> chore: Making embedding optional in retrieve_online_documents

MANIFEST.in, sdk/python/feast/feature_server.py, sdk/python/feast/static/chat/index.html, sdk/python/feast/ui_server.py
This pull request introduces several enhancements to the Feast feature server, including the addition of a chat UI, WebSocket support, and improvements to the server's API documentation.
1.  `MANIFEST.in`:
- Added a new line to include static files in the package.
2. `sdk/python/feast/feature_server.py`:
- Imported new modules and libraries (asyncio, os, importlib_resources, WebSocket, WebSocketDisconnect, StaticFiles).
- Added new classes for chat functionality (ChatMessage, ChatRequest).
- Extended get_app function to document its purpose and endpoints in detail.
- Introduced new endpoints:
- /chat: POST endpoint to process chat requests.
- /chat: GET endpoint to serve the chat UI.
- /ws/chat: WebSocket endpoint for real-time chat communication.
- Created a ConnectionManager class to …
=> feat: Add an OOTB Chat uI to the Feature Server to support RAG demo

ui/src/components/EuiCustomLink.tsx, ui/src/components/FeaturesInServiceDisplay.tsx, ui/src/components/FeaturesListDisplay.tsx, ui/src/pages/data-sources/DataSourcesListingTable.tsx, ui/src/pages/entities/EntitiesListingTable.tsx, ui/src/pages/entities/FeatureViewEdgesList.tsx, ui/src/pages/feature-services/FeatureServiceListingTable.tsx, ui/src/pages/feature-views/ConsumingFeatureServicesList.tsx, ui/src/pages/feature-views/FeatureViewListingTable.tsx, ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx, ui/src/pages/feature-views/components/FeatureViewProjectionDisplayPanel.tsx, ui/src/pages/feature-views/components/RequestDataDisplayPanel.tsx, ui/src/pages/features/FeatureOverviewTab.tsx, ui/src/pages/saved-data-sets/DatasetsListingTable.tsx
EuiCustomLink was the last JavaScript component, convert it to TypeScript too.
No related issue.
The `href` prop was never used, so we omit it from the props type definition, and no longer pass it to the component. (We define `href` in EuiCustomLink based on the passed `to` prop.)
We could also have chosen to drop the `to` prop and use `href` instead, but `to` is used by [React Router's Link](https://reactrouter.com/6.29.0/components/link), and it makes sense to use the same name in EuiCustomLink since we pass it to React Router's `navigate` function; the naming hints that it's tied to React Router and not just a regular URL path.
These changes partially overlap with #5004, but I'll remove such changes from the other PR if this gets merged first, and vice versa.
=> chore: Convert EuiCustomLink to TypeScript in /ui

ui/src/FeastUI.tsx, ui/src/FeastUISansProviders.tsx, ui/src/components/FeaturesInServiceDisplay.tsx, ui/src/components/FeaturesListDisplay.tsx, ui/src/components/ObjectsCountStats.tsx, ui/src/components/ProjectSelector.tsx, ui/src/pages/RootProjectSelectionPage.tsx, ui/src/pages/Sidebar.tsx, ui/src/pages/data-sources/DataSourcesListingTable.tsx, ui/src/pages/entities/EntitiesListingTable.tsx, ui/src/pages/entities/FeatureViewEdgesList.tsx, ui/src/pages/feature-services/FeatureServiceListingTable.tsx, ui/src/pages/feature-services/FeatureServiceOverviewTab.tsx, ui/src/pages/feature-views/ConsumingFeatureServicesList.tsx, ui/src/pages/feature-views/FeatureViewListingTable.tsx, ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx, ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx, ui/src/pages/feature-views/components/FeatureViewProjectionDisplayPanel.tsx, ui/src/pages/feature-views/components/RequestDataDisplayPanel.tsx, ui/src/pages/features/FeatureOverviewTab.tsx, ui/src/pages/saved-data-sets/DatasetsListingTable.tsx
Sets the React Router [basename](https://reactrouter.com/6.28.2/router-components/browser-router#basename) to avoid repeating the `PUBLIC_URL` environment variable.
This is pretty much a re-do of https://github.com/feast-dev/feast/pull/3541 but with only internal changes. Related short discussion started in https://github.com/feast-dev/feast/pull/3514#issuecomment-1472661945.
I verified that the environment variable still works by starting the app with `PUBLIC_URL=/feast-ui yarn start` (also `PUBLIC_URL=http://localhost:3000/feast-ui yarn start` somehow works):
**Note:** I originally included some changes that affected the behavior (see discussion below), but eventually decided to keep this as purely refactoring, and make other kinds of improvements separately.
=> chore: Set router basename to simplify paths in /ui

docs/reference/alpha-web-ui.md, ui/README.md
- Use subheadings in Customization section in alpha-web-ui.md too (they are already used in ui/README.md)
- Mark code examples as jsx for colors
None.
See the documents rendered with these changes in [alpha-web-ui.md](https://github.com/peruukki/feast/blob/ui-docs-formatting-improvements/docs/reference/alpha-web-ui.md#custom-basename) and [ui/README.md](https://github.com/peruukki/feast/tree/ui-docs-formatting-improvements/ui#custom-basename)
=> docs: Small formatting improvements in UI documentation

.github/workflows/operator-e2e-integration-tests.yml, Makefile, infra/feast-operator/Makefile, infra/feast-operator/test/e2e/e2e_test.go, infra/feast-operator/test/upgrade/upgrade_test.go, infra/feast-operator/test/utils/test_util.go, sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Cleans up unused ubuntu installations, switches kind container dir to use /mnt, and only copies specific folders during feature-server image build. This PR also skips additional image builds for later tests. Only one image build is necessary for the operator and feature-server, respectively.
Fixes https://github.com/feast-dev/feast/issues/5108
reverts some of the changes made in https://github.com/feast-dev/feast/pull/5089
recent addition of pytorch appears problematic ...  adding at least 755mb
```shell
Downloading torch-2.2.2-cp311-cp311-manylinux1_x86_64.whl (755.6 MB)
```
=> fix: Increase available action VM storage and reduce dev feature-server image size

docs/reference/alpha-vector-database.md
moving https://github.com/feast-dev/feast/pull/5116 to main
=> doc: Fix typo alpha-vector-database.md (#5116)

.github/workflows/build_wheels.yml
Since the `0.42.0` release, our workflow has no longer been uploading the sdist tarball to PyPi. This PR aims to fix this by consolidating the wheels and source builds to a single job and uploading said artifacts to the same temp storage which feeds the PyPi upload job.
It's worth noting that the separate source job appears to have previously been created to resolve some issues that the `make install-go-ci-dependencies` was causing. This make command is no longer in use as it has since been commented out.
https://github.com/feast-dev/feast/blob/75f5a90536f7caa566b38b9c368ec33a90d2bfa5/Makefile#L649-L651
=> chore: Consolidate wheels/source builds & artifacts for release

docs/reference/alpha-web-ui.md, ui/README.md, ui/src/FeastUI.tsx, ui/src/FeastUISansProviders.tsx, ui/src/index.tsx
We currently always fetch the project list from the root path by default, even if the UI is served from a non-root path via PUBLIC_URL.
It seems reasonable to assume that the project list would be served from the same path as the UI by default, so change the default project list URL to include the [basename from PUBLIC_URL](https://github.com/feast-dev/feast/blob/2ac4906da2e87aa1f7457430dce75dcf8d3075a4/ui/src/FeastUI.tsx#L18). This way you don't need to specify a custom `projectListPromise` for this base case, as shown by the changes in ui/src/index.tsx.
The PUBLIC_URL environment variable is now taken into account by default when fetching the project list. This is a breaking change only if all these points apply:
1. You're using Feast UI [as a …
=> feat!: Include PUBLIC_URL in defaultProjectListPromise URL in /ui

sdk/python/feast/type_map.py
When pushing a data frame to a store and the data frame have a `List[int64]` (to store an array not used for embedding) I was getting an error of type not exits.
This fixed it.
=> fix: Cant add different type of list types

.github/workflows/build_wheels.yml, .github/workflows/publish_images.yml, docs/reference/registries/sql.md, examples/kind-quickstart/01-Install.ipynb, examples/kind-quickstart/init-job.yaml, examples/podman_local/README.md, examples/podman_local/docker-compose.yml, examples/rbac-remote/client/k8s/admin_user_resources.yaml, examples/rbac-remote/client/k8s/readonly_user_resources.yaml, examples/rbac-remote/client/k8s/unauthorized_user_resources.yaml, examples/rbac-remote/client/oidc/admin_user_resources.yaml, examples/rbac-remote/client/oidc/readonly_user_resources.yaml, examples/rbac-remote/client/oidc/unauthorized_user_resources.yaml, infra/charts/feast-feature-server/README.md, infra/charts/feast-feature-server/values.yaml, infra/charts/feast/charts/feature-server/README.md, infra/charts/feast/charts/feature-server/values.yaml, infra/charts/feast/charts/transformation-service/README.md, infra/charts/feast/charts/transformation-service/values.yaml, infra/feast-helm-operator/Makefile, infra/feast-helm-operator/config/manager/kustomization.yaml, infra/feast-operator/Makefile, infra/feast-operator/config/default/related_image_fs_patch.yaml, infra/feast-operator/config/manager/kustomization.yaml, infra/feast-operator/config/overlays/odh/params.env, infra/feast-operator/dist/install.yaml, infra/feast-operator/internal/controller/services/services_types.go
**_ONLY MERGE RIGHT BEFORE THE NEXT RELEASE_**
Moving release image to quay.io. With this PR, I've tried to change all necessary CI and image references.
In order for the image pushes to succeed, we'll need the following secrets added to this GH repo's settings.
- QUAYIO_USERNAME
- QUAYIO_TOKEN
At the same time, we'll want to **delete** the following existing secrets -
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN
Fixes https://github.com/feast-dev/feast/issues/5046
=> chore: Move release images to quay.io

.github/workflows/build_wheels.yml, .github/workflows/master_only.yml
Cleans up unused ubuntu installations during the master only image build CI.
Relates to https://github.com/feast-dev/feast/pull/5112
=> ci: Increase available VM storage for `master_only` & `build_wheels` workflows (cherry-pick)

infra/charts/feast-feature-server/README.md, infra/charts/feast-feature-server/templates/deployment.yaml, infra/charts/feast-feature-server/values.yaml
This PR let the feast-festure-server helm chart support the env, volume and volumemount config in values.yaml. And if not provide any values, it will keep the same render result as before.
Why I raise this juse because I am deploy the server in GKE, but in out case we need access the AWS dynamoDB as the online store for test now. After my expriment, I need add the env, volume and volumemount in the deployment manifest, but the config can not support those fields, I have to patch them after helm upgrade. So just made this change to support them.
N/A
N/A
=> feat: Feast-festure-server helm support more deployment config

sdk/python/feast/infra/registry/proto_registry_utils.py
Profiling indicates that a large amount of time is spent in creating features views from the protobuf representations for every call to the online feature retrieval interfaces.
In our testing setup where features are retrieved from 24 features views, 80%+ of the time spent in Feast excluding networking operations is due to the above. On my local machine (M2 Mac), this time can exceed 15ms.
This PR introduces a decorator that caches the results of `get_any_feature_view`, which will remove the need to call `FeatureView.from_proto` in many cases when retrieving online features.
In principle, the decorator could also be used for other functions such as `get_feature_view`.
=> feat: Cache get_any_feature_view results

sdk/python/feast/batch_feature_view.py, sdk/python/feast/on_demand_feature_view.py, sdk/python/feast/stream_feature_view.py, sdk/python/feast/transformation/base.py, sdk/python/feast/transformation/factory.py, sdk/python/feast/transformation/mode.py, sdk/python/feast/transformation/pandas_transformation.py, sdk/python/feast/transformation/python_transformation.py, sdk/python/feast/transformation/spark_transformation.py, sdk/python/feast/transformation/sql_transformation.py, sdk/python/feast/transformation/substrait_transformation.py, sdk/python/tests/conftest.py, sdk/python/tests/example_repos/example_feature_repo_with_bfvs.py, sdk/python/tests/integration/feature_repos/universal/feature_views.py, sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py, sdk/python/tests/unit/test_feature_views.py, sdk/python/tests/unit/test_on_demand_feature_view.py, sdk/python/tests/unit/test_stream_feature_view.py
Created a Transformation interface. it still works with the current pandas_transformation, python_transformation etc.
The next step is refactor the BatchMaterializationEngine to make it works for both Materialization and Transformation.
https://github.com/feast-dev/feast/issues/4584
https://github.com/feast-dev/feast/issues/4277#issuecomment-2427772928
https://github.com/feast-dev/feast/issues/4696
=> feat: Kickoff Transformation implementationtransformation code base

examples/operator-quickstart/01-Install.ipynb
The notebook suggests that it will use a Kind cluster for implementation, but then ends up using Colima. I removed the references to Kind, so that users won't be confused.
=> docs: Removed ref to unused kind

sdk/python/feast/infra/online_stores/dynamodb.py
In some cases it can be useful to be able to control the timeout and retry behavior of (async) DynamoDB connections. This PR exposes the respective functionality of (aio)botocore in the current project. By default, `connect_timeout` and `read_timeout` are set to 60 seconds, which is the default in (aio)botocore (https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html). Therefore this value is currently also implicitly used.
The `DynamoDBOnlineStoreRetryConfig` model was introduced to stay close to what the configuration would look like in botocore. If preferred, the respective fields could also be moved into the top level config model, i.e., DynamoDBOnlineStoreConfig.
=> feat: Add async DynamoDB timeout and retry configuration

infra/feast-operator/go.mod, infra/feast-operator/internal/controller/featurestore_controller_tls_test.go, infra/feast-operator/internal/controller/services/services_types.go, infra/feast-operator/internal/controller/services/tls.go, infra/feast-operator/internal/controller/services/tls_test.go
The operator searches for the `odh-trusted-ca-bundle` ConfigMap and mounts it into the Feast containers. In case the standalone feast operator is deployed and the ConfigMap is not present, the operator will not mount it.
This change is required when the Feast operator is deployed with ODH or RHOAI.
example of volume mount.
=> feat: Operator mounts the odh-trusted-ca-bundle configmap when deployed on RHOAI or ODH

.github/workflows/release.yml
This PR adds compiling and attaching feast-operator e2e test binaries to the GitHub release,  so that it can be used anywhere by simply downloading.
(This is required for running upstream tests in RHOAI downstream builds)
=> chore: Add compiled go test binary in github release assets

Makefile
Adds a Makefile target for formatting the UI code.
This was requested in #5149 (if I understood the request correctly).
The `ui` directory requires the `NPM_TOKEN` environment variable to exist to run any package manager command via [.npmrc](https://github.com/feast-dev/feast/blob/master/ui/.npmrc). I just always define it to an empty value like in these changes, don't know if there is a more convenient way, or if we can assume that the developer already has it defined in their environment.
=> chore: Add format-ui Makefile target

docs/reference/data-sources/push.md
Fixed space typo at PUSH docs.
It looks like there is no space between `the` and `FeatureStore.write_to_online_store`
Deleted new line between those words.
=> fix: Fix space typo in push.md docs

infra/charts/feast-feature-server/templates/deployment.yaml
There's a typo in deployment.yaml of the chart. The actual value is metrics.enabled while in the deployment.yaml its metrics.enlabled. 
The issue fixes the metrics.enabled in the chart.
N/A
=> fix: Typo in metrics.enabled in feast-feature-server chart

ui/src/components/ExportButton.tsx, ui/src/pages/data-sources/Index.tsx, ui/src/pages/entities/Index.tsx, ui/src/pages/feature-services/Index.tsx, ui/src/pages/feature-views/Index.tsx, ui/src/pages/features/FeatureListPage.tsx
This PR adds support in UI for exporting features, feature-views, feature-services, data-sources, etc. 
- As a user, I should be able to export all entities in either csv or json format.
- As a user, I should be able to filter in search box/filter by tags and export only required data.
Screenshot:
=> feat: Added export support in feast UI

examples/rag/feature_repo/feature_store.yaml, examples/rag/milvus-quickstart.ipynb
This PR updates the Milvus RAG quickstart example to ensure consistency between the tutorial content and actual implementation:
- Fixed the configuration in `feature_store.yaml` to use proper Milvus parameters
- Updated the tutorial overview section to correctly reference Milvus as the online store instead of SQLite
- Aligned all documentation with the actual implementation to prevent confusion
The previous version contained inconsistencies where the tutorial mentioned SQLite while the actual implementation used Milvus. This mismatch caused confusion for users trying to follow the example. Additionally, some Milvus configuration parameters were incorrect, causing runtime errors.
- Corrected online store references throughout the tutorial
- Fixed Milvus configuration parameters in …
=> fix: Update milvus-quickstart and feature_store.yaml with correct Milvus Config

sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py, sdk/python/tests/unit/online_store/test_online_retrieval.py
Add keyword search support to Milvus online store implementation. This enables searching for documents in the Milvus store using text queries, in addition to the existing vector similarity search. The implementation supports:
1. Pure keyword search using `query_string` parameter
2. Vector similarity search using `embedding` parameter (existing functionality)
3. Hybrid search combining both text and vector similarity 
Keyword search is implemented using the LIKE operator for text fields, allowing users to find documents containing specific text without requiring vector embeddings.
Fixes #5123
The implementation follows a similar pattern to the SQLite online store's keyword search functionality, but uses Milvus' filter capabilities. It maintains backward compatibility with all existing …
=> feat: Enable keyword search for Milvus

docs/reference/offline-stores/postgres.md, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/tests/unit/infra/offline_stores/contrib/postgres_offline_store/test_postgres.py
This PR gives users the option to use CTEs for querying historical features instead of the current approach of creating a table, using the table and then dropping the table.
The option sits behind a flag that's configurable on the Offline Store configuration.
When trying to join more than 1 or 2 entities to a feature view, we started noticing performance issues. During this time, we were able to manipulate the query SQL to use a CTE instead of the TABLE created by default, and saw noticeable improvements in getting results back.
We believe this will have limited if any downsides to the existing implementation.
There's a note that this SQL template should stay in sync w/ Redshift, but we are now drifting.
=> feat: Enable users to use Entity Query as CTE during historical retrieval

sdk/python/feast/repo_config.py
This PR fixes incorrect module paths for the Qdrant online store in `repo_config.py`. The current paths were pointing to a non-existent module (`feast.infra.online_stores.cqdrant.QdrantOnlineStore`), which was causing import errors when using legacy configurations with Qdrant online store.
The changes update the paths to the correct module location:
`feast.infra.online_stores.qdrant_online_store.qdrant.QdrantOnlineStore`
Fixes #5206
=> fix: Update Qdrant online store paths in repo_config.py

docs/reference/registries/README.md
The link to more information about registries on [this page](https://docs.feast.dev/reference/registries) is broken. This change fixes that.
=> Fix broken link to registry documentation

sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_type_map.py
I used Trino as offline store. And feast supports a various data types by Trino-supported data types([docs](https://trino.io/docs/current/language/types.html)) 
But feast doesn't support Trino-based `real` type. the type means `float32`. I just add the mapping `real` to `float32`. 
A float32 type is supported in the trino as offline store
=> feat: add `real`(float32) type for trino offline store

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/qdrant_online_store/qdrant.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/online_store/test_universal_online.py
Fixed integration tests for milvus and qdrant.
```
make test-python-universal-milvus-online
make test-python-universal-qdrant-online
```
- sdk/python/feast/feature_store.py
- Removed override of distance_metric in _retrieve_from_online_store. This was always overriding distance_metric with default value of vector_search_metric even wrong value is passed. It's required only in v2 method. It was added in https://github.com/feast-dev/feast/pull/4971 . 
- sdk/python/feast/infra/online_stores/qdrant_online_store/qdrant.py 
- Fixed `json.loads() `when `get_list_val_str` returns `None`. In `online_write_batch()`, we are assuming that every value will be a a vector/embedding. But some of the features (like `string_feature: "a"`) are not embeddings. 
- …
=> fix: Fixed integration tests for qdrant and milvus

sdk/python/feast/feature_server.py
Remove entity_rows parameter from retrieve_online_documents_v2 call in feature server
=> fix: Remove entity_rows parameter from retrieve_online_documents_v2 call

infra/feast-operator/config/overlays/rhoai/delete-namespace.yaml, infra/feast-operator/config/overlays/rhoai/kustomization.yaml, infra/feast-operator/config/overlays/rhoai/params.env, infra/feast-operator/config/overlays/rhoai/params.yaml, infra/scripts/release/files_to_bump.txt
This adds a new kustomize overlay for RHOAI Operator installations. Currently, the only real difference in this overlay is the use of a RH product image - `registry.redhat.io/openshift4/ose-cli:v4.15`
=> chore: Add kustomize overlay to Operator for RHOAI install support

sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
Fixes get_online_features for milvus:
```
"/Users/farceo/dev/feast/sdk/python/feast/infra/online_stores/online_store.py", line 199, in get_online_features
read_rows = self.online_read(
File "/Users/farceo/dev/feast/sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py", line 421, in online_read
type(getattr(val, proto_attr)).__args__[0],
AttributeError: __args__
```
After fix:
```
def run_entity_retrieval_demo():
entity_retrieved_features = store.get_online_features(
features=[
"docling_transform_docs:vector",
"docling_transform_docs:chunk_id",
"docling_transform_docs:chunk_text",
"docling_transform_docs:document_id",
],
entity_rows=[{"document_id": "doc-1", "chunk_id": "chunk-1"}],
)
print("docling transformed features retrieved via entity =") …
```
=> fix: Fix milvus online_read

pyproject.toml, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/tests/unit/infra/offline_stores/contrib/postgres_offline_store/test_postgres.py
Currently, when trying to `get_historical_features` from a postgres offline store without specifying a FeatureView, the call fails due to bad SQL generated. This PR fixes the SQL generated and also introduces a way(via `sqlglot`) to validate the SQL as part of unit tests to hopefully keep this from happening in the future.
https://github.com/feast-dev/feast/issues/5239
The RedShift implementation is most likely suffering from this same issue as the template code is basically the same.
=> fix: Allow get_historical_features with only On Demand Feature View

sdk/python/feast/feature_store.py, sdk/python/feast/infra/online_stores/postgres_online_store/postgres.py, sdk/python/tests/integration/online_store/test_universal_online.py
This PR enhances the PostgreSQL online store to support **hybrid search capabilities**, combining both vector similarity search and full-text search.  
Specifically:
- Introduces the ability to perform hybrid queries using both embeddings and keyword-based search.
- Extends `retrieve_online_documents_v2` function to handle vector-only, text-only, and hybrid cases gracefully.
- Improves feature retrieval by dynamically selecting features based on query type (distance, text_rank).
- Adds comprehensive integration tests to validate:
- Vector similarity search (L2 and cosine distance)
- Full-text search
- Hybrid search (vector + text)
- Edge cases (non-matching queries, category filtering)
This update supports the broader goal of enabling more intelligent, contextual document retrieval in …
=> feat: Add retrieve online documents v2 method into  pgvector 

sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/tests/unit/infra/offline_stores/contrib/postgres_offline_store/test_postgres.py
This PR fixes a bug introduced w/ the `entity_select_mode`. Currently, if a user sets `entity_select_mode="embed_query` and then passed a DataFrame, we fail. This should not happen as we can no longer be in a mixed state of both SQL queries w/ `entity_select_mode="embed_query` and DataFrames.
N/A
N/A
=> fix: Embed Query configuration breaks when switching between DataFrame and SQL

examples/rbac-local/01.3-setup-feast.ipynb
This is a small PR to fix the parameter in the RBAC local example, specifically for the `Permissions` class instantiation. The current class instantiation has a `name_patterns` parameter (plural) instead of the singular as used in the example. 
Without this fix, the example instantiation fails with an error. 
You can verify the parameters needed with:
```
from feast.permissions.permission import Permission
help(Permission)
```
which returns the following (note the plural `name_patterns` parameter):
```
Init signature:
Permission(
name: str,
types: Union[list['FeastObject'], ForwardRef('FeastObject'), NoneType] = [],
name_patterns: Union[str, list[str], NoneType] = [],
actions: Union[list[feast.permissions.action.AuthzedAction], feast.permissions.action.AuthzedAction] = …
```
=> fix: Fixed Permissions object parameter in example

docs/how-to-guides/entity-reserialization-of-from-v2-to-v3.md, sdk/python/feast/infra/key_encoding_utils.py, sdk/python/feast/repo_config.py, sdk/python/tests/unit/infra/test_key_encoding_utils.py
Not fully but in the next release the serialization 2 would be completely deprecated to resolve https://github.com/feast-dev/feast/issues/5180
=> feat: Serialization version 2 deprecation notice

sdk/python/feast/feature_store.py
PR fixes the redundant timezone conversion in the logs. 
```
Materializing 1 feature views from 2025-04-05 02:30:00+05:30 to 2025-04-05 20:30:00+05:30 into the postgres online store.
```
Fixes #5227
=> fix: Materialization logs

.github/workflows/java_pr.yml, .github/workflows/operator-e2e-integration-tests.yml, .github/workflows/operator_pr.yml, .github/workflows/pr_integration_tests.yml, .github/workflows/pr_local_integration_tests.yml, .github/workflows/pr_remote_rbac_integration_tests.yml, .github/workflows/smoke_tests.yml, .github/workflows/unit_tests.yml
=> fix: Update actions to remove check skip tests

docs/reference/registries/remote.md, sdk/python/feast/registry_server.py
Remove misleading HTTP prefix from gRPC endpoints in logs and documentation since gRPC servers don’t serve standard HTTP requests that the http:// prefix implies
=> fix: Remove misleading HTTP prefix from gRPC endpoints in logs and doc

sdk/python/feast/feature_server.py, sdk/python/feast/feature_store.py, sdk/python/tests/unit/test_on_demand_python_transformation.py
This PR introduces a new `transform_on_write` flag to various functions and classes in the Feast SDK. The flag allows users to enable or disable transformations of data when writing to the online or offline store. This feature improves flexibility in managing data transformations during feature ingestion.
This feature is particularly useful if you want to batch transform a set of data (e.g., using Spark) and upload that transformed data to the online store **_and_** then want to also offer transformation on writes with the Feast Feature Server using an On Demand transformation.
- **`sdk/python/feast/feature_server.py`**
- Added `transform_on_write` attribute to `WriteToFeatureStoreRequest` and `PushFeaturesRequest` classes.
- Updated `push` and `write_to_online_store` functions to pass …
=> feat: Make transform on writes configurable for ingestion

sdk/python/feast/infra/common/retrieval_task.py, sdk/python/feast/infra/compute_engines/feature_builder.py, sdk/python/feast/infra/compute_engines/local/feature_builder.py, sdk/python/feast/infra/compute_engines/local/nodes.py, sdk/python/feast/infra/compute_engines/spark/feature_builder.py, sdk/python/feast/infra/compute_engines/spark/node.py, sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py, sdk/python/feast/infra/offline_stores/contrib/couchbase_offline_store/couchbase.py, sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssql.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py, sdk/python/feast/infra/offline_stores/dask.py, sdk/python/feast/infra/offline_stores/duckdb.py, sdk/python/feast/infra/offline_stores/ibis.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/feast/infra/offline_stores/redshift.py, sdk/python/feast/infra/offline_stores/remote.py, sdk/python/feast/infra/offline_stores/snowflake.py, sdk/python/feast/offline_server.py, sdk/python/tests/integration/compute_engines/spark/test_compute.py
The major change in this PR is making the start_date and end_date in pull_all_from_table_or_query optional:
```
def pull_all_from_table_or_query(
config: RepoConfig,
data_source: DataSource,
join_key_columns: List[str],
feature_name_columns: List[str],
timestamp_field: str,
created_timestamp_field: Optional[str] = None,
start_date: Optional[datetime] = None,
end_date: Optional[datetime] = None,
) -> RetrievalJob:
```
The reason is the API should be able to let the user skip the time range selection, and return all entities with features.
This will also make the current `materialization` and `get_historical_features` in Compute Engine to be able to use this API.
The change is non-breaking, and the API currently is only used in `retrieve_feature_service_logs`, and `retrieve_saved_dataset`.
=> feat: Offline store update pull_all_from_table_or_query to make timestampfield optional

infra/feast-operator/internal/controller/featurestore_controller_db_store_test.go, infra/feast-operator/internal/controller/featurestore_controller_ephemeral_test.go, infra/feast-operator/internal/controller/featurestore_controller_kubernetes_auth_test.go, infra/feast-operator/internal/controller/featurestore_controller_loglevel_test.go, infra/feast-operator/internal/controller/featurestore_controller_objectstore_test.go, infra/feast-operator/internal/controller/featurestore_controller_oidc_auth_test.go, infra/feast-operator/internal/controller/featurestore_controller_pvc_test.go, infra/feast-operator/internal/controller/featurestore_controller_test.go, infra/feast-operator/internal/controller/featurestore_controller_tls_test.go, infra/feast-operator/internal/controller/services/services.go, infra/feast-operator/internal/controller/services/services_types.go
With this PR, the Operator will honor whatever number of replicas the Feast Deployment is scaled to (by the user, HPA, etc.).
Currently, the Operator enforces only 1 replica per Feature Store Deployment. We should leave this up to the user. While Feast does not support any kind of HA implementation, certain data store types may support horizontal scaling of feast.
Doing this also gets the Operator out of the business of making any future HA or scaling decisions.
=> fix: Operator - remove default replicas setting from Feast Deployment

sdk/python/feast/feature_store.py
Refactored code to make it easier toread.
=> chore: Refactor transform on write

sdk/python/feast/infra/online_stores/dynamodb.py, sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
* currently only global online config tags for dynamo are added as table tags
* update the table creation to include feature view specific tags as well
* this is helpful for cost tracking, alerting by ownership, etc
=> feat: Add feature view tags to dynamo tags

ui/src/components/RegistryVisualization.tsx, ui/src/components/RegistryVisualizationTab.tsx, ui/src/pages/feature-views/FeatureViewLineageTab.tsx, ui/src/pages/feature-views/RegularFeatureViewInstance.tsx
1. **Registry Visualization Enhancements**
- **Filter by Type and Name:**
- Added dropdown menus to filter objects in the registry visualization by type (`dataSource`, `entity`, `featureView`, `featureService`) and name.
- Introduced a new `filterNode` prop in the `RegistryVisualization` component to apply these filters.
- Updated logic in the `RegistryVisualization` component to filter relationships based on the selected type and name.
- **UI/UX Improvements:**
- Added new UI components such as `EuiSelect`, `EuiFormRow`, and `EuiFlexGroup` for a more user-friendly filter interface.
2. **Feature Lineage Tab**
- Added a new `FeatureViewLineageTab` component to visualize the lineage of a feature view.
- Integrated the tab into the `RegularFeatureViewInstance` component:
- Added a "Lineage" …
=> feat: Add feature view lineage tab and filtering to home page lineage

ui/src/App.css, ui/src/FeastUISansProviders.tsx, ui/src/components/RegistryVisualization.tsx, ui/src/components/ThemeToggle.tsx, ui/src/contexts/ThemeContext.tsx, ui/src/index.css, ui/src/pages/Layout.tsx
Add Dark mode.
Also fix a bug where child object of the DAG weren't included in graph.
=> feat: Add dark mode toggle to Feast UI

ui/src/pages/feature-views/FeatureViewLineageTab.tsx
Add Permission-Based Filtering to Feature View Lineage Tab
This PR introduces a feature to filter the registry visualization in the Feature View Lineage Tab based on user-selected permissions. It enhances the usability of the Feature View Lineage Tab by allowing users to focus on specific actions or permissions when exploring lineage data.
1. **UI Enhancements:**
- Added a dropdown (`EuiSelect`) to filter nodes by permissions.
- Integrated the dropdown with the `RegistryVisualization` component to dynamically update the visualization based on the selected permission.
2. **State Management:**
- Introduced a `useState` hook to manage the state of the selected permission action (`selectedPermissionAction`).
3. **New Utility Integration:**
- Utilized `filterPermissionsByAction` from …
=> fix: Fix lineage entity filtering

ui/src/components/CommandPalette.tsx, ui/src/components/GlobalSearchShortcut.tsx, ui/src/components/RegistrySearch.tsx, ui/src/pages/Layout.tsx
Improve search results format.
When hitting ⌘+K you'll see:
And the results are:
This pull request introduces the following features and improvements to the user interface (UI) components:
---
- Added a `CommandPalette` component to the UI.
- Integrated the command palette into the `Layout` component.
- Added keyboard shortcut (`Cmd+K` or `Ctrl+K`) to open the command palette globally across the app.
- Debug logging for keypress events related to opening the command palette.
- Ensured proper event handling by utilizing `window.addEventListener` for keydown events in both `GlobalSearchShortcut` and `Layout` components.
---
- Improved the functionality in `GlobalSearchShortcut` by adding detailed logging and more robust keypress detection.
- Updated the `useEffect` hook to ensure consistent …
=> feat: Improve search results formatting

infra/feast-operator/internal/controller/services/client.go, infra/feast-operator/internal/controller/services/services.go
We need to allow a user to add their own annotations to any Operator created objects. While we already do so for the vast majority of said objects, 2 of them currently override any custom annotations. With this PR, we adjust the logic so that it we merely add to the annotations of these 2 object types, instead of overriding them completely.
Fixes https://github.com/feast-dev/feast/issues/5302
=> fix: Allow custom annotations on Operator installed objects

README.md, docs/reference/feature-servers/registry-server.md, sdk/python/feast/api/registry/rest/__init__.py, sdk/python/feast/api/registry/rest/data_sources.py, sdk/python/feast/api/registry/rest/entities.py, sdk/python/feast/api/registry/rest/feature_services.py, sdk/python/feast/api/registry/rest/feature_views.py, sdk/python/feast/api/registry/rest/permissions.py, sdk/python/feast/api/registry/rest/projects.py, sdk/python/feast/api/registry/rest/rest_registry_server.py, sdk/python/feast/api/registry/rest/rest_utils.py, sdk/python/feast/api/registry/rest/saved_datasets.py, sdk/python/feast/cli/serve.py, sdk/python/feast/feature_store.py, sdk/python/feast/permissions/server/rest.py, sdk/python/tests/unit/api/test_api_rest_registry.py, sdk/python/tests/unit/api/test_api_rest_registry_server.py
This PR add 
- option to serve HTTP REST apis for registry server via FastAPI. 
- implements REST endpoints corresponding to gRPC methods.
- REST endpoints mirror the gRPC interface but use intuitive HTTP methods and routes.
- tests for registry REST endpoints.
This will allow easier integration with browser based web apps/UIs. 
`# feast serve_registry --rest-api`
=> feat: Added rest-apis serving option for registry server

sdk/python/feast/repo_operations.py, sdk/python/tests/unit/infra/scaffolding/test_repo_operations.py
It seems that `ignore_paths` added in [#4276](https://github.com/feast-dev/feast/pull/4276) does not take effect
=> fix: The ignore_paths not taking effect duration feast apply

Makefile, docs/project/development-guide.md, sdk/python/feast/ui/README.md
This PR adds `make build-ui-local` command which can be used while doing development and it is useful when you are making changes to the React UI code and want to see them live via the backend.
This command also helps you to deploy unreleased version of frontend locally for testing.
=> chore: Added make command to build locally built Feast UI package

sdk/python/feast/feature_server.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> fix: resolve Python logger warnings

README.md, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
Feast’s Trino connector generated SQL like:
```sql
SELECT ...
FROM
SELECT ...
FROM my_table
```
which Trino rejects with:
`TrinoUserError: TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 60:9: mismatched input 'SELECT'. Expecting: '(', 'JSON_TABLE', 'LATERAL', 'TABLE', 'UNNEST', <identifier>")`
By wrapping the subquery in `(...) AS alias`, we produce valid Trino SQL in accordance with its grammar rules for subqueries.
This PR updates the Trino offline store connector’s Jinja SQL template so that the `FROM` clause always wraps the `featureview.table_subquery` in parentheses and assigns it an explicit alias.
Previously:
```jinja
FROM {{ featureview.table_subquery }}
```
Now:
```jinja
FROM (
{{ featureview.table_subquery }}
) AS {{ featureview.name }}__subquery
```
N/A — …
=> fix: Fix Trino offline store SQL in Jinja template

sdk/python/feast/type_map.py
When exporting features to parquet files (via `to_remote_storage()`) columns of type `NUMBER` are converted to the pyarrow `decimal128` type. This type is translated into `decimal.Decimal` in python when trying to convert it into proto values (https://github.com/feast-dev/feast/blob/648c53dc64ad88077e49e56f0cfc70756d6a5824/sdk/python/feast/utils.py#L282).
Eventually, it fails when the conversion into a proto value is done because `decimal.Decimal` is not supported as a valid type in https://github.com/feast-dev/feast/blob/648c53dc64ad88077e49e56f0cfc70756d6a5824/sdk/python/feast/type_map.py#L313. As far as I could see there was nothing immediately against adding `Decimal` to the supported list as it can be converted into Double. I might be overlooking something however.
I stumbled upon …
=> feat: Add Decimal to allowed python scalar types

Makefile
Removing java commands from top of Makefile
=> chore: Removing java commands from top of Makefile

sdk/python/feast/infra/offline_stores/snowflake.py
When using the Snowflake storage integration to export features as parquet files on S3 it can be useful to set a maximum file size. When working with the Lambda materialization engine we faced the issue that the number of rows per file and thus per invoked Lambda function was so large that the Lambda functions timed out. 
With the new `max_file_size` parameter the file size can be reduced so that each Lambda function needs to write less rows to the online store.
Snowflake docs https://docs.snowflake.com/en/sql-reference/sql/copy-into-location#copy-options-copyoptions
=> feat: Add max_file_size to Snowflake config

Makefile
Reading Makefile is difficult, adding help to get better understanding. 
```
Usage:
make <target>
help             Display this help.
test             Run unit tests for Python and Java
protos           Compile protobufs for Python SDK and generate docs
build            Build protobufs, Java code, and Docker images
format           Format Python and Java code
format-python    Format Python code
lint             Run linters for Python and Java
lint-python      Lint Python code
Python SDK - local
install-python-dependencies-dev  Install Python dev dependencies using uv (editable install)
install-python-dependencies-minimal  Install minimal Python dependencies using uv (editable install)
Python SDK - system
install-python-dependencies-ci  Install Python CI dependencies in system environment …
```
=> chore: Added make help

README.md, docs/reference/offline-stores/trino.md
[Trino (contrib)](https://docs.feast.dev/reference/offline-stores/trino) documentation page still gave code example with `type: feast_trino.trino.TrinoOfflineStore`, which is a class from an archived project [Shopify/feast-trino](https://github.com/Shopify/feast-trino).
[Trino offline store example in documentation is outdated #4837](https://github.com/feast-dev/feast/issues/4837)
Also this PR adds a comment about `coerce_tz_aware: false`, which prevents (possibly a bug) Feast Trino connector from adding time zones to pandas dataframes when using Hive Metastore, This resulted in an error during execution of `feast.get_historical_features()`: `TrinoUserError: TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Unsupported Hive type: timestamp(3) with time zone")`
=> chore: Update Trino (contrib) docs

sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
This PR allows for a local remote instance of Milvus to connect, as previously it was bypassed by `provider: local` which remains and is correct but not the only consideration when using local milvus. The PR also updates the variable from `url` to `uri` as expected by the MilvusClient.
N/A — this issue was found independently and not yet tracked.
=> fix: Update milvus connect function to work with remote instance

README.md, sdk/python/tests/integration/feature_repos/universal/online_store/milvus.py
PR https://github.com/feast-dev/feast/pull/5382 removed default path for milvus causing failures in integration tests. This PR fixes integration tests by setting path in MilvusOnlineStoreCreator. 
```
ERROR sdk/python/tests/integration/online_store/test_universal_online.py::test_online_retrieval_success[ParameterSet(values=(LOCAL:File:milvus:python_fs:False,), marks=[], id=None)] - pymilvus.exceptions.ConnectionConfigException: <ConnectionConfigException: (code=1, message=uri: localhost:19530 is illegal, needs start with [unix, http, https, tcp] or a local file endswith [.db])>
ERROR sdk/python/tests/integration/online_store/test_universal_online.py::test_retrieve_online_milvus_documents[ParameterSet(values=(LOCAL:File:milvus:python_fs:False,), marks=[], id=None)] - …
```
=> test: Fixed path for milvus tests

sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py, sdk/python/tests/integration/feature_repos/repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/online_store/milvus.py
This PR allows for a local remote instance of Milvus to connect, as previously it was bypassed by provider: local which remains and is correct but not the only consideration when using local milvus. The PR also updates the variable from url to uri as expected by the MilvusClient.
Milvus expects that host starts with `[unix, http, https, tcp] or a local file endswith [.db]`, so updated `localhost` default to `http://localhost`.
N/A
=> fix: Updating milvus connect function to work with remote instance

sdk/python/feast/infra/online_stores/sqlite.py
In all other places of the codebase we deal with timestamps in the `utc` timezone.
During experiments with online retrieval from SQLite I found that there're timestamps without tz-info.
I want to add it to be consistent.
N/A
N/A
=> feat: SQLite online retrieval. Add timezone info into timestamp.

sdk/python/tests/integration/online_store/test_universal_online.py
Add asyncio to integration test
=> fix: Add asyncio to integration test

docs/reference/data-sources/overview.md, docs/reference/data-sources/trino.md, sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
This PR fixes `ArrowNotImplementedError: ("NumPyConverter doesn't implement <list<item: int64>> conversion. ", 'Conversion failed for column with type float64')` error when calling `FeatureStore.get_historical_features().to_df()`.
Explanation: If I define some feature of type `array(bigint)` in Trino source after some joins a column with that feature may contain `None` values. Pandas (NumPy) will infer this column as float64, even though it still contains valid int64 arrays.
```diff
def _to_arrow_internal(self, timeout: Optional[int] = None) -> pyarrow.Table:
"""Return payrrow dataset as synchronously including on demand transforms"""
return pyarrow.Table.from_pandas(
-       self._to_df_internal(timeout=timeout), schema=self.pyarrow_schema
+       self._to_df_internal(timeout=timeout)
) …
```
=> fix: Fix NumPy - PyArrow array type mapping in Trino offline store

sdk/python/feast/cli/cli.py, sdk/python/tests/unit/transformation/test_spark_transformation.py
Allow user to set chdir and feature-store-yaml cli options via env variables.
Fixes #5416
=> feat: Allow to use env variable FEAST_FS_YAML_FILE_PATH and FEATURE_REPO_DIR

sdk/python/feast/infra/online_stores/snowflake.py
This PR fixes a critical bug in SnowflakeOnlineStore.online_write_batch.
Currently, the method sets autocommit=False but does not explicitly call conn.commit() after writing data and running the INSERT OVERWRITE query. As a result, data is not persisted - the transaction is discarded when the connection closes - even though no error is raised.
This causes:
Data appears in first reads (same connection)
Data disappears after session ends - table is empty in Snowflake UI and subsequent reads return nothing.
Adding conn.commit() ensures that the transaction is persisted correctly.
Fixes #5431
This is a minimal one-line fix, but solves a critical data loss bug.
I will look into tadding a test which would fail for current implementation. Since this is …
=> fix: Add missing conn.commit() in SnowflakeOnlineStore.online_write_batch

docs/reference/data-sources/push.md, sdk/python/feast/data_source.py, sdk/python/feast/inference.py, sdk/python/tests/unit/test_data_sources.py
feat: make batch_source optional for PushSource
This PR addresses a common pain point when using `PushSource` without a historical data source. Previously, `batch_source` was required even when not needed, forcing users to create dummy files just to satisfy the schema.
With this change:
- `batch_source` is now optional in `PushSource`
- `from_proto` and `to_proto` updated to safely handle absence of `batch_source`
- Added a test to ensure the functionality works as expected
Fixes #5440
- Added unit test: `test_push_source_without_batch_source`
- All tests pass locally (`pytest tests/unit/test_data_sources.py`)
- No breaking changes introduced
=> feat: Make batch_source optional in PushSource (#5440)

infra/feast-operator/test/e2e_rhoai/feast_postupgrade_test.go, infra/feast-operator/test/e2e_rhoai/feast_preupgrade_test.go, infra/feast-operator/test/utils/test_util.go
Added RHOAI upgrade test scenario of credit-scoring example to verify the functionality of a Feast FeatureStore
after upgrade. 
- Introduced `feast_preupgrade_test` to ensure the FeatureStore CR is correctly set up prior to upgrade
- Added `feast_post_upgrade_test` to validate feast apply and materialize functionality after upgrade
- Implemented `ReplaceNamespaceInYamlFilesInPlace` utility to dynamically update namespaces in YAMLs,
preventing conflicts with existing namespaces used by other tests
- Removed model training functionality from Feast apply and materialize tests, as it is not relevant to validate
=> test: Add RHOAI upgrate test to validate feast apply and materialize functionality

docs/reference/online-stores/hybrid.md, sdk/python/feast/infra/online_stores/hybrid_online_store/hybrid_online_store.py, sdk/python/feast/infra/online_stores/hybrid_online_store/hybrid_online_store_repo_configuration.py, sdk/python/tests/integration/feature_repos/universal/online_store/hybrid_online_store.py, sdk/python/tests/integration/online_store/test_hybrid_online_store.py
This PR introduces HybridOnlineStore, enabling routing of online feature operations to different backends based on a tag (e.g., tribe) on the FeatureView.
Supports multiple online store backends in a single Feast deployment.
Allows multi-tenancy and flexible data management strategies.
Includes integration tests with mocking for Redis (no live Redis required).
Documentation and usage examples are included in code docstrings.
=> feat: Add HybridOnlineStore for multi-backend online store routing

Makefile, sdk/python/tests/integration/conftest.py, sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
`
test-python-integration-rbac-remote` tests are causing GitHub runners to terminate due to the memory issues.
- The `RemoteOfflineStoreDataSourceCreator` class was missing a teardown() method. When tests ran, feast serve_offline subprocesses were started but never cleaned up. This was the main reason behind github runner termination.
- Also, fixed the keycloak setup to share a single Keycloak instance across all test runners, allowing us tests to run with more pytest runnners. 
Fixes #4904
=> fix: Fix remote rbac integration tests

sdk/python/feast/infra/offline_stores/dask.py
=> fix: Preserve remote URIs (e.g. s3://) in DaskOfflineStore path

.github/workflows/build_wheels.yml
macOS-14 runners has a dependency on the GNU gettext library (libintl.8.dylib), but this library wasn't available on the runner.  
Fixing - https://github.com/feast-dev/feast/actions/runs/15988854964/job/45099219895
=> fix: Fix verify wheels workflow for macos14

.github/workflows/build_wheels.yml
=> fix: Move Install OS X dependencies before python setup

docs/reference/feature-servers/registry-server.md, sdk/python/feast/api/registry/rest/data_sources.py, sdk/python/feast/api/registry/rest/entities.py, sdk/python/feast/api/registry/rest/feature_services.py, sdk/python/feast/api/registry/rest/feature_views.py, sdk/python/feast/api/registry/rest/permissions.py, sdk/python/feast/api/registry/rest/projects.py, sdk/python/feast/api/registry/rest/rest_utils.py, sdk/python/feast/api/registry/rest/saved_datasets.py, sdk/python/feast/lineage/registry_lineage.py, sdk/python/tests/unit/api/test_api_rest_registry.py, sdk/python/tests/unit/infra/test_registry_lineage.py
This enhancement allows users to query relationships and lineage information for all Feast objects (entities, feature views, data sources, feature services, etc.) through a consistent `include_relationships` parameter.
- Include all relationships (both direct and indirect) for the object(s) in the list and get API response. 
- Added `get_object_relationships()` function for single object relationship queries.
- Added `get_relationships_for_objects() `function for bulk relationship queries.
- Added relationship for entity <-> data sources and test coverage for entity-to-data source relationships.
- Updated API endpoint documentation with relationship examples.
=> feat: Added relationship support to all API endpoints

.github/workflows/publish_web_ui.yml
Fixes npm auth issue. Newer `setup-node@v3` +` Node 16+` version requires : 
1. Setup Node with registry-url: registry-url: 'https://registry.npmjs.org'
2. Use NODE_AUTH_TOKEN: `NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}`
=> fix: Fix NPM authentication

sdk/python/feast/infra/offline_stores/snowflake_source.py
Default precision in Snowflake is 38 ([Docs](https://docs.snowflake.com/en/sql-reference/data-types-numeric#number)).
Current realisation executes a bunch of `MAX(column)` queries to check the exact precision.
This PR introduces a small optimisation to execute a single query for all columns.
N/A
N/A
=> feat: Snowflake source. fetch MAX in a single query

sdk/python/feast/api/registry/rest/codegen_utils.py, sdk/python/feast/api/registry/rest/data_sources.py, sdk/python/feast/api/registry/rest/entities.py, sdk/python/feast/api/registry/rest/feature_services.py, sdk/python/feast/api/registry/rest/feature_views.py, sdk/python/feast/api/registry/rest/features.py, sdk/python/feast/api/registry/rest/saved_datasets.py, sdk/python/feast/api/registry/rest/templates/data_source_template.jinja2, sdk/python/feast/api/registry/rest/templates/entity_template.jinja2, sdk/python/feast/api/registry/rest/templates/feature_service_template.jinja2, sdk/python/feast/api/registry/rest/templates/feature_template.jinja2, sdk/python/feast/api/registry/rest/templates/feature_view_template.jinja2, sdk/python/feast/api/registry/rest/templates/push_source_template.jinja2, sdk/python/feast/api/registry/rest/templates/request_source_template.jinja2, sdk/python/feast/api/registry/rest/templates/saved_dataset_template.jinja2, sdk/python/tests/unit/api/test_api_rest_registry.py
This PR adds `featureDefinition` field to all resource GET API responses containing dynamically generated, copy-pasteable Python code examples for all resource types (feature views, entities, data sources, feature services, features, saved datasets). These examples should help developers understand how these resources are defined programmatically.
Also, added tests to verify code generated is correct python code. 
Ex:
```
{
"spec": {
"name": "driver",
"joinKey": "driver_id"
},
"meta": {
"createdTimestamp": "2025-07-18T11:52:59.070198Z",
"lastUpdatedTimestamp": "2025-07-18T11:52:59.070198Z"
},
"featureDefinition": "from feast import Entity\n\ndriver = Entity(\n    name=\"driver\",\n    join_keys=['driver_id'],\n) "
}
```
=> feat: Provide ready-to-use Python definitions in api

sdk/python/feast/feature_store.py, sdk/python/tests/unit/online_store/test_online_writes.py, sdk/python/tests/utils/test_wrappers.py
Adds validation to `write_to_online_store` and `write_to_online_store_async` to prevent empty dataframes from being written to the online store.
**Changes:**
- Validates completely empty dataframes 
- Validates dataframes with entity data but empty feature columns
- Works with both `df` and `inputs` parameters
- Throws descriptive `ValueError` messages
[RHOAIENG-27681](https://issues.redhat.com/browse/RHOAIENG-27681)
Added comprehensive unit tests in `TestEmptyDataFrameValidation` class.
=> fix: Added support to handle empty dataframe

docs/reference/feature-servers/registry-server.md, sdk/python/feast/api/registry/rest/__init__.py, sdk/python/feast/api/registry/rest/metrics.py, sdk/python/feast/api/registry/rest/rest_registry_server.py, sdk/python/feast/api/registry/rest/rest_utils.py, sdk/python/feast/infra/registry/base_registry.py, sdk/python/feast/infra/registry/contrib/azure/azure_registry_store.py, sdk/python/feast/infra/registry/file.py, sdk/python/feast/infra/registry/gcs.py, sdk/python/feast/infra/registry/registry.py, sdk/python/feast/infra/registry/remote.py, sdk/python/feast/infra/registry/s3.py, sdk/python/feast/infra/registry/snowflake.py, sdk/python/feast/infra/registry/sql.py, sdk/python/tests/unit/api/test_api_rest_registry.py, sdk/python/tests/unit/api/test_api_rest_registry_server.py, sdk/python/tests/unit/infra/registry/test_registry.py
This PR enhances the Feast Registry Server API with visit logging and metrics capabilities, providing better observability and user activity tracking.
- Recent Visit Logging
- Tracks user interactions with registry objects (entities, features, feature views, etc.)
- Stores visit history per user and per project in registry metadata.
- Configurable and stores 100 last visits records per user by default.
- Metrics APIs
`/metrics/resource_counts` - Get resource counts per project or globally.
`/metrics/recently_visited` - Retrieve recent visit history.
=> feat: Added recent visit logging api for registry server

docs/getting-started/faq.md, sdk/python/feast/cli/features.py, sdk/python/feast/feature_store.py, sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/feast/infra/offline_stores/offline_utils.py, sdk/python/feast/infra/offline_stores/remote.py, sdk/python/feast/infra/passthrough_provider.py, sdk/python/feast/infra/provider.py, sdk/python/feast/infra/utils/postgres/connection_utils.py, sdk/python/feast/offline_server.py, sdk/python/tests/unit/infra/offline_stores/contrib/postgres_offline_store/test_postgres.py
Fixes #5474
Now all folowing combinations just works out of the box:
Possible 1 (Returns data during the given timerange):
------------
```python
training_df = store.get_historical_features(
features=[
"driver_hourly_stats:conv_rate",
"driver_hourly_stats:acc_rate",
"driver_hourly_stats:avg_daily_trips",
],
start_date=datetime(2025, 7, 1, 1, 00, 00),
end_date=datetime(2025, 7, 2, 3, 30, 00),
).to_df()
```
Possible 2 (Returns data during the end_date minus TTL time in feature view):
------------
```python
training_df = store.get_historical_features(
features=[
"driver_hourly_stats:conv_rate",
"driver_hourly_stats:acc_rate",
"driver_hourly_stats:avg_daily_trips",
],
end_date=datetime(2025, 7, 2, 3, 30, 00),
).to_df()
```
Possible 3 (Returns data from the start date to now time): …
=> feat: Offline Store historical features retrieval without entity df, but based on datatime range

sdk/python/feast/utils.py
This fix addresses an issue where entity value types were incorrectly mapped when using feature views with join key aliases.
Previously, when using feature views with join key aliases (like in the example below), the `entity_type_map` would use the original column name instead of the aliased join key:
```python
user_entity = Entity(
name="user",
join_keys=["user_id"],
value_type=ValueType.INT32,
description="User entity for the matching platform",
)
match_service = FeatureService(
name="match_service",
features=[
user_profile_fv.with_name("user"),
user_profile_fv.with_name("target_user").with_join_key_map(
{"user_id": "target_user_id"}
),
],
)
```
This caused `target_user_id` to be interpreted as `ValueType.INT64` instead of the correct entity value type (`ValueType.INT32` in this case). …
=> fix: Correct entity value type mapping for aliased feature views

sdk/python/feast/data_source.py
Inherits the timestamp fields from batch source / data source to push source.
Fixes: https://github.com/feast-dev/feast/issues/5549
=> fix: Push Source inherits the timestamp fields from Data Source

docs/reference/feature-servers/registry-server.md, sdk/python/feast/api/registry/rest/entities.py, sdk/python/feast/api/registry/rest/features.py, sdk/python/feast/api/registry/rest/lineage.py, sdk/python/feast/api/registry/rest/rest_registry_server.py, sdk/python/feast/api/registry/rest/rest_utils.py, sdk/python/feast/lineage/registry_lineage.py, sdk/python/feast/registry_server.py, sdk/python/tests/unit/api/test_api_rest_registry.py, sdk/python/tests/unit/infra/test_registry_lineage.py, ui/src/parsers/parseEntityRelationships.ts
This PR adds the consistent error responses with HTTP status codes included in the JSON response body for rest registry apis. Added global exception handlers for rest server. 
Also, fixed the the entity to on-demand feature view relationship. The issue was that the lineage generation code was not creating relationships between entities and on-demand feature views.
=> feat: Implemented consistent error handling for rest registry apis

sdk/python/feast/registry_server.py, sdk/python/tests/unit/api/test_api_rest_registry.py
This PR fixed the filtering issue for On-demand feature view when filtering by request source data source.
There was an issue in the filtering of the data in the `api/v1/feature_views` API when the type of data_source and the feature view is of type on-demand there is no data being returned but if we remove the data source param it was returning the feature views. This PR fixed the issue.
=> fix: Fixed filtering based on data_source for ODFVs

sdk/python/feast/infra/compute_engines/spark/utils.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py, sdk/python/tests/unit/infra/compute_engines/spark/test_nodes.py, sdk/python/tests/unit/transformation/test_spark_transformation.py
Fixes: https://github.com/feast-dev/feast/issues/5607
=> fix: Fix hostname resolution for spark tests

sdk/python/feast/infra/offline_stores/contrib/ray_offline_store/ray.py, sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py, sdk/python/feast/infra/offline_stores/offline_store.py, sdk/python/tests/unit/test_retrieval_job_dataframe.py
Add `to_feast_df` in the offline Retrieval Job.
https://github.com/feast-dev/feast/issues/5581
=> feat: Feast dataframe phase2

infra/feast-operator/docs/namespace-registry.md, infra/feast-operator/internal/controller/featurestore_controller.go, infra/feast-operator/internal/controller/featurestore_controller_namespace_registry_test.go, infra/feast-operator/internal/controller/services/namespace_registry.go, infra/feast-operator/internal/controller/services/services.go, infra/feast-operator/internal/controller/services/services_types.go, infra/feast-operator/internal/controller/suite_test.go
The Feast Namespace Registry is a feature that automatically creates and maintains a centralized ConfigMap containing information about all Feast feature store instances deployed by the operator. This enables dashboard applications and other tools to discover and connect to Feast instances across different namespaces. This addresses:
1. **ConfigMap Creation**: The operator creates a ConfigMap in the appropriate namespace:
- **OpenShift AI**: `redhat-ods-applications` namespace (or DSCi configured namespace)
- **Kubernetes**: `feast-operator-system` namespace
2. **Access Control**: A RoleBinding is created to allow `system:authenticated` users to read the ConfigMap
3. **Automatic Registration and removal**: When a new feature store instance is created, it automatically registers its …
=> feat: Feast Namespaces registry for client ConfigMaps availability

sdk/python/feast/infra/offline_stores/contrib/ray_offline_store/ray.py, sdk/python/feast/infra/ray_shared_utils.py
This PR adds support to run Ray Datasets operations on remote Kuberay cluster. Implemented `RemoteDatasetProxy` class, that wraps all Ray Dataset operations in `@ray.remote` functions, ensuring they execute on KubeRay cluster workers.
https://github.com/feast-dev/feast/issues/5633
=> feat: Added RemoteDatasetProxy that executes Ray Data operations remotely

sdk/python/feast/infra/offline_stores/bigquery.py, sdk/python/tests/unit/infra/offline_stores/test_bigquery.py
With pydantic version 2.9.2, values dict inside field validator will have all details like project_id, billing_project_id nested within data, this PR handles that and has one test case to validate.
Fixes #4678
=> fix: Adapt project_id_exists validator for updated pydantic version
